### ISSUE TITLE
Add Support for Belgica

### ISSUE THREAD

**Issue by Horemheb** [lovasoa/dezoomify#10]
Hello..
there are a few good manuscripts I would like to dezoomify here, too, but as usual, it comes to me quite impossible to do that..
Could you kindly add Support as you always do?
Thanks a Lot!

http://images.kbr.be/multi/KBR_9961-62Viewer/imageViewer.html

**Comment by lovasoa** [comment]
OK, I've worked on it, and finally got it to work.
They use a zoomable image software that I had never seen before : [XLimage](http://www.centrica.it/products/xlimage-2/). I works pretty much the same way as zoomify and seadragon, so adding support for it wasn't too difficult.

Commit to come.
