### ISSUE TITLE
BL British Library Firefox failed blob resource

### ISSUE THREAD

**Issue by Sylbo** [lovasoa/dezoomify#100]
Hi, suddenly, BL stops working for me. Tiles load, but when I try to download the image, Firefox opens the download window and seems to start downloading. But it stops immediately. 

Download message error: Failed - blob resource

Using http://ophir.alwaysdata.net/dezoomify/dezoomify.html
BL pages: http://www.bl.uk/manuscripts/Viewer.aspx?ref=yates_thompson_ms_13_f106v
Firefox 50.0 Windows 10

Also tried Firefox in incognito mode, Chrome with no luck.

Appreciate your marvelous work.

Thanks!

**Comment by lovasoa** [comment]
I cannot reproduce the error. Can you give more more details ? Maybe open the developer console (*Tools > Web development > Web console* in firefox), open dezoomify, and take a screenshot of the error(s) you get ?

**Comment by Sylbo** [comment]
16:43:05.897 TypeError: this._recipeManager is null[Learn More]  LoginManagerParent.jsm:77:9
16:43:50.568 [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWebBrowserPersist.savePrivacyAwareURI]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://global/content/contentAreaUtils.js :: internalPersist :: line 571"  data: no]  (unknown)
16:43:50.614 [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIAnnotationService.setPageAnnotation]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://app/modules/DownloadsCommon.jsm :: onDownloadChanged :: line 781"  data: no]  (unknown)

**Comment by lovasoa** [comment]
This doesn't look like an error in dezoomify. This looks like an error in firefox or one of his modules.

**Comment by Sylbo** [comment]
OK, if you cannot reproduce the problem and this doesn't look like a Dezoomify error, perhaps it's a local problem with this machine. I'm gonna try with another computer and/or reinstalling Firefox. Thanks!

**Comment by lovasoa** [comment]
I would be very careful, it looks like you have undesired code running on your computer. It might be a virus or an adware. I would advise not to use your credentials on any website until you figured out what is going on, and you are sure you got rid of it.

**Comment by lovasoa** [comment]
Oh, I've seen this *Failed - blob resource* too while experimenting today.
I reported the bug to firefox : https://bugzilla.mozilla.org/show_bug.cgi?id=1318917
In the meantime, a workaround that worked for me is to disable *multi-process* (Electrolysis) in firefox.

**Comment by Sylbo** [comment]
The workaround didn't work for me. But today I tried Firefox Nightly 53, same platform, W10x64, and it works. It seems to be solved on future stable releases of FF. Thanks!
