### ISSUE TITLE
Help for downloading images from Motic Digital Slides

### ISSUE THREAD

**Issue by atultiwari** [lovasoa/dezoomify#103]
Hi,

Thank you for your work. I am sure, it must be helping a lot of people. Unfortunately, in my case it didn't work. I wanted to download some microscopic slide images for offline study purpose. But, it seems dezoomify does not support download from Motic Digital Slides Server.

For e.g. - following is the link of a microscopic image (free access)
[http://122.160.116.48/DSStore/HtmlViewer.aspx?Id=16247](http://122.160.116.48/DSStore/HtmlViewer.aspx?Id=16247)

One might need user id and password to access it.
User id - free
Password - free

I am no programmer (just a medical student). I tried my best and failed. Can you please help me on how to download zoomed high quality image from this link and/or links like this.

Thanks.
Regards,
Atul

**Comment by lovasoa** [comment]
Please see : https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages

**Comment by lovasoa** [comment]
![canvas-bad](https://cloud.githubusercontent.com/assets/552629/20649096/b0ab75c0-b4d0-11e6-8897-afc23b5b406e.jpg)

**Comment by atultiwari** [comment]
Thank you very much for the reply and your efforts. I will check this as soon as I get online from my laptop.

Regards.

**Comment by lovasoa** [comment]
You're welcome :wink:

**Comment by atultiwari** [comment]
Hi,
Thank you for the trick you provided.
It did work in some of the cases.

However in many of the cases there was no image shown, despite I see the progress bar for downloading and in some cases images load but not able to save them in Firefox. I have also set gfx.max-alloc-size value to 2000000000.

e.g. 
Image is loading but can't save (tileHandler.ashx?Id=19087)-
[http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://122.160.116.48/DSStore/code/tileHandler.ashx?Id=19087&imageId=-1&tierIndex=0&tileLevel=1&tilePositionX={{X}}&tilePositionY={{Y}}&contentType=image/jpeg&isCropped=1](http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://122.160.116.48/DSStore/code/tileHandler.ashx?Id=19087&imageId=-1&tierIndex=0&tileLevel=1&tilePositionX={{X}}&tilePositionY={{Y}}&contentType=image/jpeg&isCropped=1)


Image is not at all loading (tileHandler.ashx?Id=19110) -
[http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://122.160.116.48/DSStore/code/tileHandler.ashx?Id=19110&imageId=-1&tierIndex=0&tileLevel=1&tilePositionX={{X}}&tilePositionY={{Y}}&contentType=image/jpeg&isCropped=1](http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://122.160.116.48/DSStore/code/tileHandler.ashx?Id=19110&imageId=-1&tierIndex=0&tileLevel=1&tilePositionX={{X}}&tilePositionY={{Y}}&contentType=image/jpeg&isCropped=1)


Can you please help me again to find a way to download these.

Thanks.
