### ISSUE TITLE
Please support this site: https://scrolls.uchicago.edu

### ISSUE THREAD

**Issue by Huginn22** [lovasoa/dezoomify#104]
As the title said, please support this site: 
https://scrolls.uchicago.edu/scroll/demon-queller-zhong-kui-giving-his-sister-away-marriage

This image over 10000 pixel so I tried the bash script firstly, however, it didn't work. How could I solve this problem if I meet it again?  Isn't the bash script all-purpose? Hopping you could give me answers, I really appreciate it. :)

**Comment by lovasoa** [comment]
You can use the generic dezoomer
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://scrolls.uchicago.edu/sites/scrolls.uchicago.edu/files/scroll_bin/7160410/7-{{X}}-{{Y}}.jpg

**Comment by koxivega** [comment]
Excuse me if I interfere; how come I tried deeper zoom level, 8 and 9 but it doesn't work. 
For this image https://scrolls.uchicago.edu/scroll/profusion-flowers I tried
https://scrolls.uchicago.edu/sites/scrolls.uchicago.edu/files/scroll_bin/09.05.031/9-{{X}}-{{Y}}.jpg

7-{{X}}-{{Y}}.jpg loads everything in one single tile
8 and 9-{{X}}-{{Y}}.jpg don't show tiles assembling but bar goes in progress.

Does it happens only to me?
thanks

**Comment by Huginn22** [comment]
I tried the generic dezoomer which you suggested, but it still couldn't work. When the progress bar went 99%, it stopped. And it just showed 3 pieces of the image from the beginning to the end.

**Comment by Huginn22** [comment]
It happens to me too... 😞 @koxivega

**Comment by Huginn22** [comment]
Could you tell me how to get higher quality version of this image? Because when I instead 8 for 7, the image just a blank page. I really need your help, thank you. @lovasoa

**Comment by lovasoa** [comment]
If you have problems because the image is too large, then you should read our wiki page about very large images. It has a few advices that may help you.

**Comment by lovasoa** [comment]
I just tested [dezoom.sh](https://github.com/lovasoa/dezoom.sh) to download a small part of your image, and it works fine.

**Comment by lovasoa** [comment]
![result-low](https://cloud.githubusercontent.com/assets/552629/21013221/a27a85b8-bd72-11e6-8532-4befb42e92a9.jpg)

**Comment by Huginn22** [comment]
Yeah,I downloaded the image with the other computer. Turns out it's my internet speed problem. I think I know what should I do. Thank you very much for making time for answering my questions. 😊
