### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gryfmedia** [lovasoa/dezoomify#106]
Dezoomfy is not working with this page

http://www.webumenia.sk/dielo/SVK:GMB.C_4349/zoom

**Comment by lovasoa** [comment]
It works just fine. It uses the DeepZoom protocol.

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://www.webumenia.sk/fcgi-bin/iipsrv.fcgi?DeepZoom=/GMB/X4400/GMB--C_4349--1_1--_2014_02_06_--L2_WEB.jp2.dzi
