### ISSUE TITLE
Failed - blob resource

### ISSUE THREAD

**Issue by lollyman59** [lovasoa/dezoomify#107]
Dear Sir, 

I have always been using dezoomify quite satisfactory via Firefox, until recently.  When I try to dezoomify a picture I can get it completely displayed on my computer screen but I can not safe it on my file.  The error read "Failed - blob resource".  If my understanding is correct, this is Firefox's issue.  However, do you have any suggestion on how I can get by with this problem.  Your response to the subject is highly appreciated.

Best Regards,
Amornvat

**Comment by lollyman59** [comment]
Look like someone have the same problem: https://bugzilla.mozilla.org/show_bug.cgi?id=1318271

**Comment by lovasoa** [comment]
I reported this issue too: https://bugzilla.mozilla.org/show_bug.cgi?id=1318917

A workaround is to disable e10s

**Comment by lollyman59** [comment]
Thanks  very much for your prompt response, as always.  I tried to find way to disable e10s, somehow I can't do it straightforwardly in my current Firefox (Version 50.0.2).  At this moment I used Google Chrome instead and dezoomify seems to be working OK except in some large dowloaded file when the Chrome ignored to the right click and "save image as..." completely.

**Comment by lovasoa** [comment]
Then you should report a bug to chrome too :)
