### ISSUE TITLE
Difficult deep zoom image

### ISSUE THREAD

**Issue by ezekielar** [lovasoa/dezoomify#109]
`http://www.cinematheque.fr/fr/catalogues/appareils/collection/camera-film-35-mmap-10-2520.html`

Cannot download original size images.
Please help!
Many thanks!

**Comment by lovasoa** [comment]
You can use the generic dezoomer:

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://www.cinematheque.fr/fr/catalogues/appareils/data/deepzoom/183922/183922-hd_files/12/{{X}}_{{Y}}.jpg

**Comment by lovasoa** [comment]
![index](https://cloud.githubusercontent.com/assets/552629/20969816/258803f6-bca4-11e6-83dc-d544e06d0e3b.jpg)

**Comment by ezekielar** [comment]
I cannot know how to thank you!

**Comment by lovasoa** [comment]
De rien :)
