### ISSUE TITLE
First version of your link http://jk.g6.cz/dezoomify.html

### ISSUE THREAD

**Issue by Horemheb** [lovasoa/dezoomify#11]
Hello Lovasoa
I am having always the same issue with this old link of urs. When I right click and select save image mozilla opens a save page link which is blank.. many times it does like this and only sometimes the window opens correctly and I can save the page... Any solution to this issue?
I am downloading from this manuscript: http://www1.arkhenum.fr/images/bm_verdun_ms/ms/OEB/MS0107/images/B555456201_MS0107_042r
Your old link worked for that.. but I am now getting quite always a blank page when I try to save in Mozilla.. 
You know I didn't want to bother you with another issue.. this link seemed to work just fine. In the new dezoomify page this manuscript doesn't seem to be downloadable so I was using the old link but I began getting this issue... :-|
Thanks! 
Yours sincerely
HoremHeb

**Comment by lovasoa** [comment]
The link you give is a mirror that was created by someone else some time ago while I had troubles with my host provider. I have [asked him to update his mirror](https://commons.wikimedia.org/wiki/User_talk:Jklamo#Your_mirror_of_dezoomify), but he still hasn't done it.

So please use http://ophir.alwaysdata.net/dezoomify/dezoomify.html, at least until he updates his mirror.

If you have a recent version of firefox, then you should file a new bug on [their bugzilla](https://bugzilla.mozilla.org/). What you describe doesn't look like a problem in dezoomify, but like a problem in firefox.

**Comment by Horemheb** [comment]
No selection works for that manuscript in the "new" mirror.. Already tried them all :(

**Comment by Horemheb** [comment]
Yeah that's a mozilla bug. It sometimes happens with the "new" mirror as well. I thought you could advise me something to go round it :)

**Comment by lovasoa** [comment]
No, but firefox is a free and open-source software, you really should fill a bug report on their bugzilla.

**Comment by lovasoa** [comment]
What do you mean by 
> No selection works for that manuscript in the "new" mirror

?

**Comment by Horemheb** [comment]
I get no image no matter what I select among the choices, dezoomify, seadragon, PFF, etc.
http://www1.arkhenum.fr/images/bm_verdun_ms/ms/OEB/MS0107/images/B555456201_MS0107_042r

**Comment by lovasoa** [comment]
I get a 403 Forbidden when I try to access http://www1.arkhenum.fr/images/bm_verdun_ms/ms/OEB/MS0107/images/B555456201_MS0107_042r ...

**Comment by Horemheb** [comment]
yeah that's the link I copy paste in the old mirror and download the image, but it doesn't work directly
the manuscript is at this web page http://www1.arkhenum.fr/images/bm_verdun_ms/ms/OEB/MS0107/index.html

**Comment by lovasoa** [comment]
OK, I get it, this is a regression.
You should have opened an issue earlier! ;)

I am going to fix this. Until I fix the bug you can use the full url of the xml file in the latest version of zoomify:
http://www1.arkhenum.fr/images/bm_verdun_ms/ms/OEB/MS0107/images/B555456201_MS0107_042r/ImageProperties.xml

**Comment by Horemheb** [comment]
Ok thanks! You know old link worked but I couldn't save pages anymore thanks to Mozilla.. hopefully I won't get the same issue in the new mirror!!!
:(

**Comment by lovasoa** [comment]
Don't hope too hard, as I said, I think the problem is on firefox's side. You really should tell them about your issue!

**Comment by Horemheb** [comment]
Yeah there's the blank window and the game is over LOL. I googled this issue.. they say how to overcome it but.. not much luck :( Thank You!
With your hints with Gallica I could save it in a Paint Image. LOL. I chose save copy instead of save image and copied-pasted it on a blank paint bmp ;) Here this way doesn't work. right clicking just gives me the save option and not the copy... :(

**Comment by lovasoa** [comment]
Yes, because with gallica, you can have direct access to the image. When you have to use dezoomify, what you can is not an image, but an HTML canvas element.

**Comment by lovasoa** [comment]
And as I said, you really should **report a bug to mozilla**.

**Comment by Horemheb** [comment]
Yeah, I send them the report twice. But many seem to have the same problem and no mozilla new version seems to solve it.. I can have a try with older mozilla versions... maybe one works.. thanks for ur precious help anyway! :D

**Comment by lovasoa** [comment]
What do you mean you have reported it twice ? What is the URL of your report ?
I don't think trying old versions of firefox is very useful.

I fixed the bug and uploaded the new version. Now, you can enter URLs such as the one you posted in dezoomify, and it works.

**Comment by Horemheb** [comment]
U r right. Older version don't solve the problem. I went thru the see image option. Mozilla realised it couldn't open and so a pop up window appears and u can add a note and forward the issue directly to Mozilla..

**Comment by Horemheb** [comment]
There IS a Way Out. When I get the blank save window, I shut mozilla down get into the options and change the download folder. Every time I get the blank window. It seems to work. Of course the download takes longer but there's no way to get mozilla continously working with the dezoomify page I am afraid.. :)

**Comment by ezoombook** [comment]
There is one way.

**Comment by lovasoa** [comment]
There is one way. It's getting in touch with mozilla so that they fix the bug in firefox. You have one occasion to contribute to a major free software, I think you should do it.

**Comment by lovasoa** [comment]
https://bugzilla.mozilla.org/
