### ISSUE TITLE
Nautical chart that's zoomify, I'm stumped

### ISSUE THREAD

**Issue by toddnbrown** [lovasoa/dezoomify#110]
I'm working on a christmas gift for my grandfather. Long story short, I really need to get this nautical chart, so I can customize it and frame it for him. I can't seem to get the de-zoomify to work. Any help is greatly appreciated. 

http://www.nauticalchartsonline.com/chart/zoom?chart=131-00-1863

**Comment by macdorli** [comment]
http://www.nauticalchartsonline.com/tiles/131-00-1863/ImageProperties.xml

Try this ;)

**Comment by toddnbrown** [comment]
Thank you so much. That worked like a charm!
