### ISSUE TITLE
Support for libwww.freelibrary.org

### ISSUE THREAD

**Issue by macdorli** [lovasoa/dezoomify#111]
I tried all the methods .... I hope. :)

http://libwww.freelibrary.org/digital/item/zoom/17273

Thanks

**Comment by lovasoa** [comment]
The generic dezoomer works:

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://gis.freelibrary.org/erdas-iws/erdas/imagex/?request=image&cache=true&transparent=true&type=jpg&l=0&tx={{X}}&ty={{Y}}&ts=256&fill=FFFFFF&quality=100&layers=%2Ffoc%2Fpdce%2Fecw%2Fpdce03907.ecw&style=default&srs=EPSG:0

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/21011044/cfbef536-bd68-11e6-92d3-ede8346a5130.jpg)

**Comment by macdorli** [comment]
of course {{X}} {{Y}} you're really cool :)
