### ISSUE TITLE
balat.kikirpa.be - any chance?

### ISSUE THREAD

**Issue by gregg128** [lovasoa/dezoomify#115]
Hi,
Is there any chance to support http://balat.kikirpa.be/cgi-bin/hrbroker.pl?f=b135612&d=c2950b09fa85830244be1073f9f583be 
?
Thanks in advance!

**Comment by lovasoa** [comment]
It's already supported :smiley: 

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://balat.kikirpa.be/deepzoom/749/tmp/deepzoom0NlaMpgc

**Comment by lovasoa** [comment]
You should read our https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#the-page-uses-an-image-viewer-supported-by-dezoomify-but-dezoomify-still-doesnt-work-what-to-do-
