### ISSUE TITLE
Cannot save canvas in Firefox 50.1.0

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#116]
I usually use Firefox + dezoomify to save zoomable images, firefox support dezoomify much better than chrome, in chrome, even size as NGL  images cannot be saved, while I can save much bigger images in firefox. But recently I found that firefox version high than 47 has some problem with dezoomify, some big images can be saved in version 47 cannot be saved in 48,49... and when I upgrade to 50, things became worse, I even cannot save a single canvas file,  I understand this is not dezoomify's  problem, anyone else notice the problem? Now I stay with firefox 47.

**Comment by lovasoa** [comment]
And did you try the gfx.malloc-size trick described in the FAQ?

16 января 2017 г. 13:53:36 GMT+03:00, dancorpse <notifications@github.com> пишет:
>I usually use Firefox + dezoomify to save zoomable images, firefox
>support dezoomify much better than chrome, in chrome, even size as NGL 
>images cannot be saved, while I can save much bigger images in firefox.
>But recently I found that firefox version high than 47 has some problem
>with dezoomify, some big images can be saved in version 47 cannot be
>saved in 48,49... and when I upgrade to 50, things became worse, I even
>cannot save a single canvas file,  I understand this is not dezoomify's
> problem, anyone else notice the problem? Now I stay with firefox 47.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lovasoa/dezoomify/issues/116

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by lovasoa** [comment]
Maybe you should make a detailed bug report to Firefox (and to chrome). 

16 января 2017 г. 13:53:36 GMT+03:00, dancorpse <notifications@github.com> пишет:
>I usually use Firefox + dezoomify to save zoomable images, firefox
>support dezoomify much better than chrome, in chrome, even size as NGL 
>images cannot be saved, while I can save much bigger images in firefox.
>But recently I found that firefox version high than 47 has some problem
>with dezoomify, some big images can be saved in version 47 cannot be
>saved in 48,49... and when I upgrade to 50, things became worse, I even
>cannot save a single canvas file,  I understand this is not dezoomify's
> problem, anyone else notice the problem? Now I stay with firefox 47.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lovasoa/dezoomify/issues/116

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by dancorpse** [comment]
I've not tried gfx.max-alloc-size for this problem, bcs the images can be displayed fully, but cannot save as png. I've tried gfx.max-alloc-size for those very large images displayed as blank.

**Comment by lovasoa** [comment]
These problems seem to be fixed in firefox nightly (53). It can save very large canvas (using the gfx trick).

You can update to nightly (but the browser might be otherwise buggy), or just wait until firefox 53 is released.

**Comment by dancorpse** [comment]
Thanks, I'll have a try!
