### ISSUE TITLE
maps.hungarica.hu

### ISSUE THREAD

**Issue by trajano12345** [lovasoa/dezoomify#118]
https://maps.hungaricana.hu/en/MOLTerkeptar/2274/view/?bbox=-4495%2C-4910%2C8499%2C-31

plz...any idea ?
thx

**Comment by psinacio** [comment]
Have you managed to download it?

**Comment by lovasoa** [comment]
Better late then never ! I just added support for hungaricana. You URL now works natively in dezoomify:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://maps.hungaricana.hu/en/MOLTerkeptar/2274/view/?bbox=-4718%2C-5938%2C8722%2C997

![canvas](https://user-images.githubusercontent.com/552629/70159726-aae33800-16b9-11ea-92dc-cf27825f9c3b.jpg)

**Comment by lovasoa** [comment]
Hungaricana has a scheme where it encrypts its tile URLs, it took some work to figure out exactly what they were doing. See #346. I hope the new dezoomer will be useful...

**Comment by RerumFontes** [comment]
Any idea?
https://archives.hungaricana.hu/hu/charters/view/176471/?pg=0&bbox=961%2C-5278%2C4589%2C-2416

**Comment by RerumFontes** [comment]
Thanks!

**Comment by trajano12345** [comment]
hi, 
plz, any idea ?thx
https://maps.hungaricana.hu/en/OSZKTerkeptar/2115/view/?pg=0&bbox=-1611%2C-11676%2C20292%2C247  
https://maps.hungaricana.hu/en/OSZKTerkeptar/2115/view/?pg=1&bbox=-1409%2C-11577%2C20493%2C346 
https://maps.hungaricana.hu/en/OSZKTerkeptar/2115/view/?pg=2&bbox=-291%2C-11133%2C21612%2C791
    En jueves, 12 de diciembre de 2019 8:33:42 UTC, RerumFontes <notifications@github.com> escribió:  
 
 
Thanks!

**Comment by lovasoa** [comment]
Oh, the format of these pages is a little different from the others... I'll see if I find the time to work on it.

In the meantime, you can still use your browser's network monitor to locate the image metadata file URL (a `.ecw` file), and give that to dezoomify.

In your example the URL is `https://static-cdn.hungaricana.hu/tile/imagesize/charters/olpic/036800/DL_036630/DL_036630_orig_r.ecw`, and it works with dezoomify:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://static-cdn.hungaricana.hu/tile/imagesize/charters/olpic/036800/DL_036630/DL_036630_orig_r.ecw

**Comment by RerumFontes** [comment]
Thanks a lot, it's working fine!

**Comment by lovasoa** [comment]
Ok, the new format wasn't hard to figure out. It's working now:
https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://archives.hungaricana.hu/hu/charters/view/176471/?pg=0&bbox=961%2C-5278%2C4589%2C-2416

Don't forget to hard-refresh the page to get the latest version.

**Comment by RerumFontes** [comment]
So useful!
Thank you again!

**Comment by trajano12345** [comment]
hi,https://maps.hungaricana.hu/en/OSZKTerkeptar/2115/view/?pg=0&bbox=-1611%2C-11676%2C20292%2C247 


I can't locate the image metadata file URL (.ecw file), to give that to dezoomify.....thx alot
    En jueves, 12 de diciembre de 2019 11:50:41 EET, Ophir LOJKINE <notifications@github.com> escribió:  
 
 
Ok, the new format wasn't hard to figure out. It's working now:
https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://archives.hungaricana.hu/hu/charters/view/176471/?pg=0&bbox=961%2C-5278%2C4589%2C-2416

Don't forget to hard-refresh the page to get the latest version.

**Comment by lovasoa** [comment]
@trajano12345 : I fixed dezoomify. Now you can enter your URL directly into dezoomify, without having to look for the `.ecw`:


https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://maps.hungaricana.hu/en/OSZKTerkeptar/2115/view/?pg=0&bbox=-1611%2C-11676%2C20292%2C247


Also, when you reply by email, can you please remove the previous messages quotes that your email agent seems to be adding automatically ? This will make the thread easier to follow.

**Comment by trajano12345** [comment]
you are very kind, thank you .. but it doesn't work for meT

**Comment by lovasoa** [comment]
Please be more specific !
If something doesn't work, then you should make a detailed bug report, listing exactly what you are doing, and what the results are. You can attach screenshots to make your report more explicit.  We have a bug report template that can help:

https://github.com/lovasoa/dezoomify/issues/new?assignees=lovasoa&labels=bug&template=1_bug_report.md&title=%5Bbug%5D
