### ISSUE TITLE
Additional support for kbr.be

### ISSUE THREAD

**Issue by philip2011** [lovasoa/dezoomify#120]
Hi,  is there any way to dezoomify this: http://uurl.kbr.be/1040094 (same as: http://viewerd.kbr.be/gallery.php?map=A/1/7/3/0/1/7/7/)?

This is also the Royal Library of Belgium which should be supported already through xLimage, but doesn't seem to work...

Thanks!

**Comment by lovasoa** [comment]
Looks like they now use [ajax-zoom](http://www.ajax-zoom.com/)

**Comment by Marrazo** [comment]
Has anybody been successful in figuring this out? I've been trying to find a backdoor for days now, but haven't been successful despite the large amount of available documentation (.ajax-zoom.com/index.php?cid=docs) .

**Comment by lovasoa** [comment]
Well it wasn't easy. I managed to download it with [dezoom.sh](https://github.com/lovasoa/dezoom.sh), but I had to add a new parameter to it. The server refuses the download if you don't have the right Referer HTTP header.

### Command used

```sh
./dezoom.sh -X 13 -Y 16 -p '--referer=http://viewerd.kbr.be/gallery.php?map=A/1/7/3/0/1/7/7/' 'http://viewerd.kbr.be/display/A/1/7/3/0/1/7/7/zoomtiles/BE-KBR00_A_1730177_0000_00_00_0001/4-%X-%Y.jpg'
```

### Result

![img](https://user-images.githubusercontent.com/552629/39622096-497cf600-4f91-11e8-832d-e28b25986f9b.jpg)

**Comment by lovasoa** [comment]
Unfortunately, there is no way to implement this in dezoomify. Browsers do not allow faking the referrer header when loading an image from an external source.

**Comment by Marrazo** [comment]
I talked to somebody working at the Belgian Royal Library in the meanwhile. That person informed me they will most probably implement a download function for all out-of-copyright material (like Rijksmuseum Amsterdam) when they next update their viewer to tie in with their upcoming digital delivery/request platform. Huray.

**Comment by lovasoa** [comment]
A quick note for people who would still want to download images from kbr.be today. It can be done with [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs).

1. First you have to find out the tile URLs template. We have [a tutorial dedicated to that](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial)
2. At step 5 of the tutorial, when you found the tile URL template, launch dezoomify-rs from a terminal using the following command:
```sh
./dezoomify-rs --header 'Referer: https://viewerd.kbr.be/' 'https://viewerd.kbr.be/display/A/2/2/0/0/0/0/2/0000-00-00_00/zoomtiles/BE-KBR00_A-2200002_0000-00-00_00_0213/2-{{X}}-{{Y}}.jpg'
```
(where you replace `https://viewerd.kbr.be/display/A/2/2/0/0/0/0/2/0000-00-00_00/zoomtiles/BE-KBR00_A-2200002_0000-00-00_00_0213/2-{{X}}-{{Y}}.jpg` with the actual tile URL template you found)

**Comment by petrarch1603** [comment]
I followed these instructions and I get a "invalid image error: The image format could not be determined." error. Anybody else have this problem?

**Comment by BorisDekorte** [comment]
Hello Lovasoa,

I'm having problems as well with the kbr.be site ..

URL : [](https://viewerd.kbr.be/gallery.php?map=A/1/6/1/6/2/4/8/BE-KBR00_A_1616248_0000_00_00_0001.jpg)
URL from 1 tile : [](https://viewerd.kbr.be/display/A/1/6/1/6/2/4/8/zoomtiles/BE-KBR00_A_1616248_0000_00_00_0001/4-0-0.jpg)

So, in dezoomify-rs.exe I enter : 
dezoomify-rs --header "Referer: https://viewerd.kbr.be/display/A/1/6/1/6/2/4/8/zoomtiles/BE-KBR00_A_1616248_0000_00_00_0001/4-{{X}}-{{y}}.jpg"

This results is following error : 
" ERROR PNG encoding error: Zero width not allowed "

![Screenshot-error](https://user-images.githubusercontent.com/86778933/124114654-1d222700-da6d-11eb-86ce-8b2f8c7651a7.JPG)

Hope you can help me out.
Great extension so far !! 

Boris

**Comment by lovasoa** [comment]
@BorisDekorte : I moved your comment to dezoomify-rs: https://github.com/lovasoa/dezoomify-rs/issues/138
