### ISSUE TITLE
Tiles missing

### ISSUE THREAD

**Issue by Language-Lover** [lovasoa/dezoomify#121]
I'm having difficulty dezoomifying this image: http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://digital.bodleian.ox.ac.uk/inquire/viewer.dzi?DeepZoom=04a6bd8f-ef6a-4175-90b7-5d6cddb330ba.dzi
I've already downloaded several images from this site with no trouble at all, but this one presents an error message. The strange thing is that the image works very well on the original site. My question is, could it be determined where the error lies? And what can be done to remedy it?

BTW, I can still save the image, albeit with those tiles missing.

Here is the error message:
![digital bodleian ox ac uk error message](https://cloud.githubusercontent.com/assets/20437689/22495144/c21c1580-e80b-11e6-8183-99b48366f398.png)

Here is the image on the digital.bodleian.ox.ac.uk:
![digital bodleian ox ac uk](https://cloud.githubusercontent.com/assets/20437689/22495219/5bee3b52-e80c-11e6-9206-af97981d4fee.png)

**Comment by lovasoa** [comment]
Did you check you can access the tile mentioned in the error message ?

**Comment by lovasoa** [comment]
The tile is effectively not present.

 - http://digital.bodleian.ox.ac.uk/inquire/viewer.dzi?DeepZoom=04a6bd8f-ef6a-4175-90b7-5d6cddb330ba_files/13/7_21.jpg


```console
$ curl -v "http://digital.bodleian.ox.ac.uk/inquire/viewer.dzi?DeepZoom=04a6bd8f-ef6a-4175-90b7-5d6cddb330ba_files/13/7_21.jpg"
*   Trying 129.67.246.49...
* Connected to digital.bodleian.ox.ac.uk (129.67.246.49) port 80 (#0)
> GET /inquire/viewer.dzi?DeepZoom=04a6bd8f-ef6a-4175-90b7-5d6cddb330ba_files/13/7_21.jpg HTTP/1.1
> Host: digital.bodleian.ox.ac.uk
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: image/jpeg
< Server: Microsoft-IIS/7.5
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< Date: Wed, 01 Feb 2017 00:46:21 GMT
< Content-Length: 0
< cache-control: max-age=86400
< X-Varnish: 12105957 16646911
< Via: 1.1 varnish-v4
< X-Cache: HIT
< X-Cache-Hits: 4
< age: 0
< Access-Control-Allow-Origin: *
< Accept-Ranges: bytes
< Connection: keep-alive
< 
* Connection #0 to host digital.bodleian.ox.ac.uk left intact
```

The best you can do is downloading a lower-resolution tile from the same place in the image, and paste it on the image you downloaded using an image manipulation software like Gimp.

**Comment by lovasoa** [comment]
Here is one on the tile you can use:
```
http://digital.bodleian.ox.ac.uk/inquire/viewer.dzi?DeepZoom=04a6bd8f-ef6a-4175-90b7-5d6cddb330ba_files/12/1_10.jpg
```

![](http://digital.bodleian.ox.ac.uk/inquire/viewer.dzi?DeepZoom=04a6bd8f-ef6a-4175-90b7-5d6cddb330ba_files/12/1_10.jpg)

**Comment by Language-Lover** [comment]
Thank you for taking time to respond.
