### ISSUE TITLE
Bonhams

### ISSUE THREAD

**Issue by Pyb75** [lovasoa/dezoomify#123]
It would be great to download high-res images from Bonhams. They have a lot of paintings that would be interesting for Wikimedia.

http://www.bonhams.com/auctions/23917/#/aa0=1&MR0_length=100&w0=list&aj0=lot_number_asc&m0=0

A medium resolution is available here : http://images1.bonhams.com/image?src=Images/live/2017-01/03/24123872-4-1.jpg

But I didn't succeed to obtain high-resolution pictures.

**Comment by lovasoa** [comment]
![full size image](http://images1.bonhams.com/image?src=Images%2Flive%2F2017-01%2F03%2F24123872-4-1.jpg&width=3368&height=4728&autosizefit=0&format=jpg&strip=1&stats=0&tile=1:1)

**Comment by lovasoa** [comment]
The url is

```
http://images1.bonhams.com/image?src=Images/live/2017-01/03/24123872-4-1.jpg&tile=1:1
```

If you can want to download other images from the same site, open the source code of the page in which the image is in your browser.

Search for a part that looks like

```html
<img
			src="http://images1.bonhams.com/image?src=Images/live/2017-01/03/24123872-4-1.jpg&amp;width=640&amp;height=480&amp;autosizefit=1"
			alt="Adolphe Alexandre Lesrel (French, 1839-1929) A winning hand"
			title="Adolphe Alexandre Lesrel (French, 1839-1929) A winning hand"
			class="autogallery clickable"
			
		/>
```

Extract the image source url. In this case, this is `http://images1.bonhams.com/image?src=Images/live/2017-01/03/24123872-4-1.jpg&amp;width=640&amp;height=480&amp;autosizefit=1`

Replace the end of the url (everything after `.jpg`) by `&tile=1:1`. In this case, you get `http://images1.bonhams.com/image?src=Images/live/2017-01/03/24123872-4-1.jpg&tile=1:1`

**Comment by dancorpse** [comment]
This is quite useful!

**Comment by chengischan** [comment]
can someone help me do the same thing for images on Sothebys
