### ISSUE TITLE
Help for downloading images from http://trin-sites-pub.trin.cam.ac.uk

### ISSUE THREAD

**Issue by Andrew190** [lovasoa/dezoomify#124]
Dear Sir,

When trying to download 8 page: http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://trin-sites-pub.trin.cam.ac.uk/manuscripts/B_5_20/manuscript.php?fullpage=1&startingpage=8 
loaded only 1 page. 

Tell me what to do

Thank you so much

**Comment by lovasoa** [comment]
You have to follow the instructions in our wiki:
https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#the-page-uses-an-image-viewer-supported-by-dezoomify-but-dezoomify-still-doesnt-work-what-to-do-

You have to find the URL of the small meta-information page, and give that to dezoomify.

In your case:
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://trin-sites-pub.trin.cam.ac.uk/manuscripts/B_5_20/page_11.xml


But you don't really need dezoomify here, as all the pages are accessible directly in JPG here:
http://trin-sites-pub.trin.cam.ac.uk/manuscripts/B_5_20/
