### ISSUE TITLE
IIIF image size bug

### ISSUE THREAD

**Issue by jonkarni** [lovasoa/dezoomify#125]
Hi there.

http://rosetta.nli.org.il/delivery/DeliveryManagerServlet?dps_pid=IE28308320
I have tried to download images from this site but it seems that they changed the system so you wont be able to download full image:
http://iiif.io/api/image/2/level1.json

Can you add support for this files?
Thanks,
Jon

**Comment by lovasoa** [comment]
They use IIIF, that is alreay supported, but it looks like we have a bug.

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://iiif.nli.org.il/IIIF/FL28311264/info.json

**Comment by jonkarni** [comment]
I found that they have canceled the 'native' option.
but thanks!

**Comment by gregg128** [comment]
Hi,
I've tried to dl this: http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://iiif.nli.org.il/IIIF/FL28311264/info.json
I always get a chess-board like image. Any help? Thanks in advance!

**Comment by lovasoa** [comment]
> I always get a chess-board like image. Any help? Thanks in advance!

I think this is the same issue as #219
