### ISSUE TITLE
Cannot dezoomify this

### ISSUE THREAD

**Issue by miccomte** [lovasoa/dezoomify#126]
Hello,
I am trying to dezoomify: http://www.swaen.com/zoomV2.php?id=31329

Here is the answer I get, but I can access this URL:

Error: Unable to load tile. Check that your internet connection is working and that you can access this url:
http://www.swaen.com/zoomV2.php?id=31329

(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)
You should read our FAQ, and, if you think this is an issue with dezoomify itself, report a bug on the bugtracker .

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/23813351/8c7e9126-05ef-11e7-80ee-7208542846ae.jpg)

**Comment by lovasoa** [comment]
You can simply download the zif file from the page and convert it using https://github.com/lovasoa/ZIF/#

**Comment by miccomte** [comment]
Thanks a lot.
