### ISSUE TITLE
About the shell script

### ISSUE THREAD

**Issue by Huginn22** [lovasoa/dezoomify#127]
Hi,
I used the shell script which you created, but it happened like this.
For example: 
./dezoom.sh 30 20 "the address of the image.jpg"
Guessing xmax...
Failed to download '30'
Failed to download '30'
Failed to download '30'
Failed to download '30'
Failed to download '30'
....
I don't know what happened, so I have to bother you, excuse me.
Hoping you could tell me how so solve it, thank you so much.  😄

**Comment by Huginn22** [comment]
Here is the address of the image: http://image.dpm.org.cn/dyx.html?path=/tilegenerator/dest/files/image/8831/2011/3024/img0005.xml 
http://image.dpm.org.cn Maybe you could surpport this site too. @lovasoa

**Comment by lovasoa** [comment]
It's because you don't invoke the script correctly. Please read the documentation for this script: https://github.com/lovasoa/dezoom.sh#dezoomsh

If the script doesn't work, or you have suggestions, you should post them [there](https://github.com/lovasoa/dezoom.sh/issues) rather than here.

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/23831009/e6626a98-0728-11e7-939a-6af783078dce.jpg)

**Comment by Huginn22** [comment]
Thank you for your patience and bashing this image. I will try again, and pay attention to it next time. Have a good day. :)

**Comment by lovasoa** [comment]
Thank you, have a good day too !
If something isn't clear in the documentation, you can propose changes. In the repository, open [README.md](https://github.com/lovasoa/dezoom.sh/blob/master/README.md), and click on the little pencil at the top.

You can also contribute to the wiki: https://github.com/lovasoa/dezoom.sh/wiki
