### ISSUE TITLE
Artsy - Uncaught Error: Invalid JSON

### ISSUE THREAD

**Issue by adamanty** [lovasoa/dezoomify#129]
Firstly thanks for providing this tool, Iovasoa!

Not sure if you can help, but I'm not having much luck trying to pull the images from Artsy as described in the previous issue thread.

E.g. https://www.artsy.net/artwork/jean-francois-rauzier-barcelona-veduta

When I try 'Select automatically' it says:
Uncaught Error: Invalid JSON:
https://fusion.artsy.net/api/v1/artwork/jean-francois-rauzier-barcelona-veduta
(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)

With SeaDragon (DZI) selected it says:
TypeError: null is not an object (evaluating 'response.documentElement')

Any help would be greatly appreciated!
Adam

**Comment by EdoLom** [comment]
I confirm that dezoomify does not work (anymore) with Artsy: «Error: Invalid JSON: [URL here] (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)»
Using the developer tools does not allow to get the json file, as it is likely obtained through POST rather than the GET method.

**Comment by lovasoa** [comment]
See https://github.com/lovasoa/dezoomify-rs/issues/44

You can download images from artsy using the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial)
