### ISSUE TITLE
NYPL

### ISSUE THREAD

**Issue by awhizard** [lovasoa/dezoomify#13]
hey friend!
any chance to have it working with NYPL?
No way to get for example this:
http://digitalcollections.nypl.org/items/be0cb251-48d0-c292-e040-e00a18063de1
They are all PD images ..
Thank you!

**Comment by lovasoa** [comment]
It looks like it wouldn't be hard to add support for this. They use seadragon.

 * The base URL is of type `http://digitalcollections.nypl.org/items/{id}`
 * Then, you can get the image metadata by querying `http://access.nypl.org/image.php/{id}/tiles/config.js`
 * Then, you can access the tiles at `http://access.nypl.org/image.php/{id}/tiles/{rotation}/{zoom}/{x}_{y}.png`

**Comment by lovasoa** [comment]
I'll try to add this support to zoomify when I have more time, and preferably after I've found a way to refactor the existing code. Unless you really need support for NYPL soon.

**Comment by awhizard** [comment]
Thank you for looking! This is a great resource site.
No rush here .. take your time!!
I am doing some site hunting for historical images and books so, if you don't mind, I can add a topic with a list of those that doesn't work if you like the idea ;-)
And .. let me know if I can do something back for you (donation etc)
Have a great day ;-)

**Comment by lovasoa** [comment]
Oh, yes, it would be great if you could open an issue here for every site on which dezoomify doesn't work as expected!

I think the best donation you can do is put a link back to dezoomify on whatever work you are using it for. But this is not required :)

**Comment by awhizard** [comment]
I will for sure! ;-)

**Comment by lovasoa** [comment]
Looks like they offer a full resolution download, so dezoomify isn't needed here.
