### ISSUE TITLE
Invalid JSON error? Help please!

### ISSUE THREAD

**Issue by Nushles** [lovasoa/dezoomify#132]
Hello, I'm new to the website and having trouble downloading this image from Artsy.

https://www.artsy.net/artwork/herb-ritts-batman-back

Could someone please help me understand why I'm getting the following error?
Error: Invalid JSON: https://fusion.artsy.net/api/v1/artwork/herb-ritts-batman-back (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)

**Comment by Kinryu** [comment]
I see the website uses DZI (Deep Zoom Image). https://openseadragon.github.io/examples/tilesource-dzi/

**Comment by EdoLom** [comment]
I confirm that dezoomify does not work (anymore) with Artsy: «Error: Invalid JSON: [URL here] (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)»
Using the developer tools does not allow to get the json file, as it is likely obtained through POST rather than the GET method.

**Comment by lovasoa** [comment]
Duplicate of #129
