### ISSUE TITLE
ZIF image download problem

### ISSUE THREAD

**Issue by michaelw3** [lovasoa/dezoomify#135]
Hi,
thanks a lot for this useful tool!

i'm having trouble dezoomifying images from sites that use ZIF images, is it possible to use the tool for that?
if not could you add this option?

Thanks,
Michael

**Comment by lovasoa** [comment]
https://github.com/lovasoa/ZIF/#zif

**Comment by michaelw3** [comment]
@lovasoa thanks for the link, so if i understand correct you are in the middle of building a tool to dezoomify this type of files?

**Comment by lovasoa** [comment]
No, this tool has existed for a long time and is functional. 
-- 
Простите за краткость, создано в K-9 Mail.

**Comment by michaelw3** [comment]
so how can i dezoom the url that i have?

**Comment by lovasoa** [comment]
You download the ZIF file, and open it in the tool I gave you a link to.

**Comment by michaelw3** [comment]
OK got sorry, didn't really understood how in the first place.
thanks a lot!
