### ISSUE TITLE
Krpano Error

### ISSUE THREAD

**Issue by humodor** [lovasoa/dezoomify#136]
Creating an image from Krpano fails approximately in three quarters (60-80%). This is true for all tested URLs (XML files).

Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
https://cdn1.360cities.net/pano/rskphotography/00837201_OuterHarbor.jpg/cube/left/tile/512/4/1/11.jpg?orig=6b91bc5236d80cbc5bc9e0444e19d37d
(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)

Examples: http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://www.360cities.net/embed_iframe/outer-harbor.xml
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://www.360cities.net/embed_iframe/laukvik-midnight-sun.xml

Is there any solution, please?
Thanks ;)

**Comment by betavr** [comment]
Same problem here.

**Comment by betavr** [comment]
The problems is that Math.ceil is being used to calculate rows/cols instead of Math.round in zoommanager.js. One can fix this by adding these lines to krpano.js:

```
                                        data.tileSize = parseInt(maxlevel.parentElement.getAttribute("tilesize"));
                                        data.width = maxsize[0];
                                        data.height = maxsize[1];
+
+                                       data.nbrTilesX = Math.round(data.width / data.tileSize);
+                                       data.nbrTilesY = Math.round(data.height / data.tileSize);
+
                                        data.origin = firstUrl;
                                        data.url = maxlevel.firstElementChild.getAttribute("url");
                                        ZoomManager.readyToRender(data);
```

**Comment by lovasoa** [comment]
Wow, I don't know why this proposed fix did not catch my attention earlier. Thank you @betavr, and sorry for the 2 year delay 😬 !
