### ISSUE TITLE
US University Special Collections

### ISSUE THREAD

**Issue by Laowai75** [lovasoa/dezoomify#137]
Hi, thank you for this wonderful project as well as your support for my question.

Most American Universities use the same zooming tool (I think) to display their online digital collections, and dezoomify does not work. I tried all options available. Here's an example of an image on the University of Las Vegas website:

http://d.library.unlv.edu/cdm/singleitem/collection/hughes/id/631/rec/3

Error message:
Uncaught Error: Unable to find a proper dezoomer for:
http://d.library.unlv.edu/cdm/singleitem/collection/hughes/id/631/rec/3
(http://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)

I am using an up to date version of Chrome (Version 52.0.2743.82 m (64-bit)).

Can you please assist me?

Thank in advance!!!

**Comment by lovasoa** [comment]
![](http://d.library.unlv.edu/utils/ajaxhelper/?CISOROOT=hughes&CISOPTR=631&action=2&DMSCALE=80&DMWIDTH=9999&DMHEIGHT=9999&DMX=06&DMY=0)

**Comment by lovasoa** [comment]
You can access the full-size image directly from their website, you don’t need dezoomify.

1. Open the network inspector in your browser.
2. Zoom in the image.
3. Find the URL of a single tile. For instance: 
`http://d.library.unlv.edu/utils/ajaxhelper/?CISOROOT=hughes&CISOPTR=631&action=2&DMSCALE=200&DMWIDTH=512&DMHEIGHT=512&DMX=6656&DMY=5120&DMTEXT=&DMROTATE=0`
1. Replace the values in the url. Set `DMX=0`, `DMY=0`, `DMWIDTH=9999`, and `DMHEIGHT=9999`
1. This gives you http://d.library.unlv.edu/utils/ajaxhelper/?CISOROOT=hughes&CISOPTR=631&action=2&DMSCALE=200&DMWIDTH=9999&DMHEIGHT=9999&DMX=0&DMY=0&DMTEXT=&DMROTATE=0

**Comment by Laowai75** [comment]
Hi lovasoa,
Thank you! I will try it out!
Regards,
Laowai75
