### ISSUE TITLE
.dzi file from e-corpus.org doesn't work

### ISSUE THREAD

**Issue by awhizard** [lovasoa/dezoomify#14]
Hi there!
I am testing some sites and I found this one having an issue:
I find the .dzi path, past it into dezoomify and select seadragon.
It started loading the page but stops at 0% and stay there. nothing happens.
Links:
http://www.e-corpus.org/notices/102464/gallery/
http://www.e-corpus.org/notices/102464/gallery/773640.dzi

Thank you if you find the time to have a look and for your work!

**Comment by lovasoa** [comment]
Ok, I added some special code to handle e-corpus and now it works.
While viewing any image in e-corpus, you can click `Copy selected thumb link` (*sic*), and copy-and-paste the link that appears in dezoomify.

But `seadragon.js` looks more and more like a bunch of heterogeneous lines to support various websites. I wish I had more time, to clean everything up a little.

**Comment by awhizard** [comment]
Thanks friend! It works perfectly.
I know what you mean about time :-(

**Comment by lovasoa** [comment]
Looks like e-corpus doesn't work anymore
