### ISSUE TITLE
Add support for EoS Project

### ISSUE THREAD

**Issue by KaiMSchmitt** [lovasoa/dezoomify#140]
Any way to dezoomify this? http://eos.naturkundemuseum-berlin.de/sites/eos.naturkundemuseum-berlin.de/files/krpano/MFNB_Col_Scarabaeidae_Cetoniinae_D152/MFNB_Col_Scarabaeidae_Cetoniinae_D152.xml

**Comment by lovasoa** [comment]
Paste the URL in the text field, check *krpano*, and then click submit.

**Comment by KaiMSchmitt** [comment]
I already tried, got this failure message:
'NS_ERROR_FAILURE: 
(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:62)'

**Comment by lovasoa** [comment]
I just tried it, it works.

**Comment by KaiMSchmitt** [comment]
Tried again in other browser, worked perfectly. Thanks!

**Comment by lovasoa** [comment]
![canvas-30](https://cloud.githubusercontent.com/assets/552629/26033658/8535b5ec-38b8-11e7-8d45-0aad572d7325.jpg)
