### ISSUE TITLE
Requesting support for National Library of New Zealand

### ISSUE THREAD

**Issue by NickKiwi** [lovasoa/dezoomify#144]
Hello from Down Under! 

Would you please be able to help with the National Library of New Zealand? They use the so-called 'IIPMooViewer', which seems to be have been developed by the library itself. I tried all the options in Dezoomify but nothing works. Here's an example:

http://ndhadeliver.natlib.govt.nz/delivery/DeliveryManagerServlet?dps_pid=IE6521555&dps_custom_att_1=emu

I hope you can help.

Nick

**Comment by BartChris** [comment]
Hey Nick,

try this URL:
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://ndhadeliver.natlib.govt.nz/iipsrv?FIF=2013/02/28/ac_1/FL16263173&CNT=1&SDS=0,90&JTL=2,14

You need to retrieve the actual image souce which is in this case:
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://ndhadeliver.natlib.govt.nz/iipsrv?FIF=2013/02/28/ac_1/FL16263173&CNT=1&SDS=0,90&JTL=2,14

Best

**Comment by Laowai75** [comment]
It worked perfectly! Thanks for the instruction!
