### ISSUE TITLE
Digital Commonwealth

### ISSUE THREAD

**Issue by awhizard** [lovasoa/dezoomify#15]
Another great rich PD site!
https://www.digitalcommonwealth.org/search/commonwealth:7m01br33f

It seems I can get the full image searching for the source file and changing the last parameter

https://iiif.digitalcommonwealth.org/commonwealth%3A7m01br34q/0,0,1800,2637/450,/0/default.jpg
to for example
https://iiif.digitalcommonwealth.org/commonwealth%3A7m01br34q/0,0,1800,2637/5000,/0/default.jpg

Not so easy though ..
;-)

**Comment by lovasoa** [comment]
You can use "full" as a value for the image region and image width, which is easier: https://iiif.digitalcommonwealth.org/commonwealth%3A7m01br34q/full/full/0/default.png


The documentation of IIIF is here: http://iiif.io/

**Comment by awhizard** [comment]
it works! thank you!
