### ISSUE TITLE
Could you please add support for these ECW-based JPEGs ?

### ISSUE THREAD

**Issue by User5555555** [lovasoa/dezoomify#152]
Hi, I'm trying to download fully zoomed JPEGs from http://fotogrammi.regione.abruzzo.it/sampleiws/fotogrammi.asp?VOLO=VIGM54&&LOTTO=1&&STR_=48&&FOTO=1686

The tile URL seems to me http://fotogrammi.regione.abruzzo.it/ecwp/ImageX.dll?image?cache=true&transparent=true&type=jpg&l=0&tx=9&ty=9&ts=256&fill=FFFFFF&quality=60&layers=/VIGM54/1/48/1686.ecw&srs=EPSG:RAW but even trying a few variants, I can't seem to be able to download it at full resolution.

Could you help me?

Thank you

**Comment by lovasoa** [comment]
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://fotogrammi.regione.abruzzo.it/ecwp/ImageX.dll?image?cache=true&transparent=true&type=jpg&l=0&tx={{X}}&ty={{Y}}&ts=256&fill=FFFFFF&quality=60&layers=/VIGM54/1/48/1686.ecw&srs=EPSG:RAW

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/26662754/d904b86a-468e-11e7-9a5a-0088c601a6ca.jpg)

**Comment by lovasoa** [comment]
You're welcome )
