### ISSUE TITLE
seek support for https://www.dordrechtsmuseum.nl

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#153]
https://www.dordrechtsmuseum.nl/objecten/gezicht-op-dordrecht/ , what is the zoom tool for this site? I cannot find out the exact url for images.
Thanks!

**Comment by lovasoa** [comment]
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://images.memorix.nl/die/topviewjson/beeldbank/8703f0dc-a9c8-29d4-6294-2dc2784a4d51?checkIfTiled=1

The dezoomer is **TopViewer**.

![canvas](https://cloud.githubusercontent.com/assets/552629/26723064/6010b0cc-479b-11e7-9d6c-fcfb29e0d0bb.jpg)

**Comment by dancorpse** [comment]
Thanks! I've tried this url earlier: https://images.memorix.nl/die/topviewjson/beeldbank/8703f0dc-a9c8-29d4-6294-2dc2784a4d51?checkIfTiled=1 and Select automatically but it doesn't work, it'll only work by choosing TopViewer.
