### ISSUE TITLE
Script to download image instead of using "Save As?"

### ISSUE THREAD

**Issue by tarchuletta** [lovasoa/dezoomify#156]
I apologize if I'm asking this in the wrong venue, but I'm looking for a way to use Dezoomify to download images all within a script. I want to be able to download images without having to right click and "Save As." I've tried using wget but all it saves are the .js files and such.

Here's an example:

wget -m -r -np -nd http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://www.example.com/images/filename.xml

When using the script above, it downloads .js files and such, but none of them contain the image file.

Is what I'm trying to do even possible? Is there someway I can use Python to go to Dezoomify, enter the url of the xml file, and then simulate a "Save As" to download the image? I'm very new to all of this, so excuse my ignorance. 

Thanks.

**Comment by lovasoa** [comment]
What you are trying to do is possible.

dezoomify is a js application, and for obvious security reasons wget doesn't execute javascript code. So you can't directly download the image by pointing wget to the page.

You have to execute the js code from dezoomify locally. For that, you can use dezoomify node application.
If the URL pattern of the tiles of your image is simple enough, you can also use dezoom.sh.

Detailed instructions can be found on our wiki: https://github.com/lovasoa/dezoomify/wiki/Very-large-images

**Comment by tarchuletta** [comment]
Thank you very much for your reply. I was able to get it to work. For those running Mac OS X, to use the [node application](https://github.com/lovasoa/dezoomify/wiki/Very-large-images), you can do the following:

**Install Homebrew if you haven't already, paste the following into Terminal:**
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Install NodeJS:**
brew install node

**Next you have to install node-canvas, but you can only do this if you have Cairo and Pango installed. You can read about that [here](https://github.com/Automattic/node-canvas) here if you want, or just follow the instructions below.**

**To install Cairo and Pango:**
brew install pkg-config cairo pango libpng jpeg giflib

**Now you can install node-canvas:**
npm install canvas

**Download the script for Dezoomify from github like this:**
git clone https://github.com/lovasoa/dezoomify.git

**Go to the application repository:**
cd dezoomify/node-app

**Install dependencies:**
npm install

**Test to see if it worked by using the following in terminal:**
node dezoomify-node.js "http://www.hyper-photo.com/hyperpano/babel17/" "babel17.jpg"

**Locate node-app folder to find the .jpg (mine was in Users/myname/dezoomify/node-app).**

I've got another question though if that's okay. I don't know much about JavaScript, but when I was using wget I was able to have it access images that had similar names by using curly braces in the URL, e.g. www.example.com/images/photo{1..9}.jpg. wget would run this URL starting with www.example.com/images/photo1.jpg all the way up to www.example.com/images/photo9.jpg, so I'd get 9 images from one line of code. Is there a way to do this within the node-app? I've already tried the curly braces syntax, but to no avail.

**Comment by lovasoa** [comment]
Nice detailed instructions! Would you mind pasting them to our wiki, in order to help other potential mac users ?

**Comment by lovasoa** [comment]
The bracket syntax comes from your shell, not curl itself. Your shell replaces `str{1..2}` by `str1 str2` before launching the command. 

 You can simply use a for loop in your shell in order to download several images with dezoomify. 

`for i in $(seq 1 10); do node dezoomify.js http://example/$i result$i.jpg; done`

**Comment by tarchuletta** [comment]
Wow, that's awesome. Thank you! For me the syntax was only slightly different. I had to use the following:

`for i in {1..9}; do node dezoomify-node.js "http://example/${i}" "result${i}.jpg"; done`

That's so cool. And I'd be more than happy to add the instructions above to the wiki!
