### ISSUE TITLE
Support for new site http://digitool.is.cuni.cz

### ISSUE THREAD

**Issue by psinacio** [lovasoa/dezoomify#157]
Hello Everyone.

I would really appreciate some support here in order to dezoomify this link below.
I tried the generic one, but I was not able to get it....

http://digitool.is.cuni.cz:5881/ImageServer/dtlimagenav.jsp?filename=L2V4bGlicmlzL2R0bC9zdG9yYWdlX21hcC8yMDEyLzExLzMwL3ZpZXdfMi8xMDQ5MjY2

**Comment by incte8** [comment]
Try this: [http://digitool.is.cuni.cz:5881/ImageServer/imageserver?&res=1&viewwidth=2908&viewheight=3626&x=0&y=1413&imgClickX=600&imgClickY=1796&rotation=0&requestId=6&filename=L2V4bGlicmlzL2R0bC9zdG9yYWdlX21hcC8yMDEyLzExLzMwL3ZpZXdfMi8xMDQ5MjY2&imageActionSelect=imageclick%2Czoomin&display_plugin=&thumbnailActionSelect=thumbclick&collectionName=](url)
