### ISSUE TITLE
daguerreobase.org

### ISSUE THREAD

**Issue by awhizard** [lovasoa/dezoomify#16]
http://www.daguerreobase.org/en/browse
any chance to have this working?
It seems based on IIPIMAGE!

Thanks and have a nice weekend!

**Comment by lovasoa** [comment]
If it's really an iipimage server, then you don't need dezoomify. The protocol allows you to access the full image directly http://iipimage.sourceforge.net/documentation/protocol/

I won't have my computer with me during this weekend though, so I cannot check now.

**Comment by awhizard** [comment]
ok  mate, I will wait ;-)
thank you!

**Comment by lovasoa** [comment]
This is fixed, you can try with any image from daguerreobase.

**Comment by lovasoa** [comment]
Sorry for having taken an 8-month long weekend.

**Comment by awhizard** [comment]
hi friend! 
I've been MIA also :-)
Thanks for the job .. it works perfectly!!
