### ISSUE TITLE
Fail to download

### ISSUE THREAD

**Issue by Huginn22** [lovasoa/dezoomify#169]
Hi! I typed the address : http://content.ngv.vic.gov.au/col-images/zooms/Cf101035/TileGroup1/5-{{X}}-{{Y}}.jpg and use dezoomify to bash the image, but it didn't work. Hoping you could help, thank you so much. 😄 
Source of the image: https://www.ngv.vic.gov.au/explore/collection/work/53937/

**Comment by dancorpse** [comment]
https://github.com/lovasoa/dezoomify/issues/78, I've asked about images for the same website, try this: 
http://content.ngv.vic.gov.au/col-images/zooms/Cf101035/ImageProperties.xml.

**Comment by Huginn22** [comment]
Thank you so much! It worked! 😄   @dancorpse
