### ISSUE TITLE
Add Support for Gallica

### ISSUE THREAD

**Issue by Horemheb** [lovasoa/dezoomify#17]
Hello Lovasoa
Hope u'r doing fine
this trick of urs to access Gallica pages (http://gallicalabs.bnf.fr/iiif/ark:/12148/btv1b8449691v/f11/full/full/0/native.png) doesn't work anymore.
Can you fix it please?
when u can, of course!
Thanks!

**Comment by lovasoa** [comment]
OK, they seem to have removed the ability to select "full" as an image width. I might work on it later, but in the meantime, you can still select high values of width? For instance: http://gallicalabs.bnf.fr/iiif/ark:/12148/btv1b8449691v/f11/full/3100/0/native.png

**Comment by awhizard** [comment]
it seems they changed everything...
any chance for these stuffs?
http://gallica.bnf.fr/ark:/12148/btv1b8479004f
Thanks!

**Comment by jbcpollak** [comment]
:+1: Support for Gallica would be useful

**Comment by lovasoa** [comment]
They've changed their server again, and now the first link works again.

**Comment by lovasoa** [comment]
All instructions are at : https://fr.wikisource.org/wiki/Wikisource:Gallica

**Comment by Arekkusu1998** [comment]
This system for dezoom maps NO LONGER WORKS!!! Sigh ...
