### ISSUE TITLE
Problem with artsy's pictures

### ISSUE THREAD

**Issue by Heliodore70** [lovasoa/dezoomify#177]
I can't dezoomify artsy's pictures any more too.

**Comment by EdoLom** [comment]
I confirm that dezoomify does not work (anymore) with Artsy: «Error: Invalid JSON: [URL here] (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)»
Using the developer tools does not allow to get the json file, as it is likely obtained through POST rather than the GET method.

**Comment by lovasoa** [comment]
Duplicate of #129
