### ISSUE TITLE
geographicus.com: Error: Unable to find a proper dezoomer

### ISSUE THREAD

**Issue by RRSounds** [lovasoa/dezoomify#179]
Tried several possibilities, but could not get this site to work with dezoomify.
Returned following error message:

Error: Unable to find a proper dezoomer for:
https://www.geographicus.com/mm5/graphics/00000001/zoomify/NewJersey-kitchell-1860/ImageProperties.xml?noCacheSfx=1507452001481

(http://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)

**Comment by RRSounds** [comment]
My bad! Sorry. I didn't realize that anything following ".xml" must be deleted before submitting a URL to dezoomify.
Once I did that, we were golden. Thanks for all your work, David

**Comment by tubage170** [comment]
https://www.geographicus.com/mm5/graphics/00000001/zoomify/NewJersey-kitchell-1860/ImageProperties.xml
you can use this link,.

**Comment by efadallas** [comment]
Can anybody help me with the similar situation:

Error: Unable to find a proper dezoomer for: https://fineartamerica.com/featured/1881-lonesome-dove-map-texas-map-store.html (http://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)

**Comment by efadallas** [comment]
I also went to https://www.geographicus.com and try to locate the image of NewJersey-kitchell-1860 to see if I can figure out how you come up with the URL https://www.geographicus.com/mm5/graphics/00000001/zoomify/NewJersey-kitchell-1860/ImageProperties.xml?noCacheSfx=1507452001481 but I have no clue. I copied any image URL to dezoomer directly but it didn't work.
