### ISSUE TITLE
Dezoomify was working OK until ...

### ISSUE THREAD

**Issue by lollyman59** [lovasoa/dezoomify#18]
Thanks for developing this Dezoomify program.  I have been using it until recently.  Somehow, it doesn't work for me when you update the screen to incoporate other "dezoomify" programs.  I regularly use, for example, http://www.christies.com/lotfinder/ZoomImage.aspx?image=http://www.christies.com/lotfinderimages/d59175/d5917534&IntObjectID=5917534&lid=1  However, it doesn't work recently.  I really appreciate for your time looking in this matter.

**Comment by lovasoa** [comment]
The url you give seems to work perfectly well on the latest version of dezoomify: http://ophir.alwaysdata.net/dezoomify/dezoomify.html

Can you please give more details about the issue ?

**Comment by lollyman59** [comment]
Thanks you very much for your quick reply.  I have tried again and ... 
Yes, it seems to work perfectly this time.  Somehow it didn't this 
morning (my time in Australia).  At the same time when I was trying to 
use the program, there was a message saying the Dezoomify account was 
suspended?   May be there was some glitch.  However, it works alright 
now.  And thanks again for your reply and for developing this wonderful 
program.

**Comment by lovasoa** [comment]
You're welcome.
And, yes, my web host account was suspended this morning. See #19.
I've requested an account on tuxfamily.org. If they accept, then I'll have a better quality host, that won't arbitrarily suspend my account, still for free. If they don't, then we might see that "account suspended" message again later.
