### ISSUE TITLE
gigapixels at museefabre website

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#182]
http://oeuvresgigapixels.museefabre.montpellier3m.fr/Mieris.html 
What zoom tool is this? I could not find out the proper image url.
Who can help?

**Comment by GH-2017** [comment]
Hi Dan,

it is Krpano Panorama Viewer v1.18.5.
Which is sth. easily established in FireFox, as the right mouse function isn't disabled by this zoom tool.
Here's the UR which Dezoomify uses after one selects krpano:
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://oeuvresgigapixels.museefabre.montpellier3m.fr/Mieris.html
It does load the corresponding tiles when launched, but on my machine next only displays a blank page.
I'm not convinced it is a memory issue, for when I try the same in IE11, I get an error message straight away,:
"Unable to get property 'getAttribute' of undefined or null reference
(http://ophir.alwaysdata.net/dezoomify/dezoomers/krpano.js:60)"
IE will not even start loading these tiles...
Maybe someone else has more luck?

**Comment by dancorpse** [comment]
Oh, dezoomify does not select automatically, need to select manually! But the same, loading blank tiles. This is maybe because of the the image is far too big, even if I've changed the gfx.max-alloc-size in FF to 2000000000, the page is still blank.

**Comment by GH-2017** [comment]
Hi Dan,

if the automatic selection doesn't function as expected, the user still has the possibility to pick the appropriate tool himself. When one knows which tool is used on a website, it seems logical to select it right awat, provided it is among the possible choices.
Too bad that available memory doesn't seem the issue. I have no clue why this image doesn't work. I fear this can only be answered by someone able to look into the loading/recomposing processes of the tool. I'm merely a user, like you.

GH-2017

**Comment by lovasoa** [comment]
Hello ! 
  I've [added support for krpano](https://github.com/lovasoa/dezoomify-rs/issues/50) in  [dezoomify-rs](https://lovasoa.github.io/dezoomify-rs/). SO now you can download even huge images that would make dezoomify in the browser crash.
