### ISSUE TITLE
please support new site

### ISSUE THREAD

**Issue by medlis** [lovasoa/dezoomify#184]
http://wakpp.vumop.cz/?core=zpravy&action=showZprava&kodKraj=VY&kodOkres=JIH&kodZprava=5715&cesta=VY/JIH/_017_JZD_Dobronin_001.pff

**Comment by lovasoa** [comment]
Zoomify already supports the PFF format, but this site wraps the PFF viewer in an iframe.
You have to provide the iframe URL to dezoomify and select "Zoomify PFF" as the format.

https://wakpp-db.vumop.cz/WAKPP/viewer.php?source=/zpravy/VY/JIH/_017_JZD_Dobronin_002.pff

![image](https://user-images.githubusercontent.com/552629/58544562-d1538280-8201-11e9-9ec8-7f1b5009c691.png)
