### ISSUE TITLE
Can't download images

### ISSUE THREAD

**Issue by Golbstein** [lovasoa/dezoomify#185]
Hello, 
I have tried to download the large image from the following link:
https://www.biomax.us/index.php?route=product/zoomify&park=30947
In chrome it gives error, and in iExplorer only 1/8 of the image is shown
how can I download the full image?

Thanks!

**Comment by dancorpse** [comment]
I tried in firefox, the canvas is loading blank tiles , even if I change the max-alloc-size to 2000000000, I think the image is far too huge...
