### ISSUE TITLE
Is the Dezoomify website having issues?

### ISSUE THREAD

**Issue by scouserdave** [lovasoa/dezoomify#188]
I can't seem to download images from a regular source using the .json file anymore. Please try yourself in case I'm mistaken. I'm using the ophir.alwaysdata.net/dezoomify/dezoomify.html page to download. Is there an alternative page I could use?

Thank you.

**Comment by scouserdave** [comment]
http://ophir.alwaysdata.net/ - "Account suspended"

**Comment by zhlynn86** [comment]
Account suspended happen again

**Comment by ar-jan** [comment]
I put up a copy of dezoomify for the time being, you can find it [here](https://dezoomify.neo.slimternet.nl/dezoomify.html).

**Comment by scouserdave** [comment]
Dear ar-jan, thank you very much!

**Comment by dancorpse** [comment]
Thanks! Really helpful! Seems lovasoa seldom come here currently.

**Comment by scouserdave** [comment]
I emailed lovasoa a couple of days ago, but no reply yet.

**Comment by dancorpse** [comment]
I'm a regular user of dezoomify tool but I have no knowledge of code, maybe we have to help each other here. I know another mirror http://jk.g6.cz/dezoomify.html, but it hasn't been updated for long time.

**Comment by lovasoa** [comment]
Hi, I'm here! I don't have a lot of time to take care of dezoomify at the moment, sorry 😬 ! But I reactivated the account.

If someone is ready to host the site officially and reliably, please make a sign !

**Comment by scouserdave** [comment]
Hi, please don't apologise. You have done a fantastic job. Thank you.

**Comment by dancorpse** [comment]
Always thanks for your awesome tool !
