### ISSUE TITLE
Account Suspended

### ISSUE THREAD

**Issue by awhizard** [lovasoa/dezoomify#19]
Hi friend!
It seems something is going wrong with the Dezoomify page!
It reports 'Account Suspended' :-(
http://ophir.alwaysdata.net/dezoomify/dezoomify.html

**Comment by lovasoa** [comment]
OK, I fixed it.

I'm really sorry for this issue. I'm using a free web host, that suspends my account when I don't connect often enough. But as I don't make any money with dezoomify, I don't really want to take a better quality, paid, host.

**Comment by awhizard** [comment]
you rock man!
I am not a developer BUT I was yet thinking to learn the how to :-))
thank you very much and have a great Sunday!

**Comment by lovasoa** [comment]
Thank you!

If you want to learn how to program, and want to contribute to dezoomify later, you can learn javascript on the mozilla developper network: https://developer.mozilla.org/en-US/Learn/Getting_started_with_the_web/JavaScript_basics
