### ISSUE TITLE
Digitool

### ISSUE THREAD

**Issue by jonkarni** [lovasoa/dezoomify#2]
Can you add support for the JTS? I think it uses Digitool.
Here is an example URL:
http://garfield.jtsa.edu:1801/webclient/DeliveryManager?pid=273552&custom_att_2=direct

Thank you!

**Comment by lovasoa** [comment]
The tool they use is not called digitool, but [aware image server](http://www.aware.com/imaging/archivepack.html), and it allows [direct image download](http://garfield.jtsa.edu:5881/ImageServer/imageserver?res=2&viewwidth=360000&viewheight=2500&x=0&y=0&filename=L2V4bGlicmlzL2R0bC9qM18xL2RpZ2l0b29sL2hvbWUvcHJvZmlsZS9zdG9yYWdlL2JpZ3N0cmVhbXMvMjAxNC8wNC8wMi9maWxlXzExLzI3Mzk0Mg%3D%3D).

The feature is just not exposed publicly on garfield.jtsa.edu. You just need to find, for each file that you want to download, its filename, width and height, and then hit:

http://garfield.jtsa.edu:5881/ImageServer/imageserver?res=2&viewwidth={{width}}&viewheight={{height}}&x=0&y=0&filename={{filename}}

It might not allow you to give full width and height, bu you'll never have more than 2 or 3 tiles to assemble.

To find the filename, you can right-click on the original page, then select "This frame -> Show this frame only" in firefox. The filename will be in the url of the page that appears.

**Comment by lovasoa** [comment]
This tool allows you to generate the images you want to download:

http://garfield.jtsa.edu:5881/ImageServer/awimagenav.jsp?res=3&x=0&y=700&viewheight=768&viewwidth=1024&rotation=0&fullimage=true&rootelement=Image&stylesheetpath=%2Fexlibris%2Fdtl%2Fu3_1%2Fdtle%2Ftomcat%2Fwebapps%2FImageServer%2Ftest.xsl&useplugin=false&title=Positano&filename=L2V4bGlicmlzL2R0bC9qM18xL2RpZ2l0b29sL2hvbWUvcHJvZmlsZS9zdG9yYWdlL2JpZ3N0cmVhbXMvMjAxNC8wNC8wMi9maWxlXzExLzI3Mzk0Mg%3D%3D&imgclickx=1888&imgclicky=2236&requestId=8&previousRes=3&thumbnail.x=120&thumbnail.y=222

Again, you need the (base64-encoded) filename.

**Comment by jonkarni** [comment]
THANKS!!!
But I have got to ask, how do I give that tool (http://garfield.jtsa.edu:5881/ImageServer/awimagenav.jsp?re....) other links to work with?
For example, I tried to take the filename from this link:
http://garfield.jtsa.edu:1801/webclient/DeliveryManager?pid=294656&custom_att_2=direct
But, when I replace it with the filename in the link you gave, i get error.

**Comment by jonkarni** [comment]
I have got it!
I narrowed the link you gave me to this:
http://garfield.jtsa.edu:5881/ImageServer/awimagenav.jsp?&viewheight=5979&viewwidth=4568&fullimage=true&filename={{filename}}%3D
and now when I give it other links, it works! 
Thank you so much for all the help!
JonKarni

**Comment by lovasoa** [comment]
The last `%3D` is part of `{{filename}}`. They simply encode their filenames in [base64](https://en.wikipedia.org/wiki/Base64), meaning that they often end with a `=` (coded `3D` in ascii).

I'm glad I could help.
