### ISSUE TITLE
Add Support for Issuu

### ISSUE THREAD

**Issue by Horemheb** [lovasoa/dezoomify#20]
Hello Lovasoa
Hope you're doing fine
of course first of all thanks for your valuable help!
I'd like to download pages or books from the website issuu and with ordinary downloaders I just get large thumbnails quality
Can dezoomify help?
Giving you an example of a magazine I'd like to download

http://issuu.com/baranes/docs/les_belles_heures_du_duc_de_berry__

Thanks for any help you might give

See you
HoremHeb

**Comment by lovasoa** [comment]
Hi!
Sorry for having taken so long.

I've taken a look at the issue. The website doesn't use any image tiling technique, so you won't need dezoomify.

Their images are contained in their swf files. Just inspect the network (ctr-maj-Q in firefox), download the swf file of the page you're interested in, then extract your image as jpg using a tool like [swfextract](http://wiki.swftools.org/wiki/Swfextract)
