### ISSUE TITLE
Dezoomify does not work with www.worcesterart.org images

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#203]
For this image: http://vps343.pairvps.com:8080/emuseum/media/view/Objects/6801/34794?t:state:flow=de7a5ce3-2625-4638-921a-935b493ed69c
the image path is: 
http://vps343.pairvps.com:8080/emuseum/internal/media/zoomifyDispatcher/DP2196/ImageProperties.xml
But dezoomify return with error message: TypeError: response is null.
And then I tried Generic dezoomer: 
http://vps343.pairvps.com:8080/emuseum/internal/media/zoomifyDispatcher/DP2196/TileGroup0/4-{{X}}-{{Y}}.jpg, image loading but failed at 98%, anyone can help?

**Comment by lovasoa** [comment]
I'm closing the issue since the URL is not accessible anymore. Sorry for not being able to help in time.

**Comment by lovasoa** [comment]
#350 also references emuseum
