### ISSUE TITLE
unable to loading images harvardartmuseums.org

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#204]
https://www.harvardartmuseums.org/collections/object/303728?position=2 this picture, the iiif image path should be:  https://idscache.harvardartmuseums.org/ids/iiif/17386548/info.json (Am I anything wrong for the path?), but dezoomify returned error message: Uncaught Error: Unable to load tile.
I'm aware that the image can be downloaded, but I'd like to have a try of the tool.

**Comment by MrChrisWin** [comment]
Harvard Museum offers an option to download it. The resolution from dezoomify is the same as download.

**Comment by lovasoa** [comment]
great, let's close this issue then
