### ISSUE TITLE
Support for http://embassyofthefreemind.com

### ISSUE THREAD

**Issue by Bobdreams** [lovasoa/dezoomify#209]
Hi, 

Many Thanks about this tool ! 

I can use with this site : 

http://embassyofthefreemind.com

Exemple : with this page : 

http://embassyofthefreemind.com/nl/collectie/online-catalogus/detail/c34331dd-ba64-2023-9684-af81394e5654/media/fb9eafbe-abd4-6100-4a4f-6878024e86ea

Is download juste the first page of the book, and note the page i ask... 

Someone can help me ? 

Many thanks

**Comment by BartChris** [comment]
You need to specify the path to the deepzoom xml.
https://images.memorix.nl/rit/deepzoom/fb9eafbe-abd4-6100-4a4f-6878024e86ea.dzi

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://images.memorix.nl/rit/deepzoom/fb9eafbe-abd4-6100-4a4f-6878024e86ea.dzi

**Comment by Bobdreams** [comment]
Hi, 

MANY THANKS ABOUT YOUR HELP !
