### ISSUE TITLE
www.lbi.org tricky

### ISSUE THREAD

**Issue by hannahteal** [lovasoa/dezoomify#215]
I tried replacing with {{X}}{{Y}} as per the tutorial, but cannot get it to work. Is this one of those impossible ones?

**Comment by dancorpse** [comment]
Can you give a image path for example?

**Comment by hannahteal** [comment]
Yes. Here's one:
http://digital.cjh.org/ImageServer/dtlscrollnav.jsp?filename=L3JlcG9zaXRvcnkvYmlnc3RyZWFtczYvbGJpLzIwMTgvMDEvMTcvbGJpXzEvNTYyOTEzNQ==&display_plugin=false&res=2

**Comment by dancorpse** [comment]
Hmmm, sorry, I have no idea for this zoomer, we need lovasoa 's help...

**Comment by lovasoa** [comment]
Simply replaceing x and y as per the tutorial seems to work for me:
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://digital.cjh.org/ImageServer/tileServer?filename=L3JlcG9zaXRvcnkvYmlnc3RyZWFtczYvbGJpLzIwMTgvMDEvMTcvbGJpXzEvNTYyOTEzNQ==&zoom=4&x={{X}}&y={{Y}}&rotation=0


![img](https://user-images.githubusercontent.com/552629/39620827-c714f61c-4f8c-11e8-8955-5c4fc992c4f1.jpg)
