### ISSUE TITLE
Doesn't open USGS geomaps

### ISSUE THREAD

**Issue by Stroop14** [lovasoa/dezoomify#216]
This used to work and for some reason now it doesn't. Please any help would be amazing.

https://ngmdb.usgs.gov/ngm-bin/pdp/zui_viewer.pl?id=34598

Thanks

**Comment by dancorpse** [comment]
Here is the path https://ngmdb.usgs.gov/img2/81000_81999/81605_1/ImageProperties.xml, try this.

**Comment by Stroop14** [comment]
It works you're a genius! Thank you very much!!!
