### ISSUE TITLE
NGA（national gallery of art) images

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#217]
Recently I noticed that the path for NGA zoomable images is not accessible. 
eg: https://www.nga.gov/image-zoomer.html?path=/public/objects/1/2/2/5/1225-primary-0-nativeres.ptif

the path should be https://media.nga.gov/fastcgi/iipsrv.fcgi?deepzoom=/public/objects/1/2/2/5/1225-primary-0-nativeres.ptif.dzi and the link returned: _Bad Request. Consult the IIIF Image Specifications or the IIP Protocol and try re-formulating the request,_ 
whereas dezoomify returned with TypeError: response is null

But the NGA image path used to work with dezoomify. I've tried NGA images before.

**Comment by lovasoa** [comment]
It seems to just work: http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/1/2/2/5/1225-primary-0-nativeres.ptif&SDS=0,90&JTL=6,155

**Comment by lovasoa** [comment]
![img](https://user-images.githubusercontent.com/552629/39627089-d95335a6-4fa4-11e8-8c2a-c98bd807c349.jpg)

**Comment by dancorpse** [comment]
Oh,yes, this works, thank you Lovasoa.

**Comment by Tricesimo** [comment]
I am also trying to download a painting from the NGA:
https://www.nga.gov/image-zoomer.html?path=/public/objects/4/6/5/2/1/46521-primary-0-nativeres.ptif#8:0.3219720658745049,0.2111803756476684

I see that there's 25 files similar to the one you suggested for dancorpse above, but when I try one, it loads very slowly to 100%, and then says "converting image" but doesn't go any further - screen remains blank. Is the image too large to be downloaded? I am using Firefox.
