### ISSUE TITLE
IIIF : blank space between tiles

### ISSUE THREAD

**Issue by zafrirron** [lovasoa/dezoomify#219]
One of the main reasons to use Dezoomify is retrieving original image ... in case of using 
{scheme}://{server}{/prefix}/{identifier}/info.json method... 
you get a single image with all tiles (separated)...it would be great to be able to get all tiles connected back to get the original image....will save lots of work.

thanks

**Comment by lovasoa** [comment]
This is not a feature, this is a bug in dezoomify.

**Comment by lovasoa** [comment]
Example URL:  I've tried to dl this: http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://iiif.nli.org.il/IIIF/FL28311264/info.json

**Comment by lovasoa** [comment]
It looks like the tile size advertised in [the metadata file](http://iiif.nli.org.il/IIIF/FL28311264/info.json) (1024) is not the same as the one returned by the server when requesting [the tiles](http://iiif.nli.org.il/IIIF/FL28311264/2048,4096,1024,1024/1024,1024/0/default.jpg) (576)

**Comment by lovasoa** [comment]
Fixed in https://github.com/lovasoa/dezoomify/commit/b75b8de5f81313900cf8f0d7cc794dec21e89bc8

**Comment by BartChris** [comment]
Thanks a lot! Do you know what is going on here:
http://iiif.nli.org.il/IIIF/FL49983028/info.json
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://iiif.nli.org.il/IIIF/FL49983028/info.json
?

**Comment by lovasoa** [comment]
Please open a different issue if what you describe is not related to this one. It looks like the server is returning non-square tiles, that are not supported by dezoomify. http://iiif.nli.org.il/IIIF/FL49983028/0,0,1024,1024/1024,1024/0/default.jpg
