### ISSUE TITLE
Phillips Auction

### ISSUE THREAD

**Issue by BBskies** [lovasoa/dezoomify#22]
Thank you for creating such a great service!

I was hoping to download the images from the Phillips auction website.
Such as this one: http://www.phillips.com/detail/RICHARD-PRINCE/UK010414/8
It seems to use deep zoom / openseadragon, but I can't seem to make it work.  I can't find the image path.
Do you think it's possible?
Unfortunately, I don't know how to do javascript myself.   
Many many thanks!

**Comment by lovasoa** [comment]
They don’t seem to be using any tiling system. The plain image is available directly on their server. For the example you give, it is on : http://www.phillips.com/Xigen/lotimg/Richard-Prince/UK010414/8/2000/4000.jpg


Each image is accessible at its own url : `http://www.phillips.com/Xigen/lotimg/{id}/2000/4000.jpg`, where `{id}` is the part of the url of the viewing page after `detail/`.

**Comment by lovasoa** [comment]
Oh, and if you want to see the image in the best resolution available, replace `2000` and `4000` by very high numbers.

So the url to use is `http://www.phillips.com/Xigen/lotimg/{id}/9999/9999.jpg`.

And for your example, it gives: http://www.phillips.com/Xigen/lotimg/Richard-Prince/UK010414/8/9999/9999.jpg

**Comment by BBskies** [comment]
Fantastic!  That is great, thank you very much!
So helpful!  I applied it to the other works on the site, and it works like a charm.
Thanks for replying so quickly.

**Comment by lovasoa** [comment]
You're welcome!
