### ISSUE TITLE
Problem loading images from https://maps.nls.uk

### ISSUE THREAD

**Issue by look2020** [lovasoa/dezoomify#221]
It was working one week ago. But now it does not work any more. Here are image links:
https://maps.nls.uk/view/101465395
https://maps.nls.uk/imgsrv/iipsrv.fcgi?iiif=/10146/101465395.jp2/info.json

Error message shown:
Error: Unable to load tile. Check that your internet connection is working and that you can access this url: undefined/0,0,256,256/256,256/0/native.jpg (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)

**Comment by dancorpse** [comment]
It does not work for me either...

**Comment by scouserdave** [comment]
Same issue. Please help. Thanks.

**Comment by lovasoa** [comment]
The problem should be fixed. See http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://maps.nls.uk/imgsrv/iipsrv.fcgi?iiif=/10146/101465395.jp2/info.json

Don't forget to clean your browser cache when retrying (Ctrl-Shift-R on firefox).

**Comment by scouserdave** [comment]
Thank you so much for your help. I love you!
