### ISSUE TITLE
Can't load zoom image from Encyclopaedia Universalis

### ISSUE THREAD

**Issue by Verra13** [lovasoa/dezoomify#223]
Hello. Can you help me load this image    https://www.universalis.fr/encyclopedie/jorg-haider/

**Comment by lovasoa** [comment]
Bonjour! This is not a tiled image, you don't need dezoomify.
The image is simply loaded from https://www.universalis.fr/medias/photo/ph00p114.jpg

In firefox, you can simply use the [Page info window](https://support.mozilla.org/en-US/kb/firefox-page-info-window) to find the images in a page and download them.
