### ISSUE TITLE
Leaflet Zoomify

### ISSUE THREAD

**Issue by bejb1** [lovasoa/dezoomify#224]
Hi! I am trouble dezoomify-ing the following link. 

http://toposvalbard.npolar.no/xflyfoto.html?lang=en&id=S36_2408

I tried using the generic replacing a file path with {{x}} and {{y}} but the way the set is constructed seems to be somewhat different than shown in the tutorial in that there are "tile groups." 

The page seems to be using something called Leaflet Zoomify.

Any thoughts, and thanks!

**Comment by bejb1** [comment]
Oh wait! I have figured out by using the ImageProperties.xml instead of the TileGroup subfolder URL

Best,

**Comment by lovasoa** [comment]
It uses the standard zoomify format:

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://toposvalbard.npolar.no/flyfoto/S36_2408a/ImageProperties.xml
