### ISSUE TITLE
Adding @dancorpse to the collaborators of this project

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify#226]
Hi @dancorpse !
  You have been very active (much more than me) on this project's issue pages lately. Would you like to be added to the project's collaborators ? This would notably allow you to add labels and close to other people's issues. And if you feel like it, you could even contribute code.

**Comment by dancorpse** [comment]
Thanks Lovasoa, that's fine, however I have to say, I do not have any knowledge about code, I'm a dezoomify user from years ago, I always have issues to ask myself, and at the same time, I'd like to help people here within my limited knowledge about your dezoomify tool.

**Comment by lovasoa** [comment]
Here it is, you have been added, you now just have to [accept the invitation](https://github.com/lovasoa/dezoomify/invitations).
