### ISSUE TITLE
Smithsonian Institutions 

### ISSUE THREAD

**Issue by awhizard** [lovasoa/dezoomify#227]
Hi there!
I love the challenges but this time I think it's too much for me LOL.
I tried in any way to get images from this site but no way! What I know is that they use Seadragon but I am unable to find any json or zif or such files.
Here you go:

http://collections.si.edu/search/detail/edanmdm:nmah_1442766?q=record_ID%3Anmah_1442766&record=1&hlterm=record_ID%3Anmah_1442766&inline=true

Any help please?

Thanks!

AW #

**Comment by lovasoa** [comment]
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://ids.si.edu/ids/viewTile/A/5cd/5cd26363ce50680e92f621436b7e0591_files/13/{{X}}_{{Y}}.jpg

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/39665847-81914942-509a-11e8-907d-891832e43a90.jpg)
