### ISSUE TITLE
Again on .ZIF files ..

### ISSUE THREAD

**Issue by awhizard** [lovasoa/dezoomify#23]
Hello there!
I had a look at your parser
http://lovasoa.github.io/ZIF/
mentioned in the issue 21
https://github.com/lovasoa/dezoomify/issues/21
but I am unable to get the zif here for example
http://juilliardmanuscriptcollection.org/manuscript/harmony-exercises/
maybe I missed something in searching it? :-/
Thank you for your help btw ;-)

**Comment by lovasoa** [comment]
While you are viewing the image using the  zoomify viewer in your browser, open the network inspector (ctrl-maj-Q in Firefox). You will see the url of the zif file appear.

I built my parser so that I can include it in zoomify later. But I don't really have a lot of time at the moment.

**Comment by lovasoa** [comment]
For your example, the file is here: http://manuscript.gallery/juilliard/zoomify/images/MACOX/MACOX_001.zif

**Comment by awhizard** [comment]
that's perfect! Thank you so much ;-)
have a nice day!
