### ISSUE TITLE
IIIF images - image slightly stretched?

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#233]
Not until recently, did I noticed that the images get by adding info.json for IIIF images were all slightly stretched. Here is an example: 

http://ophir.alwaysdata.net/dezoomify/dezoomify.html?dezoomer=on#https://images.britishart.yale.edu/iiif/b1c121ef-99a4-4ccd-be41-af7afcfe7f80/info.json

The image below: (I scale down it a bit, cos it's too large) 

![info](https://user-images.githubusercontent.com/19525152/39847263-35574058-5433-11e8-893c-4a0abf1688e6.jpg)

Whereas image get by method of replacing full for region and size: https://images.britishart.yale.edu/iiif/b1c121ef-99a4-4ccd-be41-af7afcfe7f80/full/full/0/native.jpg

(Same, I scale down the image)
![native](https://user-images.githubusercontent.com/19525152/39847814-30ecd0a2-5436-11e8-8685-a343d52a47c9.jpg)

The right end and bottom part of the first image is stretched comparing with the 2nd image! (2nd one should be the right image).

Who can tell the mystery?

Any the same with nationalmuseum stockholm images: 

http://ophir.alwaysdata.net/dezoomify/dezoomify.html?dezoomer=on#http://nationalmuseumse.iiifhosting.com/iiif/669e2f43fd3ad5a8a02fc2bc8781a90e51a652c5953de4bd71697f69bdbf909d/info.json

and 

http://nationalmuseumse.iiifhosting.com/iiif/669e2f43fd3ad5a8a02fc2bc8781a90e51a652c5953de4bd71697f69bdbf909d/full/full/0/default.jpg  -- (Why here I replaced by full, but the image is only 1000px?)

**Comment by lovasoa** [comment]
This should be fixed by #263. Please re-open if otherwise.

**Comment by dancorpse** [comment]
Thanks Lovasoa! The problem fixed!
