### ISSUE TITLE
can't dezoomify this site

### ISSUE THREAD

**Issue by dixonbg** [lovasoa/dezoomify#237]
Hi,
I'm trying to dezoomify this [link](https://www.sofia-agk.com/ServerFiles/Zoomify?url=esoft.portal%2FDRUJBA%20II-04.2018%2FPRZ.zif)
The .js says it is Zoomify 4.01 Pro
I had some success with a modified dezoomify-py (the Python version) a year ago. 
```
        image_path_regexes = [
            ('zoomifyImagePath=([^\'"&]*)[\'"&]', 1),
            ('var\s+url\s?=\s?\'([^\']+)\'[^\']+\'(/\?url=[^\']+)',None)] #new regex
        for rx, group in image_path_regexes:
            m = re.search(rx, content)
            if m:
                if group:
                    image_path = m.group(group)
                else:  
                    image_path = ''.join(m.groups())
                break
```
That was a year ago and I had to learn some Python to make the change.
Now, I can't get it to work. I can't host php, but I've tried the hosted version - again with no success.
They most have changed something... Version maybe?
Can anyone take a quick look and tell me what is so specific about this site?

Thanks

**Comment by lovasoa** [comment]
This is a ZIF file. It can be simply downloaded at https://www.sofia-agk.com/ServerFiles/DisplayZoomify/?url=esoft.portal/DRUJBA%20II-04.2018/PRZ.zif and opened with [this online zif file reader](http://lovasoa.github.io/ZIF/). 

See [more about the ZIF format here](https://github.com/lovasoa/ZIF/#).

**Comment by lovasoa** [comment]
![default](https://user-images.githubusercontent.com/552629/40320120-d43764fa-5d2a-11e8-84c9-31ee42140f41.jpg)

**Comment by lovasoa** [comment]
You can get the download URL just by looking at the network tab of your browser's web console.
