### ISSUE TITLE
Big Images won't save.

### ISSUE THREAD

**Issue by awhizard** [lovasoa/dezoomify#24]
Hi friend!
I am playing a bit with dezoomify and I am having problems saving big images.
Tested with Firefox, Chrome and IE.
The image is correctly dezoomified BUT when you right  click on 'save image as' nothing happens!

Here is an example:

http://polona.pl/item/4129391/4/

dezoomify-seadragon choosen

Thanks!
## Important edit

There is now a wiki page about this: https://github.com/lovasoa/dezoomify/wiki/Very-large-images

**Comment by lovasoa** [comment]
The code that is executed when you click "save image as" is not part of dezoomify, it's part of your browsers.

**Comment by awhizard** [comment]
Yes I supposed that. I hoped you had suggestions ;-)
Have a nice evening and thanks!

**Comment by hannolans** [comment]
Same for me, Good work, but sadly FireFOx seems not to work with saving large canvas images (100Mb)

**Comment by lovasoa** [comment]
Please go complain here : https://bugzilla.mozilla.org/show_bug.cgi?id=1200524 :)

**Comment by dancorpse** [comment]
I have problem with chrome "save images as"(don't know when chrome has this function, before there's no) , no matter how I click, nothing happens,but it's works well in firefox. I know it's not a issue of dezoomify.

**Comment by lovasoa** [comment]
> I have problem with chrome "save images as"(don't know when chrome has 
> this function, before there's no) ,
>
You can report an issue to chrome 
https://www.chromium.org/for-testers/bug-reporting-guidelines

**Comment by dancorpse** [comment]
Can I mention dezoomify when I describe details of the issue?

**Comment by lovasoa** [comment]
Of course you can. Give as much details as possible.

**Comment by dancorpse** [comment]
I tried small images, they worked, so that's the problem, big images! But it's an improve for Chrome to support saving html5 canvas to png files.

**Comment by lovasoa** [comment]
I added a new functionality that should help those working with very large images. See https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#dezoomify-shows-a-progress-bar-but-my-image-appears-to-be-completely-blank
