### ISSUE TITLE
Collectie Gelderland does not work with dezoomify

### ISSUE THREAD

**Issue by VDK** [lovasoa/dezoomify#240]
Image example:

http://www.collectiegelderland.nl/organisaties/nederlandsopenluchtmuseum/voorwerp-PR.9540

In the source there are references to Zoomify, but dezoomify gives me the error:

<code>
Uncaught TypeError: Cannot read property 'documentElement' of null

(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:360)
</code>

Which points to Collectie Gelderland having batly formatted xml. 

[The xml file](http://igem.adlibsoft.com/collectiegelderland/nom/PR.9540/ImageProperties.xml) does in fact have no any proper document type declaration. :(

**Comment by lovasoa** [comment]
Sorry for not answering earlier. The xml file you give seems to be working fine with dezoomify today:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://igem.adlibsoft.com/collectiegelderland/nom/PR.9540/ImageProperties.xml



![canvas](https://user-images.githubusercontent.com/552629/71828194-2281f980-30a2-11ea-8d2b-82ad27f93bf2.jpg)


I can't test the webpage itself as it seems not to be online anymore.

I'll close this issue, do not hesitate to reopen it or open another one if you are still experiencing issues.
