### ISSUE TITLE
http://www.nclandgrants.com - doesn't dezoom

### ISSUE THREAD

**Issue by feezell** [lovasoa/dezoomify#241]
For example, the following URL displays a zoomify frame. The dezoomifier doesn't work. I've tried all of the available sections.

http://www.nclandgrants.com/frame/?fdr=61&frm=735

**Comment by dancorpse** [comment]
Pls try: http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://www.nclandgrants.com/zoom/ncarchives/landgrantbooks/S108-160-15n/z/F00735/ImageProperties.xml , it's worked.

**Comment by feezell** [comment]
That worked.  Thanks.
