### ISSUE TITLE
National Gallery of Art (Washington DC)

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#242]
I am trying to download a painting from the NGA:
https://www.nga.gov/image-zoomer.html?path=/public/objects/4/6/5/2/1/46521-primary-0-nativeres.ptif#8:0.3219720658745049,0.2111803756476684

I see that there's 25 files similar to the one you suggested for user "dancorpse" in another closed issue, but when I try one, it loads very slowly to 100%, and then says "converting image" but doesn't go any further - screen remains blank. Is the image too large to be downloaded? I am using Firefox.

**Comment by dancorpse** [comment]
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/4/6/5/2/1/46521-primary-0-nativeres.ptif&SDS=0,90&JTL=7,475, I tried this with firefox, the output screen shot is as follow:  
![default](https://user-images.githubusercontent.com/19525152/41888454-18434262-7938-11e8-9915-9b8167c167ac.jpg)
I've tried several paintings on NGA website, some returned with blank canvas, some with twisted images, I guess this was for the sake of the image size.

**Comment by dancorpse** [comment]
Recently I've encountered many times that dezoomify returned with stretched images, my issues still remained unsolved.

**Comment by Tricesimo** [comment]
Using that link, I get the same as I did before - it's stuck at the "Converting Image" page. Must be the sheer size of it. Thanks for trying.

**Comment by dancorpse** [comment]
I can get the proper image since I've updated firefox to version 61.0.

**Comment by lovasoa** [comment]
I confirm it works fine with the latest firefox.


![canvas](https://user-images.githubusercontent.com/552629/71827749-2d885a00-30a1-11ea-9ba4-c7532a55b5b2.jpg)
