### ISSUE TITLE
Can't download zoom image 

### ISSUE THREAD

**Issue by Verra13** [lovasoa/dezoomify#244]
Hello!
Can't download zoom image from this page https://www.finna.fi/Record/siiri.urn:nbn:fi-vapriikkihttp%253A%252F%252Fmuseosiiri.tampere.fi%253A8080%252FVALOKUVA%252Fcontent%252FSIR_EXEC%252Fimages%252Fprimary%252F2003092909%252F10648158151110.jpg
This link from XHR (https://www.finna.fi/AJAX/JSON?method=getSimilarRecords&id=siiri.urn%3Anbn%3Afi-vapriikkihttp%253A%252F%252Fmuseosiiri.tampere.fi%253A8080%252FVALOKUVA%252Fcontent%252FSIR_EXEC%252Fimages%252Fprimary%252F2003092909%252F10648158151110.jpg) don't work.
Can you help me. Thanks.

**Comment by dancorpse** [comment]
This is not a zoomable image consist of tiles.

**Comment by lovasoa** [comment]
Yes, this is a single image, you don't need dezoomify to download it. Just find the link and save it:


https://www.finna.fi/Cover/Show?id=siiri.urn%3Anbn%3Afi-vapriikkihttp%253A%252F%252Fmuseosiiri.tampere.fi%253A8080%252FVALOKUVA%252Fcontent%252FSIR_EXEC%252Fimages%252Fprimary%252F2003092909%252F10648158151110.jpg&index=0&size=large

![](https://www.finna.fi/Cover/Show?id=siiri.urn%3Anbn%3Afi-vapriikkihttp%253A%252F%252Fmuseosiiri.tampere.fi%253A8080%252FVALOKUVA%252Fcontent%252FSIR_EXEC%252Fimages%252Fprimary%252F2003092909%252F10648158151110.jpg&index=0&size=large)
