### ISSUE TITLE
Art Institute Chicago

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#245]
Can anyone find a way to download the pictures embedded in this reader?

https://publications.artic.edu/monet/reader/paintingsanddrawings/section/135470/135470_anchor

Each picture appears to be a zoomable image made up of tiles, but I can't seem to find any link to them that would allow a download.

**Comment by dancorpse** [comment]
This is IIPImage, e.g. painting _**Cliff Walk at Pourville**_, you can find out https://publications-images.artic.edu/fcgi-bin/iipsrv.fcgi?fif=osci/Monet_18/Color_Corrected/G38376.ptif by inspecting elements,  just replace fif with deepzoom and add .dzi after ptif, you got: http://ophir.alwaysdata.net/dezoomify/dezoomify.html?dezoomer=on#https://publications-images.artic.edu/fcgi-bin/iipsrv.fcgi?DeepZoom=osci/Monet_18/Color_Corrected/G38376.ptif.dzi, it works.
I knew this from lovasoa before, pls refer to #49 .

**Comment by Tricesimo** [comment]
Excellent! Many thanks.
