### ISSUE TITLE
Deezoomify not working with NS Archives

### ISSUE THREAD

**Issue by Pjparusel** [lovasoa/dezoomify#247]
Hello,

I've used dezoomify with the NS Archives for years, but lately, it just returns a number of different errors depending on which version you try.   I've spent hours trying to figure out the issue on my own but I'm stumped.

Just wondering if you can offer any insight?  Here's a representive URL I was working on:  https://novascotia.ca/archives/maps/greatmaps.asp?ID=105

Thanks in advance and keep up the great work!
Paul

**Comment by dancorpse** [comment]
This is ZIF file. Inspect elements of Chrome or Firfox, look up under network-xhr, there is zif file, https://novascotia.ca/archives/zoom/greatmap/201586820.zif, save to local, and opened with this [online zif file reader](http://lovasoa.github.io/ZIF/).

**Comment by Pjparusel** [comment]
Thank you for the info, it's much appreciated!  

Paul
