### ISSUE TITLE
Art Gallery of Ontario

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#248]
The AGO displays their works using a Deep Zoom tool. Does Dezoomify work with these?

Examples (artist page / zoom page):

https://ago.ca/collection/object/l69.2
https://ago.ca/node/28622/mirador

https://ago.ca/collection/object/97/1608
https://ago.ca/collection/object/97/1608

https://ago.ca/collection/object/71/260
https://ago.ca/node/28394/mirador

**Comment by dancorpse** [comment]
This is iiif image，eg: for this image: https://ago.ca/node/28622/mirador, the actual image url is http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5%2F8728.jp2/info.json（I don't know why when I input this url to dezoomify, the converting always stuck at 50%), or you can simply replace region and size with "full" as follows: http://ec2-52-2-247-250.compute-1.amazonaws.com/loris/co5%2F8728.jp2/full/full/0/default.jpg

Here is the wiki for IIIF image: https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server

**Comment by dancorpse** [comment]
And I tried this image: https://ago.ca/collection/object/97/1608, the url is http://loris-1015814219.us-east-1.elb.amazonaws.com/loris/co5%2Fago.28669.jp2/info.json, I got the following image(scaled down) 
![canvas-info](https://user-images.githubusercontent.com/19525152/43505859-c97ae430-959a-11e8-9ab9-240c182e399a.jpg), and the image I got by replacing region and size with full/full is as follows: 
![canvas](https://user-images.githubusercontent.com/19525152/43505945-0d6a8420-959b-11e8-8f69-9870566a9289.jpg), compare the 2 images, the lower part of the first on is a bit stretched! I've an  issue here for this strange problem still remain unsolved.

**Comment by lovasoa** [comment]
This should be fixed by #263. Please re-open if otherwise.
