### ISSUE TITLE
Incomplete image yielded

### ISSUE THREAD

**Issue by k444** [lovasoa/dezoomify#249]
dezoomfiy yielded only about 2/3 of the whole image with the right side missing form http://tois.nichibun.ac.jp/chizu/images/002466357_o.html

**Comment by dancorpse** [comment]
What browse you use? I've tried with firefox and the image is complete. I've encountered such problem before  I updated firefox to version 61.0. Maybe you can try updating your browser.

**Comment by k444** [comment]
I use firefox 61.0 and the gfx.max-alloc-size is changed to 2000000000, but that still renders incomplete picture.

**Comment by lovasoa** [comment]
the link seems to be dead, so I'm closing the issue. We can restart investigating this if you provide a new URL.
