### ISSUE TITLE
McCord Museum

### ISSUE THREAD

**Issue by antoinemalette** [lovasoa/dezoomify#25]
Hi there,

First of all, let met thank you a lot for the work you've been doing. It's wonderful.
I think I'd also need a little hand here.  I've been trying for hours to save images from the McCord-Museum (Montreal) website and I simply can't find out how to do it.  I've tried to find the image path but couldn't find it.

Let's take this image for example: http://collection.mccord.mcgill.ca/fr/collection/artefacts/MP-0000.236.1

I've tried to extract the image with this URL but it doesn't seem to work.  I've tried with another link (http://collection.mccord.mcgill.ca/scripts/large.php?accessnumber=MP-0000.236.1&zoomify=true&Lang=2&imageID=150623) which is the full-screen page of the same image, but it won't work either.

Could you please help me bit?
Thanks a lot again for your time and effort, it is greatly appreciated.

Antoine

**Comment by lovasoa** [comment]
Sorry, I'm currently on hollidays abroad and don't have a computer with me. But I'll take a look whenever I can. Just not not in the next few days.

**Comment by antoinemalette** [comment]
Thank you very much for your quick answer.
Please take your time and most of all, enjoy the rest of your holidays!
