### ISSUE TITLE
Generic dezoomer - image in two folders, can't recieve complete image

### ISSUE THREAD

**Issue by ErinBaker** [lovasoa/dezoomify#254]
Using: `http://amh.adlibhosting.com/atlasofmutualheritage/zoomify/E30_939C/TileGroup0/5-{{X}}-{{Y}}.jpg`

It appears the image is broken into two TileGroup folders, 0 and 1.

The first half loads from folder TileGroup0, but I cannot get the remaining tiles to load from TileGroup1 when using the URL `http://amh.adlibhosting.com/atlasofmutualheritage/zoomify/E30_939C/TileGroup1/5-{{X}}-{{Y}}.jpg`

![image](https://user-images.githubusercontent.com/14230773/45083773-d5e18380-b126-11e8-96b1-85406274cd0c.png)

**Comment by dancorpse** [comment]
Can you give the url of the zoomer?

**Comment by ErinBaker** [comment]
Using `http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://amh.adlibhosting.com/atlasofmutualheritage/zoomify/E30_939C/TileGroup0/5-{{X}}-{{Y}}.jpg` with the Generic dezoomer option

**Comment by ErinBaker** [comment]
And here's the source: http://www.atlasofmutualheritage.nl/nl/Kaart-Mekong-rivier.7357

**Comment by dancorpse** [comment]
You don't have to use generic dezoomer, for zoomify images, just replace the words starting from "TileGroup" and afterwards with "ImageProperties.xml"

http://ophir.alwaysdata.net/dezoomify/dezoomify.html?dezoomer=on#http://amh.adlibhosting.com/atlasofmutualheritage/zoomify/E30_939C/ImageProperties.xml
