### ISSUE TITLE
b

### ISSUE THREAD

**Issue by peasantplucker** [lovasoa/dezoomify#255]

**Comment by dancorpse** [comment]
Try generic dezoomer: http://ophir.alwaysdata.net/dezoomify/dezoomify.html?dezoomer=on#https://maps.historic-liverpool.co.uk/1847panoramicview/6/{{X}}/{{Y}}.png, but my loading failed to finish, pls try from your side.

**Comment by peasantplucker** [comment]
Thank you so much. I had the same issues, but it worked. It downloaded the complete map and stopped at 58%, but also tried to download other parts of the map which I cropped out.

**Comment by lovasoa** [comment]
Please restore the original question.
