### ISSUE TITLE
Cant dezoomify images at archiviodistatotorino.beniculturali.it

### ISSUE THREAD

**Issue by mapper2** [lovasoa/dezoomify#258]
Sample public link: http://archiviodistatotorino.beniculturali.it/work/visuares.php?uad=145226&cart_id=5083

Sample tile link to above image: http://archiviodistatotorino.beniculturali.it/fcgi-bin/iipsrv.fcgi?FIF=/nas/TOC00149/003928.tif&cnt=1&sds=0,90&jtl=4,70

Regards,
M

**Comment by dancorpse** [comment]
Could not open this link: http://archiviodistatotorino.beniculturali.it/fcgi-bin/iipsrv.fcgi?FIF=/nas/TOC00149/003928.tif&cnt=1&sds=0,90&jtl=4,70

**Comment by mapper2** [comment]
Somethings changed on the site
heres a new image link http://archiviodistatotorino.beniculturali.it/dbadd/visua.php?uad=288905&indx=8&rife=
and a link to a tile on that image
http://archiviodistatotorino.beniculturali.it/fcgi-bin/iipsrv.fcgi?FIF=/mnt/nas/Rab_Orta/02966.tif&cnt=1&sds=0,90&jtl=2,3

**Comment by mapper2** [comment]
Did it work for you? I get an error message stating that "property or method log2 not supported by object"

**Comment by dancorpse** [comment]
Yes，I can complete loading. What browser did you use?

**Comment by mapper2** [comment]
IE 11 32bit: error "property or method log2 not supported by object" at "seadragon,js:104"
Edge latest 32bit: works
Chrome latest 32bit: works and works not, memory issue?
Firefox (in safe mode) 62 32bit: reads tiles, does not show them and stops att 100% but does not finish

**Comment by mapper2** [comment]
Tested with Win7 and Win10

**Comment by mapper2** [comment]
Lest I forget: Thanks for the help :-)

**Comment by mapper2** [comment]
P.S. I have found the large image info (https://github.com/lovasoa/dezoomify/wiki/Very-large-images)

**Comment by mapper2** [comment]
Did some more testing with more memory.
Test image is the above 9510x13854 px image
IE: error "property or method log2 not supported by object" at "seadragon,js:104" (obviously no diff here)
Edge: the more memory the merrier. Faster. Can show and save the 9510x13854 px image with no problems.
Chrome: sucks, but manages to slowly render the image with more memory, no speed increase though.
Firefox/Opera: not tested this time

**Comment by noahdollar** [comment]
I've found that disabling hardware acceleration in Firefox seems to load large images much faster and fix many of the problems I was having with them. Might be worth a shot if this is still an issue for you.
