### ISSUE TITLE
Archieven.nl doesn't work

### ISSUE THREAD

**Issue by VDK** [lovasoa/dezoomify#26]
Archieven.nl is a fairly big site of Dutch archives. It uses zoomify, though dezoomify can't decode its content.

An example of a database entry is this: 
http://www.archieven.nl/nl/zoeken?mivast=0&mizig=962&miadt=5&miaet=14&micode=1785&minr=4418367&miview=ldt

If you follow the iframes, you find the zoomify viewer here:

http://files.archieven.nl/viewer/?p=aWQ9Mzc4MTQzMjA4JnZpZXdlcj12aWV3ZXIyJmFkdF9pZD01JnRvZWdhbmc9MTc4NSZmaWxlPTE2MDAxXzE3MDAwJTVjMTc4NV8xNjY3NC5qcGcmbmFtZT12aWV3ZXIyJndhdGVybWFyaz1odHRwJTNhJTJmJTJmZmlsZXMuYXJjaGlldmVuLm5sJTJmNSUyZm1pX2ZpbGVzJTJmaW1hZ2VzJTJmd2F0ZXJtZXJrJTJmd2F0ZXJtZXJrX2ZpbmFsLnBuZyZtaXprX2FsbGU9Jm1pb2llPSZtaXNlc3NpZD0yYzQ4NzI1NGJkYTBhYTg3OTIyMmQ1OGZlNWJmMzdlNw%3d%3d&k=07384563959cfddb3739f6c5607f3e61

Even feeding this link into dezoomify doesn't result in any result though

**Comment by lovasoa** [comment]
Hmmm... The bug seem to have been introduced by cca17e36859d965e05f1428266a3c863f8df9342

**Comment by lovasoa** [comment]
Have to think about it...

**Comment by lovasoa** [comment]
Until the bug is resolved, you can enter the following link in dezoomify: http://img.archieven.nl/cgi-bin/iipsrv.fcgi?Zoomify=5%2F1785%2F16001_17000%2F1785_16674.jp2/ImageProperties.xml

**Comment by VDK** [comment]
Thanks
Op 18 nov. 2015 10:05 schreef "Ophir LOJKINE" <notifications@github.com>:

**Comment by lovasoa** [comment]
This is fixed. You can test it with : http://www.archieven.nl/maisi_ajax_proxy0.php?mivast=0&mizig=962&miadt=5&miaet=185&micode=1785&minr=8193963&milang=nl&misort=last_mod|asc&miview=viewer2

This is a little slow, because it has to load 3 files recursively before starting to load tiles, but it works.

**Comment by VDK** [comment]
It does work, there is just a error message that also shows up:


> Uncaught TypeError: Cannot read property 'click' of undefined (http://ophir.alwaysdata.net/dezoomify/dezoomify.html:17)

**Comment by lovasoa** [comment]
Verry strange. I don't see this error, and line 17 of `http://ophir.alwaysdata.net/dezoomify/dezoomify.html` is a blank line.

What browser do you use? Do you have browser extensions that may be inserting code into the page?

**Comment by VDK** [comment]
Chrome on Win10. I have a ad blocker.

It actually apparently hasn't got anything to do with this bug: it shows up about a seconds after http://ophir.alwaysdata.net/dezoomify/dezoomify.html is loaded. Line 17 is a blank line inbetween </head> and <body>

**Comment by lovasoa** [comment]
Can you open the console (Ctrl-Maj-J) and take a screenshot when the error happens (without loading anything in dezoomify). I suspect you to have a buggy or malicious extension or virus that loads code into the page.

**Comment by TaliesinDS** [comment]
Is archieven.nl supposed to work ?
I can't get it to work with `https://www.archieven.nl/nl/zoeken?mivast=0&mizig=210&miadt=143&miaet=1&micode=112&minr=893574&miview=inv2`

The desktop client just says this: ```
Enter an URL or a path to a tiles.yaml file:
https://www.archieven.nl/nl/zoeken?mivast=0&mizig=210&miadt=143&miaet=1&micode=112&minr=893574&miview=inv2
ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - custom: The 'custom' dezoomer cannot handle this URI
 - google_arts_and_culture: The 'google_arts_and_culture' dezoomer cannot handle this URI
 - zoomify: The 'zoomify' dezoomer cannot handle this URI
 - generic: The 'generic' dezoomer cannot handle this URI
 - pff: Unable to create the dezoomer: Invalid meta information file: missing field `file`
 - IIPImage: The 'IIPImage' dezoomer cannot handle this URI
 - nypl: The 'nypl' dezoomer cannot handle this URI
 - iiif: Unable to create the dezoomer: Invalid IIIF info.json file: expected value at line 1 column 1
 - deepzoom: Unable to create the dezoomer: Unable to parse the dzi file: Syntax: 27:91 Unexpected token inside qualified name: >
 - krpano: Unable to create the dezoomer: Unable to parse the krpano xml file: Syntax: 27:91 Unexpected token inside qualified name: >
```


Separate tile urls in case this helps: "https://preserve.archieven.nl/cgi-bin/iipsrv.fcgi?Zoomify=cache%2Ffonc-hhd%2F45118650e970b587655b27d77ec02e0d.jp2/TileGroup0/4-10-0.jpg"

**Comment by Benomrans** [comment]
@TaliesinDS 
Hello,
It might be much easier using the Dezoomify extension for this site: https://lovasoa.github.io/dezoomify-extension/
it would provide the needed xml file instead of editing the tiles urls.
for this image, the url to be passed to Dezoomify is: https://preserve.archieven.nl/cgi-bin/iipsrv.fcgi?Zoomify=cache%2Ffonc-hhd%2F45118650e970b587655b27d77ec02e0d.jp2/ImageProperties.xml
