### ISSUE TITLE
Support for web.nli.org.il

### ISSUE THREAD

**Issue by Language-Lover** [lovasoa/dezoomify#260]
I can't figure out how to dezoomify images from the National Library of Israel (web.nli.org.il), particularly at this link http://web.nli.org.il/sites/NLI/Hebrew/digitallibrary/pages/viewer.aspx?presentorid=MANUSCRIPTS&docid=PNX_MANUSCRIPTS000044560-1#|FL21042309
Thank you

**Comment by dancorpse** [comment]
It does not show a image, only black background

**Comment by dancorpse** [comment]
Dezoomify do has some problem with IIIF images. Refer to this  **Harvard Mirador issue #250**

**Comment by lovasoa** [comment]
This should be fixed by #263. Please re-open if otherwise.
