### ISSUE TITLE
The Morgan Library & Museum (Zoomify *.zif)

### ISSUE THREAD

**Issue by Kinryu** [lovasoa/dezoomify#261]
Cannot parse this image
https://www.themorgan.org/collection/hours-of-henry-viii/198
http://host.themorgan.org/facsimile/h8/default.asp?id=198&width=100%25&height=100%25&iframe=true

Since the accessible .zif file type is a protected container there is no extract the original file from it.

**Comment by dancorpse** [comment]
Got it: http://host.themorgan.org/facsimile/images/h8/MSH0008_C_0191_verso-0192_recto.zif

**Comment by dancorpse** [comment]
What browser you use? It works for me in Firefox. But not in Chrome(click save as image but nothing happened).

**Comment by Kinryu** [comment]
Thank you. The dialog does indeed work in Firefox but not in Chrome.
