### ISSUE TITLE
incomplete image, "unable to load tile" on IIIF server

### ISSUE THREAD

**Issue by etameta** [lovasoa/dezoomify#264]
Hello, in trying to download this image https://ids.lib.harvard.edu/ids/iiif/11160215/info.json using ophir, all goes well until 92% complete, then I always get this message:

> Uncaught Error: Unable to load tile.
> Check that your internet connection is working and that you can access this url:
> https://ids.lib.harvard.edu/ids/iiif/11160215/12288,2048,1024,1024/1024,1024/0/default.jpg
> 
> (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)

This happens both in Firefox and in Chromium.

Indeed, trying to open the indicated URL, I get a 404. But zooming the image using the server's viewer correctly show all of the tiles.

Maybe the tile naming scheme changes at some point within the image, and dezoomify doesn't know?

**Comment by dancorpse** [comment]
Same with you, stuck at 92%. It seems dezoomify do has some problem with IIIF images. Like this issue #250 .

**Comment by lovasoa** [comment]
This should be fixed by #263. Please re-open if otherwise.
