### ISSUE TITLE
Problem with British Museum (Deep Zoom)

### ISSUE THREAD

**Issue by Gsusmartin** [lovasoa/dezoomify#265]
Hi!

I am trying to download an image from the British Museum website but I can't.

Url: https://www.britishmuseum.org/whats_on/past_exhibitions/2014/d%C3%BCrers_paper_triumph.aspx
or https://www.britishmuseum.org/whats_on/past_exhibitions/2014/dürers_paper_triumph.aspx

I select the Seadragon (Deep Zoom Image) option and I get the next error:
Uncaught TypeError: Cannot read property 'documentElement' of null
(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:360)

When I select the Generic dezoomer option It seems that It will work but nope. I get this:
Uncaught Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://www.britishmuseum.org/whats_on/past_exhibitions/2014/d%C3%BCrers_paper_triumph.aspx
(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:178)

Do you know if there is a way to download the image?

Thanks.

**Comment by dancorpse** [comment]
This should be the image path: https://www.britishmuseum.org/images/deepzoom/TriumphalArch1/dzc_output.xml
However this image is extremely huuuge, Size Width="64942" Height="78906". My browser remains at 0% always, pls have a try at your side.

**Comment by dancorpse** [comment]
You may try generic dezoomer with lower level: eg: level 14 https://www.britishmuseum.org/images/deepzoom/TriumphalArch1/dzc_output_files/14/{{X}}_{{Y}}.jpg, but I failed from level 15 on, level 15 loading failed at 46%, level 16 failed at 44% , while level 17 failed at 0%, level 17 seems to be the highest level.
