### ISSUE TITLE
Error: Unable to find a proper dezoomer

### ISSUE THREAD

**Issue by efadallas** [lovasoa/dezoomify#267]
I have tried several ways to this link and always failed to use dezoomify, Is anyone can help me with this:

Link: https://fineartamerica.com/featured/1881-lonesome-dove-map-texas-map-store.html

Error: Unable to find a proper dezoomer for: https://fineartamerica.com/featured/1881-lonesome-dove-map-texas-map-store.html (http://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)

**Comment by efadallas** [comment]
@lovasoa  Would you please advice if there is anything I can do to download the full version of this image? I have very limited knowledge at the moment, I spent more than 30 hours to ready all the information from internet but have no clue what I am doing. Please help me out! Thank you

**Comment by lovasoa** [comment]
I do not really have the time to help now, but this seems possible to dezoom with [dezoom.sh](https://github.com/lovasoa/dezoom.sh)

Image tiles are accessible through: https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x=100&y=0

(just change the x and y parameters)

**Comment by efadallas** [comment]
Hi Lovasoa,

Thanks for the information. Hopefully I can figure it out now. Do we have to be a member so as to get support or what is the benefit as a member? I see the pricing for the member which is very reasonable. I am a new leaner in this area but I would like to learn more by working on my own projects.

**Comment by lovasoa** [comment]
member of what? there is no membership option. I currently do not offer any paid support for dezoomify. However, I might do so in the future, let me know if you would be interested.

**Comment by efadallas** [comment]
I think I went to the link of other website and see the Pricing $7 for basic support per month. Sorry my mistake. Yes I am interested in it, I am willing to pay you for a fee just to get this project done. You can tell me how much and how I can proceed with the payment

**Comment by efadallas** [comment]
I did installed cygwin and have some errors when during installation. I choose continue. after installed Cygwin I put the URL:  ./dezoom.sh https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x=%x&y=%y, It failed. I copied all the content of what I did: 

Sam@Sam-PC ~
$ export http_proxy=http://username:password@host:port/

Sam@Sam-PC ~
$ wget - wget -O dezoom.sh "https://raw.githubusercontent.com/lovasoa/dezoom.sh/master/dezoom.sh"
Error parsing proxy URL http://username:password@host:port/: Bad port number.
Error parsing proxy URL http://username:password@host:port/: Bad port number.
--2018-12-05 21:54:35--  https://raw.githubusercontent.com/lovasoa/dezoom.sh/master/dezoom.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.48.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.48.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5063 (4.9K) [text/plain]
Saving to: ‘dezoom.sh’

dezoom.sh           100%[===================>]   4.94K  --.-KB/s    in 0.001s

2018-12-05 21:54:35 (5.49 MB/s) - ‘dezoom.sh’ saved [5063/5063]

FINISHED --2018-12-05 21:54:35--
Total wall clock time: 0.3s
Downloaded: 1 files, 4.9K in 0.001s (5.49 MB/s)

Sam@Sam-PC ~
$ chmod +x dezoom.sh

Sam@Sam-PC ~
$ ./dezoom.sh https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x=%x&y=%y
[1] 3076
[2] 5652
[3] 5884
[4] 6856
[2]   Done                    widthmedium=565
[3]   Done                    heightmedium=800

Sam@Sam-PC ~
$ Guessing xmax...
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Guessing ymax...
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Failed to download 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633'
Didn't manage to download any tile.

[1]-  Exit 1                  ./dezoom.sh https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633
[4]+  Done                    x=%x

**Comment by lovasoa** [comment]
You have to add quotes around the url

**Comment by lovasoa** [comment]
` ./dezoom.sh 'https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x=%x&y=%y'`

**Comment by lovasoa** [comment]
and you also have to set the interval between successive x and y values (the width and height of tiles):
-u : the interval between two successive values of %X (default: 1 if xmax > xmin, -1 otherwise)
-v : the interval between two successive values of %Y (default: 1 if ymax > ymin, -1 otherwise)

**Comment by lovasoa** [comment]
You have to figure out the width and height of tiles and specify them to dezoom.sh as -u and -v. You set 100 and 100, but I do not think these are the correct values.
I just started a new job, and I currently do not have time to do proper consulting work on the side. But I will think of it for the future.

**Comment by efadallas** [comment]
I test the URL of image file by increasing 100 on X or Y and it give me the right image tile, X 0 Y 0 shows the very top left image tile, x 500 y 0 shows the top right image tile,  x 0 y 700 shows the left bottom and x 500 y 700 shows the bottom right image tile. Looks like I the number should be ok.

When you got more time can you look into deeper step to see if you can test and figure it out. I have no rush just try to get this one work if possible. If you do test it please also advice if we can get rid of the watermark?

Thanks and have a good weekend.

**Comment by efadallas** [comment]
I tried other images and i got the same problem. Can you try to work on the image to see if you can get it done? Please help! Thank you.

**Comment by efadallas** [comment]
@lovasoa Hope everything went well with your new job. I know you are busy all the time. I tried again on this image based on the information you provided, I am able to download image but the image downloaded is not corrected, it only combined by the same top left tile.

The image link: https://fineartamerica.com/featured/1881-lonesome-dove-map-texas-map-store.html

The top left tile: https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x=0&y=0

The bottom right tile: https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x=500&y=700

What I put in the Cygwin:  ./dezoom.sh -x 0 -y 0 -X 500 -Y 700 -u 100 -v 100 "https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x=%x&y=%y"

And it is able to download the image but not the right result.
Whenever you get sometime can you please look into it to see what the problem is? Please help me out. Thank you.

**Comment by lovasoa** [comment]
The tiles for this image are not squared. But it can be dezoomed using [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) and it's custom dezoomer.
Here is the `tiles.yaml` I used:

```yaml
url_template: "https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x={{x*100/600}}&y={{y*100/599}}"

variables:
  # The x position of tiles goes from 0 to the image width with an increment of the tile width
  - name: x
    from: 0
    to: 3000
    step: 600 # Tile width

  - name: y
    from: 0
    to: 4193 # Image height
    step: 599 # Tile height
```

and the result : 

![dezoomified](https://user-images.githubusercontent.com/552629/63249498-dc9ad500-c269-11e9-8d70-cd47c402b71e.jpg)

**Comment by lovasoa** [comment]
Woops. Looking at the file, it looks like I have the same problem as you had

**Comment by lovasoa** [comment]
But it looks like nothing can be done. The tiles do not cover the whole image.

First tile:
![](https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x=0&y=0)

Second tile:
![](https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x=100&y=0)

As you can see, the left size of the letter `T` is neither on the first tile nor on the second one.

**Comment by efadallas** [comment]
Thank you Lovasoa. Appreciate your time. Ok i will give up now since there is nothing we can do.


Sent from Yahoo Mail for iPhone


On Monday, August 19, 2019, 3:19 AM, Ophir LOJKINE <notifications@github.com> wrote:


But it looks like nothing can be done. The tiles do not cover the whole image.

First tile:


Second tile:


As you can see, the left size of the letter T is neither on the first tile nor on the second one.

**Comment by lovasoa** [comment]
Well, what you could do if you really want this image is find out how many pixels are missing at the right and at the bottom of each tile, and use pixels from the low-res image to fill the gaps...

**Comment by efadallas** [comment]
Good idea. I will play with it. Thanks again


Sent from Yahoo Mail for iPhone


On Monday, August 19, 2019, 7:36 AM, Ophir LOJKINE <notifications@github.com> wrote:


Well, what you could do if you really want this image is find out how many pixels are missing at the right and at the bottom of each tile, and use pixels from the low-res image to fill the gaps...

**Comment by ZenithRogue** [comment]
Heyo, I randomly came across this.

If you add `&domainUrl=%20%20%20%20%20%20%20%20%20%20` to your image request URL, it will cancel out the watermarks.

Their renderer is rather stupid, and will validate any text as a valid watermark URL as long as it is at least 20 characters long

**Comment by zaz** [comment]
You could download overlapping tiles and then stitch them together using OpenCV or something:

    wget "https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=565&heightmedium=800&x="{0,1,2,3,4,5}"00&y="{0,1,2,3,4,5,6,7}"00&domainUrl=%20%20%20%20%20%20%20%20%20%20"
    wget "https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=21821633&widthmedium=113&heightmedium=160&x="{0,1}"00&y="{0,1}"00&domainUrl=%20%20%20%20%20%20%20%20%20%20"

The above divides `widthmedium` and `heightmedium` by 5.  You could use another number; the results don't have to be integers, but it does seem that the aspect ratio needs to be roughly correct.

**Comment by Federcc** [comment]
Hi everyone

reviewing the tiles, in this image for example
https://fineartamerica.com/featured/sacred-geometry-141-endre-balogh.html
in the mosaic:
https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=6413592&widthmedium=730&heightmedium=730&x=300&y=300&domainUrl=fineartamerica.com

if I change widthmedium=730
a widthmedium=717, shift the tile to the left exactly half of what was needed to complete the image

and if I do the same with the following tile:
https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=6413592&widthmedium=730&heightmedium=730&x=400&y=300&domainUrl=fineartamerica.com

change widthmedium=730
a widthmedium=743 moves the image to the right the other half that was needed to complete the image

the same happens with heightmedium

My question is how do I automate the download of the mosaics and then join them?

Thank you.

**Comment by Joseph0002** [comment]
bump

**Comment by BelieveInBunny** [comment]
can someone help me with this image?
https://fineartamerica.com/featured/marcus-aurelius-antoninus-augustus-black-and-white-daniel-coulmann.html

**Comment by o-r-i-z-u-r-u** [comment]
Hi folks, I'm trying the following `tiles.yaml` on an image of the [JWST](https://fineartamerica.com/featured/hubble-02-pierre-vuaillet.html):

```
url_template: "https://render.fineartamerica.com/previewhighresolutionimage.php?artworkid=41243916&widthmedium=730&heightmedium=730&x={{x*100/599}}&y={{y*100/599}}.jpg&domainUrl=++++++++++"
 variables:
  - { name: x, from: 0, to: 4744, step: 599 } # Image width, in pixels
  - { name: y, from: 0, to: 4744, step: 599 } # Image height, in pixels)
```
This is the result ![here](https://user-images.githubusercontent.com/88693606/210177064-d6d8bc19-f20d-49ea-a3d8-0c50c57eaa16.jpg)

You can see - if you zoom right in -  there's overlap between tiles. Very similar to @efadallas's  example of the US map showing "new exico", "texs" and "coorado"

Couple of other things I've noticed:

- the tiles *should* be `593` (because 8 tiles \* 593 gives the total image size of 4744 × 4744) 
...but the output of the yaml is creating tiles of `599`.  
It seems the sneaky folks there have applied a `0.99` constant? i.e. 599 × 0.99 = 593

- the coordinates on the grid are from 0,0 to 700,700, in steps of 100 (for 8 × 8 tiles)
- the template requires `.jpg` in the URL for it to download properly
- occasionlly spits out blank tiles like in the image above (server error?)

So what I haven't quite figured out is whether (and where) I should be using the tiles sizes of `593`, `599` and `730` in the yaml. Can anyone throw some pointers?

**Comment by zdillingham** [comment]
Does anyone have any updates on being able to grab these images easier?

**Comment by Geremia** [comment]
@lovasoa I think your yaml parameters aren't quite right. You're not getting the full image.

**Comment by WOLINM** [comment]
The images from art of america are removed
