### ISSUE TITLE
Can't dezoomify images from BMLonline

### ISSUE THREAD

**Issue by KaiMSchmitt** [lovasoa/dezoomify#268]
I would like to download some images from this site, but I couldn't get any useful link with my browser's network inspector to dezoomify.

Sample link (site uses openlayers): http://mss.bmlonline.it/s.aspx?Id=AWOIe4fJI1A4r7GxMH_Y&c=Manuel%20Philis%20Carmina%20varia#/oro/1

Regards
Kai

**Comment by lovasoa** [comment]
It looks like they are using zoomify, which is supported. 
You can find the URL of individual tiles, and replace `TileGroupK/X-Y-Z.jpg` by `/ImageProperties.xml` to get the URL of the meta-information file to enter in dezoomify

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\Teca\Plutei\Lotto03\.\P000907_32.19\pyr\Plut._32.19_0001.tif/ImageProperties.xml

**Comment by KaiMSchmitt** [comment]
Works perfektly! Many thanks.
