### ISSUE TITLE
Add support for Mindat

### ISSUE THREAD

**Issue by sachaw** [lovasoa/dezoomify#269]
https://www.mindat.org/
seems to use OpenSeadragon

**Comment by sachaw** [comment]
I have done some investigating and found the following:

- dezoomify correctly detects Seadragon
- dzi format, example: https://www.mindat.org/dzi_files/88/8848/884848.dzi
- directly trying to access tiles results in a 403: https://www.mindat.org/dzi_files/88/8848/884848_files/11/2_2.png
- loading all tiles from the official site then letting dezoomify use the cached images work

200 Request Headers
![image](https://user-images.githubusercontent.com/11172820/50470560-13835880-0a05-11e9-8042-29ab1a79d7e9.png)
403 Request Headers
![image](https://user-images.githubusercontent.com/11172820/50470569-239b3800-0a05-11e9-8371-c33328863655.png)

After firing up insomnia, I tried a request with identical headers to the successful one, and slowly removed them, I brought it down to the `Referer` header.

When set to blank: `403`
When set to viewers url: `200`
when set to website root: `403`
when set to `https://www.mindat.org/photo`: `200`

Hence setting a permanent header of `Referer: https://www.mindat.org/photo` should work

**Comment by lovasoa** [comment]
By default, dezoomify does not proxy images, so it cannot use a fake referer. However, you can force it to use a tile proxy that will fake the referer, see: https://github.com/lovasoa/dezoomify/wiki/Very-large-images#tiles-proxy
