### ISSUE TITLE
access session-protected pages

### ISSUE THREAD

**Issue by agakanee** [lovasoa/dezoomify#27]
an example image that doesn't dezoomify:
https://quickserve.cummins.com/qs3/portal/service/wiring/english/4021346/. 

I wonder if it's because quickserve requires a login, but I have an active session in another tab open. 

The zoomifyimage path is just a stub: "zoomifyImagePath=/rtgraphics/english/w-diagrams/4021346"

**Comment by lovasoa** [comment]
Yes, if it requires a session, then dezoomify can't work with it.

Because of a [browser restriction](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), dezoomify can't access directly the server, and uses a proxy instead. This could eventually be solved by providing dezoomify as an independent application, or a browser extension, but this is quite some work.

**Comment by lovasoa** [comment]
I reopen it and rename this issue from "Quickserve Online Images" to "access session-protected pages".

**Comment by agakanee** [comment]
Great, thanks. I thought that might be it, but i didn't specifically see that as a restriction. Maybe this thread will save someone else some time down the road. 

Super nice script othwerise!

**Comment by lovasoa** [comment]
If you really need your image, and know a little bit of python, you can use [dezoomify.py](https://commons.wikimedia.org/wiki/Help:Zoomable_images/dezoomify.py), and edit it so that it sends your session informations to the server.

**Comment by lovasoa** [comment]
It is now possible to access session-protected pages, but there is no nice GUI for that.

## How to access protected pages
 * Find the cookie that authenticates you on the site.
    * (in firefox, from the site's page, you can do "Ctrl-I" > "Security" > "View Cookies"
 * Open dezoomify.
 * Open the web console inside dezoomify. (In firefox: Ctrl-Maj-K)
 * Type: `ZoomManager.cookies = "Cookie1=Value1; Cookie2=Value2"`(replace *Cookie1*, *Value1*, etc., by the actual name of your cookies, that you found at step 1).
 * Paste the Url of your session-protected page in dezoomify, as you would do normally.
 * Press *Submit*
 * Enjoy

**Comment by Kltidwell** [comment]
Could you please give examples of cookies that would be needed for something like this?

**Comment by lovasoa** [comment]
We now have a [wiki page dedicated to protected webpages](https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages) feel free to contribute to it, or open a new issue if you find it unclear.
