### ISSUE TITLE
Unable to display the larger maps

### ISSUE THREAD

**Issue by scouserdave** [lovasoa/dezoomify#272]
Ref: https://maps.nls.uk/view/102344096

Hi, 

I've ran into a problem with Firefox when using dezoomify to download the larger (15000 x 10000 approx pixels) maps at the National Library of Scotland website. The page is blank. The smaller (9000 x 6000 approx pixels) maps appear to be OK. It was working fine when I last used it and thought the latest version of Firefox was the reason. I rolled Firefox back to a March 2018 version, but I'm having the same problem. The image is visible in Chrome, but as I knew already, unable to save the image.

Thanks for any assistance.

**Comment by scouserdave** [comment]
Sorry, please close this issue. I upped the gfx.max-alloc-size in Firefox and it's working again. This is something I have never had to do since I've had this laptop. I just presumed the later version of Firefox over the past 18 months had changed it themselves.

Thanks.

**Comment by lovasoa** [comment]
I don't think Firefox will ever have a very large gfx.max-alloc-size by default. This would make it can more often, when few memory is available.
