### ISSUE TITLE
I can't open this openseadragon image.

### ISSUE THREAD

**Issue by tompy86** [lovasoa/dezoomify#274]
Hi
I tried to open this image but i couldn't manage.
https://www.romaierioggi.it/pianta-di-roma-marre-1876/
How can i do ?
Thanks in advance

**Comment by dancorpse** [comment]
The zoomable image is not shown for me.

**Comment by tompy86** [comment]
![piantadi roma](https://user-images.githubusercontent.com/46522268/50957047-88529a00-14bd-11e9-9e95-a9dad4a1f512.JPG)
You must click the button "toggle full page"

**Comment by dariussnow** [comment]
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://www.romaierioggi.it/wp-content/openseadragon_files/marre/marre_files/14/{{X}}_{{Y}}.jpg

**Comment by dancorpse** [comment]
You can also use this : http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://www.romaierioggi.it/wp-content/openseadragon_files/marre/marre.xml

**Comment by tompy86** [comment]
Thank you very much !!!! Really very kind
