### ISSUE TITLE
Download map from archives Cartesius

### ISSUE THREAD

**Issue by Cartesis** [lovasoa/dezoomify#275]
Hello

Please can you help me download this image:
https://search.arch.be/imageserver/topview.php?FIF=514/514_0549_000/514_0549_000_00458_000/514_0549_000_00458_000_0_0001.jp2

Dezoomify automatically selects IIPImage but I am getting a red error message:
 'Uncaught Error: Invalid IIPImage information file.(http://ophir.alwaysdata.net/dezoomify/dezoomers/iipimage.js:34)'

My webbrowser: Google Chrome 71 on Mac OS X (Yosemite) (latest version)

I have been trying for several hours using the tips from the FAQ.

Thank you so much.

**Comment by Cartesis** [comment]
I am sorry, I don't know what you mean by 'Remove old php stream context option from proxy'. I am not familiar with writing code. Can you please give some more explanation? Thank you in advance.

**Comment by lovasoa** [comment]
Dezoomify could not access the URL you gave because of a problem with that PHP script. Now it can access the URL, but it looks like the image is not in a format supported by dezoomify.
