### ISSUE TITLE
De-zoomify images from stanford's Hoover Institution Library website

### ISSUE THREAD

**Issue by algae21** [lovasoa/dezoomify#279]
Hi,

Usually I can figure them out pretty quick, but this one's been a bear.  I've tried changing the x y coordinates using the generic dezoomer and I either get the standard sized image, or I get an incomplete set of  large tiles all jumbled up.  Can anyone help on this?  The link is:

https://digitalcollections.hoover.org/objects/33356/when-the-bonds-mature--you-will-pay-now-or-in-the-months-to?ctx=80bf64e5-0166-497c-a910-ef2bc49cda15&idx=0

Thank you so much!

**Comment by lovasoa** [comment]
This is a standard zoomify image, you just need to find the ImageProperties.xml : 

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://digitalcollections.hoover.org/internal/media/zoomifydispatcher/114859/ImageProperties.xml

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/52185178-e0f72780-281c-11e9-91cd-6d1ee9c66ce1.png)
