### ISSUE TITLE
British Library: Greek Manuscripts

### ISSUE THREAD

**Issue by schmidhauser** [lovasoa/dezoomify#28]
I think the images of Greek MSS at the BL cannot be dezoomified. An example:

http://www.bl.uk/manuscripts/Viewer.aspx?ref=burney_ms_276_f031ar

http://www.bl.uk/manuscripts/Proxy.ashx?view=burney_ms_276_f031ar_files/12/2_3.jpg

http://www.bl.uk/manuscripts/Proxy.ashx?view=burney_ms_276_f033ar.xml

Or am I missing something?

**Comment by lovasoa** [comment]
Did you select the right zoomable image format? For the British Library, it's seadragon.

**Comment by schmidhauser** [comment]
Yes, now it works! I tried with seadragon yesterday – many times… – but for some reason I always got an error message. I should have made a screen shot. Anyway, thank you so much for this. It's so much easier to read the MS without having to zoom in and out and in and out… All best!

**Comment by lovasoa** [comment]
So is it working for you now?
Next time you have a problem, you should attach a screenshot, if possible with the development console opened (ctrl-maj-K on firefox).
