### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by zoom0** [lovasoa/dezoomify#280]
someone please try to save this two maps .png

http://www.gss.hr/hgss/kartografija/dubrovnik/

http://www.gss.hr/static/karte/biokovo/biokovo/ImageProperties.xml

thank you

**Comment by dancorpse** [comment]
The files size is too huge to upload here. Those two images are workable with dezoomify.

**Comment by zoom0** [comment]
somehow I cant save this images after loading in dezoomify. please someone save an upload it somwhere. thank you

**Comment by zoom0** [comment]
why is closed thread?

**Comment by scouserdave** [comment]
I've uploaded them to https://ufile.io/lhgui and https://ufile.io/5kojo

They'll be deleted after 30 days.
