### ISSUE TITLE
British Library 'Loading the tiles (100%)' - stuck on 'Converting image...'

### ISSUE THREAD

**Issue by bednarz** [lovasoa/dezoomify#282]
Using the FAQ instructions I got the xml from the page:
http://www.bl.uk/magnificentmaps/zoomify_files/the_island_map/ImageProperties.xml

Gets to 100% on the tiles, then seems to hang on 'Converting image...'
Any help would be greatly appreciated!

**Comment by dancorpse** [comment]
It maybe bcs the image size,too huge.

<IMAGE_PROPERTIES WIDTH="24608" HEIGHT="17210" NUMTILES="8856" NUMIMAGES="1" VERSION="1.8" TILESIZE="256"/>

**Comment by bednarz** [comment]
Ah, if it's that big is there no way around it?

**Comment by bednarz** [comment]
I wouldn't even mind manually stitching the tiles together if there is a way of extracting them all to my computer...

**Comment by lovasoa** [comment]
For very large images, you can use dezoomify.py: https://github.com/lovasoa/dezoomify-py

**Comment by bednarz** [comment]
Ended up getting it working via:
https://github.com/lovasoa/dezoomify/tree/master/node-app

Thanks for the tool!

**Comment by Arekkusu1998** [comment]
I have the same problem with very large images but I can't understand how to use that node (https://github.com/lovasoa/dezoomify/tree/master/node-app) or any other method to avoid the issue. 
Maybe, I do this in Firefox: about:config > gfx.max-alloc-size > set its value to whatever I want. But ... I don't know the value, and it may make my browser unusable!

**Comment by lovasoa** [comment]
For future reference: [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs#dezoomify-rs) supports very large images like this one, and should be easier to use than the node application.

Here is the original image, downloaded by dezoomify-rs:

![canvas](https://user-images.githubusercontent.com/552629/62765843-4e686700-ba91-11e9-8bff-0a057e01bfe6.jpg)
