### ISSUE TITLE
Please help me to extract image from http://hmdaprojects.hmda.gov.in/hada/default.aspx

### ISSUE THREAD

**Issue by Pradeepyl** [lovasoa/dezoomify#284]
Please help me to extract image from http://hmdaprojects.hmda.gov.in/hada/default.aspx

**Comment by scouserdave** [comment]
https://ufile.io/0d86r

This link will delete in 30 days.

**Comment by Pradeepyl** [comment]
Thank you, But can you brief the procedure/ fix to overcome the difficulties I had faced.

**Comment by scouserdave** [comment]
It could be your processor isn't powerful enough or you're not waiting long enough after clicking 'save image.' When I click 'save image,' it took 74 seconds before the folder page opened up. I'm using Windows 10 with Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 2904 Mhz, 2 Core(s), 4 Logical Processor(s).

I am not technically savvy. All I can say is that it does work.
