### ISSUE TITLE
zoomable image is shown for me but I can't save it

### ISSUE THREAD

**Issue by zoom0** [lovasoa/dezoomify#285]
http://www.gss.hr/static/karte/biokovo/biokovo/ImageProperties.xml

http://www.gss.hr/hgss/kartografija/dubrovnik/

Please someone try to save this two images and send me on my email. Thank you very much.

**Comment by scouserdave** [comment]
I've uploaded them to https://ufile.io/lhgui and https://ufile.io/5kojo

They'll be deleted after 30 days

**Comment by zoom0** [comment]
thank you so much @scouserdave

**Comment by zoom0** [comment]
can you try this one Im also unable to save even I have modified max alloc size. thnx 

http://www.gss.hr/static/karte/medvednica/medvednica/ImageProperties.xml

**Comment by lovasoa** [comment]
@zoom0 : Did you read our [FAQ](https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ) ?
Can you please post a precise description of your problem, as well as your operating system, your browser and it's version ?

You can also try setting a [tile proxy](https://github.com/lovasoa/dezoomify/wiki/Very-large-images#tiles-proxy).

**Comment by scouserdave** [comment]
> can you try this one Im also unable to save even I have modified max alloc size. thnx
> 
> http://www.gss.hr/static/karte/medvednica/medvednica/ImageProperties.xml

Seems to work for me. You can download it at https://drive.google.com/file/d/1tGTMwqpDKMK3sMRJxsJqEHQ1fYujJfMB/view?usp=sharing

**Comment by lovasoa** [comment]
It works for me too 

![canvas](https://user-images.githubusercontent.com/552629/62723695-90ea5f00-ba11-11e9-9abe-e4da699b0f69.jpg)
