### ISSUE TITLE
Unable to find a proper dezoomer (mines-paristech)

### ISSUE THREAD

**Issue by MrSoulPC915** [lovasoa/dezoomify#286]
Hello, I would like some help to compile an image.
It seems that the engine is OpenSeadragon, but dezoomify can't find a proper dezoomer.

https://patrimoine.mines-paristech.fr/document/Atlas_Fourcy_Paris_1859

Thank you in advance.

**Comment by dancorpse** [comment]
Hi, pls try : http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://patrimoine.mines-paristech.fr/files/zoom_tiles/Atlas_cartes/Atlas_Fourcy_Paris_1859/Atlas_Fourcy_Paris_1859_01_Couverture_zdata/ImageProperties.xml
