### ISSUE TITLE
Easyzoom

### ISSUE THREAD

**Issue by themantripleman** [lovasoa/dezoomify#287]
Not sure if it's possible, but is there a method for using dezoomify on Easyzoom? For this page, https://easyzoom.com/imageaccess/ec482e04c2b240d4969c14156bb6836f, for example.

**Comment by lovasoa** [comment]
It looks like they use a single file, in a format they call `szi`. The URL of the file can be found in the network console of your browser, in your case : 

https://easyzoom.blob.core.windows.net/tiled/ad156ec8-3738-4395-8896-d15cf2992b87/ad156ec8-3738-4395-8896-d15cf2992b87.szi

Once downloaded, it appears that this file is in fact a simple zip.
Once unzipped, it reveals a folder containing tiles for a seadragon image.
Dezoomify can be used with a local web server to assemble these tiles.

Here is the result : 

![trade-zoom](https://user-images.githubusercontent.com/552629/58699285-6939a380-839d-11e9-9ba1-80df79b62994.jpg)

**Comment by themantripleman** [comment]
Cool, thanks for the info and reply.

**Comment by lovasoa** [comment]
Note from 2021: [dezoomify-rs](https://dezoomify-rs.ophir.dev/) can be used to reconstruct the original image after the unzip step.
