### ISSUE TITLE
Can’t dezoomify from asmilano.it (IIPImage)

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify#288]
Sample public link: http://www.asmilano.it/Divenire/ua.htm?idUa=10645310. Choose a map, click on "vedi nel contesto archivistico>immagini" and activate plug-in. I read another similar issue (https://github.com/lovasoa/dezoomify/issues/117) but I didn't understand how to fix the problem.
Regards
A

**Comment by dancorpse** [comment]
Click one map and the image is all black for me, how come?

**Comment by Arekkusu1998** [comment]
Thank you for your reply, Dancorpse!
What you said is true: this website is complicate. So, follow this procedure. 
First of all, make sure you have Adobe Flash Player installed on your computer. 
Then, starting from the black page, click on the top right "vedi la carta nel contesto archivistico" (= see the map in the archival context). 
On the page that opens, next to "Scheda completa" (= description of the map), click on "Immagini": at this point a blank page should appear with the writing in the middle "Fai click per attivare Adobe Flash Player" (= click to activate Adobe Flash Player). 
Click, activate Flash and a small zoomable map would appear.
Refresh the previous black page and the big zoomable map should appear. By doing so, everything should be ok ... I hope.
Dezoomify don't work: when I click on maps, not appear the link "copy image address" (and, unfortunately, I'm not familiar with either scripts or nodes). 
Is there an intuitive solution, please?

**Comment by dancorpse** [comment]
Got it!

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://www.asmilano.it/fast/iipsrv.fcgi?deepzoom=/opt/divenire/files/./tifs/05/63/563559.tif.dzi

This is IIPimage and can follow this way, pls refer to my old issue :https://github.com/lovasoa/dezoomify/issues/49, where lovasoa has explained.

**Comment by Arekkusu1998** [comment]
Thank you so much for your aid, dancorpse: I could never have solved the issue without you!
However, very large images're still a problem: Dezoomify works but appears: "Loading the tiles (100%) - Converting image...". 
In https://github.com/lovasoa/dezoomify/issues/272 scouserdave proposes to raise the gfx.max-alloc-size in Firefox: but how much? What number should I put, please? I don't want may make my browser unusable 😢.
In https://github.com/lovasoa/dezoomify/issues/282 lovisoa proposes to use dezoomify.py but, frankly, I don't understand anything: I should install the Python 3 script and then ... and then boh (yes: I'm a TERRIBLE dummy!).

**Comment by dancorpse** [comment]
I have the same problem with extremely large images also, it may be because of the memory. And I do not have any knowledge abt dezoomify.py either.  : ) 
Regarding max-alloc-size in FF, pls refer to https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ
you can change the value to 2000000000, but it does not seem to be always effective for me.

**Comment by Arekkusu1998** [comment]
Thanks again for your advice and your precious indication, dancorpse: I followed the instructions recommended by lovisoa and I was able (although with some difficulties) to download even very large images 😊.

**Comment by rigel71** [comment]
I tried, but I can't download ... only 100% red line and converting image. where am I wrong?

**Comment by Arekkusu1998** [comment]
rigel71 (by the way, nice nickname: a very bright star of Orion's constellation!), I believe you're downloading a very large image. If you have raised the size gfx.max-alloc in Firefox to 2000000000 following these instructions (https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ) but the problem persists, it could mean that the image is really too much great ... but I'm not a programmer and there's another solution that I dont' understand: **Dezoomify.py**. Read: https://github.com/lovasoa/dezoomify/issues/282.
Your issue is yet a bit vague 🤔 : it would be useful to know which image you cannot download.

**Comment by Arekkusu1998** [comment]
rigel71 (by the way, nice nickname: a very bright star of Orion's constellation!), I believe you're downloading a very VERY large image. If you have raised the size gfx.max-alloc in Firefox to 2000000000 following these instructions (https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ) but the problem persists, it could mean that the image is really too much great ... but I'm not a programmer and there's another solution that I dont' understand: Dezoomify.py. Read: #282.
Your issue remains yet a bit vague thinking : it would be useful to know which image you cannot download.

**Comment by rigel71** [comment]
http://www.asmilano.it/Divenire/ua.htm?idUa=10637439 
I have to dezooming this maps
are you italian? 
we can contact us directly rigel456@virgilio.it :-)

**Comment by Arekkusu1998** [comment]
Yes ... but I come neither from Milan nor from Lombardy; I live in one of the Regions that were administered by the Habsburgs in Northern Italy (and, unfortunately, also by the Napoleon!).
As you asked, I will write to you in the mailbox.

**Comment by lovasoa** [comment]
Hello everyone!
  It's nice to see people helping each other.
  Special thanks  to @dancorpse for being so reactive and helping everyone so often here.
  @rigel71 your image is really large (15001x48002 pixels). Dezoomify currently cannot handle such large images, and probably will never be able to, due to browser limitations.
   I started a [new project](https://github.com/lovasoa/dezoomify-rs) just today that should eventually be able to handle very large images, but it's not ready yet.

**Comment by rigel71** [comment]
hello Lovasoa!
 @dancorpse was really precise and detailed in the explanation. I thank him and you for your attention. I am in no hurry to download very large files. if you have suitable software in the future I will gladly test it.

**Comment by dancorpse** [comment]
Hi, Everyone
It's my pleasure to solve the problems! However there's still lots of issues I cannot help, I really wish I could have further knowledge.

**Comment by rigel71** [comment]
sorry Arekkusu1998, 
I have to thank infinitely for your interest in my problem and your advice.
you have been precious :-)

**Comment by Arekkusu1998** [comment]
A new version of Dezoomify to download very large images? 
**It's great news**, **[lovisoa](https://github.com/lovasoa)**: I have some really huge maps that even with the _gfx.max-alloc-size_ trick in Firefox I can't see 😭.

**Comment by lovasoa** [comment]
@Arekkusu1998 After the last update, dezoomify should not choke on very large images anymore. I also updated the wiki pages about very large images.

**Comment by rigel71** [comment]
hi i tested to dezoomify this new update with UI.MAX_CANVAS_AREA = 67108864 but result an error
Error: Unable to load tile. Check that your internet connection is working and that you can access this url: http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536765.tif&JTL=7,0.
How i can do?

**Comment by lovasoa** [comment]
@rigel71  What error did you see before ?

**Comment by rigel71** [comment]
i copy the url and in console copy UI.MAX_CANVAS_AREA = 67108864
then start to dezoomify but result 
**Caricamento in corso di contenuto non attivo misto (non sicuro) “http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536765.tif&JTL=7,0” su una pagina sicura
zoommanager.js:318:1
Caricamento in corso di contenuto non attivo misto (non sicuro) “http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536765.tif&JTL=7,1” su una pagina sicura
zoommanager.js:318:**
then th red Error: Unable to load tile. Check that your internet connection is working and that you can access this url: http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536765.tif&JTL=7,0 (https://ophir.alwaysdata.net/dezoomify/zoommanager.js:190)
I don't know what is the problem

**Comment by lovasoa** [comment]
You can get rid of the message about [passive mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Mixed_passivedisplay_content) by loading the http version of dezoomify (http://ophir.alwaysdata.net/dezoomify/dezoomify.html) These messages don't seem to be related to `MAX_CANVAS_AREA` anyway.

**Comment by Arekkusu1998** [comment]
Excuse me, **[@rigel71](https://github.com/rigel71)**, but I don't understand what image you're trying to dezoomify from the Milan State Archive: I clicked all urls you indicated, but the result is this absurde:
> TIFFReadEncodedTile failed for /opt/divenire/files/./tifs/05/36/536765.tif
>
Can I know which map it is? Maybe (**maybe**!) I can help 🤔.

**Comment by rigel71** [comment]
Hi @Arekkusu1998, i have do dezoomify the map of Averara and Ornica in CATASTO LOMBARDO VENETO. CENSO STABILE. MAPPE ORIGINALI PRIMO RILIEVO. if you could help me I would be very grateful.

**Comment by Arekkusu1998** [comment]
Good morning, @rigel71.
I'm sorry: worst news.
First of all, I tried to dezoomify the Municipality of **Averara**, using the following urls: http://www.asmilano.it/fast/iipsrv.fcgi?deepzoom=/opt/divenire/files/./tifs/05/36/536765.tif.dzi (Sheet 1) and http://www.asmilano.it/fast/iipsrv.fcgi?deepzoom=/opt/divenire/files/./tifs/05/36/536766.tif.dzi (sheet 2) .
In both cases **I get the message you see _below_**.
Then, I tried to dezoomify the Municipality of **Ornica**, but I _can't even visualize the sheets_.
Discouraged, I let one day pass.
Now all the cadastral sheets of the Milan State Archive **_is no longer even visible_**😢. _WHY_😨??? I have no idea if this is a transient problem that only exists in these days, or if it is the beginning of a software restyling. I just know it piss me off (cioè _sono incazzato nero_, tanto per capirsi 😠 ... mi scusi il linguaggio) ...
![Screenshot](https://user-images.githubusercontent.com/48092608/58947230-ccee1300-8787-11e9-8ab2-f4f80e3dc8f5.png)

**Comment by rigel71** [comment]
I wrote to the archive to get an explanation. 
yesterday I tried with Averara in a moment that we saw the maps and downloaded it at 35% and then stopped. maybe they are doing updates. I hope.
even my friends are stuck in their works.
I'm waiting for an answer from the archive.
we hope well...

**Comment by rigel71** [comment]
YEAH! it's ok
thanks Lovasoa!!! :-)

**Comment by Arekkusu1998** [comment]
Very good, @rigel71: I'm glad the matter was resolved with everyone's profit (even if it makes me feel that I cannot help). Hoping, obviously, that Milan State Archive will no longer do these bad jokes ... or worse, _**changing** the parameters_ to the software DIVENIRE. 
Good work to You & Your friends.

**Comment by lovasoa** [comment]
The new project I was talking about, [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs), is now in a usable state and can easily dezoom super-large images.

**Comment by amadvance** [comment]
Just to report that dezoomify-rs works well with www.asmilano.it, even with big images.

The command-line to use is: dezoomify-rs http://www.asmilano.it/fast/iipsrv.fcgi?IIIF=/opt/divenire/files/./tifs/05/36/536992.tif/info.json

Which image to download is selected by the "05/36/536992" triplet. It's easy to find it, enabling the browser Web Console/Network panel while showing the image in the browser itself. Also the Dezoomify browser extension can be used to find out the triplet to use.

But take care that the link proposed by the Dezoomify browser extension doesn't work (like
http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536992.tif). Just pick the the "05/36/536992" and copy it in the example URL above.

This is an example session. The program allows also to select what size to download.

```
C:\>dezoomify-rs http://www.asmilano.it/fast/iipsrv.fcgi?IIIF=/opt/divenire/files/./tifs/05/36/536992.tif/info.json
Trying to locate a zoomable image...
Downloading http://www.asmilano.it/fast/iipsrv.fcgi?IIIF=/opt/divenire/files/./tifs/05/36/536992.tif/info.json...
Found the following zoom levels:
0. 536992.tif (13997 x 15238 pixels,  3300 tiles)
1. 536992.tif ( 6998 x  7619 pixels,   840 tiles)
2. 536992.tif ( 3499 x  3809 pixels,   210 tiles)
3. 536992.tif ( 1749 x  1904 pixels,    56 tiles)
4. 536992.tif (  874 x   952 pixels,    16 tiles)
5. 536992.tif (  437 x   476 pixels,     4 tiles)
6. 536992.tif (  218 x   238 pixels,     1 tiles)
Which level do you want to download?
0
Dezooming 536992.tif (13997 x 15238 pixels,  3300 tiles)
[ETA:0s] ######################################## 3300/3300 Downloaded all tiles.
Saving the image to dezoomified.jpg...
Saved the image to \\?\C:\dezoomified.jpg
Done!
dezoomify-rs http://www.asmilano.it/fast/iipsrv.fcgi?IIIF=/opt/divenire/files/./tifs/05/36/536729.tif/info.json
```

Bye!

**Comment by lovasoa** [comment]
@amadvance : Oh, it looks like you found a bug in the dezoomify extension ! Would you care to report it on the [dezoomify extension bug tracker](https://github.com/lovasoa/dezoomify-extension/issues) ? You can specify the webpage you are on, the result you get, and the result you would expect instead.

**Comment by amadvance** [comment]
Hi @lovasoa 

I don't know to what app the bugs is, and if there is a bug or not.

Anyway, it happens for all the images of www.asmilano.it: Like this one: http://www.asmilano.it/Divenire/document.htm?idDoc=10643414&idUa=10643413&first=0&last=0

The proposed link by Dezoomify is: http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536992.tif

Downlading that link with Dezoomify always fails with: (after getting to 100% tiles download)
```
TypeError: Argument 1 is not valid for any of the 1-argument overloads of URL.createObjectURL.

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:133)
```
Downlading that link with dezoomify.rs always fails with:
```
C:\>dezoomify-rs.exe http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536992.tif
Trying to locate a zoomable image...
Downloading http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536992.tif...
network error: HTTP status client error (400 Bad Request) for url (http://www.asmilano.it/fast/iipsrv.fcgi?FIF=/opt/divenire/files/./tifs/05/36/536992.tif&_sm_byp=iVVHW4f5VttPrDRk)
```

I workarounded the issue using the IIIF protocol, that the IIPImage server supports, even if not explicitly used by the www.asmilano.it site. So, it's likely right that the Dezoomify proposes the FIF link. But not idea why it doesn't work.

Bye!
