### ISSUE TITLE
Problem with dzi file at National Archives

### ISSUE THREAD

**Issue by notbob1959** [lovasoa/dezoomify#29]
First, thanks for this very useful piece of software!

Found associated dzi file for image at National Archives but I get this error: Unable to extract informations from the given file !

Image:
https://research.archives.gov/id/7029407
associated dzi file:
https://catalog.archives.gov/OpaAPI/media/7029407/opa-renditions/image-tiles/95-GP-3287-Box0552_003_001_AC.jpg.dzi

**Comment by lovasoa** [comment]
Interesting! I think I found where the error comes from:
The [small proxy](https://github.com/lovasoa/dezoomify/blob/master/proxy.php#L5) we use to make requests uses PHP streams to make the requests, and by default they don't send any header.

And the server refuses to serve the dzi file when the `User-Agent` header isn't set.

**Comment by notbob1959** [comment]
Works now. Thanks again!

**Comment by lovasoa** [comment]
You're welcome, I'm glad to help :)
