### ISSUE TITLE
Unable to dezoomify from archive.thulb.uni-jena.de

### ISSUE THREAD

**Issue by Arekkusu1998** [lovasoa/dezoomify#292]
I tried to dezoomify https://archive.thulb.uni-jena.de/ufb/rsc/viewer/ufb_derivate_00011987/ThULB_129489816_1866_Perthes_0506_Rescan.tif, even with the "Generic dezoomer", but I failed. Can you help or advise me please?
Regards.

**Comment by dancorpse** [comment]
Hi, it works with Generic dezoomer, you should figure out the highest zoom level, in chrome, right click - choose "inspect" , navigate to "application", under frame section, click "image" bar, there are the image tiles, the image url structure is like "xxxxxxxxxxxx/{zoom level}/{{X}}/{{Y}}.jpg", guess out the highest level of the image is "6", so pls have a try: http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://archive.thulb.uni-jena.de/ufb/servlets/MCRTileServlet/ufb_derivate_00011987/ThULB_129489816_1866_Perthes_0506_Rescan.tif/6/{{X}}/{[Y}}.jpg

**Comment by Arekkusu1998** [comment]
Thank you so much again for your aid, Dancorpse 😃 : your explanations were very clear!!
Now, I understand also where and how to go to find the tiles for "Generic Dezoomer" (the video tutorial of lovisoa has the screen in French ... and a few old: I had some difficulties to comparate with nowday Chrome ...). 
However, there's a strange thing ... a mistery: to download the map I had to invert the abscissa and ordinate: **first** put {{Y}} and **only after** {{X}}, otherwise watch what I get 😳 (the image is reduced): it's hilarious, isn't it?

![canvas](https://user-images.githubusercontent.com/48092608/56889935-376cae80-6a78-11e9-8397-dc4a1c0ff794.png)

**Comment by Arekkusu1998** [comment]
I've accidentally closed the issue, my God 🙄 ! What's wrong on my mind???

**Comment by dancorpse** [comment]
Oh, I'm sorry, I did not even notice this problem! That's exactly the case in my old issue: #228 , still remain unsolved!

**Comment by Arekkusu1998** [comment]
Indeed it's a mystery 😩 ...

However, I have read the problem you're saying: https://github.com/lovasoa/dezoomify/issues/228. 
I was able to dezoomify the first painting ("**The Church at Chailly**") without problems using Firefox and with the image's path https://b.tiles.dx.artsmia.org/1637/5/{{X}}/{{Y}}.png. The image I get is 9216 x 7680 px, its weight is 192 MB and it's _**complete**_. 
Let me know if the issue persists even with Firefox.

About the second portrait ("**Seated Shepherdess**"), what occurs to you, occurs to me too: the tiles loaded are mismatched. 
But perhaps there's an alternative. 
In Chrome, right click - choose "Inspect"; navigate to "Network" and to "Img"; hit "Ctrl+R" and look to the long blue barrel (the values of the line should be the following: _1397.jpg | 200 | jpeg | bundle.js:22 | from disk cache_); click on the blue barrel and choose "Open in new tab". A new page should open with the complete and _**perfect**_ painting with this resolution: 1569 x 1920 px (which is basically almost the maximum zoom level you can get, if you make a comparison with website). 
Yes: bit complicate 🤔, I'm sorry!

**Comment by dancorpse** [comment]
Wow, great! The first painting now is complete with dezoomify! And the second, I found the full image by following your steps, Now I know how to get the full image without using dezoomify at this website: https://4(or any number).api.artsmia.org/full/xxxx.jpg :) Thank you so much!
