### ISSUE TITLE
Can't Download at High Resolution (Google Arts and Culture)

### ISSUE THREAD

**Issue by solvethis** [lovasoa/dezoomify#296]
Hello,
I just found out Dezoomify on Reddit. I am trying to download an [art piece ](https://artsandculture.google.com/asset/the-tortoise-trainer/3AFvsWCD87FIWg) from Osman Hamdi as high as possible. 

Actually, the program gives me (2373x4400), very high res image, but I saw more available sizes on [different site.](http://gigafineart.herokuapp.com/gcidownload)

<img width="1295" alt="Dezoomify   GigaFineArt" src="https://user-images.githubusercontent.com/51164335/58562589-34f5a400-8232-11e9-9307-6a155403f995.png">

Is there any way to download the image on a higher resolution than the default one? Can I select a size before saving?

Thank you,
It is great to have an alternative of GigaFineArt

**Comment by lovasoa** [comment]
Dezoomify currently restricts the maximum width and height of the downloaded image to 8192 x 8192 (it will take the largest zoom level that has both its width and its height under 8192). There is two reasons for that: 
 * dezoomify uses a free shared web host, and the google arts & culture dezoomer requires us to make a request to our host for each tile of the image. We don't want to put our server under too much load.
 * Your browser probably cannot create a canvas with an area of more than half a billion pixels anyway.

[GAPDecoder](https://github.com/expenses/gapdecoder) is another project that takes the form of a python script. It is less easy to install, but has none of the above limitations.

We may still discuss the limit (8192 is quite arbitrary). I could also add a way for advanced users to work around it.

**Comment by lovasoa** [comment]
By the way, does GigaFineArt work for you ? I tried it, and it produced completely black images.

**Comment by lovasoa** [comment]
I updated dezoomify. The limit is now set on the total area in pixels of the image. It is 268,435,456 by default and you can override it by setting `UI.MAX_CANVAS_AREA = 1073741824` in your browser console before starting the dezooming. However, be warned that your browser may refuse to create such a large canvas.

**Comment by solvethis** [comment]
> By the way, does GigaFineArt work for you ? I tried it, and it produced completely black images.

I tried on many browsers. It only works on Mozilla Firefox. So it doesn't work on Safari, Edge and Internet Explorer etc.

**Comment by solvethis** [comment]
> Dezoomify currently restricts the maximum width and height of the downloaded image to 8192 x 8192 (it will take the largest zoom level that has both its width and its height under 8192). There is two reasons for that:
> 
> * dezoomify uses a free shared web host, and the google arts & culture dezoomer requires us to make a request to our host for each tile of the image. We don't want to put our server under too much load.
> * Your browser probably cannot create a canvas with an area of more than half a billion pixels anyway.
> 
> [GAPDecoder](https://github.com/expenses/gapdecoder) is another project that takes the form of a python script. It is less easy to install, but has none of the above limitations.
> 
> We may still discuss the limit (8192 is quite arbitrary). I could also add a way for advanced users to work around it.

I understand what would happen to browser. Actually I tried to download Python but I am not be able to use it. My programming skills are just low.

**Comment by solvethis** [comment]
> I updated dezoomify. The limit is now set on the total area in pixels of the image. It is 268,435,456 by default and you can override it by setting `UI.MAX_CANVAS_AREA = 1073741824` in your browser console before starting the dezooming. However, be warned that your browser may refuse to create such a large canvas.

Thank you very much :)
 With this high-quality art pieces is more accessible to me. Also, I won't need a google account for adding favorites anymore. Because I can access them offline when I downloaded.

**Comment by lovasoa** [comment]
**[dezoomify-rs](https://github.com/lovasoa/dezoomify-rs#dezoomify-rs)** now supports google arts and culture, and it can download images at even the largest zoom levels.
