### ISSUE TITLE
IIIF and bavarikon.de 

### ISSUE THREAD

**Issue by kaithaba** [lovasoa/dezoomify#298]
Can't for the life of me figure out what Dezoomify needs to dig out the full-size photos on bavarikon.de. It seems to me like the right URL to feed in would be this 

https://www.bavarikon.de/iiif/BSB-BAR-0000000000062999/info.json

(where the number would obviously be the specific picture you want) but it keeps giving me the Uncaught Error: Unable to load first tile: https://www.bavarikon.de/iiif/BSB-BAR-0000000000062999/0,0,1024,1024/1024,1024/0/default.jpg

It basically seems to be blocking requests and won't let Dezoomify find the first tile; the same problem others have had, right? 

The photo I was trying to get is on this page:
https://www.bavarikon.de/object/bav:BSB-BAR-0000000000062999

What am I doing wrong? Apologies since this overlaps with some of the other questions, but as I couldn't find a solution that worked for this particular site, I had to ask.

**Comment by lovasoa** [comment]
It looks like the server responds with a **403 Not Authorized** HTTP response whenever the Referer HTTP header is not set to an URL from their own website. Dezoomify currently does not fake a referer when querying tiles, but it could...

**Comment by lovasoa** [comment]
You might be able to do something with [dezoom.sh](https://github.com/lovasoa/dezoom.sh), using the wget_params options to set a custom referer. It will require some technical knowledge, though.

**Comment by kaithaba** [comment]
Thanks; I figured it was an authorisation issue. But as for the referrer hack, I'm afraid I'm more of a Photoshop nerd and my skillset doesn't extend to that area. If you can think of a workaround in the future, I'd be grateful, of course!

**Comment by lovasoa** [comment]
I also updated dezoomify to fake the referer when tile requests go through the server.

This means that `https://www.bavarikon.de/iiif/BSB-BAR-0000000000062999/info.json` now works on dezoomify if you [set up a tile proxy](https://github.com/lovasoa/dezoomify/wiki/Very-large-images#tiles-proxy).

![dezoomify-result](https://user-images.githubusercontent.com/552629/60403403-f3437a80-9b9c-11e9-869c-2a10e680c15e.jpg)


I also published a new version of [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) today with support for faking HTTP headers, including the referer.

**Comment by kaithaba** [comment]
Works beautifully now, thank you! And extra thanks for graciously showing how to set up that proxy for us less code-savvy types. Mightily kind of you :)

**Comment by tywuser** [comment]
I have just tried the above described example with https://www.bavarikon.de/iiif/BSB-BAR-0000000000062999/info.json on dezoomify using the suggested proxy setup (proxy.php) and unfortunately it does not work in my case (Error message: "Unable to fetch https:..").
The image that I would actually like to download is: https://www.bavarikon.de/object/bav:GDA-OBJ-0000000000000030 (I tried to dezoomify using the URL https://www.bavarikon.de/iiif/GDA-OBJ-0000000000000030/info.json following the example above but it does not work either.)
Am I doing something wrong?
