### ISSUE TITLE
Issue with https://www.sydstories.com.au/#/gallery/slides/images

### ISSUE THREAD

**Issue by Laowai75** [lovasoa/dezoomify#299]
Hi everyone,

I tried everything I could with this website but have been unsuccessful: https://www.sydstories.com.au/#/gallery/slides/images

Can you please help out?

Thank you in advance for your kind assistance!

**Comment by lovasoa** [comment]
Looks like you can use the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#the-page-uses-an-image-viewer-that-is-not-supported-by-dezoomify-is-there-still-a-chance-) here.
https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://d374ql52oni4o2.cloudfront.net/assets/Chapter_01/Slide_06/1_2_1_BotanyBay-map_/18/map_tile_{{X}}_{{Y}}.png

![canvas](https://user-images.githubusercontent.com/552629/59570095-206b3580-9093-11e9-9c71-92cdc100a37e.png)

**Comment by Laowai75** [comment]
Thank you very much!
