### ISSUE TITLE
error - Uncaught TypeError: Cannot read property 'importKey' of undefined

### ISSUE THREAD

**Issue by janko216** [lovasoa/dezoomify#300]
I run dezoomify on my own page.., but I always get this error: 

"Uncaught TypeError: Cannot read property 'importKey' of undefined
(http://xyz.cz/zoom/dezoomers/google-arts-culture-crypto.js:11) "

I managed to download an image from google-arts, but after first success it has changed and now I'm not able to run it anymore... Do you have any ideas, please? Thank you in advance! It's a really usefull library.

**Comment by lovasoa** [comment]
The google arts and culture dezoomer uses the browser's cryptographic APIs, which are available only to https pages in chrome. You have to serve dezoomify in HTTPS if you want to use the google arts and culture dezoomer in google chrome.

**Comment by janko216** [comment]
I works :-) Thank you!
