### ISSUE TITLE
Downloading from Ashmolean Museum

### ISSUE THREAD

**Issue by Sindi43** [lovasoa/dezoomify#302]
Hello,

I tried to download this image :

http://collections.ashmolean.org/collection/search/per_page/25/offset/0/sort_by/relevance/object/49078

Unfortunately dezoomify doesn't work...

Can you help me?

Thx!

**Comment by lovasoa** [comment]
http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://collections.ashmolean.org/media/ashmole6_collection/zoom/Collections/Single_Objects/WA/WA_1952/WA_1952_0000/WA_1952_6_2-a/GeneratedImages/dzc_output.xml


![canvas](https://user-images.githubusercontent.com/552629/61598688-a560e600-ac21-11e9-9d4d-0f8e83686ea0.jpg)

**Comment by lovasoa** [comment]
You can read the FAQ to learn how to find the URL to give dezoomify: https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ

**Comment by Sindi43** [comment]
Thank you very much!

It works for all images except this one:
http://collections.ashmolean.org/collection/search/per_page/25/offset/0/sort_by/date/object/49977

I have a bug and this message:

Error: Unable to load tile. Check that your internet connection is working and that you can access this url: http://collections.ashmolean.org/media/ashmole6_collection/zoom/Collections/Single_Objects/WA/WA_1955/WA_1955_0000/WA_1955_67-a/GeneratedImages/dzc_output_files/13/11_0.jpg (https://ophir.alwaysdata.net/dezoomify/zoommanager.js:190)
