### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Sindi43** [lovasoa/dezoomify#305]
Hello

Dezoomify works for all images except this one:
http://collections.ashmolean.org/collection/search/per_page/25/offset/0/sort_by/date/object/49977

I have a bug and this message:

Error: Unable to load tile. Check that your internet connection is working and that you can access this url: http://collections.ashmolean.org/media/ashmole6_collection/zoom/Collections/Single_Objects/WA/WA_1955/WA_1955_0000/WA_1955_67-a/GeneratedImages/dzc_output_files/13/11_0.jpg (https://ophir.alwaysdata.net/dezoomify/zoommanager.js:190)

Thx for your help !

**Comment by lovasoa** [comment]
Well, as stated in the error message, some of the tiles are not available. This is not a bug in dezoomify. The mentioned tile is not available: 
http://collections.ashmolean.org/media/ashmole6_collection/zoom/Collections/Single_Objects/WA/WA_1955/WA_1955_0000/WA_1955_67-a/GeneratedImages/dzc_output_files/13/11_0.jpg
