### ISSUE TITLE
New Site Support: https://texashistory.unt.edu

### ISSUE THREAD

**Issue by sootymicrobe** [lovasoa/dezoomify#307]
Hello,

I tried to download an image divided in tiles:

https://texashistory.unt.edu/ark:/67531/metapth177646/m1/1/zoom/?resolution=6&lat=4744&lon=3517

Unfortunately dezoomify doesn't work (generic dezoomer method). I can't seem to find what type of zoom it is either.
When I try to do the generic dezoomer with "https://texashistory.unt.edu/ark:/67531/metapth177646/m1/1/tiles/TileGroup3/6-{{X}}-{{Y}}.jpg" I get the error message, "Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
https://texashistory.unt.edu/ark:/67531/metapth177646/m1/1/tiles/TileGroup3/6-0-3.jpg

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:190)"

Can you help me?

Thank you!

**Comment by lovasoa** [comment]
The dezoomer they use is zoomify, which is (of course) supported by dezoomify. You only have to find the meta-information url (replacing the end of the url with `ImageProperties.xml`):

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://texashistory.unt.edu/ark:/67531/metapth177646/m1/1/tiles/ImageProperties.xml

![texashistory](https://user-images.githubusercontent.com/552629/62556400-12f15100-b875-11e9-9edb-ab5e9391993c.jpg)
