### ISSUE TITLE
[new site support] rkd.nl - topviewer, not working? 

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#308]
rkd.nl is using topviewer, this site worked well with dezoomify before, but today when I try to loading pictures dezoomify returned with :　Uncaught Error: Invalid JSON: 
Example here: 
https://rkd.nl/en/explore/images/record?filters%5Bkunstenaar%5D=Isra%C3%ABls%2C+Jozef&filters%5Bcollectienaam%5D%5B0%5D=Gemeentemuseum+Den+Haag&query=&start=16
This there anything wrong?
And I tried the link  in issue #251, also return with failure notice.

**Comment by lovasoa** [comment]
You can open the network monitor to get the small meta-information file (see the FAQ for how to do that), and then use that in dezoomify:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://images.rkd.nl/rkd/topviewjson/memorix/1af28adc-22f7-78a0-6648-98337c56b364?checkIfTiled=1

You have to manually select TopViewer as the dezoomer.

**Comment by lovasoa** [comment]
It looks like there is a bug in dezoomify that is triggered by the special characters in the URL. When I copy-paste the URL you gave (without opening it, just copy-pasting the URL text from your message), it works:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://rkd.nl/en/explore/images/record?filters%5Bkunstenaar%5D=Isra%C3%ABls%2C+Jozef&filters%5Bcollectienaam%5D%5B0%5D=Gemeentemuseum+Den+Haag&query=&start=16

When I first open it, then copy-paste the URL from the address bar in my browser, it doesn't.


![canvas](https://user-images.githubusercontent.com/552629/62934243-57747380-bdc4-11e9-9f59-4dbcadd46e08.jpg)

**Comment by lovasoa** [comment]
I am in fact getting inconsistent results. Retrying the same URL several times sometimes gives an `Invalid JSON` result, and sometimes works... And this isn't very easy to test, since `rkd.nl` takes a long time to respond every time.

**Comment by lovasoa** [comment]
I am closing this for now. We will reopen it if we can make sure the issue comes from dezoomify and not rkd.nl.

**Comment by dancorpse** [comment]
It seems to work well today, I will try again on another day.
And further more yesterday I was not able to find out the meta-information from the network monitor by hitting F5, but today it works~~
