### ISSUE TITLE
Issue with dezoomify

### ISSUE THREAD

**Issue by vva1913** [lovasoa/dezoomify#31]
Hello,
I'm trying to extract the image of zoom-based script of online bibliotheque. Previously I managed to extract over hundred of images, however, now I experience an issue as none of dezoomify options works. I end up with error:
```
Error !
Uncaught TypeError: Cannot read property 'documentElement' of null (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:199)
```

The link I use to extract image is: http://polona.pl/item/5904599/0/
Previously I managed to simply copy the url to dezoomify and it was building up tiles allowing me to save a canvas.png file. If you could have a look at the script in case anything has changed, that would be highly appreciated!

Thank you!
Maria

**Comment by lovasoa** [comment]
Hi! Yes, I've worked on zoomify recently, and this may be a regression. I'm going to look at it asap.

**Comment by lovasoa** [comment]
Thr problem seems to come from dbe016ae07a0bc1a72d851fa4b36b735c707f413.
We now fake a browser while requesting resources, and polona.pl doesn't serve JSON to browsers.

Plus, there is a bug in error reporting that prevents the right error to be reported.
