### ISSUE TITLE
Request support for loading an image from tiles that have different link paths

### ISSUE THREAD

**Issue by Molotov1234** [lovasoa/dezoomify#310]
I found this problem trying to download the best zoom avaiable in the
 image from

https://artsearch.nga.gov.au/zoom/zoom.cfm?zimagepath=36334&view=lrg&irn=36334

Generic dezoomer works up to a point. I always get an incomplete image. It seems that the problem is that the website keep tile images as resources in different address. To be able to load the full image, dezoomify should be able to create an image from tiles of different address

If I start by https://artsearch.nga.gov.au/zoom/36334/TileGroup1/6-{{X}}-{{Y}}.jpg, the image stops loading at tile 6-42-4 and I get the following error:

![image](https://user-images.githubusercontent.com/54158985/63137689-b3e6b700-bfad-11e9-919b-5789999f5b42.png)

Searching on the website source, I found out that image 6-42-4 is in another repository, as listed:
https://artsearch.nga.gov.au/zoom/36334/TileGroup2/6-{{X}}-{{Y}}

If I try to use this link in dezommer, it does not work and presents the following error:

![image](https://user-images.githubusercontent.com/54158985/63137979-eba22e80-bfae-11e9-9826-366b20c20188.png)

It seems that, in order to work, the code must start loading the image from tile /6-0-0.jpg . But this file is not in /TileGroup2 , but in /TileGroup1

To be able to form a complete image, generic dezoomer should be able to load tiles from 4 different "TileGroups"

https://artsearch.nga.gov.au/zoom/36334/TileGroup1/ 
https://artsearch.nga.gov.au/zoom/36334/TileGroup2/ 
https://artsearch.nga.gov.au/zoom/36334/TileGroup3/ 
https://artsearch.nga.gov.au/zoom/36334/TileGroup4/ 

Is there a workaround? Thks

**Comment by lovasoa** [comment]
Hello, and thank you for using dezoomify!
The generic dezoomer is the one to use in last resort. In case your image is in a format that is already supported by dezoomify, you should use the specialized dezoomer for this format. See the [FAQ](https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ).

In this case, the image uses the zoomify zoomable image format, and you can find the meta-information file by replacing `TileGroupN/Z-X-Y.jpg` with `ImageProperties.xml` : 

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://artsearch.nga.gov.au/zoom/36334/ImageProperties.xml

![canvas](https://user-images.githubusercontent.com/552629/63151111-03a69c00-c009-11e9-8dd8-7f9ccfa130dc.jpg)
