### ISSUE TITLE
[new site support] Leiden University Libraries

### ISSUE THREAD

**Issue by Jakeukalane** [lovasoa/dezoomify#312]
Leiden University Libraries. Important libraries with many manuscripts.
I want to download this: https://socrates.leidenuniv.nl/view/item/1602811 They said "Restriction on access: Download provided" that it means there is no restriction suposedly, but the dowloades image is extremely small.

Also, the PDF download is not the full resolution, although is bigger than the image download.

So, when in the inspector, I found this https://socrates.leidenuniv.nl/iiif/2/item:1602811~JP2~b49ef9bbbe16a4ef41ea14ea2515f00abd9726cb03267f363242242e7d255b99~default (the title is info.json) that it says 403 forbbiden although in the browser is used by the zoomify IIIF... Previewing in chrome has this code: https://pastebin.com/raw/Q4Kai38X it seems to me the proper thing, but it lacks json format somehow (I tried to upload to other place to make dezoomify work with it, but is not valid)

Also the 403 errors prevents from doing anything with 
https://socrates.leidenuniv.nl/iiif/2/item:1602811~JP2~b49ef9bbbe16a4ef41ea14ea2515f00abd9726cb03267f363242242e7d255b99~default/0,2032,3010,2031/3010,/0/default.jpg → https://socrates.leidenuniv.nl/iiif/2/item:1602811~JP2~b49ef9bbbe16a4ef41ea14ea2515f00abd9726cb03267f363242242e7d255b99~default/0,full/full/0/native.jpg

I hope my report is correct.
Thank you very much!

greetings!

**Comment by lovasoa** [comment]
Hello, I'm away from my computer and will do some tests with this site later. 
There is generally two solutions to work around sites restricting access to tiles: using a tile proxy or using dezoomify-rs. Have a look at our FAQ for details about how to use them.

**Comment by lovasoa** [comment]
It looks like the site restricts the downloads based on the `Referer` header, but has a very generous maximum area restriction (400000000 square pixels). So the whole image can be downloaded at once just by making a request with the right referer:

```
wget -O dezoomed.jpg "https://socrates.leidenuniv.nl/iiif/2/item:1602811~JP2~4866b265d063716c5f9ef678ffb988016df2d4075b82e53aaa6a652864943b57~default/full/max/0/default.jpg" --header "Referer: https://socrates.leidenuniv.nl/view/item/1602811"
```

Which gives:
![img](https://user-images.githubusercontent.com/552629/63636739-b7e09c00-c673-11e9-9cdb-adad43b0df24.jpg)

**Comment by lovasoa** [comment]
And in case you would encounter a website that does not have this generous max download area, you can always use [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs), which allows setting custom headers for tile requests. Here is how you would call dezoomify-rs:

```
/dezoomify-rs 'https://socrates.leidenuniv.nl/iiif/2/item%3A1602811%7EJP2%7E4866b265d063716c5f9ef678ffb988016df2d4075b82e53aaa6a652864943b57%7Edefault/info.json' --header "Referer: https://socrates.leidenuniv.nl/view/item/1602811"
```

**Comment by lovasoa** [comment]
I am also going to update the [How to access protected pages](https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages) wiki page in order to mention this kind of Referer restrictions.
