### ISSUE TITLE
[new site support] raremapsdotcom

### ISSUE THREAD

**Issue by worldnam** [lovasoa/dezoomify#313]
### Site name and desciption 
What is the name and the URL of the site you would like dezoomify to support ?
How to download full resolution images from raremapsdotcom?

### Example URLs
 - Give the URLs of viewing pages
https://www.raremaps.com/gallery/detail/46087/south-america----southern-part-hulsius

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.
Uncaught Error: Invalid XML:
https://www.raremaps.com/gallery/detail/46087/,g=d.XML

(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:191)

**Comment by lovasoa** [comment]
You have to find the meta-information file. See the [Frequently Asked Questions](https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ) for more information about how to do that.

In your case, it is `ttps://storage.googleapis.com/raremaps/img/dzi/img_46087.dzihttps://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://storage.googleapis.com/raremaps/img/dzi/img_46087.dzi`:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://storage.googleapis.com/raremaps/img/dzi/img_46087.dzihttps://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://storage.googleapis.com/raremaps/img/dzi/img_46087.dzi
