### ISSUE TITLE
Hagley Museum

### ISSUE THREAD

**Issue by ellipsograph** [lovasoa/dezoomify#314]
The Hagley Museum seems to use be doing something to prevent IIIF images from being downloaded.

Example page: https://digital.hagley.org/LMSS_2268_OS04_14_002
Metadata: https://digital.hagley.org/iiif/2/islandora%3A2609582/info.json

Error returned by Dezoomify page:
Error: Unable to load first tile: https://digital.hagley.org/iiif-server/iiif/2/islandora%3A2609582/0,0,1024,1024/1024,/0/default.jpg

**Comment by lovasoa** [comment]
I just updated the [dezoomify's wiki page about protected images](https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages), which contains information about how to work around the limitation.

**Comment by lovasoa** [comment]
![s](https://user-images.githubusercontent.com/552629/63648139-99d67280-c72b-11e9-9d73-c55b8c5857fa.jpg)

**Comment by ellipsograph** [comment]
If I'm understanding the instructions on the wiki for working around this issue in dezoomify this is the process:
• open dezoomify page
• paste the metadata file into the form
• open the browser console
• paste "ZoomManager.proxy_tiles = "proxy.php";" (without the quotes, obviously) and hit return

At which point Firefox returns an error "ReferenceError: ZoomManager is not defined".

Clearly, this works and the problem is me — but I can't see what I'm missing. (I can't get the syntax for correctly including a referring page in dezoomify-rs to work, either.)

**Comment by lovasoa** [comment]
Can you show a screen capture of where you are pasting the command exactly? One where we can see the page, the console, and the error message.

**Comment by lovasoa** [comment]
as for dezoomify-rs, you can call it in the following way:

```
./dezoomify-rs --header "Referer: https://digital.hagley.org/LMSS_2268_OS04_14_002" "https://digital.hagley.org/iiif/2/islandora%3A2609582/info.json"
```

**Comment by ellipsograph** [comment]
Dezoomify browser proxy. Apparently, the problem I was experiencing had something to do with Firefox not properly initializing a tab that was already open for Dezoomify. There had been nothing at all in the console, even when I refreshed the page, but since I don't spend much time in the console, I found that more curious than immediately concluding that something was wrong.

Once I opened a new tab and followed all the instructions, everything worked as advertised.


As for dezoomify-rs, my mistake was not realizing that I needed to specify both the referring page AND the metadata file from the command line — and then specify the metadata file AGAIN when the program launches. I'm not sure how I missed that, but it's clearly right there in the docs.


Merely as an observation, the sizes of the files returned by both methods are vastly different: 136 MB PNG for the browser-based downloader, and 10 MB JPEG for dezoomify-rs.

**Comment by lovasoa** [comment]
In dezoomify-rs, normally, when you give the metadata file as an argument on the command-line, it doesn't ask for it again when running.

By default, when you right-click on a canvas in firefox and click "save as", it creates a [PNG](https://en.wikipedia.org/wiki/Portable_Network_Graphics). PNG is a lossless image format: it saves the exact value of each pixel, at the expense of large file sizes.

dezoomify-rs supports several output image formats, but by default, when you do not specify an output file name, it creates [JPEG](https://en.wikipedia.org/wiki/JPEG) file (with the name `dezoomified.jpg`). JPEG is a *lossy* image format: it tries to store only the most important information from the original pixels. It creates *compression artifacts*: the image that is saved is not completely the same as the original. But the advantage is that it creates significantly smaller files.

**Comment by ellipsograph** [comment]
I used the entire command line argument you supplied, and dezoomify-rs asked for the metadata file. Is this a bug? Is there something about this syntax that caused it to ask again?

[Terminal.png](https://postimg.cc/MfXpm6ky)

**Comment by lovasoa** [comment]
Ooops ! Yes it's a bug.

**Comment by ellipsograph** [comment]
Happy to help. Sorry for not reporting the bug under the correct product.
