### ISSUE TITLE
https://collections.lib.uwm.edu 

### ISSUE THREAD

**Issue by Historyguy1975** [lovasoa/dezoomify#316]
https://collections.lib.uwm.edu/

Treasure trove of geographical and historical images

Example URLs: https://collections.lib.uwm.edu/digital/collection/catw/id/2645/rec/5
 
urrent error message: Uncaught Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:

Hi, I saw that there was another topic on the same site a few years ago. However, I was not able to make it work. I found the link for the individual tiles, for example: https://cdm17272.contentdm.oclc.org/digital/iiif/catw/2645/2048,0,2048,2048/1024,/0/default.jpg?highlightTerms=undefined%20undefined%20undefined%20undefined%20undefined%20undefined%20undefined%20undefined

But what to do after? I hope you can provide some more direction? Thank you for your patience!

**Comment by lovasoa** [comment]
https://cdm17272.contentdm.oclc.org/digital/iiif/catw/2645/full/max/0/default.jpg

![](https://cdm17272.contentdm.oclc.org/digital/iiif/catw/2645/full/max/0/default.jpg)

**Comment by lovasoa** [comment]
Related issue: #74

**Comment by lovasoa** [comment]
And if you really want to use dezoomify, you have to find the meta-information file `info.json`. In your case `https://cdm17272.contentdm.oclc.org/digital/iiif/catw/2645/info.json ` : 

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://cdm17272.contentdm.oclc.org/digital/iiif/catw/2645/info.json
