### ISSUE TITLE
http://digitalcollections.library.gsu.edu

### ISSUE THREAD

**Issue by Historyguy1975** [lovasoa/dezoomify#318]
### Site name and desciption
http://digitalcollections.library.gsu.edu, Best resource for Georgia (The US State) history

### Example URLs
 - Page with image: http://digitalcollections.library.gsu.edu/cdm/singleitem/collection/eastern/id/57630/rec/203
 - URL for one of the image tiles: http://digitalcollections.library.gsu.edu/utils/ajaxhelper/?CISOROOT=eastern&CISOPTR=57630&action=2&DMSCALE=200&DMWIDTH=512&DMHEIGHT=512&DMX=512&DMY=1536&DMTEXT=&DMROTATE=0

### Current error message
Uncaught Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
http://digitalcollections.library.gsu.edu/cdm/singleitem/collection/eastern/id/57630/

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:191)

Hi, this is very frustrating as I cracked this one a few years back, but for the life of me I cannot get it done now. I have been working on it for an hour. Can you please provide guidance? Thank you as always!

**Comment by lovasoa** [comment]
Hello! 
  it looks like you have the x and y coordinates of the tiles in the tile URL. Looks like the perfect job for [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs)'s custom dezoomer.

**Comment by lovasoa** [comment]
Or even easier: it looks like you can just fiddle with the tile URL parameters to request the whole image at once:

`http://digitalcollections.library.gsu.edu/utils/ajaxhelper/?CISOROOT=eastern&CISOPTR=57630&action=2&DMWIDTH=9999&DMHEIGHT=9999&DMX=0&DMY=0`

![full image](http://digitalcollections.library.gsu.edu/utils/ajaxhelper/?CISOROOT=eastern&CISOPTR=57630&action=2&DMWIDTH=9999&DMHEIGHT=9999&DMX=0&DMY=0)

**Comment by dancorpse** [comment]
Although this is a closed issue, I have further questions.
I tried to download this picture with dezoomify-rs, which I'm not quite understand how to use it, finally I  got this screen: 
![20190905083532](https://user-images.githubusercontent.com/19525152/64302932-39132980-cfb8-11e9-87ce-e30ea696ba3c.png)

**Comment by lovasoa** [comment]
Hi dancorpse! 
  You can use the *custom YAML* dezoomer in dezoomify-rs for this image. You will have to create a tiles.yaml file (instructions about what to write in this file can be found in the will of dezoomify-rs ) and than give dezoomify-rs the path to this file instead of an url. Do not hesitate to open an issue on dezoomify-rs if you think it's documentation is not clear.

**Comment by dancorpse** [comment]
Thanks, lovasoa, I'll have a try~~
