### ISSUE TITLE
Prague Archive Catalogue

### ISSUE THREAD

**Issue by lucifuk** [lovasoa/dezoomify#319]
I live in Prague and interesting by history.
Prague Archive Catalogue has a large collection of very interesting old png images. Some of them I downloaded by Dezoomify used URL from page source. But suddenly something changed at script and Dezoomify reporting:

Error: Unable to fetch http://images.ahmp.cz/mrimage/ahmp/zoomify/cz/archives/CZ-321100010/NAD-157/dao/images/0015/840c767d2c5898d8218cc5f780b4e97b.jpg
The server responded:
fopen(http://images.ahmp.cz/mrimage/ahmp/zoomify/cz/archives/CZ-321100010/NAD-157/dao/images/0015/840c767d2c5898d8218cc5f780b4e97b.jpg): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:394)

Here is main page
http://katalog.ahmp.cz/pragapublica/MenuBar.action
and here Collection of Photograph
http://katalog.ahmp.cz/pragapublica/PaginatorResult.action?_sourcePage=haZ3ErZqiDfXcXegP9gsYOizHbcVe5gKXcWH4Vrbe-8en-7ECFoOFlZ3Pjgc1JqrjbhndPafzMMQdeTOKVNRTImShr8uTMl0f_bdDjcL-mE%3D&row=51

Thank you for respond
ML

**Comment by lovasoa** [comment]
Why did you close the issue? Did you solve your problem?

**Comment by lucifuk** [comment]
Sorry, reopened now. Problem still alive.

**Comment by lovasoa** [comment]
You have to find the metadata file. For that, you can replace `TileGroupN/Z-X-Y.jpg` in the individual tile URLs by `ImageProperties.xml`. For example

```
http://images.ahmp.cz/mrimage/ahmp_watermark/zoomify/cz/archives/CZ-321100010/NAD-158/dao/images/0001/e58c47c3dc2ed93867eb706717ca1e25.jpg/TileGroup0/4-0-6.jpg?noCacheSfx=1567064794463
```

gives

```
http://images.ahmp.cz/mrimage/ahmp_watermark/zoomify/cz/archives/CZ-321100010/NAD-158/dao/images/0001/e58c47c3dc2ed93867eb706717ca1e25.jpg/ImageProperties.xml
```

which you can open in dezoomify:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://images.ahmp.cz/mrimage/ahmp_watermark/zoomify/cz/archives/CZ-321100010/NAD-158/dao/images/0001/e58c47c3dc2ed93867eb706717ca1e25.jpg/ImageProperties.xml

![canvas](https://user-images.githubusercontent.com/552629/63921053-5d17bd80-ca42-11e9-94b8-bae840b1b343.png)

**Comment by lucifuk** [comment]
WOOW it's working. Good job lavasoa. I'm now happy :)
Many THANKS
