### ISSUE TITLE
JPG format?

### ISSUE THREAD

**Issue by lucifuk** [lovasoa/dezoomify#323]
Please can I get from dezoomify jpg instead png format?
Originaly are images on web in jpg about 1-2 Mb but when I download png it is huge canvas about 16 Mb.
Like here: http://images.ahmp.cz/mrimage/ahmp/zoomify/cz/archives/CZ-321100010/NAD-157/dao/images/0020/a0a478160cab95292004a6df7110a4fc.jpg/ImageProperties.xml

**Comment by lovasoa** [comment]
Hello,
  Usually, dezoomify does not control the output format, your browser does. When the tiles are requested through a proxy server, then dezoomify offers a download button, and the image is saved in JPEG. See out wiki page about large images for information about how to activate the tile proxy.
