### ISSUE TITLE
Error in dezoomify Map

### ISSUE THREAD

**Issue by day2suede** [lovasoa/dezoomify#325]
Can anyone help to dezoomify this map as below,

https://www.albert-bichot.com/carto/leaflet.php

I cannot access any xml file for dezoomify, I can see the map tiles are generated by Leaflet.
Thank you so much

**Comment by lovasoa** [comment]
You can simply use the generic dezoomer (see the FAQ). In this case, the generic url to use is: `https://www.albert-bichot.com/carto/6/{{X}}/{{Y}}.png`

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://www.albert-bichot.com/carto/6/{{X}}/{{Y}}.png

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/65834897-0ec73a00-e2e0-11e9-8538-72afa667222c.jpg)

**Comment by day2suede** [comment]
Dear lovasoa,
Thanks a lot!!!
Kenneth    Ophir LOJKINE (<notifications@github.com>) 在 2019年9月29日星期日 下午11:39:25 [GMT+8] 寫道：
