### ISSUE TITLE
New problem with bavarikon.de?[new site support]

### ISSUE THREAD

**Issue by tywuser** [lovasoa/dezoomify#326]
The solution presented in issue #298 does not seem to work anymore. I have tried the example described there - https://www.bavarikon.de/iiif/BSB-BAR-0000000000062999/info.json on dezoomify using the suggested proxy setup (proxy.php) and unfortunately it does not work in my case (Error message: "Unable to fetch https:..").

The image that I would actually like to download is: https://www.bavarikon.de/object/bav:GDA-OBJ-0000000000000030. I tried to dezoomify it using the URL https://www.bavarikon.de/iiif/GDA-OBJ-0000000000000030/info.json following the example above but it does not work either.
Am I doing something wrong? Thanks a lot in advance for any help in this respect.

**Comment by lovasoa** [comment]
You should follow the instructions in the faq to find the URL of the info.json file. In this case, it's `https://api.digitale-sammlungen.de/iiif/image/v2/bav:GDA-OBJ-0000000000000030/info.json`

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://api.digitale-sammlungen.de/iiif/image/v2/bav:GDA-OBJ-0000000000000030/info.json

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/65834841-5ac5af00-e2df-11e9-9093-07b3797d0c66.jpg)

**Comment by lovasoa** [comment]
No proxy is required

**Comment by tywuser** [comment]
Thank you very much.
