### ISSUE TITLE
Library of Congress Flash Player Book

### ISSUE THREAD

**Issue by mariamhayat** [lovasoa/dezoomify#327]
Hi everyone, Can dezoomify work on this?

https://www.loc.gov/flash/pagebypage/buccaneers/bookBorder.html

I'm trying to get the 'Henry Morgan' page
I can find the individual images files in Network:
https://www.loc.gov/flash/pagebypage/buccaneers/zoom/14/TileGroup0/4-12-4.jpg

Not sure what stitches them together.

**Comment by lovasoa** [comment]
I recently added support for tile image URLs in the zoomify dezoomer, so you can enter the individual image file address that you found directly in dezoomify, and it will automatically find the other image tiles and dezoomify the full image:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://www.loc.gov/flash/pagebypage/buccaneers/zoom/14/TileGroup0/4-12-4.jpg


![canvas](https://user-images.githubusercontent.com/552629/66295821-771fa800-e8ec-11e9-9c12-df88d79db1d7.jpg)

**Comment by mariamhayat** [comment]
Hi lovasoa,
Thank you so much for helping me with my dezoomify request, it worked like a charm!
I really appreciate the work you put in, thank you again,
Best,
Mariam


________________________________
