### ISSUE TITLE
Problem With The Library Company Of Philadelphia

### ISSUE THREAD

**Issue by algae21** [lovasoa/dezoomify#329]
I've spent 2 hours and every way I could think of, but can't make it work.  I can enlarge it in the window and "save image as" which gives me large canvas fragments that I can stitch together,, but I can't get dezoomify to do the job for me.

https://digital.librarycompany.org/islandora/object/digitool%3A107030

**Comment by lovasoa** [comment]
You can download the full-resolution image by clicking *Display resolution JPEG2000* on the page. The zoomable image you see on the page is created from that page.

**Comment by lovasoa** [comment]
![JP2_digitool_107030_A  Singer, gent's, ladies', misses' and childrens, fine shoes, 104 N  Second St , Philadelphia](https://user-images.githubusercontent.com/552629/66742985-32aa8400-ee79-11e9-90ea-0bd190bdafa3.jpg)

**Comment by lovasoa** [comment]
Also, we now have issue templates. Next time you want to report a new site that doesnt work with dezoomify, please use the [new site support](https://github.com/lovasoa/dezoomify/issues/new?assignees=lovasoa&labels=new+site+support&template=0_new-site-support.md&title=%5Bnew+site+support%5D) issue template.

**Comment by dancorpse** [comment]
Is it a openseadragon zoom tool? If I want to request the image via dezoomify, what is the metadata file?

**Comment by lovasoa** [comment]
> Is it a openseadragon zoom tool? 
Yes. But openseadragon supports several protocols, and this image uses a protocol that dezoomify does not implement. 

> If I want to request the image via dezoomify, what is the metadata file?
You can't.

There is not much interest in implementing this protocol in dezoomify since the original image can be downloaded directly anyway.

**Comment by dancorpse** [comment]
Thanks for reply, lovasoa~
