### ISSUE TITLE
https://beeldbank.spaarnestadphoto.com/

### ISSUE THREAD

**Issue by Historyguy1975** [lovasoa/dezoomify#331]
### https://beeldbank.spaarnestadphoto.com/

This is a popular site with Dutch historical images.

### Example: https://beeldbank.spaarnestadphoto.com/search.pp?showpicture=6292&page=1&pos=5
 
Hi, I tried the most common methods of dezoomifying, but to no avail. I hope you can assist! Thank you, as always.

**Comment by lovasoa** [comment]
The usual technique (described in the FAQ) works just fine here. Open the browser's network inspector and find the metadata file, then pass it to dezoomify.

`https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://beeldbank.spaarnestadphoto.com/_tiles/6d6b396377737a7546433677626a7433485966692f513d3d.xml`

![canvas](https://user-images.githubusercontent.com/552629/67076319-372eaf80-f18d-11e9-81e6-2a86af56ada7.png)
