### ISSUE TITLE
Google Arts token

### ISSUE THREAD

**Issue by rirgang** [lovasoa/dezoomify#334]
Hi Lovasoa

Google Arts has changed something about image tokens.

In the vast majority of cases it is resulting in error even though others are working as usual.

Problem url example:
https://artsandculture.google.com/asset/heimdall-returns-brisingamen-to-freyja/VwHgmYY3np1SWQ

Error:
Uncaught Error: Unable to find google arts image token

(https://mysite.com/dezoomify/dezoomers/google-arts-culture.js:14)

I updated to the latest version and the error persists:

Thanks

RK

**Comment by lovasoa** [comment]
I just tried the example image you gave and it works just fine in dezoomify.
![dezoomify-result](https://user-images.githubusercontent.com/552629/67330864-4d39c880-f51d-11e9-9518-33dac2dfbed0.jpg)


Please do a [hard-refresh](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/) of dezoomify in your browser, and if you can reproduce the problem, re-open this issue and list the urls for which dezoomify encounters a problem.

**Comment by lovasoa** [comment]
Oh I just noticed that the error message says:

> Error:
> Uncaught Error: Unable to find google arts image token
> (https://**mysite.com**/dezoomify/dezoomers/google-arts-culture.js:14)

**mysite.com** is not the official dezoomify mirror :wink: 

Please open an issue on github **only when you encounter an issue with the latest version of dezoomify** ! In this case, yoursite.com probably just runs a version of dezoomify that does not include the [latest fixes](https://github.com/lovasoa/dezoomify/commits/master)

**Comment by rirgang** [comment]
Hi Lovasoa.

We run your scripts on our dedicated server, it is faster ... I only used mysite in the example to not show the site publicly.
What I did was clone the zip files and update on our server. I did not understand the difference, missing some update in the github files will be?

Thanks for awesome script

**Comment by rirgang** [comment]
Please just ignore my last response.
I really must have been wrong in uploading the scripts.
I downloaded it again and sent it to our server.
It worked perfectly
Once again I'm sorry and congratulations on your work.

Thanks

**Comment by lovasoa** [comment]
Maybe you should put in place an automated script that clones the sources of dezoomify to your server on a regular basis ? This would avoid running an outdated version again in the future
