### ISSUE TITLE
[new site support] Can't download images from www.swaen.com

### ISSUE THREAD

**Issue by Ayack** [lovasoa/dezoomify#335]
### Site name and description
www.swaen.com

Contains many ancient maps.

### Example URLs
 - https://www.swaen.com/zoom_map.htm?zoomifyImagePath=/os/zoom2/44381X/
 - https://www.swaen.com/zoom_map.htm?zoomifyImagePath=/os/zoom2/44381B/
 - https://www.swaen.com/zoom_map.htm?zoomifyImagePath=/os/zoom2/44381C/
 - https://www.swaen.com/zoomV5eedownload.php?id=16809&zif_first=true

### Current error message
Error: Invalid zoomify XML info file: https://www.swaen.com/zoom_map.htm?zoomifyImagePath=/os/zoom2/44381B/os/zif/44381B.zif/ImageProperties.xml

(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:191)

Thanks.

**Comment by lovasoa** [comment]
Hello,

This site seems to allow viewing zoomable using two protocols: [ZIF](https://github.com/lovasoa/ZIF/blob/master/README.md) and  the traditional zoomify xml format.

If you remove `&zif_first=true` from your last URL, you can a traditional zoomify page, that works with dezoomify
 (`https://www.swaen.com/zoomV5eedownload.php?id=16809`):

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://www.swaen.com/zoomV5eedownload.php?id=16809

![canvas](https://user-images.githubusercontent.com/552629/67563331-bd646c00-f720-11e9-8a7f-cb754a674b3b.jpg)


Concerning ZIF files, you can just download them (first finding their URL in your browser console), and then using a tool such as my [online ZIF file viewer](http://lovasoa.github.io/ZIF/) to view them and convert them to simple PNG images.

For instance, this ZIF file

 `https://www.swaen.com/os/zif/44381C.zif`

gives:

![canvas](https://user-images.githubusercontent.com/552629/67563609-54312880-f721-11e9-92ea-fe0387cfd8d0.jpg)

**Comment by Ayack** [comment]
Thanks a lot!
