### ISSUE TITLE
Etsy

### ISSUE THREAD

**Issue by thistehneisen** [lovasoa/dezoomify#336]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?

https://www.artsy.net/artwork/raimonds-staprans-road-to-redondo-shores

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.

Etsy is super popular.

### Example URLs
 - Give the URLs of viewing pages
 - give the URLs of metadata files if you found them

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.

**Comment by lovasoa** [comment]
Etsy is not supported directly, but you can use the generic dezoomer with it.

1. Open your browser's network console while zooming into the image.
2. You'll notice the image tiles appearing in the console.
3. Take the url of a tile (one that appeared while browsing the fully zoomed image). For instance, for the image you gave:  
`https://d32dm0rphc51dk.cloudfront.net/Dfp6R8xs76eJgWlfwfRYFA/dztiles/13/5_8.jpg`
4. Replace the last two numbers with `{{X}}` and `{{Y}}`. In our example, this gives: `https://d32dm0rphc51dk.cloudfront.net/Dfp6R8xs76eJgWlfwfRYFA/dztiles/13/{{X}}_{{Y}}.jpg`
5. Paste the result in dezoomify, selecting the generic dezoomer.

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://d32dm0rphc51dk.cloudfront.net/Dfp6R8xs76eJgWlfwfRYFA/dztiles/13/{{X}}_{{Y}}.jpg

![canvas](https://user-images.githubusercontent.com/552629/67667759-d8c4b680-f96e-11e9-9a24-e6a37eeda1a3.jpg)

**Comment by C-B-B** [comment]
At my end I get overlap artifacts when using the generic dezoomer on Artsy, e.g. here: https://www.artsy.net/artwork/kobina-nyarko-mmban-hurrings
Is there any known work-around for that?
Thanks!
