### ISSUE TITLE
Bonhams Image zoom

### ISSUE THREAD

**Issue by surao101** [lovasoa/dezoomify#338]
### Site name and description
https://www.bonhams.com

### Example URLs
https://www.bonhams.com/auctions/25443/lot/14/
https://www.bonhams.com/auctions/24691/lot/20/

### Current error message
Using the page URL and using "Select Automatically" it gives the following error

```
Uncaught Error: Unable to find a proper dezoomer for:
https://www.bonhams.com/auctions/25443/lot/14/

(https://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)
```

**Comment by dancorpse** [comment]
I remembered there was an old issue regarding bonhams images, https://github.com/lovasoa/dezoomify/issues/123

**Comment by scouserdave** [comment]
Right click on image, open image in new tab. The image link will look like this https://images1.bonhams.com/image?src=Images/live/2019-01/31/94635517-1-2.jpg&width=640&height=480&autosizefit=1 

Remove "&width=640&height=480&autosizefit=1"  and you'll have the full size image.
