### ISSUE TITLE
Support for unibe.ch ( Informationsverbund IDS Basel Bern)

### ISSUE THREAD

**Issue by ar-jan** [lovasoa/dezoomify#34]
On for example [this](http://biblio.unibe.ch/web-apps/maps/zoomify.php?col=ryh&pic=Ryh_7906_6) url I get `Error: Unable to find a proper dezoomer for the given URL.`. It does seem to be using zoomify. Can this site be supported?

**Comment by lovasoa** [comment]
Yes, they use zoomify, but they don't use a standard library to read the image info. Instead, they use their [own script](view-source:http://biblio.unibe.ch/web-apps/maps/assets/javascripts/openlayers-load.js)

**Comment by lovasoa** [comment]
Here it is, I added support for this site (based on url and page source detection).

**Comment by ar-jan** [comment]
Awesome, thanks!
