### ISSUE TITLE
[new site support] collection.nationalmuseum.se

### ISSUE THREAD

**Issue by trudvangarer** [lovasoa/dezoomify#341]
### Site name and desciption
http://collection.nationalmuseum.se/
National Museum of Sweden has a great digital collection of scandinavian art. It works with openseadragon, but, sadly, the built-in dezoomify seadragon option is not working.

### Example URLs
http://collection.nationalmuseum.se/eMP/eMuseumPlus?service=direct/1/ResultListView/result.t1.collection_list.$TspTitleImageLink.link&sp=10&sp=Scollection&sp=SfieldValue&sp=0&sp=2&sp=3&sp=SdetailList&sp=0&sp=Sdetail&sp=0&sp=F&sp=T&sp=11

### Current error message
Uncaught Error: Invalid XML:
http://collection.nationalmuseum.se/eMP/eMuseumPlus?service=direct/1/ResultListView/result.t1.collection_list.$TspTitleImageLink.link&sp=10&sp=Scollection&sp=SfieldValue&sp=0&sp=2&sp=3&sp=SdetailList&sp=0&sp=Sdetail&sp=0&sp=F&sp=T&sp=11

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:191)

**Comment by lovasoa** [comment]
It looks like they use IIIF. Have a look at this wiki page: https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server

**Comment by scouserdave** [comment]
It works for me. I found the .json file link and posted it in dezoomify http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://nationalmuseumse.iiifhosting.com/iiif/dcd10ea50cd389bda25863fe1e60c6f7f2c38663fdbcfcca9f48965091442cb4//info.json
