### ISSUE TITLE
[bug] deutschefotothek.de

### ISSUE THREAD

**Issue by runxel** [lovasoa/dezoomify#343]
There was issue #76, which was resolved, but I'm having trouble. It doesn't seem to work.
Test with [this](http://www.deutschefotothek.de/documents/obj/71485143/b_bpk_0000000_00016982).

**Comment by runxel** [comment]
Nevermind, you can find the full res picture in the source code...

**Comment by Nicram-Badatflyski** [comment]
Hi, could you show where the full image code is please?
Can't find it personally.
Exemple [here](http://www.deutschefotothek.de/documents/obj/71052561/df_dk_0010001_2445)
thank you.
KR

**Comment by runxel** [comment]
Hey @Nicram-Badatflyski,
just look out for a `span` with the class of `ete-openlayers-src`.
Hope this helps! :)

**Comment by Nicram-Badatflyski** [comment]
Thank you very much, !!!!!
will try this!

Mvg

    Le samedi 16 novembre 2019 à 21:14:38 UTC+1, Lucas Becker <notifications@github.com> a écrit :  
 
 
Hey @Nicram-Badatflyski,
just look out for a span with the class of ete-openlayers-src.
Hope this helps! :)
