### ISSUE TITLE
[new site support] Dallas Museum of Art not properly dezooming

### ISSUE THREAD

**Issue by rahidz** [lovasoa/dezoomify#344]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.

### Example URLs
 - Example art: https://collections.dma.org/artwork/5202197
 - Example of URL: https://collections.dma.org/media/tiled-images/171970189901341_pyramid.ptif_files/13/{{X}}_{{Y}}.jpg

### Current error message

Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
https://collections.dma.org/media/tiled-images/171970189901341_pyramid.ptif_files/13/225_1.jpg

Both Dezoomify and Dezoomify-rs get stuck on this one, it seems to focus exclusively on the first number (it's not a huge file, 11 by 11 at most).

**Comment by lovasoa** [comment]
you don't need the generic dezoomer

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/69798477-ac03f900-11d1-11ea-9769-b0a24922d2f2.jpg)

**Comment by lovasoa** [comment]
The original layered TIFF image can also be downloaded directly from the source site, by removing everything after `.ptif` in the url you mention:

https://collections.dma.org/media/tiled-images/171970189901341_pyramid.ptif

You can then open the `ptif` file with, for example, Gimp.
