### ISSUE TITLE
[new site support] Can’t download maps from hungaricana.hu

### ISSUE THREAD

**Issue by Monmon255555** [lovasoa/dezoomify#346]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?

https://hungaricana.hu/en/

### Example URLs
 - https://maps.hungaricana.hu/en/MOLTerkeptar/5006/view/?bbox=-310%2C-5311%2C10990%2C-18

 - https://static-cdn.hungaricana.hu/tile/image/maps/mol/s012/div13/s12_div_xiii_0031/s12_div_xiii_0031.ecw/09dab00751b25b57ea4f632908c3f293

### Current error message
Uncaught Error: Unable to find a proper dezoomer for:
https://maps.hungaricana.hu/en/MOLTerkeptar/5006/view/?bbox=-310%2C-5311%2C10990%2C-18

(https://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)

**Comment by lovasoa** [comment]
The site's authors have made quite some effort to prevent the automatic image download.

After a quick investigation, it looks like the hash at the end of tile URLs is generated by encrypting the tile position in AES with the key `this is no k`.

The exact string to encode seems to be : 

```js
s = sum_ascii_values(base_path); // In our example, base_path is "maps/mol/s012/div13/s12_div_xiii_0031/s12_div_xiii_0031.ecw"
clear = (s%100) + '|' + x + '|' + y + '|' + z
padded = clear.padEnd(16, '*');
hash = AES('this is no k', clear)
```

**Comment by lovasoa** [comment]
Here is a small demonstration of the tile URL logic: https://svelte.dev/repl/91f269a2ebc84975958dd3424ead73ea?version=3.16.0

**Comment by Monmon255555** [comment]
You are so awesome! I am definitely not knowledgeable enough to get this to work but thank you so so much for your time and for trying to figure this out!

**Comment by lovasoa** [comment]
Ok, it's implemented. You can try it live on dezoomify.

[![high-resolution hungaricana image download](https://user-images.githubusercontent.com/552629/70158377-6e164180-16b7-11ea-928a-18b31e39fd4b.jpg)](https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://maps.hungaricana.hu/en/MOLTerkeptar/5006/view/?bbox=-310%2C-5311%2C10990%2C-18)

**Comment by lovasoa** [comment]
I found this old issue that referenced the same site: #118

**Comment by Monmon255555** [comment]
Amazing! Thank you so much.

I just have one question, is it possible to download different maps inside one, for example this link: https://maps.hungaricana.hu/en/MOLTerkeptar/5042/view/?pg=1&bbox=-920%2C-6139%2C9336%2C212

I always get the first map when I try to download any other number

**Comment by lovasoa** [comment]
Fixed 😃

**Comment by burnoutberni** [comment]
Came here to say thank you! <3
