### ISSUE TITLE
[new site support] EGEO world and italian geological maps

### ISSUE THREAD

**Issue by Cartographic** [lovasoa/dezoomify#348]
I ask kindly to take care of my request 
http://www.egeo.unisi.it/
it's a website full of Italian geological related maps

For the reason written above: several of rare or unique geological maps (all world)

### Example URLs
http://www.egeo.unisi.it/index.php/dettaglio-carta/?act=see&id=2491

### Current error message
Error
Uncaught Error: Unable to find a proper dezoomer for:
http://www.egeo.unisi.it/index.php/dettaglio-carta/?act=see&id=2491

(https://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)

**Comment by Cartographic** [comment]
join here

**Comment by lovasoa** [comment]
original issue: #207
