### ISSUE TITLE
New site support: munch.emuseum.com

### ISSUE THREAD

**Issue by jhoward1045** [lovasoa/dezoomify#350]
Any help getting this image, full size? 
I can't seem to quite get it. 

https://munch.emuseum.com/objects/3066/solbadere-ved-en-bukt

**Comment by lovasoa** [comment]
They seem to be using zoomify. You can find the metadata file by looking for the image tiles in your browser's network inspector. 

For instance:

```
https://munch.emuseum.com/internal/media/zoomifydispatcher/4698/TileGroup0/2-0-1.jpg
```


Then replace everything after `TileGroup` with `ImageProperties.xml` :

```
https://munch.emuseum.com/internal/media/zoomifydispatcher/4698/ImageProperties.xml
```

This is the meta-information file. You can pass it to dezoomify.

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/72913079-e5259900-3d3c-11ea-8d91-9b40cce8a40a.jpg)

**Comment by jhoward1045** [comment]
Thanks a lot!
