### ISSUE TITLE
Städel Museum Support

### ISSUE THREAD

**Issue by agmmnn** [lovasoa/dezoomify#351]
### Site name and desciption
https://sammlung.staedelmuseum.de/en/search
Can we add support for _Digital Collection of the Städel Museum_.

### Example URLs
https://sammlung.staedelmuseum.de/en/work/the-thousand-year-old-oak

https://sammlung.staedelmuseum.de/images/1002/pyramid_files/12/2_0.jpg
https://sammlung.staedelmuseum.de/images/1002/pyramid_files/12/2_1.jpg

Url Parsing(I think):
.../images/**(artwork_id)**/pyramid_files/**(zoom_lvl)**/**(tile:xy)**.jpg

I cannot find ImageProperties.xml

**Comment by lovasoa** [comment]
It uses seadragon. You can simply copy the url of one of the tiles into dezoomify and it'll work:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://sammlung.staedelmuseum.de/images/940/pyramid_files/13/8_3.jpg


![Uploading canvas.jpg…]()

**Comment by lovasoa** [comment]
The meta-information file is in https://sammlung.staedelmuseum.de/images/940/pyramid.dzi

**Comment by agmmnn** [comment]
Thank you so much.
