### ISSUE TITLE
[new site support]

### ISSUE THREAD

**Issue by trajano12345** [lovasoa/dezoomify#352]
### https://mapy.mzk.cz/en/

https://mapy.mzk.cz/en/mzk03/001/052/884/2619316647/

https://mapy.mzk.cz/mzk03/001/052/907/2619316615/

thx

**Comment by lovasoa** [comment]
Hello!
  Investigating on a new site takes a significant effort, and we do ask reporters to invest their own time into explaining their issue, and asking for help using full sentences. Can you please follow the new site support template that appears when you create an issue?

I'll reopen the issue if you edit your message to make it follow the template.

**Comment by lovasoa** [comment]
I still had a look at it, and you can just copy & paste the URL of a tile to dezoomify and it'll work. Have a look at the FAQ.

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://imageserver.mzk.cz/mzk03/001/052/884/2619316647/TileGroup2/6-13-12.jpg

![canvas](https://user-images.githubusercontent.com/552629/73250068-6bffc900-41b6-11ea-9494-1096415bc1c7.jpg)
