### ISSUE TITLE
unable to load tile from www.themorgan.org

### ISSUE THREAD

**Issue by jeffstud** [lovasoa/dezoomify#353]
Hello Lovasoa,
Thank you for your dezoomify!
I would like dezoomify to support a site www.themorgan.org.
This site has a lot of digital facsimiles of rare books.
For example, https://www.themorgan.org/collection/worksop-bestiary/1
It seems to use a brand new technology, the xhr file does not work.
Could you help me?
Thank you very much.
Best regards,
Jeff

**Comment by lovasoa** [comment]
They use the ZIF image format. You can download the whole image at once (by looking  at its URL in your browser's network inspector). Four your example

https://host.themorgan.org/facsimile/images/m81/77019v_2005.zif

Once you have downloaded it, you still have to get a tool to open it, ZIF is not a very widespread format. In a separate project, I reverse-engineered the format and created a small online converter: 

https://github.com/lovasoa/ZIF

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/73382775-6f837500-42c8-11ea-8299-8cd663788382.jpg)

**Comment by jeffstud** [comment]
Dear Lovasoa,
Thank you very much. The method does work!
Very amazing!
I am happy and grateful when I read your detailed description. Thank you for your time.
Best regards,
Jeff
