### ISSUE TITLE
Problem with www.virtuelles-kupferstichkabinett.de

### ISSUE THREAD

**Issue by Hotzenplo** [lovasoa/dezoomify#355]
www.virtuelles-kupferstichkabinett.de contains masses of engravings which are big fun to see zoomified, but would be even more pleasure to be able to dezoomify.

They give a PURL to each single picture like http://kk.haum-bs.de/?id=schenk-p-d-ae-ab3-r0190 which one can find in the description, but these adresse not work with dezoomify. It's no problem to find the tiles, but there seems to be no information file.

Any suggestions how one can use this greaaatttt tool with this page?

**Comment by lovasoa** [comment]
They use zoomify. You can just copy the URL of a tile and paste it into dezoomify : 

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://diglib.hab.de/varia/haum/schenk-p-d-ae-ab3-r0190/TileGroup0/0-0-0.jpg
