### ISSUE TITLE
Unable to dezoom rare arabic manuscripts library

### ISSUE THREAD

**Issue by mostnegm** [lovasoa/dezoomify#356]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?

AUC Library Collection: http://digitalcollections.aucegypt.edu/

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.

It contains rare scans of egyptian/middle eastern manuscripts that are no where else.

### Example URLs
 - Give the URLs of viewing pages
 - give the URLs of metadata files if you found them

http://digitalcollections.aucegypt.edu/cdm/compoundobject/collection/p15795coll21/id/2322/show/2320/rec/293

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.

"Uncaught Error: Unable to find a proper dezoomer"

**Comment by lovasoa** [comment]
If you look at the individual image tile URLs, they look like the following : `http://digitalcollections.aucegypt.edu/utils/ajaxhelper/?CISOROOT=sphinx&CISOPTR=8709&action=2&DMSCALE=200&DMWIDTH=512&DMHEIGHT=512&DMX=512&DMY=1536&DMTEXT=&DMROTATE=0`

The URL contains the parameters needed to ask for a specific portion of the image. You can abuse that, asking the whole image, by replacing the parameters: set `DMX` and `DMY` to 0, and `DMWIDTH` and `DMHEIGHT` to 9999 : `http://digitalcollections.aucegypt.edu/utils/ajaxhelper/?CISOROOT=sphinx&CISOPTR=8709&action=2&DMSCALE=200&DMWIDTH=9999&DMHEIGHT=9999&DMX=0&DMY=0&DMTEXT=&DMROTATE=0`

![](http://digitalcollections.aucegypt.edu/utils/ajaxhelper/?CISOROOT=sphinx&CISOPTR=8709&action=2&DMSCALE=200&DMWIDTH=9999&DMHEIGHT=9999&DMX=0&DMY=0&DMTEXT=&DMROTATE=0)

**Comment by lovasoa** [comment]
This site uses the same zoomable image format as digitalcollections.library.gsu.edu, you can see the previous discussion about this technology in #318

**Comment by mostnegm** [comment]
thank you so much
