### ISSUE TITLE
New site support: regards.monuments-nationaux.fr

### ISSUE THREAD

**Issue by portraitsofrulers** [lovasoa/dezoomify#358]
Hello!
I hope you have the opportunity to help me get a high resolution image from this site.

this example:

https://regards.monuments-nationaux.fr/fr/asset/highRes/id/91609

https://regards.monuments-nationaux.fr/fr/asset/fullTextSearch/search/HLW19-0089%20/page/1

(Charles VI le Bien-Aimé) HLW19-0089 

If so, please create the ability to get Zoom images using Dezoomify.
This site contains a large number of images of portraits of the rulers of Europe, especially France.
I could not find the URL from this site for Dezoomify.
The usual tools for obtaining Zoom images for this site do not work.

I am a history teacher from Russia.
High quality portraits of rulers of Europe are my many years of hobby.  I very beg you to help. 

Thanks in advance and all the best.

**Comment by lovasoa** [comment]
Здравствуйте,
  This website does not use a tiled image mechanism, it loads the full image entirely, so you don't need dezoomify to get it. You can just Shift + Right click on the image, and chose "Save as...".

![91609](https://user-images.githubusercontent.com/552629/75707758-ca412f80-5cbf-11ea-8383-8389a619115b.jpg)

**Comment by lovasoa** [comment]
I downloaded the images in bulk and I uploaded them to https://github.com/lovasoa/regards.monuments-nationaux.fr

**Comment by portraitsofrulers** [comment]
Hello!
Thank you so much for your help and all the best.
