### ISSUE TITLE
Dezoomify with Firefox, don't load the png image, site www.nga.gov

### ISSUE THREAD

**Issue by lanaloft** [lovasoa/dezoomify#365]
EG https://www.nga.gov/collection/art-object-page.1207.html do not load the image, png, only seeing a blanco field,. Same image with Chrome browser loads very very slow and often do not safe the image,.
The image file is about 340 Mb,.

**Comment by lanaloft** [comment]
I am sorry, i am new here,.I use dezoomify app in FFox. Second i tried and downloaded dezoomify-rs and paste the link i obtained from the dezoomify-add/app, but without result,..

    Am Donnerstag, 12. März 2020, 14:36:47 MEZ hat Ophir LOJKINE <notifications@github.com> Folgendes geschrieben:  
 
 


I uploaded the full-resolution image, downloaded with dezoomify, to wikimedia: https://commons.wikimedia.org/wiki/File:Rembrandt_Harmensz._van_Rijn_107.jpg

I'm moving this issue to the dezoomify repository, and closing it since I cannot reproduce the issue, but feel free to comment below. We may reopen the issue if needed.

**Comment by lovasoa** [comment]
Ok, can you copy and paste the URL you entered into dezoomify-rs and the exact output it gave ?

**Comment by lanaloft** [comment]
Thank you!!
This is the homepage: https://www.nga.gov/collection/art-object-page.82.html
And the dezoomify add on in FF gives this result: https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/8/2/82-primary-0-nativeres.ptif
It loads very fast in my opnion, but without loading an image.
In chrome it loads ver very slow, but with tiles,. in firefox no tiles. In  dezoomify rs, i put the same, pressing return and happen nothing!
   Am Donnerstag, 12. März 2020, 15:09:01 MEZ hat Ophir LOJKINE <notifications@github.com> Folgendes geschrieben:  
 
 


Ok, can you copy and paste the URL you entered into dezoomify-rs and the exact output it gave ?

**Comment by lovasoa** [comment]
dezoomify-rs doesn't support the IIPServer native format yet.

**Comment by MrChrisWin** [comment]
> Thank you!! This is the homepage: https://www.nga.gov/collection/art-object-page.82.html And the dezoomify add on in FF gives this result: https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/8/2/82-primary-0-nativeres.ptif It loads very fast in my opnion, but without loading an image. In chrome it loads ver very slow, but with tiles,. in firefox no tiles. In  dezoomify rs, i put the same, pressing return and happen nothing! Am Donnerstag, 12. März 2020, 15:09:01 MEZ hat Ophir LOJKINE <notifications@github.com> Folgendes geschrieben: Ok, can you copy and paste the URL you entered into dezoomify-rs and the exact output it gave ? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

lanaloft, try to feed Dezoomify-rs with this url "https://media.nga.gov/iiif/public/objects/8/2/82-primary-0-nativeres.ptif/info.json"
It should now give you 8 different size to download from.

**Comment by lanaloft** [comment]
Dear Chris Win,
Thank you very much, it works perfect!!
I am very pleased to download these images,. and it goes very quick, almost unbelieveable.
There is a site about the restauration about The Gent Alterpiece, and they have very high resolution images of it. But unfortunately no download function of it.
Closer to Van Eyck

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Closer to Van Eyck

The Ghent Altarpiece
 |

 |

 |


Closer to Van Eyck

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Closer to Van Eyck

The Ghent Altarpiece
 |

 |

 |





Is it possible with eg dezoomify-RS to download these? I tried with your " ïnfo.json" on the end and substitute "*viewer" with "ïiif", but without result. I have no idea, because i am not a programmer to find a solution, maybe in this case there is no solution to download it.
Btw, great work of you making that add-on dezoomify!

Best regards,
Lana

    Am Freitag, 13. März 2020, 04:14:57 MEZ hat Chris Win <notifications@github.com> Folgendes geschrieben:  
 
 



Thank you!! This is the homepage: https://www.nga.gov/collection/art-object-page.82.html And the dezoomify add on in FF gives this result: https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/8/2/82-primary-0-nativeres.ptif It loads very fast in my opnion, but without loading an image. In chrome it loads ver very slow, but with tiles,. in firefox no tiles. In  dezoomify rs, i put the same, pressing return and happen nothing! Am Donnerstag, 12. März 2020, 15:09:01 MEZ hat Ophir LOJKINE notifications@github.com Folgendes geschrieben: Ok, can you copy and paste the URL you entered into dezoomify-rs and the exact output it gave ? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.


lanaloft, try to feed Dezoomify-rs with this url "https://media.nga.gov/iiif/public/objects/8/2/82-primary-0-nativeres.ptif/info.json"
It should now give you 8 different size to download from.

**Comment by lovasoa** [comment]
I created a separate issue for the *closer to van eyck* website : https://github.com/lovasoa/dezoomify/issues/366

You can download its images using the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial)

I uploaded an example to wikimedia : 

[![https://commons.wikimedia.org/wiki/File:Ghent_Altarpiece_G_-_John_the_Baptist.jpg](https://upload.wikimedia.org/wikipedia/commons/8/8e/Ghent_Altarpiece_G_-_John_the_Baptist.jpg)](https://commons.wikimedia.org/wiki/File:Ghent_Altarpiece_G_-_John_the_Baptist.jpg)
