### ISSUE TITLE
[new site support] closertovaneyck.be

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify#366]
### Site name and desciption
closertovaneyck.be is a belgian website that offers very high definition photographs of several masterpieces

### Example URLs
 - http://closertovaneyck.be/ghentaltarpiece/#home
 - http://closertovaneyck.be/verona/#viewer/rep1=2&id1=2ea5c438ba33d699bf4c5718f5cc6bf2

#### Tile URLs

 - http://data.closertovaneyck.be/verona/tiles/25-VIS-UH/14/26_26.jpg 

### Current workaround

The pages can be downloaded using the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial). Here is an example template url to pass to dezoomify or dezoomify-rs : 

`http://data.closertovaneyck.be/ec2/tiles/00-18-VIS-HI-AT/14/{{X}}_{{Y}}.jpg`

**Comment by brushingflamboyant** [comment]
Thank you very much, it worked !

**Comment by Scanirus** [comment]
Thanks!

I realized what I was doing wrong > after copying URL to Dezoomify-rs, need to ignore network error, and after a short time the download starts:

![Eyck](https://user-images.githubusercontent.com/81745178/114515455-083faf80-9c45-11eb-869a-ede6e74652c8.jpg)

**Comment by lovasoa** [comment]
Yes, when dezoomify-rs fails to download a tile, it retries it. It should probably be made explicit in the error message. The behavior is customizable: https://github.com/lovasoa/dezoomify-rs#command-line-options

**Comment by Muddysoil** [comment]
Hi! I tried to download from the website closertovaneyck.be this week, but nothing can be downloaded from there anymore, they must have changed the technology.

Does anyone know anything about this?

**Comment by AlexanderDeLargeBrotherSir** [comment]
MADONNA WITH CANON JORIS VAN DER PAELE - https://data.closertovaneyck.be/verona/tiles/08-VIS-HI/17/{{X}}_{{Y}}.jpg

THE THREE MARYS AT THE GRAVE - https://data.closertovaneyck.be/verona/tiles/23-VIS-UH/17/{{X}}_{{Y}}.jpg

ADORATION OF THE LAMB (GHENT ALTARPIECE) - https://data.closertovaneyck.be/ec2/tiles/00-10-VIS-HI-AT/17/{{X}}_{{Y}}.jpg

ALL THESE LINKS WILL DOWNLOAD FROM CLOSER TO VAN EYCK AT THE HIGHEST RESOLUTION POSSIBLE IN PNG, JUST WAIT AND BE PATIENT FOR IT TO FINISH.

REPLACE THE NUMBER AFTER VIS-HI OR VIS-UH TO "17" AND THE {{X}}_{{Y}}.jpg IS NO BRAINER.

**Comment by AlexanderDeLargeBrotherSir** [comment]
> Hi! I tried to download from the website closertovaneyck.be this week, but nothing can be downloaded from there anymore, they must have changed the technology.
> 
> Does anyone know anything about this?/

MADONNA WITH CANON JORIS VAN DER PAELE - [https://data.closertovaneyck.be/verona/tiles/08-VIS-HI/17/{{X}}_{{Y}}.jpg](https://data.closertovaneyck.be/verona/tiles/08-VIS-HI/17/%7B%7BX%7D%7D_%7B%7BY%7D%7D.jpg)

THE THREE MARYS AT THE GRAVE - [https://data.closertovaneyck.be/verona/tiles/23-VIS-UH/17/{{X}}_{{Y}}.jpg](https://data.closertovaneyck.be/verona/tiles/23-VIS-UH/17/%7B%7BX%7D%7D_%7B%7BY%7D%7D.jpg)

ADORATION OF THE LAMB (GHENT ALTARPIECE) - [https://data.closertovaneyck.be/ec2/tiles/00-10-VIS-HI-AT/17/{{X}}_{{Y}}.jpg](https://data.closertovaneyck.be/ec2/tiles/00-10-VIS-HI-AT/17/%7B%7BX%7D%7D_%7B%7BY%7D%7D.jpg)

ALL THESE LINKS WILL DOWNLOAD FROM CLOSER TO VAN EYCK AT THE HIGHEST RESOLUTION POSSIBLE IN PNG, JUST WAIT AND BE PATIENT FOR IT TO FINISH.

REPLACE THE NUMBER AFTER VIS-HI OR VIS-UH TO "17" AND THE {{X}}_{{Y}}.jpg IS NO BRAINER.

**Comment by AlexanderDeLargeBrotherSir** [comment]
> I'm having a problem with Dezoomify for the closertovaneyck site.
> 
> I followed the procedure as described in the tutorial : in Firefox I opened my browser's developer tools while on the webpage I wanted to extract an image from (http://closertovaneyck.kikirpa.be/verona/#viewer/rep1=2&id1=29-7r-VIS), opened the network inspector, zoomed on the image until max, did right-click on the latest jpeg's line appearing in the network inspector and copy-paste its URL (this one : http://data.closertovaneyck.be/verona/tiles/29-7r-VIS/14/14_24.jpg) in Dezoomify.
> 
> When I added the {{X}} and {{Y}} as explained (so this : [http://data.closertovaneyck.be/verona/tiles/29-7r-VIS/14/{{14}}_{{24}}.jpg](http://data.closertovaneyck.be/verona/tiles/29-7r-VIS/14/%7B%7B14%7D%7D_%7B%7B24%7D%7D.jpg)), it completely failed. The followed message of error appeared :
> 
> Error: Unable to fetch http://data.closertovaneyck.be/verona/tiles/29-7r-VIS/14/%7B%7B14%7D%7D_%7B%7B24%7D%7D.jpg The server responded: fopen(http://data.closertovaneyck.be/verona/tiles/29-7r-VIS/14/%7B%7B14%7D%7D_%7B%7B24%7D%7D.jpg): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
> 
> (https://dezoomify.ophir.dev/dezoomify/zoommanager.js:418)
> 
> I tried several other solutions by changing the positioning of the signs here {{ }} all along the link but the results were the same. Can you give me an explanation on what went wrong ? I should clarify that it's the first time I've used this tool, please forgive me if my question sounds stupid. Thank you !

MADONNA WITH CANON JORIS VAN DER PAELE - [https://data.closertovaneyck.be/verona/tiles/08-VIS-HI/17/{{X}}_{{Y}}.jpg](https://data.closertovaneyck.be/verona/tiles/08-VIS-HI/17/%7B%7BX%7D%7D_%7B%7BY%7D%7D.jpg)

THE THREE MARYS AT THE GRAVE - [https://data.closertovaneyck.be/verona/tiles/23-VIS-UH/17/{{X}}_{{Y}}.jpg](https://data.closertovaneyck.be/verona/tiles/23-VIS-UH/17/%7B%7BX%7D%7D_%7B%7BY%7D%7D.jpg)

ADORATION OF THE LAMB (GHENT ALTARPIECE) - [https://data.closertovaneyck.be/ec2/tiles/00-10-VIS-HI-AT/17/{{X}}_{{Y}}.jpg](https://data.closertovaneyck.be/ec2/tiles/00-10-VIS-HI-AT/17/%7B%7BX%7D%7D_%7B%7BY%7D%7D.jpg)

ALL THESE LINKS WILL DOWNLOAD FROM CLOSER TO VAN EYCK AT THE HIGHEST RESOLUTION POSSIBLE IN PNG, JUST WAIT AND BE PATIENT FOR IT TO FINISH.

REPLACE THE NUMBER AFTER VIS-HI OR VIS-UH TO "17" AND THE {{X}}_{{Y}}.jpg IS NO BRAINER.
