### ISSUE TITLE
[new site support] : www.yumpu.com

### ISSUE THREAD

**Issue by Historyguy1975** [lovasoa/dezoomify#367]
Site: www.yumpu.com

Example: https://www.yumpu.com/fr/document/read/29580991/a-mowlems-brochure-london-city-airport-consultative-committee

This site has a wealth of uploaded magazines and reports. I am not able to find an image that can be dezoomified. Can you please assist? 

Thank you in advance!

**Comment by lovasoa** [comment]
Hello and thank you for getting in touch !
This website doesn't use tiled images. The full quality images are accessible directly from the website itself. Open your browsre's devtools network panel and you'll find the full size image URLs.

![](https://img.yumpu.com/29580991/1/1675x1195/a-mowlems-brochure-london-city-airport-consultative-committee.jpg?quality=100)

**Comment by lovasoa** [comment]
On firefox: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

On chrome: https://developers.google.com/web/tools/chrome-devtools/network

**Comment by lovasoa** [comment]
Do not hesitate to comment below if you are experiencing issues

**Comment by Historyguy1975** [comment]
Thank you, it worked. I'm an idiot, lol! Thank you as always for your kind assistance! Regards from Montreal
