### ISSUE TITLE
[bug] with Mnesys

### ISSUE THREAD

**Issue by Sindi43** [lovasoa/dezoomify#371]
Hello,

Everything works except for his images :

http://memoirevive.besancon.fr/ark:/48565/a0114642667406oI81H/1/1

http://memoirevive.besancon.fr/ark:/48565/a011464266740j6OBRf/1/1

http://memoirevive.besancon.fr/ark:/48565/a011464266740ylHGjZ/1/1

http://memoirevive.besancon.fr/ark:/48565/a011464266740SOgIPd/1/1

http://memoirevive.besancon.fr/ark:/48565/a011464266740y5YBlW/1/1

Thx for your help !

**Comment by lovasoa** [comment]
Thank you for the bug report ! I'll investigate.

**Comment by lovasoa** [comment]
The bug should be fixed. Be sure to hard-refresh https://dezoomify.ophir.dev, and then try you URLs again.

Thanks again for reporting the issue.
