### ISSUE TITLE
[new site support] Gailestingojo Jėzaus paveikslas

### ISSUE THREAD

**Issue by Leonidas120** [lovasoa/dezoomify#375]
### Gailestingojo Jėzaus paveikslas
http://www.gailestingumas.com/apie-sventove/gailestingojo-jezaus-paveikslas/

The page features the original image of Merciful Jesus

### Example URLs
 - http://www.gailestingumas.com/apie-sventove/gailestingojo-jezaus-paveikslas/

### Current error message
no reaction

**Comment by lovasoa** [comment]
You can use the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial) for this site.

The URL to give to dezoomify is 

```
http://www.gailestingumas.com/assets/sp_picture/0_{{Y}}_{{X}}.jpg
```
<a href="https://dezoomify.ophir.dev/dezoomify/dezoomify.html#http://www.gailestingumas.com/assets/sp_picture/0_{{Y}}_{{X}}.jpg">
![canvas](https://user-images.githubusercontent.com/552629/78775209-1f92ef80-7996-11ea-848f-6446d1b54e58.jpg)
</a>
