### ISSUE TITLE
Indianapolis Museum of Art

### ISSUE THREAD

**Issue by MrChrisWin** [lovasoa/dezoomify#376]
This is really an FYI. They use a dzi format.

For example this work, [Roman Capriccio: The Pantheon and Other Monuments](http://collection.imamuseum.org/artwork/50522) can be downloaded by
[http://collection.imamuseum.org/artwork/50522/0_tiled.dzi](http://collection.imamuseum.org/artwork/50522/0_tiled.dzi)

So just add /0_tiled.dzi after the listing page URL.

**Comment by lovasoa** [comment]
The image is detected successfully by the [dezoomify browser extension](https://github.com/lovasoa/dezoomify-extension/#dezoomify-extension) too, for those who don't want to fiddle with URLs manually.

**Comment by MrChrisWin** [comment]
I should have tried that. Sorry!!!
