### ISSUE TITLE
Seadragon zoom... how to find?

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#377]
There are quite a few websites using a particular kind of zoom. From what I can tell, it's Seadragon, but I can't find out what URL to paste into Dezoomify to make it work.

Here are 2 examples:

http://www.rossini.fr/html/fiche.jsp?id=8146468

https://github.com/lovasoa/dezoomify/issues/new?assignees=lovasoa&labels=new+site+support&template=0_new-site-support.md&title=%5Bnew+site+support%5D

**Comment by lovasoa** [comment]
Hi,
  I think there is a problem with your second link.
  For the first one, it's a simple image, that is not tiled, and can be downloaded directly from the website without any special tool:

```
http://drouotstatic.zonesecure.org/images/perso/zoomsrc/LOT/62/85513/54.jpg
```

![](http://drouotstatic.zonesecure.org/images/perso/zoomsrc/LOT/62/85513/54.jpg)

**Comment by lovasoa** [comment]
To find the image url, you can use for instance your browser's network monitor

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

**Comment by Tricesimo** [comment]
Sorry, I pasted the wrong link... here is the correct one:
http://cornette-saintcyr.com/html/fiche.jsp?id=11354430&np=2&lng=fr&npp=20&ordre=&aff=1&r=

It's probably the same as the first one...?

**Comment by lovasoa** [comment]
Yes, this is the same. You can also get the image from the network monitor.

http://drouotstatic.zonesecure.org/images/perso/zoomsrc/LOT/124/101598/26.jpg
