### ISSUE TITLE
Add support for krpano

### ISSUE THREAD

**Issue by petesta17** [lovasoa/dezoomify#38]
# krpano Panorama Viewer
### Website
http://krpano.com/
### File format documentation
http://krpano.com/docu/xml/#image
### Exemple 
Exemple: http://www.hyper-photo.com/hyperpano/babel17/

**Comment by lovasoa** [comment]
The dezoomer works, but the image you pointed is huge. It may trigger #24.

**Comment by lovasoa** [comment]
## Node application
Since the image can't be downloaded using a browser (it's too big), I created a node application that can locally download the image and save it. Here is [your image](https://www.dropbox.com/s/0277bt6uy33v495/babel17.jpg?dl=0)

**Comment by lovasoa** [comment]
I created a wiki page explaining how to use the node script: https://github.com/lovasoa/dezoomify/wiki/Very-large-images
