### ISSUE TITLE
[new site support] greatchicagofire.org

### ISSUE THREAD

**Issue by algae21** [lovasoa/dezoomify#382]
### Can't get things to work on https://www.greatchicagofire.org/item/ichi-06194/

I can find the tiles url with network tools, but have been pulling my hair out after that.

### Example URLs
https://www.greatchicagofire.org/item/ichi-06194/

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.

**Comment by lovasoa** [comment]
Hello,
  Unfortunately, zoomify's generic dezoomer doesn't support this tile URL format, because the x and y position in the URL are left-padded with zeroes. But [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) does : 

```
dezoomify-rs --retries 0 "https://www.greatchicagofire.org/sites/greatchicagofire.org/files/tiles/_images/i06194/layer0010/tile{{Y:04}}n{{X:04}}.jpg"
```

which gives : 
![dezoomified](https://user-images.githubusercontent.com/552629/79890675-2262fb00-8400-11ea-886f-69aa3b70eeef.jpg)

**Comment by algae21** [comment]
Thank you!  I struggle with dezoomify-rs .   I just can't get it figured out.

**Comment by lovasoa** [comment]
What is your problem exactly ? Did you manage to [download the application](https://github.com/lovasoa/dezoomify-rs/releases) and run it ?

**Comment by algae21** [comment]
I have it downloaded and it runs.  I have trouble figuring out the url's.  The only documentation I've found is the usage example, which I've played with, but I can't get the hang of it.

**Comment by lovasoa** [comment]
I think I need to make a better tutorial. The best thing we have currently is the [Generic dezoomer tutorial](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial).

In your case, there is a specificity linked to 0-padding which is documented in [dezoomify-rs's README section about the generic dezoomer](https://github.com/lovasoa/dezoomify-rs#generic)

Once you've found out the tile url pattern, you need to create an url such as `https://www.greatchicagofire.org/sites/greatchicagofire.org/files/tiles/_images/i06194/layer0010/tile{{Y:04}}n{{X:04}}.jpg` where `{{Y:04}}` will be replaced with a 4-digit number for the y-position of the tile and `{{X:04}}` will be replaced with a 4-digit number for the x-position of the tile. So the tile at (2, 13) will have the url `https://www.greatchicagofire.org/sites/greatchicagofire.org/files/tiles/_images/i06194/layer0010/tile0013n0002.jpg`.

**Comment by lanaloft** [comment]
Great!! thanks for your explanation,

**Comment by lovasoa** [comment]
I added support for padding in the generic dezoomer, you can now use `https://www.greatchicagofire.org/sites/greatchicagofire.org/files/tiles/_images/i06194/layer0010/tile{{Y:04}}n{{X:04}}.jpg` in dezoomify.

**Comment by lovasoa** [comment]
![chicago fire](https://user-images.githubusercontent.com/552629/91959434-e2dee080-ed08-11ea-948b-cd2704e273c6.jpg)
