### ISSUE TITLE
request

### ISSUE THREAD

**Issue by portraitsofrulers** [lovasoa/dezoomify#385]
Hello!
Images from this source can be downloaded using dezoomify.
But these images are corrupted by watermarks.
Is it possible, in your opinion, to get a clean (without watermarks) large image from this source:
https://rusmuseumvrm.ru/data/collections/painting/17_19/portret_knyazya_anikiti_ivanovicha_repnina_konec_1690/index.php
If yes, please advise how to do this.
Thanks in advance.

**Comment by lovasoa** [comment]
Unfortunately, if the server serves the images with a watermark, there is nothing dezoomify can do. You'll have to remove them manually.
