### ISSUE TITLE
Bug Google Arts and Culture download dosent work

### ISSUE THREAD

**Issue by Colliwomple** [lovasoa/dezoomify#386]
I open the page "https://ophir.alwaysdata.net/dezoomify/dezoomify.html" and paste in a url from google arts and culture. But i get " The server responded: fopen(https://artsandculture.google.com/asset/presidential-trip-to-california/fAHOZEizFmLXTw): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests" as failure message. Yesterday it worked without problems. I also tried the browser extention. Its the same on Firefox and Safari. I am on OSX 10.14.5  . I tried other urls from Google Arts and Culture but none works. The app dezoomify-rs works

**Comment by lovasoa** [comment]
This is a duplicate of https://github.com/lovasoa/dezoomify/issues/337

**Comment by genarolongo** [comment]
I´m having the same problem with Google Arts! Since yesterday or so, I conuldn´t manage to download any image from the site. Hope this can be fixed soon!

**Comment by lovasoa** [comment]
See #337
