### ISSUE TITLE
[new site support] archives.orne.fr

### ISSUE THREAD

**Issue by genealepretre** [lovasoa/dezoomify#393]
http://archives.orne.fr/
This is the official website about history or genealogy in Orne (Normandy, France).

Different types of links on this website :

http://gaia.orne.fr/mdr/index.php/docnumViewer/calculHierarchieDocNum/388481/1057:357811:379029:388481/768/1366

http://gaia.orne.fr/mdr/index.php/docnumViewer/calculHierarchieDocNum/96234/614539:1068:413483:413484:413486:96234/768/1366

http://gaia.orne.fr/mdr/index.php/docnumViewer/calculHierarchieDocNum/439157/138:430264:433471:434038:434039:439157/768/1366

Error message:
"An error occured while trying to dezoomify your image. This is probably because dezoomify did not manage to find a zoomable image at the address you gave."

Best regards.
genealepretre

**Comment by lovasoa** [comment]
Bonjour, 
  Je réponds en français car ce site intéresse probablement principalement des francophones. 
  Les images ne sont pas dans un format supporté par dezoomify, mais il est possible d'obtenir les images en haute résolution directement depuis le site.

  Pour cela, ouvrez [le moniteur d'activité réseau de votre navigateur](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) et zoomez sur l'image qui vous intéresse. Vous verrez apparaître les requêtes vers chacune des "tuiles" individuelles qui composent l'image. 
  Faites un clic droit sur l'une, puis "Copier l'URL".
![image](https://user-images.githubusercontent.com/552629/81509470-374df280-930b-11ea-83e9-02d777f3f6f0.png)

L'URL copiée ressemble à quelque chose comme 
```
http://gaia.orne.fr/mdr/index.php/docnumserv/getImagePart/QEB3MDExQGdhaWFpbWFnZUBOdW1AM251bUBFQ0BFQ0BFQzAwMUAzRTJfMDAxXzQxMUAzTlVNNU1JRUM0NV8xMTY2LmpwZw/NDI3LjEwMzA1MzkwMzc3MDIvMjAzOS44NzczMzg1MDAxODE0LzE3MDIuMTAzMDUzOTAzNzcwNC8yODk2Ljg3NzMzODUwMDE4MS8yNzc3LjM5Mzg1MjYyNDIxMjcvMzY4OC43ODI0OTY4NzA1NQ==
```

Collez ensuite l'URL dans un nouvel onglet, et remplacez la partie après le dernier `/` par `MC8wLzk5OTkvOTk5OS83MDAwLzcwMDA=`. Dans notre exemple cela donne : 

```
http://gaia.orne.fr/mdr/index.php/docnumserv/getImagePart/QEB3MDExQGdhaWFpbWFnZUBOdW1AM251bUBFQ0BFQ0BFQzAwMUAzRTJfMDAxXzQxMUAzTlVNNU1JRUM0NV8xMTY2LmpwZw/MC8wLzk5OTkvOTk5OS83MDAwLzcwMDA=
```

Ouvrez l'url obtenue. L'image s'affiche en grand format: 

http://gaia.orne.fr/mdr/index.php/docnumserv/getImagePart/QEB3MDExQGdhaWFpbWFnZUBOdW1AM251bUBFQ0BFQ0BFQzAwMUAzRTJfMDAxXzQxMUAzTlVNNU1JRUM0NV8xMTY2LmpwZw/MC8wLzk5OTkvOTk5OS83MDAwLzcwMDA=

![](http://gaia.orne.fr/mdr/index.php/docnumserv/getImagePart/QEB3MDExQGdhaWFpbWFnZUBOdW1AM251bUBFQ0BFQ0BFQzAwMUAzRTJfMDAxXzQxMUAzTlVNNU1JRUM0NV8xMTY2LmpwZw/MC8wLzk5OTkvOTk5OS83MDAwLzcwMDA=)

**Comment by lovasoa** [comment]
http://gaia.orne.fr/mdr/index.php/docnumserv/getImagePart/QEB3MDExQGdhaWFpbWFnZUBOVU1AM251bUBQQENBREBOQDAwMUBBRDA2MTNOVU0wMV8zUDIwMDEwMV9ETC5KUEc/MC8wLzk5OTkvOTk5OS81MDAwLzUwMDA=

![](http://gaia.orne.fr/mdr/index.php/docnumserv/getImagePart/QEB3MDExQGdhaWFpbWFnZUBOVU1AM251bUBQQENBREBOQDAwMUBBRDA2MTNOVU0wMV8zUDIwMDEwMV9ETC5KUEc/MC8wLzk5OTkvOTk5OS8yMDAwLzIwMDA=)
