### ISSUE TITLE
iiif.deutsche-digitale-bibliothek.de [new site support]

### ISSUE THREAD

**Issue by gregg128** [lovasoa/dezoomify#398]
Hi,
Could you please implement support for the deutsche-digitale-bibliothek.de ?

Here is the url I tried to download:
https://viewer.deutsche-digitale-bibliothek.de/index.php?id=1&tx_dlf[id]=https%3A%2F%2Fapi.deutsche-digitale-bibliothek.de%2Fitems%2FWQRZWVKVNS32NIWCZG3KZBMC5DF74552%2Fsource%2Frecord&tx_dlf[page]=PHYS_0003

I didn't work with the firefox extension either. The extension finds lot's of json's like:
https://iiif.deutsche-digitale-bibliothek.de/image/2/0ff56fc3-fafa-45b9-8a6c-e2c733a5f6b6/info.json
but they do not work too. 

The error for the latter json: "Error: Unable to load first tile: https://ophir.alwaysdata.net/image/2/0ff56fc3-fafa-45b9-8a6c-e2c733a5f6b6/0,0,270,330/270,/0/default.jpg"

Thank you very much in advance!

**Comment by lovasoa** [comment]
Hello and thank you for reporting this.
It looks like a bug in dezoomify: it is trying to load the tile from dezoomify itself (`ophir.alwaysdata.net`), instead of the website where they are stored (`deutsche-digitale-bibliothek.de`)

**Comment by lovasoa** [comment]
Hmm... Looking at this a little deeper, it looks like it's their implementation of the IIIF protocol that is broken. Their info.json contains `"@id":"/image/2/0ff56fc3-fafa-45b9-8a6c-e2c733a5f6b6"` whereas the specification states:

> Technical Property | Required? | Description
> -- | -- | --
> @id | Required | The base URI of the image as defined in URI Syntax, including scheme, server, prefix and identifier without a trailing slash.


Anyway, it looks like they do not implement the IIIF protocol correctly, and the images are not tiled at all, you can just access them from their server without any tool. Just look at the resources loaded by the page, you'll find the full-size image.

https://viewer.deutsche-digitale-bibliothek.de/index.php?id=1&eID=tx_dlf_geturl_eid&url=http%3A%2F%2Fgoobipr2.uni-weimar.de%2Fviewer%2Fcontent%2FPPN666351716%2F1000%2F0%2F00000005.jpg

![](https://viewer.deutsche-digitale-bibliothek.de/index.php?id=1&eID=tx_dlf_geturl_eid&url=http%3A%2F%2Fgoobipr2.uni-weimar.de%2Fviewer%2Fcontent%2FPPN666351716%2F1000%2F0%2F00000005.jpg)
