### ISSUE TITLE
digitallibrary.usc.edu

### ISSUE THREAD

**Issue by kalegana** [lovasoa/dezoomify#399]
http://digitallibrary.usc.edu
What is the name and the URL of the site you would like dezoomify to support ?

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.
cant download any picture using dezoomify from http://digitallibrary.usc.edu

### Example URLs
http://digitallibrary.usc.edu/cdm/ref/collection/p15799coll123/id/36317

### Current error message
Error: Unable to find a proper dezoomer for:
http://digitallibrary.usc.edu/cdm/ref/collection/p15799coll123/id/36317

(https://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)

**Comment by lovasoa** [comment]
You can download the full image directly from the original server, without any external tool. Have a look at the following issue: https://github.com/lovasoa/dezoomify/issues/137

http://digitallibrary.usc.edu/utils/ajaxhelper/?CISOROOT=p15799coll123&CISOPTR=36317&action=2&DMSCALE=150&DMWIDTH=9999&DMHEIGHT=9999&DMX=0&DMY=0&DMTEXT=&DMROTATE=0

![](http://digitallibrary.usc.edu/utils/ajaxhelper/?CISOROOT=p15799coll123&CISOPTR=36317&action=2&DMSCALE=150&DMWIDTH=9999&DMHEIGHT=9999&DMX=0&DMY=0&DMTEXT=&DMROTATE=0)
