### ISSUE TITLE
Artsy

### ISSUE THREAD

**Issue by kioja** [lovasoa/dezoomify#4]
I can't download images from Artsy using `http://ophir.lojkine.free.fr/dezoomify/dezoomify.html`. For instance [this one](https://www.artsy.net/artwork/sebastiao-salgado-leopard-in-the-barab-river-valley-damaraland-namibia-1)

**Comment by lovasoa** [comment]
Yep, they seem to use DeepZoom, but they don't use an xml file to store the metadata.

They seem to do several XHRs to fetch the data, and it's returned as JSON.

That mean that we would have to write code especially for artsy. This is feasible, and pull requests are welcome.

**Comment by lovasoa** [comment]
There is already some site-specific code: https://github.com/lovasoa/dezoomify/blob/master/seadragon.js#L9

**Comment by lovasoa** [comment]
And you should prefer http://ophir.alwaysdata.net/dezoomify/dezoomify.html over the `free.fr` url.

**Comment by kioja** [comment]
Well I wish I could write a pull request. Unfortunately, I have no idea how to do it myself (I don't know javascript)...

**Comment by lovasoa** [comment]
Ok, maybe I'll do it when I have time, then.

**Comment by kioja** [comment]
That would be amazing!

**Comment by iPhoneGap** [comment]
It's a great tool and thanks for all your great work. Today this tool did not work when i tried to download a zoomify image with 'zoomifyImagePath' having a space and comma(,) in it. looks like in zoomify.js you have a matchPath to check the zoomifyImagePath before to qualify for a download request. Can you please fix the issue where baseurl or zoomifyImagePath having spaces or coma etc to get qualified for image download?

**Comment by lovasoa** [comment]
Can you please provide an example URL that does not work?

**Comment by iPhoneGap** [comment]
This url did't work for me http://220.227.252.236/ehmr/shankarpally,serilingampally%20and%20ramachandrapuram.aspx

**Comment by iPhoneGap** [comment]
you are awesome lovasoa! Now I am able to grab the image. It did't work for me when i downloaded and locally has run it, but worked fine when I have run using http://ophir.alwaysdata.net/dezoomify/dezoomify.html.
One more issue if you have any help... The image i am trying to download is very huge in size around 150 to 170 MB. When I tried to save in firefox , the browser immediately reporting an error and closing abruptly. I believe this is browser issue, but I appreciate if there is any tool or patch to fix it.

**Comment by lovasoa** [comment]
There is indeed not much I can do to solve this issue. If I want dezoomify to be able to work in the browser, the image has to be loaded in memory. And I have no precise control of how the browser manages memory.

You can try with another browser, or with [another tool](https://commons.wikimedia.org/wiki/Help:Zoomable_images). For instance, you can try with [dezoomify.py](http://sourceforge.net/projects/dezoomify/), a python script that  downloads zoomify images. It has no graphical user interface, and requires you to have python installed (which you probably already have if you are running MacOS or Linux). It downloads the image without loading it in memory.

**Comment by petesta17** [comment]
lovasoa, thank you for your work on dezoomify. There is an image I'm trying to grab from the website artsy that I desperately want and have tried everything, I'm even considering grabbing all the individual tiles and piecing them together manually. Is there any way you can help, I'm very inexperienced with programming language. Thank you for anything you can do.

https://www.artsy.net/artwork/jean-francois-rauzier-barcelona-veduta/zoom
