### ISSUE TITLE
Some TopViewer sites do not work

### ISSUE THREAD

**Issue by Eagle1911** [lovasoa/dezoomify#40]
I've come across some specific Dutch archive sites which do not work with dezoomify. 

Site: www.erfgoedleiden.nl
Example URL: https://www.erfgoedleiden.nl/037fc916-5f97-be9a-ee66-5df5d29caa2e

Site: http://rhcrijnstreek.nl
Example URL: http://rhcrijnstreek.nl/bronnen/foto-s-en-kaarten/zoeken/detail/b89cc580-b402-11e3-9e78-d3d4ab4f0074/media/8045c7aa-8a2d-f541-f953-a74fdbad0c9e

Thanks,

**Comment by lovasoa** [comment]
Thank you for the bug report. I'm starting to investigate.

In the meantime, you can use the meta-information files to dezoom the images. See how to do in the FAQ: https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#the-image-uses-an-image-viewer-supported-by-dezoomify-but-dezoomify-still-doesnt-work-what-to-do-

For instance, for your first URL, the url would be: https://images.memorix.nl/lei/topviewjson/leiden/c04c453c-1440-a508-b85e-ca707d6a0fe5?checkIfTiled=1
