### ISSUE TITLE
new site support: sammlungsdatenbank-museen-dresden.de

### ISSUE THREAD

**Issue by portraitsofrulers** [lovasoa/dezoomify#400]
Hello! Is it possible to get high resolution images from this site? I tried, but Dezoomify freezes and does not start the download. http://www.sammlungsdatenbank-museen-dresden.de/de/linSearch?text=Gemälde

> Edit (@lovasoa) You had left the default message body template without filling it. I updated your message.

**Comment by lovasoa** [comment]
The images on this website do not seem to be tiled, they can be downloaded directly from the website without any external tool. On firefox, you can simply right-click on the image while pressing shift and choose *Save Image As*.

![46975](https://user-images.githubusercontent.com/552629/83339786-3e946a80-a2d1-11ea-89a8-5ad5e77bb246.jpg)

**Comment by portraitsofrulers** [comment]
Hello!
Thanks for the help. I understood how to do it, but, unfortunately, the photos are of poor quality on this site.

**Comment by portraitsofrulers** [comment]
Hello!
Thanks for the help. I understood how to do it, but, unfortunately, the photos are of poor quality on this site.
