### ISSUE TITLE
[new site support] emuseum.history.org

### ISSUE THREAD

**Issue by yango** [lovasoa/dezoomify#401]
Hi,
I wonder if it's possible to dl files from emuseum.history.org like this one:
https://emuseum.history.org/objects/8518/beadwork-and-raised-picture-of-woman-and-servant-by-unknown#
Thanks in advance!

**Comment by lovasoa** [comment]
Hello, 
  this website uses IIIF, so you can download the image without any tool.
  See the following page on our wiki: https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server


```
https://emuseum.history.org/internal/media/zoomdispatcher/193689/full/max/0/default.jpg
```


![](https://emuseum.history.org/internal/media/zoomdispatcher/193689/full/max/0/default.jpg)

**Comment by yango** [comment]
Thank you so much!
