### ISSUE TITLE
[new site support] patrimoine-numerique.ville-valenciennes.fr

### ISSUE THREAD

**Issue by genealepretre** [lovasoa/dezoomify#403]
https://patrimoine-numerique.ville-valenciennes.fr/
This is the official website of Valenciennes' Library in the Pas-de-Calais (Northern part of France).
There are old maps, pictures, censuses and rare old books.

Different types of links on this website :

https://patrimoine-numerique.ville-valenciennes.fr/ark:/29755/B_596066101_MS_GEN/MS_0809?#

https://patrimoine-numerique.ville-valenciennes.fr/ark:/29755/B_596066101_MS_0488/F_002

https://patrimoine-numerique.ville-valenciennes.fr/ark:/29755/B_596066101_DAG_INC

Error message:
"An error occured while trying to dezoomify your image. This is probably because dezoomify did not manage to find a zoomable image at the address you gave."

Best regards.
genealepretre

**Comment by lovasoa** [comment]
Actually, let's rather open a separate, more general issue in dezoomify-extension
