### ISSUE TITLE
Not work with krpano

### ISSUE THREAD

**Issue by borisfoto** [lovasoa/dezoomify#408]
Site with krpano:

https://andreiduman.com/Hi-Resolution/thumbs

direct link to panorama :

https://files.andreiduman.com/Zebra1/

direct link to xml file :
https://files.andreiduman.com/Zebra1/pano.xml

pano.xml contains all the information about the file:
<flat url="Bug9_Profile_third_retouch_v2b.tiles/l%l/%0v/l%l_%0v_%0h.jpg" multires="512,768x554,1664x1202,3200x2310,6400x4618,12800x9234"/>

All that was able to retry failed, dezoomify-rs the same didn't work.

Tried dezoomify pictures in every possible way nothing succeeded. maybe I'm doing something wrong?

**Comment by lovasoa** [comment]
Hello,
  No, you are not doing anything wrong wrong. This image is using krpano's [`multires`](https://krpano.com/docu/xml/#image.cube.multires) attribute, which is not supported in either dezoomify or dezoomify-rs.

**Comment by lovasoa** [comment]
Okay, I added support for multires in dezoomify. I'm going to open a new issue for its implementation in dezoomify-rs.

![canvas](https://user-images.githubusercontent.com/552629/85271941-c5290b80-b47b-11ea-8cfe-6d5e54b8d1c2.jpg)

**Comment by borisfoto** [comment]
Many thanks !!!! I will look forward to the realization of this opportunity on dezoomify-rs!

**Comment by borisfoto** [comment]
I will need to save these photos in jpg format. I can do it at dezoomify-rs when you add this feature there?

**Comment by lovasoa** [comment]
Yes, dezoomify-rs saves images as JPEG by default (except when they are too large for the JPEG format). In the meantime, you will have to convert the images to jpeg manually.
