### ISSUE TITLE
Not able to dezoomify this pages images.

### ISSUE THREAD

**Issue by cbleep** [lovasoa/dezoomify#41]
I've tried several workarounds and i cant seen to get these images at their full resolution. They're very large images. 
I did find a reference to Python PIL regarding the images on this site with another user here on github.

This is the site; http://microsculpture.net/splendid-necked-dung-beetle.html

Thanks for the help everyone.

**Comment by lovasoa** [comment]
They use leaflet.js

**Comment by cbleep** [comment]
Hi,  Thank you.

Is it possible for dezoomify to have functionality to support this website and leaflet.js?

**Comment by cbleep** [comment]
And really, thank you sooo much for building such an incredibly useful page/website (dezoomify), i use it often and have forwarded it to many friends of the years. I'm not a developer so my apologies for not knowing the lingo! :)

**Comment by lovasoa** [comment]
2abe500e22c1772f93de2ee2aa07a306cb871327 closes this.

**Comment by cbleep** [comment]
Thank you  for working on this im so thrilled at the possibilities!

I have tested this over the past couple of days on a few of the images (ie http://microsculpture.net/tiger-beetle.html) and the images do not load; The process moves forward and the loading the tiles... screen shows progress but the images never appear even after waiting 1/2 hour after 100% of tiles have loaded. Ive also tried selecting the microsculpture.net button and let the website autoselect, both had the same result

Thank for your help!

**Comment by lovasoa** [comment]
Yes, this is a known browser bug. You will need to download the node application. Everything is explained on our wiki: https://github.com/lovasoa/dezoomify/wiki/Very-large-images

**Comment by cbleep** [comment]
Great thank you for the info and i will do. 

Thank you so much!!

**Comment by lovasoa** [comment]
This website is still supported through the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial)
