### ISSUE TITLE
[new site support] Help downloading from the University of Aberdeen's extensive image collection

### ISSUE THREAD

**Issue by Tartan2** [lovasoa/dezoomify#415]
I recently discovered a treasure trove of historical images on the University of Aberdeen's "Library Collections" site: https://abdn.primo.exlibrisgroup.com/discovery/search?vid=44ABE_INST:44ABE_VU1&lang=en

The images are displayed in a viewer called "DigiTool": https://digitool.abdn.ac.uk/view/action/singleViewer.do?dvs=1594044589119~654&locale=en_GB&VIEWER_URL=/view/action/singleViewer.do?&DELIVERY_RULE_ID=10&frameId=1&usePid1=true&usePid2=true

At the highest zoom level I have this URL for a tile: https://digitool.abdn.ac.uk/ImageServer/imageserver?&res=1&viewwidth=415&viewheight=517&x=1046&y=1375&imgClickX=1253&imgClickY=1633&rotation=0&requestId=6&filename=L2V4bGlicmlzMS9zdG9yYWdlMi8yMDEwLzA1LzA3L2ZpbGVfMi85NTUwNA%3D%3D&imageActionSelect=imageclick%2Czoomin&display_plugin=false&thumbnailActionSelect=thumbclick&collectionName=

I have tried a few different modifications of the URL to get Dezoomify to find the tiles, but I have been unsuccessful so far.

I am desperate to get access to the full resolution images on the site and was hoping someone could help me with what to do here?

Many, many thanks for any responses.

**Comment by lovasoa** [comment]
This is the kind of images you can download using [the custom yaml dezoomer](https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example-for-the-custom-YAML-dezoomer) of [dezoomify-rs](https://lovasoa.github.io/dezoomify-rs/)

**Comment by lovasoa** [comment]
It looks like you don't actually need a dezoomifier, you can just tweak the parameters in the URL to have the server return the full image: `https://digitool.abdn.ac.uk/ImageServer/imageserver?&viewwidth=9999&viewheight=2996&x=0&y=0&filename=L2V4bGlicmlzMS9zdG9yYWdlMi8yMDEwLzA1LzA3L2ZpbGVfMi85NTUwNA%3D%3D`

![](https://digitool.abdn.ac.uk/ImageServer/imageserver?&viewwidth=9999&viewheight=2996&x=0&y=0&filename=L2V4bGlicmlzMS9zdG9yYWdlMi8yMDEwLzA1LzA3L2ZpbGVfMi85NTUwNA%3D%3D)
