### ISSUE TITLE
Heritage Auctions

### ISSUE THREAD

**Issue by monks19** [lovasoa/dezoomify#422]
Hi. I'm looking for a way to get high resolution images from Heritage auction website. I tried the Dezoomefy app, but no success.
Anyone knows of a better way ?

I know that @lovasoa did something like this for images on Bonhams a while ago: https://github.com/lovasoa/dezoomify/issues/123?fbclid=IwAR0H9HrtqFTCOJnWkkPK2j2CDN6ycm0sxo63HAiAJcZ5p-MjT6ey4G_Y2XQ

Here's a link for exemple: https://movieposters.ha.com/itm/musical/the-jazz-singer-warner-bros-1927-good-very-good-on-linen-one-sheet-27-x-41-style-a/a/7223-86003.s?ic4=GalleryView-Thumbnail-071515

Thanks if you can help out with this.

**Comment by lovasoa** [comment]
Hello,
   This image is not tiled. You can download it just by right-clicking and choosing "save image as...".


![lf](https://user-images.githubusercontent.com/552629/87758181-4326cb00-c80c-11ea-884e-825b8e93f14b.jpg)

**Comment by monks19** [comment]
Yeah. But I can't get the versions without water marks (which are available only if you don't click on them, unless I'm missing something). Any way to get those ?

**Comment by lovasoa** [comment]
No, the image on the website has watermarks. Dezoomify is just a tiled image downloader, nothing more. It doesn't remove watermarks.

**Comment by lovasoa** [comment]
The lower resolution image you see before clicking does not have a watermark, and you can also download it by right-clicking on it 

![image](https://user-images.githubusercontent.com/552629/87851849-e0f9c300-c8fc-11ea-9d04-98d8336bb89d.png)
