### ISSUE TITLE
Problem with downloading zoomify from e-gory

### ISSUE THREAD

**Issue by Aniol18** [lovasoa/dezoomify#425]
Hello!

It is some problem with downloading zoomify from e-gory.pl
Statement:
"Error: Unable to find a proper dezoomer for:
https://e-gory.pl/pliki/mapy/compass/bieszczady/index.html

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)"

Does anyone know a way to fix the problem?

Regards

**Comment by lovasoa** [comment]
Hello, 
  This page is supported 🙂  Just install the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/), activate it, then zoom into your image, and it will find the URL of the zoomable image, letting you open it with dezoomify.

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/88034709-5ce44d00-cb41-11ea-9d4b-d754fbec3dc7.jpg)

**Comment by Aniol18** [comment]
Thank you very much for downloading.
I tried to install the dezoomify browser extension, 
but some error has occurred.
I will try again.

**Comment by lovasoa** [comment]
What error? While you were doing what?

**Comment by Aniol18** [comment]
I do not remember exactly.
It was in Firefox 70.0 (32-bits).
Now I tried in Firefox Quantum ESR 60.5.0esr (32 bits) and it has installed.
I tried a different address : https://gorydlaciebie.pl/Zoomify/Bieszczadzkie_Pogranicze/
After downloading, it converts, converts, ... and it doesn't end there.
<a href="https://imge.to/i/Pdmtbk"><img src="https://c.imge.to/2020/07/22/Pdmtbk.jpg" alt="Pdmtbk.jpg" border="0" /></a>
Or when I choose "Save As" nothing happens.
