### ISSUE TITLE
collections.ashmolean.org

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#426]
Hello everyone,

 I am having issues when trying to download https://collections.ashmolean.org/media/ashmole6_collection/zoom/Collections/Single_Objects/WA/WA_1968/WA_1968_0000/WA_1968_138-a/GeneratedImages/dzc_output.xml

or 
https://collections.ashmolean.org/media/ashmole6_collection/zoom/Collections/Single_Objects/WA/WA_1962/WA_1962_0000/WA_1962_17_22-a/GeneratedImages/dzc_output.xml
Dezoomify reports:

```
Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
https://collections.ashmolean.org/media/ashmole6_collection/zoom/Collections/Single_Objects/WA/WA_1968/WA_1968_0000/WA_1968_138-a/GeneratedImages/dzc_output_files/13/9_12.jpg

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:208)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
The message says that a tile from the image could not be loaded. [The tile in question](https://collections.ashmolean.org/media/ashmole6_collection/zoom/Collections/Single_Objects/WA/WA_1968/WA_1968_0000/WA_1968_138-a/GeneratedImages/dzc_output_files/13/9_12.jpg), `https://collections.ashmolean.org/media/ashmole6_collection/zoom/Collections/Single_Objects/WA/WA_1968/WA_1968_0000/WA_1968_138-a/GeneratedImages/dzc_output_files/13/9_12.jpg`, is indeed not present on their server.

What you can do is use [dezoomify-rs](https://lovasoa.github.io/dezoomify-rs/) to download the image at a smaller zoom level, and fill in the blanks from the higher zoom level with it.

![dezoomified_14](https://user-images.githubusercontent.com/552629/88267892-d0b55f80-ccd1-11ea-8bc4-1caa4622be90.jpg)
