### ISSUE TITLE
dezoomify shows progress, but the image does not appear (in firefox)

### ISSUE THREAD

**Issue by zastas** [lovasoa/dezoomify#427]
Hello!

** Describe the bug **
Work is in progress, but the image does not open.

** To Reproduce **
Downloaded an image from the site
https://collections.slsa.sa.gov.au/resource/B+74923
https://collections.slsa.sa.gov.au/resource/B+74923/tiles.json
1. "Select automatically" mode did not work
2. Manually selected the "Micrio" mode - image extraction with the "loading the tiles" progress bar started. When it got to 100%, the image did not appear - the page is just white.

** Expected behavior **
Expecting the image to open in its original size, Dezoomify did the job of extracting but did not provide a result.

**Screenshots**
![Image 442](https://user-images.githubusercontent.com/68678470/88255660-a8256980-ccc1-11ea-9354-f1e668542589.png)

**Browser:**
 - Browser Firefox
 - Version 78.0.2 bild 20200708170202

Thank!

**Comment by lovasoa** [comment]
Hello,
  I cannot reproduce this bug locally. It looks like you hit [this firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1282074), where firefox is refusing to allocate a large canvas. The easiest is to just try in another web browser. If you want to do it in firefox, you can (temporarily) set `gfx.max-alloc-size` to a higher value, such as `2000000000` in your `about:config`.

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/88271253-2d674900-ccd7-11ea-9da5-4bed5d00efb1.jpg)

**Comment by zastas** [comment]
> Здравствуйте,
> я не могу воспроизвести эту ошибку локально. Похоже, вы нажали [эту ошибку Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1282074) , где Firefox отказывается выделять большой холст. Самое простое - просто попробовать в другом веб-браузере. Если вы хотите сделать это в Firefox, вы можете (временно) установить `gfx.max-alloc-size`более высокое значение, например, `2000000000`в вашем `about:config`.

Thanks, there is no problem on another browser, I'll use it.
