### ISSUE TITLE
dezoomify does not work with British Library now

### ISSUE THREAD

**Issue by fair2003** [lovasoa/dezoomify#43]
Let us use this example:

http://www.bl.uk/manuscripts/Viewer.aspx?ref=harley_ms_2798_fs001r

Because it did not work, I put address of xml file:

http://www.bl.uk/manuscripts/Proxy.ashx?view=harley_ms_2798_fs001r.xml

but it did not help. I know, you are very good in this, so I hope it will be not big thing to solve this problem :). Best regards,

**Comment by lovasoa** [comment]
I just tried, it worked. What do you see not working as expected ?

**Comment by fair2003** [comment]
It is working for you? That is interesting. I open:
http://ophir.alwaysdata.net/dezoomify/dezoomify.html
Then I put:
http://www.bl.uk/manuscripts/Viewer.aspx?ref=harley_ms_2798_fs001r
or 
http://www.bl.uk/manuscripts/Proxy.ashx?view=harley_ms_2798_fs001r.xml
and I get:
Preparing tiles load... (0%)

and nothing more happens.
When I use dezoomify.html on my hard disk I get:

Error !
Error: Invalid XML: http://www.bl.uk/manuscripts/Proxy.ashx?view=harley_ms_2798_fs001r.xml (file:///H:/zoommanager.js:107)
You should read our FAQ, and, if you think this is an issue with dezoomify itself, report a bug on the bugtracker.

I use Windows XP and Firefox 46.0.1 (the newest).

**Comment by lovasoa** [comment]
Yes, both URL work perfectly.

### Possible causes

 * Are you using the latest version of dezoomify (do a hard refresh of the page with `Ctrl-Maj-R`) ?
 * Do you have any extensions installed?

### If you want to use dezoomify locally
You can't just download the files, you need a proxy too.

**Comment by fair2003** [comment]
I use the latest version of dezoomify and a hard refresh did not help. But you are right about extentions. I turned off ony by one and it turned out that the extention called "RightToClick" caused the problem. Now all works excellent. Thank you for your help !!

By the way. Is there any way to save tiles on my hard disk using dezoomify? I would like to stitch them losslessly using jpegtran.

**Comment by lovasoa** [comment]
You should report an error to the addon, then.

For saving tiles, unfortunately, dezoomify doesn't allow that.

I also maintain [dezoomify-py](https://github.com/lovasoa/dezoomify-py), which can do that, but unfortunately, it doesn't support other zoomifiers then *zoomify*.

**Comment by fair2003** [comment]
I know :), dezoomify is great. It can stitch tiles from local hard disk losslessly, so I thought it would be good to use dezoomify and dezoomify-py together :).

After using dezzomify, using small utility "mozillacacheview", I can copy from cache browser tiles but I see that some are missing. But I will try yet :).

**Comment by fair2003** [comment]
Hello friend, 

It turned out that it is very easy to copy all tiles from cache browser. I did that and some other nessesary things, and then I used dezoomify-py for stitching tiles from my local disk. All was quite easy and works fine but because in DeepZoom tiles has different size - what is very strange - lossless stitching is impossible. For example size of this tile:

http://www.bl.uk/manuscripts/Proxy.ashx?view=harley_ms_2798_fs001r_files/13/0_0.jpg

is 257x257. Most of tiles has size 258x258 even in the xml file is written: Image TileSize="256".

Once more I thank you for your help !!!


  ----- Original Message -----

**Comment by fair2003** [comment]
Maybe you will be interested:
Dezoomify-py could not stitch tiles automatically, because tiles have strange size. But I stitched tiles "manually" with jpegtran. I was not sure it is possible but it works. I did windows batch (.bat) file with commands like this:
jpegtran -crop 7077x5146+0+0 5-0-0.jpg pic.jpg
jpegtran -drop +0+256 5-0-1.jpg pic.jpg pic.jpg
etc.
With dezoomify I got png file 40 MB, and with it help I copied tiles from cache browser and then using my batch file I got lossless jpg file 3,3 MB. Both files are identical.
It is very easy to get png file, and with lossless jpg there is some work :).

**Comment by lovasoa** [comment]
Or you could just have converted the png to JPEG. As I said, you barely loose any information in a JPG compress-decompress-recompress cycle.

**Comment by fair2003** [comment]
Yes, I agree but all depends of size of jpeg (compression level). If you have a lot of images you want they were small as possible. In such case the lossless stitching is the best solution.

**Comment by lovasoa** [comment]
Even if you had JPEGs with a strong compression (which is not the case here), JPEG is almost insensible to recompression. Really, you can safely just convert your png to a jpeg.

**Comment by fair2003** [comment]
I did a test. I converted png file obtained from dezoomify, to jpeg, so that its size was similar to the original file (obtained from lossless stitching). The quality of images are virtually the same, there is no noticeable difference. Only at high magnification you can see a slight differences.
Best regards,
