### ISSUE TITLE
British Museum not recognised

### ISSUE THREAD

**Issue by mahlerite57** [lovasoa/dezoomify#432]
Hello, 

Following on from issue #428 
Haven't been successful with any British Museum images, eg:

https://www.britishmuseum.org/collection/object/P_1899-0729-1

Have tried the Web UI & the app.

Thanks for a fantastic app!

**Comment by lovasoa** [comment]
Duplicate of #428

**Comment by lovasoa** [comment]
Hello !
  I closed this issue as a duplicate of #428. If you are having troubles with the solution offered there, you can comment there (with as much details as possible).
