### ISSUE TITLE
stor.artstor.org

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#433]
Hello everyone,

 I am having issues when trying to download https://stor.artstor.org/iiif/fpx/kress/d0001/kress_1204_post.fpx/info.json

Dezoomify reports:

```
Error: Unable to fetch https://stor.artstor.org/iiif/fpx/kress/d0001/kress_1204_post.fpx/info.json

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:418)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
It looks like the server expects an HTTP header named `x-jstor-access-session` in tile requests. You can get the value of this cookie in the network tools of your browser while browsing the original image viewing page, and then use [dezoomify-rs](https://lovasoa.github.io/dezoomify-rs/) to download the image with the expected HTTP header  : 

```
dezoomify-rs -H "x-jstor-access-session: H4sIAAAAAAAAAI2SW28TMRCF3_srVnmuI9895g0CRTwhpekDqhAa32BRaKK9VEJV_zve9W5CulTi0d-ZGR8fz9NVVa3qsKreVKuogzWUR8NMlE5LB5yB1gKjUzRpsboeiv1UXaMnbWweax-pKtLPSVLGgvUBCEiliOSQCGoZidZeR6OV1o6Vjmbq4CxoE6xIjGuTopPgZS5WXguveMBS3fdTeUrSM2MC0SpwIoWxBAIPhEukHiWGJFxpwb77MbQk3LdxJI-4L1OYyq9lVCphlR6l-jhOB77mSq0NXzNGpzHhV_1wOadtD5eg85dn9L5rB3RfPeXzOWdGKbXj3MwmMys5gzgBa6UT2RpJFnOIllMCgJFwGxIw8ElMsQxX_z7Gseljc-iPp9En_A7b2hctS8_XLwwJI42Y_vcvS8IIoEy_NGZERIXMkfw5QGQCSRxER8A5wwR3aCJdGNvG7_XhYems8Lu8SP90NkS18MUXUUWgJkRPkjCOSG8UQQ-cUM8gh-cdxaWj_4uq-lo-uzttDAV93pg9vib0rwjYdc24FdNDN5vx2g93s5Xb3Qjebne3u8_bmW4KPWJTt98-vb-Z-ba035wLv8xgsH_1_AdPVyns4QMAAA" "https://stor.artstor.org/iiif/fpx/kress/d0001/kress_1204_post.fpx/info.json"
[ETA:0s] ########################################  168/168  Finished tile download
Image successfully saved to 'dezoomified_6.jpg' (current working directory: ~/dezoomify-rs)
```


![dezoomified_6](https://user-images.githubusercontent.com/552629/89742370-8c7bda80-da99-11ea-8210-d76063e1624a.jpg)
