### ISSUE TITLE
https://collage.cityoflondon.gov.uk/

### ISSUE THREAD

**Issue by PinkSausage** [lovasoa/dezoomify#436]
https://collage.cityoflondon.gov.uk/

The above houses the many of London's museums digitised photography, drawing and maps.

For example - https://collage.cityoflondon.gov.uk/view-item?key=SXsiUCI6eyJ2YWx1ZSI6InNld2VyIiwib3BlcmF0b3IiOjEsImZ1enp5UHJlZml4TGVuZ3RoIjozLCJmdXp6eU1pblNpbWlsYXJpdHkiOjAuNzUsIm1heFN1Z2dlc3Rpb25zIjozLCJhbHdheXNTdWdnZXN0IjpudWxsfSwiRiI6ImV5SjBJanBiTVYxOSJ9&pg=17&WINID=1597357990808#bG8vIfyvAssAAAFz6dWrcw/240226i

Use on the site is extremely hit and miss. It will usually fail after a certain pecentage, usually around 60-70% and every now and then, if you're exceptionally lucky, it will download the full item. The error message thrown up is as follows :

"Uncaught Error: Unable to load tile. Check that your internet connection is working and that you can access this url: XXX"

Looking at the console the tiles that aren't pulled are a result of a 401 Access Denied error. The same is true for dezoomify-re.exe, except that always 401's at 0% without fail.

It almost feels like the site is detecting dezoomify pulling tiles and blocks the connection, stopping all tiles being retrieved?

**Comment by lovasoa** [comment]
Hello !

  I found out what is happening here. Their server checks for the [`Referer` HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) of incoming requests. When you load the image from the dezoomify website, your browser sets the referer to `https://ophir.alwaysdata.net/dezoomify/dezoomify.html`, which lets the server know you are not loading the tiles from the expected web viewer. 

  This problem has been encountered by others before, and several solutions exist. See [*How to access protected pages*](https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages) on our wiki. The easiest is probably to just use [the latest pre-version of dezoomify-rs](https://github.com/lovasoa/dezoomify-rs/releases) which automatically requests tiles with a referer that lets the server think you are coming from the original website.

**Comment by PinkSausage** [comment]
Is there any way to increase the quality of the images saved by dezoomify-rs? By comparison to the web version, which generates images several MB in size, the .exe generates lower res images of a few hundred kb's

**Comment by lovasoa** [comment]
Hello! You can save the images as PNGs in dezoomify-rs too. On the command line, you can invoke

```
dezoomify-rs "https://your-url" my_image.png
```

and the image will be saved as a PNG.

However, PNG files are much larger, and the gain in quality is often hardly perceptible to the naked eye.
