### ISSUE TITLE
Unable to use Arts & Culture

### ISSUE THREAD

**Issue by ranfar123** [lovasoa/dezoomify#437]
Unable to dezoomify link using Arts & Culture: https://artsandculture.google.com/asset/summer-landscape-lionel-constable-1828%E2%80%931887-british/DQHqzQwdPG0BfQ

Any link at the moment is not Dezoomify-ing.

Please open a bug report ONLY if the issue you are facing is not specific to a particular site. If you have an issue with a site in particular and would like dezoomify to add support for it, then please open a __new site support__ issue instead.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Include an URL to a zoomable image viewer page AND the URL you are giving to dezoomify.

**Expected behavior**

**Screenshots**

**Browser:**

**Additional context**

**Comment by lovasoa** [comment]
Hi. You posted the template and forgot to fill in the fields. Also, please make sure your issue hasn't been reported before.

**Comment by ranfar123** [comment]
Not sure what happened to all of the fields I entered. Also new to github so there's that. I looked just now and the issue is reported and I was able to fix it based off that report. Thanks for your help!!

**Comment by lovasoa** [comment]
No problem!
