### ISSUE TITLE
Easyzoom.com

### ISSUE THREAD

**Issue by sajaypal007** [lovasoa/dezoomify#439]
https://easyzoom.com/image/123047

There is this High Resolution image of trade routes of medieval india, i wanted to download. This site doesnt seem to work with dezoomify. Care to help?

**Comment by lovasoa** [comment]
Hello,
  The website has a download button that lets you download the full  size image.

**Comment by lovasoa** [comment]
In case the same technology is used on other websites that do not offer a download option:

They use the [SZI](https://github.com/smartinmedia/SZI-Format/blob/master/SZI%20format%20description%20-%202018-11-24.pdf) file format, which is just deepzoom image tiles in a zip container. One can simply download the file, unzip it, and use [dezoomify-rs](https://lovasoa.github.io/dezoomify-rs/) on it.

**Comment by sajaypal007** [comment]
Oops, silly me. I was using the site on mobile and it didn't show it on mobile version. Now i did desktop version and saw it. Thanks anyway.
