### ISSUE TITLE
Error: Unable to load tile

### ISSUE THREAD

**Issue by kramtronix** [lovasoa/dezoomify#44]
Trying to get this image along with a few others.

http://digital.lib.usf.edu/iipimage/iipsrv.fcgi?DeepZoom=D:/usf-sobek/content/SF/S0/02/84/06/00001/R05-00010824.jp2.dzi

Error is: Unable to load tile: http://digital.lib.usf.edu/iipimage/iipsrv.fcgi?DeepZoom=D:/usf-sobek/content/SF/S0/02/84/06/00001/R05-00010824.jp2_files/12/14_11.jpg (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:107)

Source link: http://digital.lib.usf.edu/SFS0028406/00001?search=tampa

Parent link: http://digital.lib.usf.edu

Any help would be greatly appreciated because the site only allows 10 downloads per IP a day!

### Other site claimed not to work
http://ufdc.ufl.edu/iipimage/iipsrv.fcgi?DeepZoom=//flvc.fs.osg.ufl.edu/flvc-ufdc/resources/AA/00/01/57/38/00001/1995-277-16823.jp2.dzi

**Comment by lovasoa** [comment]
Please do not open several issues here if you have one problem.

**Comment by lovasoa** [comment]
If you think this is really a problem with dezoomify, we can discuss about it here.

**Comment by lovasoa** [comment]
Can you give more information about your operating system, brower and browser version, and most importantly your intrenet connection? (for instance with http://www.pingtest.net/)

Looks like your browser randomly fails at downloading tiles. I just tested and all your URLs work fine in dezoomify.

What we could do is:
  * [] give more information in the error message
  * [] retry loading a tile a certain number of times if it fails
