### ISSUE TITLE
sammlung.belvedere.at

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#440]
Hello everyone,

 I am having issues when trying to download https://sammlung.belvedere.at/internal/media/zoomdispatcher/5728/info.json

Dezoomify reports:

```
Error: Unable to fetch https://sammlung.belvedere.at/internal/media/zoomdispatcher/5728/info.json

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:418)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
Hello,
  Where did you get this URL from ? 
  https://sammlung.belvedere.at/internal/media/zoomdispatcher/5728/info.json points to a page that does not exist.

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/552629/90493778-10d9f780-e143-11ea-9a06-b2b14dcc7cac.png">

**Comment by lovasoa** [comment]
I am closing that for now. You can still answer below, we'll reopen this if you provide more information.

**Comment by gp270661** [comment]
Another URL
https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://sammlung.belvedere.at/internal/media/zoomdispatcher/125529/info.json

Thanks

**Comment by gp270661** [comment]
Sorry for incorrect URL
https://sammlung.belvedere.at/objects/3719/anbetung-der-hl-drei-konige?

**Comment by lovasoa** [comment]
There is a download button on this page. You don't need dezoomify.
