### ISSUE TITLE
Denvert Art Museum

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#441]
https://denverartmuseum.org/object/1980.404

It appears to be using Seadragon, but this page isn't recognized by Dezoomify, and it gives the same result even after installing the extension. Not sure what else I can look for to make it work.

**Comment by lovasoa** [comment]
Hello,
  This page works fine with dezoomify. To find out what URL to give dezoomify, you can use the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/)
