### ISSUE TITLE
mnesys dezoomer always downloads the first image of the page on memoirevive.besancon.fr

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify#442]
This is absolutely brilliant, since their website displays many images in a skewed form that makes them unreadable.

One bug: it does not seem to be working with multi-page documents, always using the first image in the sequence. If I enter <http://memoirevive.besancon.fr/ark:/48565/a011322745083DEmoLu/1/117>, for example, it instead gives me the image of <http://memoirevive.besancon.fr/ark:/48565/a011322745083DEmoLu/1/1>.

_Originally posted by @adunning in https://github.com/lovasoa/dezoomify/issues/360#issuecomment-674992969_

**Comment by lovasoa** [comment]
@adunning : I improved support for multi-image pages in the mnesys dezoomer. Pages like http://memoirevive.besancon.fr/ark:/48565/a011322745083DEmoLu/1/117 now work.

**Comment by adunning** [comment]
Splendid; thank you!
