### ISSUE TITLE
barnesfoundation-collection.imgix.net

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#443]
Hello everyone,

 I am having issues when trying to download https://barnesfoundation-collection.imgix.net/tiles/5782/info.json

Dezoomify reports:

```
Error: Unable to load first tile: http://localhost:8080/5782/0,0,512,512/512,/0/default.jpg

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:208)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
Duplicate of #417

**Comment by lovasoa** [comment]
@gp270661 please look at the existing issues before creating a new one.

**Comment by lovasoa** [comment]
If you have new information to add, you can comment directly on #417
