### ISSUE TITLE
stdigitalmanifestspr.blob.core.windows.net

### ISSUE THREAD

**Issue by zastas** [lovasoa/dezoomify#445]
Hello everyone,

 I am having issues when trying to download https://stdigitalmanifestspr.blob.core.windows.net/manifest/1/4765743/manifest.json

Dezoomify reports:

```
Uncaught Error: Unable to find a mnesys viewer information file

(https://dezoomify.ophir.dev/dezoomify/dezoomers/mnesys.js:34)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
Hello,
  where does this URL come from ? What image are you trying to download ?
  The URL you give is that of an [IIIF manifest](https://iiif.io/api/presentation/2.0/#primary-resource-types), not of an image.

**Comment by zastas** [comment]
Sorry for the inattention!
https://www.bac-lac.gc.ca/eng/CollectionSearch/Pages/record.aspx?app=FonAndCol&IdNumber=3336440

**Comment by zastas** [comment]
Похоже, я зря вас побеспокоил. На сайте нет картинки с большим разрешением, чем то, что доступно по ссылке для скачивания под фото.
Вопрос закрт, ещё раз извините.
