### ISSUE TITLE
dezooming at https://runivers.ru

### ISSUE THREAD

**Issue by HapMap** [lovasoa/dezoomify#447]
Cher Ophir,

Je me demande si vous seriez prêt à développer un outil pour dézoomifier les images sur ce site Web: https://runivers.ru/lib/book3296/16681/
Il existe de nombreuses cartes de l'Empire russe d'un grand intérêt.

J'apprécie beaucoup votre aide. Dezoomify a été un excellent outil pour moi.

Meilleures salutations,
Hap
USA (en utilisant google translate)

**Comment by lovasoa** [comment]
Hi! I appreciate the effort to try and write in my native language. However these GitHub issues are public, and more people can understand them and participate when they are in english.

**Comment by lovasoa** [comment]
runivers.ru doesn't use tiled images, the full size images are included directly on the page. You can just right-click on the images to save them.

https://runivers.ru/bookreader/books/16681/0071.jpg


![](https://runivers.ru/bookreader/books/16681/0071.jpg)
