### ISSUE TITLE
https://images.natgeomaps.com/

### ISSUE THREAD

**Issue by bachelorbob** [lovasoa/dezoomify#451]
https://images.natgeomaps.com/PROD_ZOOM/TI00000736.html

Try as I might with the code, I cannot find where the source image is located.

I would purchase the digital trail map, but this one is not yet available.

Neither the Dezoomify website nor the Chrome extension can handle this website.

**Comment by lovasoa** [comment]
Hello,
  This site is already supported by dezooomify, it uses the zoomify zoomable image format. You can find the zoomable image URLs to give to dezoomify with the [dezomify browser extension](https://lovasoa.github.io/dezoomify-extension/) : 

[`https://images.natgeomaps.com/PROD_ZOOM/TI00000736_0/ImageProperties.xml`](https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://images.natgeomaps.com/PROD_ZOOM/TI00000736_0/ImageProperties.xml)

[`https://images.natgeomaps.com/PROD_ZOOM/TI00000736_1/ImageProperties.xml`](https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://images.natgeomaps.com/PROD_ZOOM/TI00000736_1/ImageProperties.xml)

[`https://images.natgeomaps.com/PROD_ZOOM/TI00000736_2/ImageProperties.xml`](https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://images.natgeomaps.com/PROD_ZOOM/TI00000736_2/ImageProperties.xml)

**Comment by kalel-89** [comment]
> Hello, This site is already supported by dezooomify, it uses the zoomify zoomable image format. You can find the zoomable image URLs to give to dezoomify with the [dezomify browser extension](https://lovasoa.github.io/dezoomify-extension/) :
> 
> [`https://images.natgeomaps.com/PROD_ZOOM/TI00000736_0/ImageProperties.xml`](https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://images.natgeomaps.com/PROD_ZOOM/TI00000736_0/ImageProperties.xml)
> 
> [`https://images.natgeomaps.com/PROD_ZOOM/TI00000736_1/ImageProperties.xml`](https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://images.natgeomaps.com/PROD_ZOOM/TI00000736_1/ImageProperties.xml)
> 
> [`https://images.natgeomaps.com/PROD_ZOOM/TI00000736_2/ImageProperties.xml`](https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://images.natgeomaps.com/PROD_ZOOM/TI00000736_2/ImageProperties.xml)

Lovasoa, did they change this? it worked in the past but i cant seem to download maps any more, not sure if im doing something wrong? i have tried with chrome plus Dezoomify-rs.exe
