### ISSUE TITLE
www.artsy.net

### ISSUE THREAD

**Issue by portraitsofrulers** [lovasoa/dezoomify#453]
Hello!
Please explain how to download this enlarged image. I did not succeed using the methods known to me through dezoomify.
https://www.artsy.net/artwork/giusto-sustermans-portrait-of-ranuccio-ii-farnese-duke-of-parma-and-piacenza

**Comment by lovasoa** [comment]
Duplicate of https://github.com/lovasoa/dezoomify/issues/129
