### ISSUE TITLE
www.mutualart.com

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#454]
Hello everyone,

 I am having issues when trying to download https://www.mutualart.com/Artwork/Allegory-of-Winter/C5A71EEAA4912719#

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
https://www.mutualart.com/Artwork/Allegory-of-Winter/C5A71EEAA4912719#

(https://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
This is not a tiled image. You can download the full image just by right-clicking on it : 

https://media.mutualart.com/Images/2020_07/09/12/122328050/13b9f545-b138-47a9-9ffa-d735e489ea46.Jpeg

![](https://media.mutualart.com/Images/2020_07/09/12/122328050/13b9f545-b138-47a9-9ffa-d735e489ea46.Jpeg)
