### ISSUE TITLE
www.musee-orsay.fr

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#456]
Hello everyone,

 I am having issues when trying to download https://www.musee-orsay.fr/en/collections/index-of-works/notice.html?no_cache=1&S=1&zoom=1&tx_damzoom_pi1%5Bzoom%5D=0&tx_damzoom_pi1%5BxmlId%5D=000948&tx_damzoom_pi1%5Bback%5D=%2Fen%2Fcollections%2Findex-of-works%2Fnotice.html%3Fno_cache%3D1%26S%3D1%26nnumid%3D000948%26cHash%3D43253ccea7

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
https://www.musee-orsay.fr/en/collections/index-of-works/notice.html?no_cache=1&S=1&zoom=1&tx_damzoom_pi1%5Bzoom%5D=0&tx_damzoom_pi1%5BxmlId%5D=000948&tx_damzoom_pi1%5Bback%5D=%2Fen%2Fcollections%2Findex-of-works%2Fnotice.html%3Fno_cache%3D1%26S%3D1%26nnumid%3D000948%26cHash%3D43253ccea7

(https://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
This website doesn't offer high-resolution images, and does not use a tiled image system. 
Instead, it composes two semi-transparent images, one of top of the other.

You can recompose the image locally in a terminal with the following small script : 


```bash
MY_URL="https://www.musee-orsay.fr/en/info/gdzoom.html?S=2&tx_damzoom_pi1[zoom]=1&tx_damzoom_pi1[xmlId]=000948&tx_damzoom_pi1[back]=%2Fen%2Fcollections%2Findex-of-works%2Fnotice.html%3Fno_cache%3D1%26S%3D2%26nnumid%3D000948%26cHash%3D8608dfc770&cHash=f8b200fd50"
curl "$MY_URL" | \
  grep -oE 'https://.*?zoom_img.php\?[a-f0-9]+' | \
  xargs -n 1 curl -O && \
  composite zoom_img.php* orsay.jpg
```
