### ISSUE TITLE
[new site support] https://bibliotheques-specialisees.paris.fr [working !]

### ISSUE THREAD

**Issue by fr75** [lovasoa/dezoomify#457]
Hi,
Here is a way to have dezoomify working. 
Sorry I have not found any best place to publish. Feel free to move it.

Downoading this website is quite easy if you use Firefox.
Here is an example :

To download the image here :
https://bibliotheques-specialisees.paris.fr/ark:/73873/pf0001947057/v0001.simple.highlight=gravure%20paris.selectedTab=thumbnail

Open on Firefox the tools/web developpments/network
Zoom on the image at maximum.
Mouse left select on the file name to copy the url of one of the tile :
https://bibliotheques-specialisees.paris.fr/in/dz/d3f/f23/bdd/FORNEY_RES_CC_274_1929_dec_A_0001_files/12/3_2.jpg
Change the URL by :
https://bibliotheques-specialisees.paris.fr/in/dz/d3f/f23/bdd/FORNEY_RES_CC_274_1929_dec_A_0001_files/12/{{X}}_{{Y}}.jpg
Copy/paste on dezoomify and select "Generic dezoomer"
That's all !

Thank you to the author for this great tool !

**Comment by lovasoa** [comment]
Thank you for your contribution. You can edit the wiki if you want to give that some visibility: https://github.com/lovasoa/dezoomify/wiki

**Comment by fr75** [comment]
Thank you for the suggestion. I have added a page.
