### ISSUE TITLE
https://www.metmuseum.org/art/collection/search/436299?searchField=All&amp;sortBy=Relevance&amp;deptids=11&amp;ao=on&amp;ft=*&amp;offset=0&amp;rpp=20&amp;pos=3[new site support]

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#458]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.

### Example URLs
 - Give the URLs of viewing pages
 - give the URLs of metadata files if you found them

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.

**Comment by lovasoa** [comment]
@gp270661 : You didn't fill the template. Look at your message above.

**Comment by gp270661** [comment]
I want to dezoomify from Metmuseum. There is an opportunity to download the image but they give smaller size. Example for the URL https://www.metmuseum.org/art/collection/search/436299?searchField=All&amp;sortBy=Relevance&amp;deptids=11&amp;ao=on&amp;ft=*&amp;offset=0&amp;rpp=20&amp;pos=3[new%20site%20support]%20#458 
Thanks

**Comment by lovasoa** [comment]
This is not a tiled image. You can download it simply by right-clicking on it

https://images.metmuseum.org/CRDImages/ep/original/DP293271.jpg

![](https://images.metmuseum.org/CRDImages/ep/original/DP293271.jpg)
