### ISSUE TITLE
http://www.museen-nord.de

### ISSUE THREAD

**Issue by portraitsofrulers** [lovasoa/dezoomify#459]
Hello!
Is it possible to get a really large image here?
Thanks and all the best.
http://www.museen-nord.de/Objekt/DE-MUS-044713/lido/dc00000232

**Comment by lovasoa** [comment]
Hello, 
  I don't see any tiled zoomable image on this website. It has traditional images that you can download from your browser without dezoomify.

**Comment by lovasoa** [comment]
http://digicult-web.digicult-verbund.de/entity-resources/images/digicult-web-sh/59/DISPLAY600_152961.jpg

![](http://digicult-web.digicult-verbund.de/entity-resources/images/digicult-web-sh/59/DISPLAY600_152961.jpg)
