### ISSUE TITLE
saving dzi file password protected

### ISSUE THREAD

**Issue by twist77** [lovasoa/dezoomify#46]
how can i grab an image or dzi file thats password protected? i saw a minor explanation but it does not make any sense. running dezoomify.py with python3 on win, the web version obviously doesnt work on protected url's

**Comment by lovasoa** [comment]
What do you mean by password protected ?

**Comment by lovasoa** [comment]
And did you read this: https://github.com/lovasoa/dezoomify/issues/27#issuecomment-209322032 ?

**Comment by twist77** [comment]
got it working

**Comment by lovasoa** [comment]
Can you give some more precisions, so that people who will have the same issue in the future can read it?

**Comment by twist77** [comment]
it was just the issue of getting the ff console to work on another 
version, will not work on chrome either (to save)

**Comment by twist77** [comment]
now with cookies everytime it shows an invalid xml error line 170

**Comment by lovasoa** [comment]
You have to give more details if you want your issue fixed.
What are you doing exactly, step by step, what are you expecting, and what are you getting instead?
Give an URL and the associated cookies.

**Comment by twist77** [comment]
its a paid subscription, can you keep the url from going to the list?

**Comment by lovasoa** [comment]
You can send me a private email to pere dot jobs at gmail dot com

**Comment by lovasoa** [comment]
> (if i put ZoomManager.cookies =  before the cookie then it says too many arguments)

What do you mean by this? You have to write

```js
ZoomManager.cookies = "your cookies"
```

You can't just skip this step.

I tried, and the xml is fetched correctly, but it looks like the tiles themselves are protected.

**Comment by lovasoa** [comment]
So you must not be typing it correctly. Don't forget the `"` around your cookie string.

**Comment by twist77** [comment]
if you try it correctly what is the result?

**Comment by lovasoa** [comment]
![twist77-small](https://cloud.githubusercontent.com/assets/552629/15512562/aa1c1682-21f1-11e6-9763-c1b65c5b6b3c.jpg)

**Comment by lovasoa** [comment]
I had to [specify a tile proxy](https://github.com/lovasoa/dezoomify/wiki/Very-large-images#tiles-proxy), but you may not have to do so, if your cookies are currently set by your browser (if you are logged in on the site).

**Comment by twist77** [comment]
ok when i enter

ZoomManager.proxy_tiles  =  "proxy.php"

into the console i get "too many arguments" again. maybe my browser is screwed up

**Comment by lovasoa** [comment]
Can you post a screenshot?

**Comment by twist77** [comment]
sent one to your private

**Comment by lovasoa** [comment]
I don't see any `too many arguments` error. What are you talking about?
But it looks like you are first trying to load the image, and then enter the commands. Of course, it has to be done in this order : 
 * **First**, you set the required variables 
 * **Then**, you start dezoomifying.

**Comment by twist77** [comment]
cleared cookies on both your site and that site, now working with new 
cookies, must be an FF error because the cookies worked for you

thanks

**Comment by twist77** [comment]
no definitely not, cookies were entered first, definite firefox error

**Comment by lovasoa** [comment]
I told told you to post a screenshot of when you get this error and you didn't...

**Comment by twist77** [comment]
can i use cookies in the python version? how?

**Comment by lovasoa** [comment]
Why don't you post the screenshot I'm asking ?

**Comment by lovasoa** [comment]
You can't use cookies in the python version.

**Comment by twist77** [comment]
i already told you i sent it to your private email

**Comment by lovasoa** [comment]
N, you didn't send any screenshot of the `too many arguments` error.

**Comment by twist77** [comment]
thats was a FF error its fixed
