### ISSUE TITLE
media.davidrumsey.com

### ISSUE THREAD

**Issue by algae21** [lovasoa/dezoomify#464]
Hello everyone,

 I am having issues when trying to download https://media.davidrumsey.com/MediaManager/srvr?mediafile=/JP2K/RUMSEY~8~1/162/8345000.jp2width=9000&height=11250

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
https://media.davidrumsey.com/MediaManager/srvr?mediafile=/JP2K/RUMSEY~8~1/162/8345000.jp2width=9000&height=11250

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
duplicate of #339
