### ISSUE TITLE
[new site support] Can't download images from Hungaricana

### ISSUE THREAD

**Issue by MarkStoji** [lovasoa/dezoomify#469]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?
Hungaricana
https://hungaricana.hu/en/

### Example URLs
https://archives.hungaricana.hu/en/urbarium/
https://static.hungaricana.hu/tile/dir/urbarium/fasc168/fasc168no038/*.ecw

### Current error message
An error occured while trying to dezoomify your image. This is probably because dezoomify did not manage to find a zoomable image at the address you gave.

**Comment by lovasoa** [comment]
Hello and thanks for getting in touch. I just tried an image on hungaricana with dezoomify and the dezoomify extension, and it works.

Can you give a precise URL ( https://static.hungaricana.hu/tile/dir/urbarium/fasc168/fasc168no038/*.ecw is not a valid url), and a set of steps you do to reproduce your issue ?

**Comment by MarkStoji** [comment]
Thank you for your reply.
I thought I must have been doing something wrong. These are the steps I took: I pressed ctrl + u and then I copied files URL to "dezoomify". This is the URL which I copied and you said it is not valid: https://static.hungaricana.hu/tile/dir/urbarium/fasc168/fasc168no038/*.ecw/. So I guess the problem is I have copied the wrong URL to "dezoomify". I will also send you the URL of the exact image I want to download: https://archives.hungaricana.hu/en/urbarium/view/hu_mnl_ol_e156_a_fasc168_no038_r/?document=1&pg=107&bbox=-1162%2C-4519%2C6582%2C49
I hope I provided you with the information you asked for.

**Comment by MarkStoji** [comment]
Hi!
I figured out what I did wrong and I successfully download images I wanted.
Sorry for bothering you and thanks for your help

**Comment by lovasoa** [comment]
> I pressed ctrl + u and then I copied files URL to "dezoomify". This is the URL which I copied and you said it is not valid: https://static.hungaricana.hu/tile/dir/urbarium/fasc168/fasc168no038/*.ecw/. 

If you don't want to use the dezoomify extension and instead want to try and find the zoomable image URL manually, you should make sure the URL you find is valid. At least try to open the URL and see what it contains.
