### ISSUE TITLE
Request support for http://www.e-rara.ch ?

### ISSUE THREAD

**Issue by Eagle1911** [lovasoa/dezoomify#47]
I would love to get several illustrations from these antique books, but I couldn't get anything useful with Ctrl+Shift+Q to dezoomify. 

Test URL: http://www.e-rara.ch/zut/content/zoom/2811016

Also, can we get a video tutorial for using dezoomify externally via cmd? I kept getting errors when installing those 'dependies'.

Thanks

**Comment by lovasoa** [comment]
Hi,
  I looked at the site, they use openlayers, which is not supported by dezoomify. I may add support for this later, but I currently don't have the time. 

  For the commandline, tool, I added a video to the documentation. If it's still not clear, don't hesitate to ask questions.

**Comment by Eagle1911** [comment]
Oke, I understand.

Now I still got problems with dezoomify via cmd on Win10. I keep gettings error when installing dependies.

`Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd c:/

c:\>node --version
v6.2.0

c:\>cd C:\dezoomify-master\node-app

C:\dezoomify-master\node-app>npm install

> canvas@1.3.15 install C:\dezoomify-master\node-app\node_modules\canvas
> node-gyp rebuild


C:\dezoomify-master\node-app\node_modules\canvas>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dezoomify-master\node-app\node_modules\canvas
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
dezoomify@1.0.0 C:\dezoomify-master\node-app
+-- jsdom@8.5.0
| +-- abab@1.0.3
| +-- acorn@2.7.0
| +-- acorn-globals@1.0.9
| +-- array-equal@1.0.0
| +-- cssom@0.3.1
| +-- cssstyle@0.2.34
| +-- escodegen@1.8.0
| | +-- esprima@2.7.2
| | +-- estraverse@1.9.3
| | +-- esutils@2.0.2
| | +-- optionator@0.8.1
| | | +-- deep-is@0.1.3
| | | +-- fast-levenshtein@1.1.3
| | | +-- levn@0.3.0
| | | +-- prelude-ls@1.1.2
| | | +-- type-check@0.3.2
| | | `-- wordwrap@1.0.0
| | `-- source-map@0.2.0
| |   `-- amdefine@1.0.0
| +-- iconv-lite@0.4.13
| +-- nwmatcher@1.3.7
| +-- parse5@1.5.1
| +-- sax@1.2.1
| +-- symbol-tree@3.1.4
| +-- tough-cookie@2.2.2
| +-- webidl-conversions@3.0.1
| +-- whatwg-url@2.0.1
| | `-- tr46@0.0.3
| `-- xml-name-validator@2.0.1
`-- request@2.72.0
  +-- aws-sign2@0.6.0
  +-- aws4@1.4.1
  +-- bl@1.1.2
  | `-- readable-stream@2.0.6
  |   +-- core-util-is@1.0.2
  |   +-- inherits@2.0.1
  |   +-- isarray@1.0.0
  |   +-- process-nextick-args@1.0.7
  |   +-- string_decoder@0.10.31
  |   `-- util-deprecate@1.0.2
  +-- caseless@0.11.0
  +-- combined-stream@1.0.5
  | `-- delayed-stream@1.0.0
  +-- extend@3.0.0
  +-- forever-agent@0.6.1
  +-- form-data@1.0.0-rc4
  | `-- async@1.5.2
  +-- har-validator@2.0.6
  | +-- chalk@1.1.3
  | | +-- ansi-styles@2.2.1
  | | +-- escape-string-regexp@1.0.5
  | | +-- has-ansi@2.0.0
  | | | `-- ansi-regex@2.0.0
  | | +-- strip-ansi@3.0.1
  | | `-- supports-color@2.0.0
  | +-- commander@2.9.0
  | | `-- graceful-readlink@1.0.1
  | +-- is-my-json-valid@2.13.1
  | | +-- generate-function@2.0.0
  | | +-- generate-object-property@1.2.0
  | | | `-- is-property@1.0.2
  | | +-- jsonpointer@2.0.0
  | | `-- xtend@4.0.1
  | `-- pinkie-promise@2.0.1
  |   `-- pinkie@2.0.4
  +-- hawk@3.1.3
  | +-- boom@2.10.1
  | +-- cryptiles@2.0.5
  | +-- hoek@2.16.3
  | `-- sntp@1.0.9
  +-- http-signature@1.1.1
  | +-- assert-plus@0.2.0
  | +-- jsprim@1.2.2
  | | +-- extsprintf@1.0.2
  | | +-- json-schema@0.2.2
  | | `-- verror@1.3.6
  | `-- sshpk@1.8.3
  |   +-- asn1@0.2.3
  |   +-- assert-plus@1.0.0
  |   +-- dashdash@1.13.1
  |   | `-- assert-plus@1.0.0
  |   +-- ecc-jsbn@0.1.1
  |   +-- getpass@0.1.6
  |   | `-- assert-plus@1.0.0
  |   +-- jodid25519@1.0.2
  |   +-- jsbn@0.1.0
  |   `-- tweetnacl@0.13.3
  +-- is-typedarray@1.0.0
  +-- isstream@0.1.2
  +-- json-stringify-safe@5.0.1
  +-- mime-types@2.1.11
  | `-- mime-db@1.23.0
  +-- node-uuid@1.4.7
  +-- oauth-sign@0.8.2
  +-- qs@6.1.0
  +-- stringstream@0.0.5
  `-- tunnel-agent@0.4.3

npm WARN dezoomify@1.0.0 license should be a valid SPDX license expression
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.3.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dezoomify-master\node-app\npm-debug.log

C:\dezoomify-master\node-app>`

Thanks

**Comment by lovasoa** [comment]
Installing node-canvas on windows isn't straightforward, but they provide a HOWTO: https://github.com/Automattic/node-canvas/wiki/Installation---Windows

Or you could just install a linux virtual machine...

**Comment by Eagle1911** [comment]
Tried Ubuntu in Vmware with no luck. Getting similar errors with canvas this.. cairo that..
I give up.

Thanks anways!

**Comment by lovasoa** [comment]
Please, just try this on your VM before giving up:

```sh
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install nodejs libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
git clone https://github.com/lovasoa/dezoomify.git
cd dezoomify/node-app
npm install
node dezoomify-node.js "http://www.hyper-photo.com/hyperpano/babel17/" "babel17.jpg"
```

Just enter your password when asked to do so.

**Comment by Eagle1911** [comment]
That works! Thanks! However, it takes me several re-tries to load all tiles completely. Big files seem to hang around 90% when loading those tiles. Raising VM ram and increasing CPU cores don't help.

Do u have any tips?

**Comment by lovasoa** [comment]
You should open another issue about that. I'll investigate this when I'll have time. I suspect it's because we load the first tiles too fast, making the server's latency increase. 

19 мая 2016 г. 11:56:30 GMT+03:00, Eagle1911 <notifications@github.com> пишет:

**Comment by Eagle1911** [comment]
Sorry for getting offtopic. But now u have mentioned server latency, I tried to decrease VMware's bandwidth from Unlimited to 10 Mbps and voila, no issues anymore. This also fixed the ''Request failed, retrying'' messages I was getting quit often when loading the tiles.

Thanks!

**Comment by lovasoa** [comment]
That's a clever idea! I still have to patch dezoomify itself in order for the issue not to be here in the first place, though. 

19 мая 2016 г. 12:59:03 GMT+03:00, Eagle1911 <notifications@github.com> пишет:

**Comment by gregg128** [comment]
e-rara (Schweizer Bibliotheken)
        Beispielseite: http://www.e-rara.ch/zut/content/pageview/102788 (Bildnummer: 102788)
        Sonderlink Höchstauflösung: http://www.e-rara.ch/download/webcache/0/102788

**Comment by lovasoa** [comment]
Ok, thank you. I'm closing this issue, then.

**Comment by gregg128** [comment]
Yep it seems to work: http://www.e-rara.ch/download/webcache/0/2748118

**Comment by Eagle1911** [comment]
The webcache file is NOT the highest quality available from them. You will see why as soon as you press the zoom icon. This will generate far superior quality. 

But sadly 'Generic dezoomer' does not work well with e-rara.ch. It just keeps loading the tiles.

**Comment by lovasoa** [comment]
Well, then let's open it again

**Comment by 1-Byte** [comment]
e-rara.ch as well as e-manuscripta.ch are supported by the VLS dezoomer now

**Comment by lovasoa** [comment]
It now works thanks to the work of @1-Byte . So I'm closing this issue.
