### ISSUE TITLE
www.artic.edu

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#470]
Hello everyone,

 I am having issues when trying to download https://www.artic.edu/iiif/static/59c7ba68-2d9b-4900-a67b-c9369f3907a4/info.json

Dezoomify reports:

```
Error: Unable to load first tile: https://example.com/iiif/59c7ba68-2d9b-4900-a67b-c9369f3907a4/0,0,256,256/256,/0/default.jpg

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:208)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
Hello,
  This is the same bug as https://github.com/lovasoa/dezoomify/issues/417
  Since it looks like it's common for websites not to follow the IIIF standard, I may implement a workaround in dezoomify that ignores the `@id` property when it is set to `localhost` or `example.com`.
