### ISSUE TITLE
[bug] Colors don't match

### ISSUE THREAD

**Issue by AnotherCollector** [lovasoa/dezoomify#474]
When using deezomify-rs I noticed that the colors don't match with the source image where the extension actually does. for example:
https://gallica.bnf.fr/ark:/12148/btv1b55002481n/f9.image.r=cresques.langEN.zoom

results: https://imgur.com/a/dg0t0Wa

**Browser:**
- Google Chrome
- Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by lovasoa** [comment]
Hello! This is a known issue in dezoomify-rs, see: https://github.com/lovasoa/dezoomify-rs/issues/67

Thanks for getting in touch anyway.
