### ISSUE TITLE
Generic Dezoomer Doesn't Work - Museo del Prado

### ISSUE THREAD

**Issue by jaaschutz** [lovasoa/dezoomify#479]
### Site name and desciption
https://www.museodelprado.es

Lot's of beautiful art

### Example URLs
https://www.museodelprado.es/en/the-collection/art-work/the-expulsion-of-the-jews-from-spain-in-1492/e93c1cd5-11c0-4e4e-8a8e-876849dac09c
- cannot find metadata files

### Current error message
Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
https://www.museodelprado.es/en/the-collection/art-work/the-expulsion-of-the-jews-from-spain-in-1492/e93c1cd5-11c0-4e4e-8a8e-876849dac09c

(http://ophir.alwaysdata.net/dezoomify/zoommanager.js:208)

**Comment by lovasoa** [comment]
Duplicate of #391 . 

See : https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial

For the example mentioned here, the URL template is : `https://content3.cdnprado.net/imagenes/Documentos/imgsem/e9/e93c/e93c1cd5-11c0-4e4e-8a8e-876849dac09c/39408981-820c-42fd-9aba-a52671598231/12/{{X}}_{{Y}}.jpg`

**Comment by jaaschutz** [comment]
It seems that after some time that the Prado has changed something (maybe their dezoomer?) to prevent dezoomify from working on its site. Is there something I am missing? 

I have copied "https://content3.cdnprado.net/imagenes/Documentos/imgsem/2e/2e9f/2e9faf04-90cf-4973-b253-c77c53dd1ccf/f450ccb9-2973-442a-89a4-fa54eeeedd20/12/5_6.jpg"

Response:
Uncaught Error: Unable to find a proper dezoomer for:
https://content3.cdnprado.net/imagenes/Documentos/imgsem/2e/2e9f/2e9faf04-90cf-4973-b253-c77c53dd1ccf/f450ccb9-2973-442a-89a4-fa54eeeedd20/12/5_6.jpg

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)

![image](https://user-images.githubusercontent.com/26257395/153953755-36af9d3d-e0aa-4a75-a240-fdde980c1fb6.png)
