### ISSUE TITLE
Can't get images from PUDL

### ISSUE THREAD

**Issue by Huginn22** [lovasoa/dezoomify#48]
Hi,
First of all,Dezoomify is great! This is the first time I use it and it really surprises me! I tested some zoomable files and it worked great! However, there comes a problem.
I want to download some images from this website but it always errors: http://pudl.princeton.edu/sheetreader.php?obj=qv33rw772
I found the .xml file but it still doesn't work.
I wish you can tell me how to solve it.
Thank you.

**Comment by lovasoa** [comment]
The site you mentioned uses an IIIF server, that allows you to download full images directly.
I wrote a wiki page on how to do: https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server

**Comment by lovasoa** [comment]
Dezoomify now supports IIIF since last commit.

This image can be dezoomified by giving this URL to dezoomify: http://libimages.princeton.edu/loris/pudl0030%2F021%2F00000001.jp2/info.json
