### ISSUE TITLE
www.asmilano.it

### ISSUE THREAD

**Issue by lciok** [lovasoa/dezoomify#482]
Hello everyone,

 I am having issues when trying to download http://www.asmilano.it/AriannaWeb/main.htm?eads=*#650136

Dezoomify reports:

```
Uncaught Error: Unable to find a proper dezoomer for:
http://www.asmilano.it/AriannaWeb/main.htm?eads=*#650136

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
Duplicate of #288
