### ISSUE TITLE
memoiredeshommes.sga.defense.gouv.fr

### ISSUE THREAD

**Issue by hannanaslan** [lovasoa/dezoomify#483]
Hello everyone,

I am having issues when trying to download
https://www.memoiredeshommes.sga.defense.gouv.fr/fr/arkotheque/visionneuse/visionneuse.php?arko=YToxMDp7czoxMDoidHlwZV9mb25kcyI7czo3OiJhcmtvX2lyIjtzOjg6ImltZ190eXBlIjtzOjc6Inpvb21pZnkiO3M6NDoicmVmMCI7czoyOiIxOSI7czo0OiJyZWYxIjtpOjI2O3M6NDoicmVmMiI7czoyOiIyNyI7czo0OiJyZWYzIjtzOjA6IiI7czo0OiJyZWY0IjtzOjA6IiI7czoxMjoiaW1hZ2VfZGVwYXJ0IjtzOjc0OiIvTEVWQU5UL1NIREdSX19HUl80X0hfNC9TSERHUl9fR1JfNF9IXzRfXzAwNC9TSERHUl9fR1JfNF9IXzRfXzAwNF8wMDAxLmpwZyI7czoxNjoidmlzaW9ubmV1c2VfaHRtbCI7YjoxO3M6MjE6InZpc2lvbm5ldXNlX2h0bWxfbW9kZSI7czo0OiJwcm9kIjt9#uielem_rotate=F&uielem_islocked=0&uielem_zoomifyInfos=1094.5%2C1484.5%2C0.35904344897271806&uielem_zoom=0

An error occured while trying to dezoomify your image. This is probably because dezoomify did not manage to find a zoomable image at the address you gave.

**Comment by lovasoa** [comment]
Hello,
  This site uses zoomify, which is already supported by dezoomify. The image metadata URL to enter in your example is : 

```
https://www.memoiredeshommes.sga.defense.gouv.fr/fr//_depot_mdh/_depot_images/LEVANT/SHDGR__GR_4_H_4/SHDGR__GR_4_H_4__004/SHDGR__GR_4_H_4__004_0001/ImageProperties.xml?noCacheSfx=1604189694058
```

You can use the dezoomify extension to find it automatically.

**Comment by lovasoa** [comment]
You can also simply download the image in full-resolution from the site itself, by clicking the small downward arrow that says "Téléchargement".
