### ISSUE TITLE
How to download from Geographicus, there are two or three maps i wanted to download but dezoomify is not working for it.

### ISSUE THREAD

**Issue by sajaypal007** [lovasoa/dezoomify#484]
How to download from Geographicus, there are two or three maps i wanted to download but dezoomify is not working for it. Here is an example of it:

https://www.geographicus.com/P/AntiqueMap/Bombay-surveyindia-1933

**Comment by lovasoa** [comment]
Dezoomify [seems to work fine](https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.geographicus.com/mm5/graphics/00000001/zoomify/Bombay-surveyindia-1933/ImageProperties.xml) on this site. They use the zoomify zoomable image format, which is supported by dezoomify. You can use the [dezoomify extension](https://lovasoa.github.io/dezoomify-extension/) to find the zoomable image URL to pass to dezoomify. In your example, it is 

```
https://www.geographicus.com/mm5/graphics/00000001/zoomify/Bombay-surveyindia-1933/ImageProperties.xml
```

**Comment by sajaypal007** [comment]
Oh Thanks, I don't use dezoomify Desktop version, only use web version and some other zoomify sites i used earlier, seemed to work fine just with url so I got confused. Anyway thanks as mostly i used mobile phone so can't dezoomify extension too. Is there another method to know such image url which can be used in mobile.

**Comment by lovasoa** [comment]
Unfortunately, neither firefox nor chrome allow installing web extensions easily on mobile, but yandex browser does: https://www.gizbot.com/how-to/tips-tricks/how-you-can-install-chrome-extensions-on-android-050121.html

**Comment by sajaypal007** [comment]
Great, thanks again
