### ISSUE TITLE
sguisard.astrosurf.com

### ISSUE THREAD

**Issue by JoshieSlug** [lovasoa/dezoomify#485]
Hello everyone,

 I am having issues when trying to download http://sguisard.astrosurf.com/Pagim/GC.html

Dezoomify reports:

```
Uncaught TypeError: Cannot read property '1' of null

(https://dezoomify.ophir.dev/dezoomify/dezoomers/zoomify-pff.js:21)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
Did you manually select zoomify-pff ? For me, the download works fine with the **Select Automatically** option for the URL you give.

**Comment by lovasoa** [comment]
Here is a downsized version of the downloaded image

![sguisard-lowqual](https://user-images.githubusercontent.com/552629/97966868-b274fa80-1dbc-11eb-9f16-5fefbb991833.jpg)

**Comment by lovasoa** [comment]
A few tiles are corrupted on the server itself, so they don't display correctly, neither on dezoomify nor on the original site itself

<img width="1653" alt="image" src="https://user-images.githubusercontent.com/552629/97967083-067fdf00-1dbd-11eb-84dd-b94e0192c9a7.png">
