### ISSUE TITLE
The Morgan Library And Museum ica.themorgan.org

### ISSUE THREAD

**Issue by jacopo81** [lovasoa/dezoomify#489]
Hello!
I could not get the image at this link: 

http://ica.themorgan.org/manuscript/page/1/77495

The Chrome extension could not detect any image so I go in developers tools then NETWORK then  XHR but can't find the link to paste in dezoomify. I only could download a .ZIF file but don't know how to open it.

Thanks in advance for any help!

Jacopo

**Comment by lovasoa** [comment]
![m273-high-0](https://user-images.githubusercontent.com/552629/99517578-cf4e2800-298f-11eb-944f-5343c0d64f16.jpg)

**Comment by jacopo81** [comment]
Wow Sir,
thanks I have many other website I'm checking and I can't download from.
Can I keep add issues in the forum? A huge thanks for this picture btw!
Jacopo Selvi

Il giorno mer 18 nov 2020 alle ore 11:19 Ophir LOJKINE <
notifications@github.com> ha scritto:

**Comment by lovasoa** [comment]
Make sure you search for other issues that may be related and that you carefully read our wiki and frequently asked questions before opening new issues. 

If you have an issue that noone had encountered before, then create a new issue here.

**Comment by jacopo81** [comment]
Ok sure!
Thanks you

Il giorno mer 18 nov 2020 alle ore 12:24 Ophir LOJKINE <
notifications@github.com> ha scritto:
