### ISSUE TITLE
Request support for National Gallery images

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#49]
Hi, Lovasoa:
If you still remembered, I've received your kindly help some months ago.
And now I have some new issues to seek for your support. 
Today I noticed that the National Gallery images does not work for me, the error is Unable to find a proper dezoomer for the given URL. (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:170). And when I open the national gallery full image viewer(full screen view), the popup window was without address bar(url) which used to have! How could I find the exact url contains the zoomable image for national gallery? I've tried to find it out from inspect element, but failed.

Thanks a lot

**Comment by lovasoa** [comment]
Can you give the url of the page from which the popup opens?

**Comment by dancorpse** [comment]
http://www.nationalgallery.org.uk/paintings/alexandre-calame-at-handeck , this for example, sometime in the past, when I input this kind of url , it also worked, and if this does not work, click full screen button and copy the url of the popup window, it will sure work. But it seems nationally gallery has hidden the url of the popup window. Thanks.

**Comment by dancorpse** [comment]
It seems national gallery has changed their structure of zoomable images?

**Comment by lovasoa** [comment]
Yes, looks like they changed their old site (https://www.nationalgallery.co.uk/), that we supported. But the good news is that the new one uses [IIPImage](http://iipimage.sourceforge.net/documentation/protocol/), and that IIPImage supports serving tiles using the deepzoom protocol, and that we already support.

You can give this URL to dezoomify, and it'll work: http://www.nationalgallery.org.uk/server.iip?DeepZoom=/fronts/N-6660-00-000003-WZ-PYR.tif.dzi

**Comment by dancorpse** [comment]
This works!
But I do not detect this line in the page source, the only things I can find are sentences like this: http://www.nationalgallery.org.uk/server.iip?FIF=/fronts/N-6660-00-000003-WZ-PYR.tif&CNT=1.0&WID=800&HEI=800&QLT=85&CVT=jpeg, do you mean I should make some revision myself, replace FIF with DeepZoom, add .dzi after .tif and delete the rest. so I can also apply the same sentence structure to other IIPImage sites?

**Comment by lovasoa** [comment]
Yes, exactly. But I'll work only [if they use IIPImage v. 0.9.8 or more](http://iipimage.sourceforge.net/documentation/protocol/#deepzoom).

I'll make the necessary modifications to dezoomify so that it can do that on its own.

**Comment by dancorpse** [comment]
Thanks! I‘ve just tried this http://www.nationalgallery.org.uk/server.iip?Zoomify=/fronts/N-6660-00-000003-WZ-PYR.tif and it also worked！ 
One more question for deep zoom, https://www.artsy.net/artwork/govinda-sah-azad-untitled/zoom, this must be deepzoom protocol, right? But the structure is quite different.

**Comment by lovasoa** [comment]
Here it is! You can try it, now dezoomify supports even IIPImage's native protocol (so we should support even versions older than 0.9.8), and has the ability to detect such viewers automatically.

That is you can now just give this to dezoomify `http://www.nationalgallery.org.uk/paintings/alexandre-calame-at-handeck`, let it choose a dezoomer automatically, and it'll work.

**Comment by lovasoa** [comment]
artsy uses it's own format (that is supported in dezoomify) to store the image's meta-information, and doesn't use traditional `.dzi` files.

**Comment by dancorpse** [comment]
I’ve noticed that dezoomify already supports artsy and national Gallery also works！Merci!

**Comment by JoshuaPlinge** [comment]
I would welcome any suggestions how to download this from the National Gallery, London. 

(I have had no difficulty with images from the National Gallery up until today).

https://www.nationalgallery.org.uk/paintings/agostino-carracci-a-woman-borne-off-by-a-sea-god
