### ISSUE TITLE
Ex Libris Digitool

### ISSUE THREAD

**Issue by jacopo81** [lovasoa/dezoomify#490]
No idea how to proceed on this website

http://digitool.is.cuni.cz:1801/view/action/nmets.do?DOCCHOICE=838511.xml&dvs=1605700742986~840&locale=it_IT&search_terms=&adjacency=&VIEWER_URL=/view/action/nmets.do?&DELIVERY_RULE_ID=3&divType=

thanks in advance!

**Comment by lovasoa** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/552629/99549957-7d6ec780-29ba-11eb-9109-81a6334f0f05.png">

**Comment by jacopo81** [comment]
I'm sorry this link was working this morning

http://digitool.is.cuni.cz:1801/view/action/nmets.do?DOCCHOICE=1040111.xml&dvs=1605714678160~222&locale=it_IT&search_terms=&adjacency=&VIEWER_URL=/view/action/nmets.do?&DELIVERY_RULE_ID=3&divType=

This is from the same source and right now is working
![Cattura](https://user-images.githubusercontent.com/74651585/99553569-96797780-29be-11eb-899c-b05d8bda42c5.JPG)

**Comment by lovasoa** [comment]
Your new link doesn't work either.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/552629/99554178-30412480-29bf-11eb-807f-ca7b789fff85.png">

You can check how dezoomify is going to see a link you give him by opening it in a new private browsing window. 

You should read https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages

**Comment by jacopo81** [comment]
ok, it seems it expires after few minutes
