### ISSUE TITLE
galleria nazionale dell'umbria

### ISSUE THREAD

**Issue by jacopo81** [lovasoa/dezoomify#491]
Hello,
any tips for this website?

https://gallerianazionaledellumbria.it/opere/102/dossale-del-farneto-102/

Thanks!

**Comment by lovasoa** [comment]
You can use the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial) : 

```
https://gestionale.gallerianazionaledellumbria.it/gnu/media/gigapixel/inv_27/4/{{X}}/{{Y}}.jpg
```

**Comment by jacopo81** [comment]
Terrific thanks!
I'm mechanically getting other images just replacing INV_XXX/4/{{X}}/{{Y}}.jpg

I'm not why it's like that but it works!
