### ISSUE TITLE
cm.chimeimuseum.org

### ISSUE THREAD

**Issue by duzine** [lovasoa/dezoomify#492]
Hello everyone,

 I am having issues when trying to download http://cm.chimeimuseum.org/Admin/fcgi-bin/iipsrv.fcgi?FIF=0000075044

Dezoomify reports:

```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

(chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Picviewer%2520CE%252B.user.js&id=77ae4442-ab2e-4aea-bc56-fe38e9cd6956:10092)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
The error does not come from dezoomify, but from a chrome extension you have installed.
