### ISSUE TITLE
cm.chimeimuseum.org

### ISSUE THREAD

**Issue by duzine** [lovasoa/dezoomify#493]
Hello everyone,

 I am having issues when trying to download http://cm.chimeimuseum.org/iipShow?doId=0000075044

Dezoomify reports:

```
Uncaught Error: Unable to find a proper dezoomer for:
http://cm.chimeimuseum.org/iipShow?doId=0000075044

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
You should use the [dezoomify extension](https://lovasoa.github.io/dezoomify-extension/) to find what URL to give dezoomify.

```
http://cm.chimeimuseum.org/Admin/fcgi-bin/iipsrv.fcgi?FIF=0000075044
```

![canvas](https://user-images.githubusercontent.com/552629/99990816-94475c80-2db4-11eb-84e4-11ef496f01d1.png)
