### ISSUE TITLE
It saves a grey image

### ISSUE THREAD

**Issue by rofarias** [lovasoa/dezoomify#495]
It is not working with 
https://gallica.bnf.fr/ark:/12148/btv1b9011860x/f1.item.r=br%C3%A9sil%20cafe.zoom#

**Comment by lovasoa** [comment]
See https://github.com/lovasoa/dezoomify/issues/359
and https://github.com/lovasoa/dezoomify/wiki/Very-large-images

If the image is too large for your browser to handle, the easiest is to use [dezoomify-rs](https://dezoomify-rs.ophir.dev/)
