### ISSUE TITLE
Saved image is smaller than in browser (National Portrait Gallery)

### ISSUE THREAD

**Issue by ackern** [lovasoa/dezoomify#496]
Dezoomify works for the National Portrait Gallery except that the image that gets saved to the computer is smaller than how it appears in the browser when Dezoomify is finished. The screenshot shows my browser and on the right is the png file that was downloaded. Strangely, the Dezoomified image in the browser is *larger* than the largest magnification at the website, but the png that is saved to the computer is slightly *smaller* than the largest magnification.

Firefox and Chrome on Win 7
Safari on Mac High Sierra 

### Site name and desciption

National Portrait Gallery (UK)

### Example URLs
 https://www.npg.org.uk/collections/search/portrait/mw15027/Cathleen-Sabine-Mann?LinkID=mp06547&role=art&rNo=0

![screenshot comparing browser and downloaded](https://user-images.githubusercontent.com/8440262/100905263-268fe480-34c8-11eb-9ba7-a563053c154f.jpg)

**Comment by lovasoa** [comment]
Your image viewer displays the image at a scale that fits its window. You can zoom in on the image, and you will the that the image quality is the same as on the original image viewer.
