### ISSUE TITLE
Webstite version works / dezoomify-rs does not work

### ISSUE THREAD

**Issue by queensoft666** [lovasoa/dezoomify#499]
### Site name and desciption
The British Library
Endangered Archives Programme

Why is this site of particular interest?
Interesting informations. (Just kidding, it's for a job)

### Example URLs
https://eap.bl.uk/archive-file/EAP262-1-1-1
More precisely: https://eap.bl.uk/archive-file/EAP262-1-1-1#?c=0&m=0&s=0&cv=0&xywh=-2845%2C-364%2C14309%2C7274

### Current error message
Dezoomify works great using the website.
But dezoomify-rs says:
ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - custom: The 'custom' dezoomer cannot handle this URI
 - google_arts_and_culture: The 'google_arts_and_culture' dezoomer cannot handle this URI
 - zoomify: The 'zoomify' dezoomer cannot handle this URI
 - generic: The 'generic' dezoomer cannot handle this URI
 - pff: Unable to create the dezoomer: Invalid meta information file: missing field `file`
 - IIPImage: The 'IIPImage' dezoomer cannot handle this URI
 - nypl: The 'nypl' dezoomer cannot handle this URI
 - iiif: Unable to create the dezoomer: Invalid IIIF info.json file: expected value at line 1 column 1
 - deepzoom: Unable to create the dezoomer: Unable to parse the dzi file: Syntax: 11:75 Unexpected token inside an entity: &
 - krpano: Unable to create the dezoomer: Unable to parse the krpano xml file: Syntax: 11:75 Unexpected token inside an entity: &

Thank you for your help!

**Comment by lovasoa** [comment]
You should give dezoomify-rs the meta-information file url, not the viewer page url that you see in your browser.

**Comment by lovasoa** [comment]
And you should make sure the image is in one of the formats supported by dezoomify-rs.

**Comment by queensoft666** [comment]
Thank you very much, I think I've got it working !!
I'm not going to post the solution just yet, maybe I get the job !

**Comment by lovasoa** [comment]
Well, the goal of dezoomify is to help everyone, and in case someone else stumbles on this page while having this kind of issues, I recommend using the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/) to find the url to feed dezoomify-rs.

And if you are having other issues with dezoomify-rs, you can open issues in [its own issue tracker](https://github.com/lovasoa/dezoomify-rs/issues).
