### ISSUE TITLE
Support for the World Digital Library (WDL)

### ISSUE THREAD

**Issue by lovasoa** [lovasoa/dezoomify#5]
Question initially submitted by @Horemheb : 

I tried to find the right link to submit to seadragon through the dezoomify web page... but I got no answer... how can I find how the world digital library files its images.. i.e. If I want to download the bible from this page... http://www.wdl.org/en/item/9910/view/1/230/ can anybody give me any hint? Thanks :)

**Comment by lovasoa** [comment]
The World Digital Library uses openseadragon, an open source implementation of the [Microsoft DeepZoom format](https://msdn.microsoft.com/fr-fr/library/cc645077%28v=vs.95%29.aspx), which is already implemented in [dezoomify](http://ophir.alwaysdata.net/dezoomify/dezoomify.html).

All you have to to is find the `.dzi` file that dezoomify needs. In order to do so, open the source code of the page and look for `dziTemplate`. In the case of the example you gave, it gives me the following line:
```
                dziUrlTemplate: "/media/9910/service/dzi/1430173705/{group}/{index}.dzi",
```
In the URL, replace `{group}` by the volume number (`1` in your case) and `index` by the page number (`230` in your case), and add `http://www.wdl.org` at the beginning to form a complete URL.
For your example, it gives: `http://www.wdl.org/media/9910/service/dzi/1430173705/1/230.dzi`.

In dezoomify, copy and paste this URL, and choose *Seadragon (Deep Zoom Image)* in the options. Click *submit*. Et voilà!

**Comment by lovasoa** [comment]
I finally implemented it. You can try it on http://ophir.alwaysdata.net/dezoomify .

**Comment by Horemheb** [comment]
Thanks! U'r amazing as usual! I was missing the "dzi" completion of the sentence.

**Comment by Horemheb** [comment]
I have tried your way to find the dezoomify working link but it's always rather hard. I am having probs with Polona. I tried to get the source code, as I tried to compose the web link in different ways in the dezoomify blank space of ur page but.. no way.. This is the page I faced and no result. LOL
http://polona.pl/item/285246/26/
