### ISSUE TITLE
Browser Extension not working on National Library of Scotland pages

### ISSUE THREAD

**Issue by SmithJustinL** [lovasoa/dezoomify#500]
I was trying to get this image:

https://auchinleck.nls.uk/view/?jp2=105v

I clicked on the browser extension for Firefox and then clicked the plus sign to maximize the image on the page. When the browser extension showed the red 1 sign, I clicked on it and it took me to the Dezoomify page. I hit enter. ERROR. I went back and did it again, and selected Generic Dezoomer. Same issue. This site is supposed to be supported so I am not sure why it's not working for me.

**Comment by Starnat63** [comment]
I thought it was just me. Even the maps that I had downloaded in the Summer don't download now. I have increased the cache even further with no luck.

[https://maps.nls.uk/view/189259259](url)

**Comment by lovasoa** [comment]
@Starnat63 : the issue you are having is not the same. Meta-information files on maps.nls.uk are invalid, but you can still fix them and pass the result to dezoomify-rs. See https://github.com/lovasoa/dezoomify-rs/issues/92

**Comment by Starnat63** [comment]
Thanks for your prompt reply. 
I downloaded dezoomify-rs and tried a few things to no avail.
This seems easy and makes sense, but....
I have no idea how to edit the files, up to now, I have only used the Dezoomify add-on on firefox.
I need to find a tutorial.

**Comment by lovasoa** [comment]
Please comment on https://github.com/lovasoa/dezoomify-rs/issues/92 with details about what your problem is.

**Comment by lovasoa** [comment]
The issue with auchinleck.nls.uk should be fixed now. Thanks for reporting it, @SmithJustinL !

**Comment by SmithJustinL** [comment]
Thank you!
