### ISSUE TITLE
www.rawpixel.com

### ISSUE THREAD

**Issue by frenksisco** [lovasoa/dezoomify#505]
Hello everyone,

 I am having issues when trying to download https://www.rawpixel.com/image/537428/free-illustration-image-van-gogh-cafe-pub

Dezoomify reports:

```
Uncaught Error: Unable to find a proper dezoomer for:
https://www.rawpixel.com/image/537428/free-illustration-image-van-gogh-cafe-pub

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
Hello !
  Thanks for getting in touch. This site doesn't seem to offer zoomable images, so you don't need a zoomable image downloader here. You can download the full images directly from  the site itself.
