### ISSUE TITLE
www.vangoghmuseum.nl

### ISSUE THREAD

**Issue by frenksisco** [lovasoa/dezoomify#506]
Hi, sorry for this second report in a short time
I am having issues when trying to download https://www.vangoghmuseum.nl/en/collection/s0195V1962
The page contains a download link but it gives you is a low resolution version of the zoomed one

Dezoomify reports:

```
Uncaught Error: Invalid JSON:
https://micrio.vangoghmuseum.nl/iiif/giZUM/info.json

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)
```
I don't understand this message. Can someone please help me ?

**Comment by radiomaniac** [comment]
Hello, I found this image in full resolution on wikipedia https://upload.wikimedia.org/wikipedia/commons/0/0e/Boomwortels_-_s0195V1962_-_Van_Gogh_Museum.jpg it even has the same ID (s0195V1962) that's inside that json file you linked. I hope this helped you.

Have a nice day

**Comment by dancorpse** [comment]
I remember that vangoghmuseum use Micrio, refer to this https://github.com/lovasoa/dezoomify/issues/309, but it seems dezoomify does not support both URLs now.

**Comment by dancorpse** [comment]
Here was another issue regarding vangoghmuseum https://github.com/lovasoa/dezoomify/issues/487, so for this image the we can use generic dezoomer to download image: 
 https://micrio-cdn.vangoghmuseum.nl/giZUM/0/{{X}}-{{Y}}.jpg, 
but I'm not quite understand the structure of their micrio tool, as the dezoomify extension is not able to detect the actual image URL, how to determine the URL template? 
@lovasoa

**Comment by lovasoa** [comment]
Ok let's close this if this is a duplicate. We can discuss on the original issue

**Comment by lovasoa** [comment]
See https://github.com/lovasoa/dezoomify/issues/309#issuecomment-855895832 . micrio hardcoded a rule to say that if a request comes from dezoomify, they should return an error message 😆

I just disabled sending the referrer with our tile requests, and vangoghmuseum.nl works again.
