### ISSUE TITLE
www.britishmuseum.org

### ISSUE THREAD

**Issue by radiomaniac** [lovasoa/dezoomify#507]
Hello everyone,

 I am having issues when trying to download https://www.britishmuseum.org/collection/object/A_1881-1210-0-1885

Tried looking under networks -> XHR, can't find a valid url.

Dezoomify reports:

```
Uncaught Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
https://www.britishmuseum.org/collection/object/A_1881-1210-0-1885

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
This zoomable image URL for this page can be found automatically with the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/), without even having to open the network manager : 

```
https://media.britishmuseum.org/iiif/Repository/Documents/2014_10/13_9/592784c9_9361_4a73_bb07_a3c3009fb2f8/00792378_001.ptif/info.json
```

![canvas](https://user-images.githubusercontent.com/552629/103545002-3de43800-4ea1-11eb-9849-10f27b0931af.jpg)

**Comment by radiomaniac** [comment]
> The zoomable image URL for this page can be found automatically with the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/), without even having to open the network manager :
> 
> ```
> https://media.britishmuseum.org/iiif/Repository/Documents/2014_10/13_9/592784c9_9361_4a73_bb07_a3c3009fb2f8/00792378_001.ptif/info.json
> ```
> 
> ![canvas](https://user-images.githubusercontent.com/552629/103545002-3de43800-4ea1-11eb-9849-10f27b0931af.jpg)

I tried with the extension and it didn't do anything, maybe I was using it wrong? The extension icon is blue when I'm on that page, I either zoom on the image or reload the page and nothing happens with it... Thanks!

**Comment by lovasoa** [comment]
Do you have the latest version of the extension? Just activating the extension and reloading the page does it for me.

**Comment by radiomaniac** [comment]
> Do you have the latest version of the extension? Just activating the extension and reloading the page does it for me.

Yes, though maybe I'm having this issue because I'm using brave browser (chromium based) and I have a but ton of extensions so maybe it has some conflict. Next time I will try with regular chrome. Thanks
