### ISSUE TITLE
Washington State University digital collections [new site support]

### ISSUE THREAD

**Issue by frauchi1** [lovasoa/dezoomify#510]
### Site name and desciption
https://content.libraries.wsu.edu/digital/collection/propaganda/search

Generic dezoomer doesn't works with some ww2 posters (mostly french). Saved image will display bottom/side line blank

### Not working with this one
I
 [Image]https://content.libraries.wsu.edu/digital/collection/propaganda/id/374
 [Tile] https://cdm16866.contentdm.oclc.org/digital/iiif/propaganda/374/6144,4096,2048,2048/1024,/0/default.jpg?highlightTerms=

### Working with this one

[Image] https://content.libraries.wsu.edu/digital/collection/propaganda/id/189/rec/7
[Tile] https://cdm16866.contentdm.oclc.org/digital/iiif/propaganda/189/0,2048,1024,952/1024,/0/default.jpg?highlightTerms=

Any ideas on how to fix this ?

**Comment by lovasoa** [comment]
This website uses IIIF and thus [already works with dezoomify](https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://cdm16866.contentdm.oclc.org/digital/iiif/propaganda/374/info.json). You can use the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/) to automatically find the image metadata file URL to pass to dezoomify.

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/103785252-48d2d000-503b-11eb-9855-32c66b2ebf0a.jpg)

**Comment by AmiralCrapaud** [comment]
Hello @lovasoa 
Hope you're doing fine!
Sorry to dig up that cold corpse, but I just so happen to be in the same situation as the OP with that very same website. And although I ended up finding the same URL through the browser extension, both the online version of dezoomify & the prompt return errors (in the case of the prompt, it finds the files, but will tell you on selection & execution "ERROR Input/Output error: Access is denied. (os error 5)")

For instance you can try it again with the same URL as the one you posted above
https://cdm16866.contentdm.oclc.org/digital/iiif/propaganda/374/info.json
You'll get the same mistakes as the ones I encountered I guess (just tried it myself)

Any idea of what could be done to go around this?

Big thanks!
