### ISSUE TITLE
https://collections.si.edu

### ISSUE THREAD

**Issue by awhizard** [lovasoa/dezoomify#511]
Hi there!
Just wondering how I can download high quality books pages like these ...
https://collections.si.edu/search/detail/edanmdm:chndm_1983-63-4?q=sample+book&fq=online_media_type%3A%22Images%22&record=74&hlterm=sample%2Bbook&inline=true
It seems you can see the image zoomified when you click tiled image:
Thanks!!
aw

**Comment by lanaloft** [comment]
click on the IIIF, then view it in the Mirador Viewer,.With  the dezoomify app eg firefox, you can load the image, saved it to a mapIt works perfect!!



    Am Mittwoch, 13. Januar 2021, 12:25:31 MEZ hat awhizard <notifications@github.com> Folgendes geschrieben:  
 
 


Hi there!
Just wondering how I can download high quality books pages like these ...
https://collections.si.edu/search/detail/edanmdm:chndm_1983-63-4?q=sample+book&fq=online_media_type%3A%22Images%22&record=74&hlterm=sample%2Bbook&inline=true
It seems you can see the image zoomified when you click tiled image:
Thanks!!
aw

**Comment by lovasoa** [comment]
Yes, @lanaloft is right, this site already works with dezoomify.

![image](https://user-images.githubusercontent.com/552629/104585287-1ab94580-5664-11eb-8c35-27bc036e3e15.png)

Right-click on "view manifest", then "Copy Link Location".

Then paste the link into dezoomify.

https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://ids.si.edu/ids/manifest/CHSDM-B014A7A8463D2_003-000001
