### ISSUE TITLE
colonialamerica.amdigital.co.uk

### ISSUE THREAD

**Issue by SmithJustinL** [lovasoa/dezoomify#512]
I have a login to this website and am trying to download the document here. I am able to view it, but no attempt to download it works. Please advise. 

https://www.colonialamerica.amdigital.co.uk/Documents/Images/CO_5_718_Part1_025/0

**Comment by lovasoa** [comment]
Hello !
If your website requires a login, you should read this page from our wiki: https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages
