### ISSUE TITLE
mza.cz

### ISSUE THREAD

**Issue by snek01** [lovasoa/dezoomify#513]
Hello,
the Moravian regional archive (Moravský zemský archiv v Brně) does not work with Dezoomify.
https://www.mza.cz/

There are two subsites:
1)
https://www.mza.cz/actapublica/
Documents with vital records.
example:
https://www.mza.cz/actapublica/matrika/detail/2992?image=216000010-000253-003368-000000-000210-000000-00-B01785-00010.jp2

2)
https://www.mza.cz/scitacioperaty/digisada/search
Documents about census.
Example:
https://www.mza.cz/scitacioperaty/digisada/detail/3611?image=226207010-000870-001785-000006-000001-01-ZN0264-00020.jp2

It is possible to use network inspector to find the URL of one of the image's tiles. But the Dezoomify does not give the final image.

Error report of the first example:
Error: Unable to load the meta-information file: 
- https://www.mza.cz/actapublica/iipsrv/iipsrv.fcgi?Deepzoom=/srv/LUN013/LUN013/216000010/216000010-000253-003368-000000-000210-000000-00-B01785/216000010-000253-003368-000000-000210-000000-00-B01785-00010.jp2.dzi: Invalid XML:
https://www.mza.cz/actapublica/iipsrv/iipsrv.fcgi?Deepzoom=/srv/LUN013/LUN013/216000010/216000010-000253-003368-000000-000210-000000-00-B01785/216000010-000253-003368-000000-000210-000000-00-B01785-00010.jp2.dzi
- https://www.mza.cz/actapublica/iipsrv/iipsrv.fcgi?Deepzoom=/srv/LUN013/LUN013/216000010/216000010-000253-003368-000000-000210-000000-00-B01785/216000010-000253-003368-000000-000210-000000-00-B01785-00010.jp2.xml: Invalid XML:
https://www.mza.cz/actapublica/iipsrv/iipsrv.fcgi?Deepzoom=/srv/LUN013/LUN013/216000010/216000010-000253-003368-000000-000210-000000-00-B01785/216000010-000253-003368-000000-000210-000000-00-B01785-00010.jp2.xml

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)

**Comment by lovasoa** [comment]
Hello,
  It looks like there is an SSL certificate issue with this website : https://www.ssllabs.com/ssltest/analyze.html?d=www.mza.cz
  An extra intermediate certificate is required to validate the website's identity, and the server doesn't provide it. Browsers download this intermediate certificate automatically, but most other tools can't. In particular, this prevents cloudflare, which we use to fetch image meta-information from websites from accessing it: https://dezoomify.ophir.dev/dezoomify/proxy.php?url=http%3A%2F%2Fwww.mza.cz%2F

  Your best hope is probably to tell mza.cz about their SSL certificate issue and ask them to fix it.

**Comment by lovasoa** [comment]
I also raised the issue to cloudflare, but I doubt they will provide any kind of support...

**Comment by snek01** [comment]
Thank you. OK, I asked them to fix their certificate issue. We will see.

**Comment by lovasoa** [comment]
It worked, they fixed it ! Congrats @snek01, you contributed to make the web a little bit better today :)

**Comment by lovasoa** [comment]
![canvas1](https://user-images.githubusercontent.com/552629/105075531-2785d100-5a8a-11eb-8113-b58d14160e05.png)

**Comment by lovasoa** [comment]
![image](https://user-images.githubusercontent.com/552629/105075611-44220900-5a8a-11eb-9344-25956698e619.png)
https://www.ssllabs.com/ssltest/analyze.html?d=www.mza.cz
