### ISSUE TITLE
Google Museum Error

### ISSUE THREAD

**Issue by Leonidas120** [lovasoa/dezoomify#518]
Please open a bug report ONLY if the issue you are facing is not specific to a particular site. If you have an issue with a site in particular and would like dezoomify to add support for it, then please open a __new site support__ issue instead.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Include an URL to a zoomable image viewer page AND the URL you are giving to dezoomify.

**Expected behavior**

**Screenshots**

**Browser:**

**Additional context**

**Comment by lovasoa** [comment]
This is not actionable. Please fill in the required information.
