### ISSUE TITLE
dezoomify did not manage to find a zoomable image at the address you gave.

### ISSUE THREAD

**Issue by yasinhemmati** [lovasoa/dezoomify#519]
Uncaught Error: Unable to fetch https://artsandculture.google.com/asset/kuss/HQGxUutM_F6ZGg
The server responded:
fopen(https://artsandculture.google.com/asset/kuss/HQGxUutM_F6ZGg): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)

**Comment by bryanzk** [comment]
Met the same problem here since this morning.

**Comment by lovasoa** [comment]
Duplicate of https://github.com/lovasoa/dezoomify/issues/337

**Comment by lovasoa** [comment]
Hello, 
  I am closing this issue since it has already been reported before. You can still comment on #337 
  This comes from google blocking the IP of dezoomify's server when too many people use it simultaneously.

**Comment by lovasoa** [comment]
I added a comment on the other issue : https://github.com/lovasoa/dezoomify/issues/337#issuecomment-773498488

The easiest is to just try again tomorrow morning. 
If you want to make a small monthly donation, we can rent more server time, and make it available 24/7.
