### ISSUE TITLE
add support for centrica.it

### ISSUE THREAD

**Issue by lakmay** [lovasoa/dezoomify#52]
I just have URL of  zoomimage tile
for example
http://uffizicloud.centrica.it/7711/closer/hi-res/A1456.imgf?cmd=tile&x=0&y=0&z=32
or 
http://uffizicloud.centrica.it/7711/closer/hi-res/A1456.imgf?cmd=tile&x=40&y=40&z=0

 How download full image or open in zoomwiewer window?
image size can see at
http://uffizicloud.centrica.it/7711/closer/hi-res/A1456.imgf?cmd=info

**Comment by lovasoa** [comment]
They use XLImage, that we already support. I'm going to add support to this site by improving the XLImage dezoomer.
Can you provide the url of the page the dezoomer is embedded in?

**Comment by lakmay** [comment]
hi? thanks
http://www.centrica.it/portfolio_page/xlimage/

**Comment by lovasoa** [comment]
OK, thanks. The url doesn't define a single image. But you can try with ` http://uffizicloud.centrica.it/7711/closer/hi-res/A1456.imgf?cmd=info`, now it works.

**Comment by lakmay** [comment]
I tried the loading  but image is empty

**Comment by lovasoa** [comment]
And if the image is too large for it to be displayed correctly, you can dezoom it at a smaller zoom level, using the new generic dezoomer. For instance, try to give this to dezoomify: `http://uffizicloud.centrica.it/7711/closer/hi-res/A1456.imgf?cmd=tile&x={{X}}&y={{Y}}&z=4`
