### ISSUE TITLE
New site support: http://graficheincomune.comune.milano.it

### ISSUE THREAD

**Issue by m-bazanelli** [lovasoa/dezoomify#521]
Hi everyone.
I can't download from http://graficheincomune.comune.milano.it/GraficheInComune/immagine/Cod.+Triv.+80,+c.+Iv+-+c.+1r
I thank you in advance for any help.

URL obtained via inspection of the page above:
http://graficheincomune.comune.milano.it/GraficheInComune/imgdbs/web/BibliotecaTrivulziana/Manoscritti/Cod.%20Triv.%2080/Cod.%20Triv.%2080,%20c.%20Iv%20-%20c.%201r.xml

Dezoomify screenshot
![image](https://user-images.githubusercontent.com/78938007/107761210-48f57800-6d2b-11eb-9f3a-3405be0ace47.png)

Dezoomify-rs screenshot
![image](https://user-images.githubusercontent.com/78938007/107761931-7858b480-6d2c-11eb-9a21-a6430f606980.png)

**Comment by Benomrans** [comment]
Hi, Try this:
Take the url of a tile from the inspector : 

http://graficheincomune.comune.milano.it/GraficheInComune/imgdbs/web/BibliotecaTrivulziana/Manoscritti/Cod.%20Triv.%2080/Cod.%20Triv.%2080,%20c.%20Iv%20-%20c.%201r/11/0_2.jpg

then replace the tile with {{X}}_{{Y}} :
http://graficheincomune.comune.milano.it/GraficheInComune/imgdbs/web/BibliotecaTrivulziana/Manoscritti/Cod.%20Triv.%2080/Cod.%20Triv.%2080,%20c.%20Iv%20-%20c.%201r/11/{{X}}_{{Y}}.jpg

pass it to dezoomify-rs and wait for it.
Best Regards.
And as always many thanks to Lovasoa.

**Comment by m-bazanelli** [comment]
Thank you for your reply, Benomrans.
Unfortunately, I've got the same error message. What am I doing wrong?

![image](https://user-images.githubusercontent.com/78938007/107778574-87e3f780-6d44-11eb-931f-247bd6abad5c.png)

**Comment by Benomrans** [comment]
well, so sorry, I guess I made a mistake, didn't view the image at largest, it should be like this: 

http://graficheincomune.comune.milano.it/GraficheInComune/imgdbs/web/BibliotecaTrivulziana/Manoscritti/Cod.%20Triv.%2080/Cod.%20Triv.%2080,%20c.%20Iv%20-%20c.%201r/12/{{X}}_{{Y}}.jpg

it works on both dezoomify directly as well as dezoomify-rs.
Best regards.

![dezoomified-2](https://user-images.githubusercontent.com/75787532/107783260-bb2d8300-6d52-11eb-951f-47109517e33e.jpg)

**Comment by m-bazanelli** [comment]
It's perfect! Thank you very much again.
