### ISSUE TITLE
emuseum.delart.org

### ISSUE THREAD

**Issue by Apollodore** [lovasoa/dezoomify#522]
Hello everyone,

 I am having issues when trying to download https://emuseum.delart.org/internal/media/zoomdispatcher/49136/info.json

Thanks

Dezoomify reports:

```
Uncaught Error: Invalid JSON:
https://emuseum.delart.org/internal/media/zoomdispatcher/49136/info.json

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
The URL you are giving doesn't seem to be valid : 

![Uploading image.png…]()

**Comment by lovasoa** [comment]
I think I understand what happened. You used the dezoomify extension and it gave you this URL.
Unfortunately, the server doesn't serve the `info.json` metadata file that dezoomify needs to download the image.

But you can still use [the usual technique to download IIIF images directly from the source server](https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server), without dezoomify: 

https://emuseum.delart.org/internal/media/zoomdispatcher/49136/full/max/0/default.jpg

![](https://emuseum.delart.org/internal/media/zoomdispatcher/49136/full/max/0/default.jpg)

**Comment by Apollodore** [comment]
Un grand merci Ophir pour votre réponse et votre magnifique travail sur Dezoomify !

**Comment by lovasoa** [comment]
De rien :)
