### ISSUE TITLE
john-taylor-arms-venetian-filigree

### ISSUE THREAD

**Issue by jacopo81** [lovasoa/dezoomify#523]
Hello
couldn't download the image with the standard tools:

https://www.artsy.net/artwork/john-taylor-arms-venetian-filigree

any advise?
Thanks!!

**Comment by lovasoa** [comment]
Hello !
  This issue is a duplicate of https://github.com/lovasoa/dezoomify/issues/129

  You can [search existing issues here](https://github.com/lovasoa/dezoomify/issues) before opening a new one.

**Comment by jacopo81** [comment]
Sorry sorry sorry!

Il giorno lun 15 feb 2021 alle ore 10:19 Ophir LOJKINE <
notifications@github.com> ha scritto:

**Comment by lovasoa** [comment]
Haha, no need to be sorry, you're welcome 😃

**Comment by jacopo81** [comment]
😊

Il lun 15 feb 2021, 11:32 Ophir LOJKINE <notifications@github.com> ha
scritto:
