### ISSUE TITLE
https://digicol.dpm.org.cn/cultural/details?id=96398

### ISSUE THREAD

**Issue by gongyugudao** [lovasoa/dezoomify#527]
Please open a bug report ONLY if the issue you are facing is not specific to a particular site. If you have an issue with a site in particular and would like dezoomify to add support for it, then please open a __new site support__ issue instead.

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. Include an URL to a zoomable image viewer page AND the URL you are giving to dezoomify.

**Expected behavior**

**Screenshots**

**Browser:**

**Additional context**

**Comment by gongyugudao** [comment]
https://digicol.dpm.org.cn/cultural/details?id=96398 希望可以獲取大圖

**Comment by lovasoa** [comment]
Please fill in the actual issue information and write a report in english.
