### ISSUE TITLE
[new site support]

### ISSUE THREAD

**Issue by gongyugudao** [lovasoa/dezoomify#528]
[###](https://digicol.dpm.org.cn/cultural/details?id=96398) Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.

### Example URLs
 - Give the URLs of viewing pages
 - give the URLs of metadata files if you found them

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.

**Comment by lovasoa** [comment]
Please fill the actual issue info.
