### ISSUE TITLE
[new site support]

### ISSUE THREAD

**Issue by gongyugudao** [lovasoa/dezoomify#529]
https://ok.daoing.com/he/dezoomify.html#https://digicol.dpm.org.cn/cultural/details?id=96398 爲何不支持請您解決

**Comment by gongyugudao** [comment]
非常感謝。

**Comment by lovasoa** [comment]
I'm not sure who is behind ok.daoing.com, but the official URL for dezoomify is https://dezoomify.ophir.dev. It is the only one that receives all the updates and fixes when I make changes here.

**Comment by lovasoa** [comment]
In the case of the site you mentioned above, you can use the generic dezoomer. 
Please read: https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial

Generic dezoomer input url:

```
https://shuziwenwu-1259446244.cos.ap-beijing.myqcloud.com/relic/368f325caa0c45979d739bfafbec9852/image-bundle/11/{{X}}_{{Y}}.png
```

https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://shuziwenwu-1259446244.cos.ap-beijing.myqcloud.com/relic/368f325caa0c45979d739bfafbec9852/image-bundle/11/{{X}}_{{Y}}.png

![canvas](https://user-images.githubusercontent.com/552629/108879380-80083b00-7601-11eb-8690-98b5db366fd8.png)
