### ISSUE TITLE
Add support for arch.be

### ISSUE THREAD

**Issue by dries1993** [lovasoa/dezoomify#53]
I want to get the image of this site http://search.arch.be/imageserver/topview.php?FIF=514/514_0549_000/514_0549_000_01097_000/514_0549_000_01097_000_0_0001.jp2

with this tool http://ophir.alwaysdata.net/dezoomify/dezoomify.html

but it returns this:
Uncaught TypeError: Cannot read property 'length' of null (http://ophir.alwaysdata.net/dezoomify/dezoomers/iipimage.js:32)

**Comment by lovasoa** [comment]
Please give all the details concerning your issue.

**Comment by dries1993** [comment]
I want to get the image of this site http://search.arch.be/imageserver/topview.php?FIF=514/514_0549_000/514_0549_000_01097_000/514_0549_000_01097_000_0_0001.jp2

with this tool http://ophir.alwaysdata.net/dezoomify/dezoomify.html

but it returns this:
Uncaught TypeError: Cannot read property 'length' of null (http://ophir.alwaysdata.net/dezoomify/dezoomers/iipimage.js:32)

**Comment by lovasoa** [comment]
This zoomable image format is currently not supported by dezoomify

**Comment by lovasoa** [comment]
I fixed the cryptic error message. You should now see `Invalid IIPImage information file`

**Comment by dries1993** [comment]
Ok. thanks for the help. Do you think it will be supported in the near future? or are there any other tools that could do the job?

**Comment by lovasoa** [comment]
I have never heard of this zoomable image format, and don't think any  tool can dezoomify it.
I encourage this to create your dezoomer, and make a pull request here, I'll merge it. Look at the `dezoomers/` folder in this repo. If you have questions, I'll answer them.

**Comment by dries1993** [comment]
I tought it would be supported because it uses Picturae Topviewer.

**Comment by lovasoa** [comment]
The structure of the tiles and the metafile really doesn't look any similar to the topwiewer we support ([example](https://www.erfgoedleiden.nl/collecties/beeldmateriaal/zoeken-in-beeldmateriaal/weergave/record/layout/default?id=037fc916-5f97-be9a-ee66-5df5d29caa2e)).
It looks like the two viewers were indeed developed by the same company, but they are different.

**Comment by lovasoa** [comment]
I really encourage you to develop a dezoomer. It isn't that complex.

 * You first have to find the structure of the meta-info file (for you, it's here: http://search.arch.be/imageserver/topview.xml.php?FIF=514/514_0549_000/514_0549_000_01097_000/514_0549_000_01097_000_0_0001.jp2&lang=nl&uid=0)
 * Extract needed information from it.
 * Find the structure of the tile urls. For you: http://search.arch.be/imageserver/getpic.php?514/514_0549_000/514_0549_000_01097_000/514_0549_000_01097_000_0_0001.jp2&291

**Comment by dries1993** [comment]
Ok. thank you very much for your help. I will do my best, but time is low for the moment and I'm not that familiar with this kind of stuff.

**Comment by lovasoa** [comment]
It has been almost 4 years, but topviewer is now supported, and the image mentioned above can be downloaded at : 

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://search.arch.be/imageserver/topview.json.php?FIF=514/514_0549_000/514_0549_000_01097_000/514_0549_000_01097_000_0_0001.jp2&uid=0&checkIfTiled=1

![canvas](https://user-images.githubusercontent.com/552629/71837933-e8bbed80-30b7-11ea-86b8-141746fc249e.jpg)
