### ISSUE TITLE
runivers.ru

### ISSUE THREAD

**Issue by HapMap** [lovasoa/dezoomify#530]
Hello everyone,

 I am having issues when trying to download https://runivers.ru/bookreader/gmaps/podratlas/map_61/tile-4-120.png

Dezoomify reports:

```
Uncaught Error: Unable to find a proper dezoomer for:
https://runivers.ru/bookreader/gmaps/podratlas/map_61/tile-4-120.png

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by HapMap** [comment]
Still looking for help dezooming this page: https://new.runivers.ru/maps/podratlas/61/

Thanks for any help.

**Comment by lovasoa** [comment]
Hello !
  You can probably download that with the [custom YAML dezoomer](https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example-for-the-custom-YAML-dezoomer) of dezoomify-rs.

**Comment by lovasoa** [comment]
Your case is covered in the *Tile index in the url* example.
