### ISSUE TITLE
dorotheum.com

### ISSUE THREAD

**Issue by surao101** [lovasoa/dezoomify#532]
Site name: dorotheum.com

It seems to have a zoomer but in base64.

### Example URLs
https://www.dorotheum.com/en/l/6955450/
https://www.dorotheum.com/en/l/6955729/

### Current error message
Oops, we have a problem
An error occured while trying to dezoomify your image. This is probably because dezoomify did not manage to find a zoomable image at the address you gave.

**Comment by lovasoa** [comment]
Hello ! 
  They use [ZIF](https://github.com/lovasoa/ZIF) images. You can download them directly from their website, and open them with any image viewer that supports bigtiff, such as gimp.

https://www.dorotheum.com/fileadmin/zoomify/live/img/38K201124/marc-chagall-6955450.zif

![image](https://user-images.githubusercontent.com/552629/109417094-734d6380-79c2-11eb-8410-4d176472b509.png)
![image](https://user-images.githubusercontent.com/552629/109417106-7e07f880-79c2-11eb-9b34-7c89b878cb2b.png)
![image](https://user-images.githubusercontent.com/552629/109417134-96781300-79c2-11eb-8978-08d61f180773.png)
