### ISSUE TITLE
Feature request: API for dezoomify?

### ISSUE THREAD

**Issue by gilbh** [lovasoa/dezoomify#533]
Greetings, 

Any chances to send a url and receive a PNG back via an API request (or a command-line tool)?

Thanks.

**Comment by lovasoa** [comment]
Running dezoomify as an API would not be free, but if you are ready to finance that, shoot me an email at `contact at ophir dot dev`

If you want a command-line tool, there is [dezoomify-rs](https://dezoomify-rs.ophir.dev/)

**Comment by gilbh** [comment]
With thanks!!

**Comment by gilbh** [comment]
Hi Ophir,

Is dezoomify-rs engine identical to the one in the web interface?
The following works fine:
https://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://images.eap.bl.uk/EAP673/EAP673_1_18/130.jp2/full/90,/0/default.jpg

-- and generates a valid PNG in the browser. But running the same URL using dezoomify-rs:
`dezoomify-rs.exe http://images.eap.bl.uk/EAP673/EAP673_1_18/130.jp2/full/90,/0/default.jpg`
throws the following errors:
```
(utils) c:\Users\Gil>dezoomify-rs.exe http://images.eap.bl.uk/EAP673/EAP673_1_18/130.jp2/full/90,/0/default.jpg
ERROR Dezoomer error: Unable to create the dezoomer: Tried all of the dezoomers, none succeeded. They returned the following errors:

 - custom: The 'custom' dezoomer cannot handle this URI
 - google_arts_and_culture: The 'google_arts_and_culture' dezoomer cannot handle this URI
 - zoomify: The 'zoomify' dezoomer cannot handle this URI
 - generic: The 'generic' dezoomer cannot handle this URI
 - pff: The 'pff' dezoomer cannot handle this URI
 - IIPImage: The 'IIPImage' dezoomer cannot handle this URI
 - nypl: The 'nypl' dezoomer cannot handle this URI
 - iiif: Unable to create the dezoomer: Invalid IIIF info.json file: expected value at line 1 column 1
 - deepzoom: Unable to create the dezoomer: Unable to parse the dzi file: Syntax: 1:1 invalid utf-8: corrupt contents
 - krpano: Unable to create the dezoomer: Unable to parse the krpano xml file: Syntax: 1:1 invalid utf-8: corrupt contents

dezoomify-rs expects a zoomable image meta-information file URL. To find this URL, you can use the dezoomify browser extension, which you can download at
- https://lovasoa.github.io/dezoomify-extension/
If this doesn't help, then your image may be in a format that is not yet supported by dezoomify-rs.
You can ask for a new format to be supported by opening a new issue on https://github.com/lovasoa/dezoomify-rs/issues
```

Or do I have to use the browser/browser-extension every time for the meta-information file URL?

Best
Gil

**Comment by lovasoa** [comment]
> Is dezoomify-rs engine identical to the one in the web interface?
  No it's not. Please read the documentation.

In your case, the URL you want to pass to dezoomify-rs is

```
http://images.eap.bl.uk/EAP673/EAP673_1_18/130.jp2/info.json
```

**Comment by lovasoa** [comment]
![dezoomified](https://user-images.githubusercontent.com/552629/110022190-e7259e00-7d2b-11eb-8495-6bdbfa53f1fc.jpg)

**Comment by gilbh** [comment]
Incredible! Works great!

Thanks Ophir! Toda Raba....
