### ISSUE TITLE
artsandculture.google.com

### ISSUE THREAD

**Issue by nikos-nikou** [lovasoa/dezoomify#537]
Hello everyone,

 I am having issues when trying to download https://artsandculture.google.com/asset/photograph/YgH_rKTSuUK1uA

Dezoomify reports:

```
Uncaught Error: Unable to fetch https://artsandculture.google.com/asset/photograph/YgH_rKTSuUK1uA
The server responded:
fopen(https://artsandculture.google.com/asset/photograph/YgH_rKTSuUK1uA): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests


(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
duplicate of https://github.com/lovasoa/dezoomify/issues/337

**Comment by lovasoa** [comment]
See https://github.com/lovasoa/dezoomify/issues/337#issuecomment-773498488
