### ISSUE TITLE
[new site support] http://mss.bmlonline.it

### ISSUE THREAD

**Issue by m-bazanelli** [lovasoa/dezoomify#538]
Hi everyone.

I can't download from **http://mss.bmlonline.it/s.aspx?Id=AWOML3QCI1A4r7GxMQr-&c=Cornelius%20Celsus#/oro/11**

I tried with no success the following URL, obtained via inspection of the page above:
**http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\Teca\Plutei\Lotto05\.\P002377_73.07\pyr\Plut._73.07_0011.tif/TileGroup0/4-{{X}}-{{Y}}.jpg**

I thank you in advance for any help.

**Comment by lovasoa** [comment]
It works out of the box with the [dezoomify extension](https://lovasoa.github.io/dezoomify-extension/)


![canvas](https://user-images.githubusercontent.com/552629/111999881-b1e7c100-8b1d-11eb-93e4-ee2e93c8bb38.jpg)
