### ISSUE TITLE
[new site support] http://portale.archiviodistatomilano.beniculturali.it

### ISSUE THREAD

**Issue by m-bazanelli** [lovasoa/dezoomify#539]
Hi.

I can't download picture # 00016 from **http://portale.archiviodistatomilano.beniculturali.it/it/viewer/#/main/viewer?idMetadato=12310&type=archive**

I've tried with no success the following URLs, obtained from the page above:

**http://metafad.archiviodistatomilano.beniculturali.it/rest/dam/archivio-di-stato-di-milano/resize/b148b505-a30f-4482-a20b-741bb18d8357/original?h={{X}}&w={{Y}}**

**http://portale.archiviodistatomilano.beniculturali.it/cache/cache_f/cache_fe/ad641bc4ce5d028ad4c739c568086217_files/1/{{X}}_{{Y}}.jpg**

Any suggestions?

**Comment by lovasoa** [comment]
Hello !
  This site already works with the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/).

```
http://portale.archiviodistatomilano.beniculturali.it/cache/cache_9/cache_9a/04946cb68410a534605ee8e7693f975f_files/0/0_0.jpg
```

![canvas](https://user-images.githubusercontent.com/552629/112002836-99c57100-8b20-11eb-87f8-a30da0a465a0.jpg)

**Comment by m-bazanelli** [comment]
Dear Ophir,

I've used the browser extension but it didn't manage to go further the message "Preparing tiles load... (0%)".
![image](https://user-images.githubusercontent.com/78938007/112010008-33901c80-8b27-11eb-8687-177e701ae2a8.png)

What I'm doing wrong?

**Comment by lovasoa** [comment]
Maybe try in another browser ? I cannot replicate your issue.

**Comment by m-bazanelli** [comment]
You're right. I've tried with Firefox instead of Chrome and this time it was ok!
Thank you again

**Comment by Arekkusu1998** [comment]
@m-bazanelli, there's another solution, if no browser loads the page correctly (even if it's a very strange hypothesis). 
Opening the Page Analyzer (**F12**), it can be seen that the file can also be dezoomified using [dezoomify- rs](https://github.com/lovasoa/dezoomify-rs) using this string: http://portale.archiviodistatomilano.beniculturali.it/cache/cache_9/cache_9a/04946cb68410a534605ee8e7693f975f.xml (you can find it searching files with **.xml** or **.json** extensions in "Network" page). 
Copy and paste the string into dezoomify-rs and choose the size level you prefer.

**Comment by m-bazanelli** [comment]
**@Arekkusu1998**, thank you very much for your hint.
By the way, I encountered the same problem on two different pc's when using the dezoomify browser extension for Chrome (but everything was OK using the Firefox extension).
