### ISSUE TITLE
[new site support] Henslowe-Alleyn Digitisation Project

### ISSUE THREAD

**Issue by JackWilton1594** [lovasoa/dezoomify#540]
### Site name and desciption
The Henslowe-Alleyn Digitisation Project
Important primary source materials for the study of theatre in Shakespeare's day.

### Example URLs
https://henslowe-alleyn.org.uk/catalogue/mss-1/article-001/01-recto/
https://henslowe-alleyn.org.uk/images/01-001-01r.jp2/info.json

### Current error message
network error: HTTP status client error (404 Not Found) for url (https://henslowe-alleyn.org.uk/henslowe3%2Fwebroot%2Fimages%2Fjp2%2F01-001-01r.jp2/1024,1024,1024,1024/1024,1024/0/default.jpg).

**Comment by JackWilton1594** [comment]
Error message in dezoomify:
Uncaught Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
http://henslowe-alleyn.org.uk/henslowe3%2Fwebroot%2Fimages%2Fjp2%2F01-001-01r.jp2/3072,6144,1024,958/1024,/0/default.jpg

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:213)

**Comment by lovasoa** [comment]
![image](https://user-images.githubusercontent.com/552629/112450581-d4175400-8d54-11eb-9f74-1183bf129890.png)

**Comment by lovasoa** [comment]
On chrome, the website opens. 

> Check that your internet connection is working and that you can access this url:
http://henslowe-alleyn.org.uk/henslowe3%2Fwebroot%2Fimages%2Fjp2%2F01-001-01r.jp2/3072,6144,1024,958/1024,/0/default.jpg

Well, it's telling you to check that you can access the given URL. If you try to open it, you will see a 404 error. The website is missing a tile, there is nothing dezoomify can do about it.

**Comment by JackWilton1594** [comment]
But the image is displaying in the Zoomify window – how can that be possible if the tile is missing?
https://henslowe-alleyn.org.uk/catalogue/mss-1/article-001/01-recto/

**Comment by lovasoa** [comment]
The viewer probably just shows the lower resolution tiles in place.
In the meantime, since this is an IIIF server, you can get the full image directly from the server

https://henslowe-alleyn.org.uk/images/01-001-01r.jp2/full/full/0/default.jpg

![](https://henslowe-alleyn.org.uk/images/01-001-01r.jp2/full/full/0/default.jpg)

**Comment by lovasoa** [comment]
https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server

**Comment by JackWilton1594** [comment]
Ah perfect. Many thanks :)
