### ISSUE TITLE
[new site support] expositions.bnf.fr

### ISSUE THREAD

**Issue by Apollodore** [lovasoa/dezoomify#542]
### Site name and description
Dear Ophir, Dezoomify supports https://gallica.bnf.fr, but maybe it could be interesting to have dezoomify supporting http://expositions.bnf.fr as well. Thank you for all you do.

### Example URLs
http://expositions.bnf.fr/orsay-gustavedore/grand/dor_260.htm

### Current error message
Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
http://expositions.bnf.fr/orsay-gustavedore/images/5ci_nq/dor_260/TileGroup0/4-11-1.jpg
(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:217)

**Comment by lovasoa** [comment]
Hello,
  I can't reproduce your issue. The image downloads just fine. Dezoomify is suggesting that you check that your internet connection is working and that you can access this url:
http://expositions.bnf.fr/orsay-gustavedore/images/5ci_nq/dor_260/TileGroup0/4-11-1.jpg

Did you do that ?

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/113595660-9a3e2b80-9639-11eb-86ab-eb7b65bc0ea6.png)

**Comment by Apollodore** [comment]
Dear Ophir, yes I checked my internet connection is working and I had no problem to access http://expositions.bnf.fr/orsay-gustavedore/images/5ci_nq/dor_260/TileGroup0/4-11-1.jpg
I don't understand but thank you very much!

**Comment by lovasoa** [comment]
I think your problem is related to chrome [automatically loading image tiles over HTTPS even when explicitly instructed to load them over HTTP](https://www.chromestatus.com/feature/4926989725073408). Google introduced this feature in chrome 86 to supposedly "improve security", but in this case, it just breaks loading images from sites that do not support HTTPS.
The best thing to do is just to use another website, which will load images over HTTP when it is told to do so. For instance, you can use [firefox](https://www.mozilla.org/en-US/firefox/new/)

**Comment by lovasoa** [comment]
Alternatively, you can manually add dezoomify to the list of HTTPS sites authorized to load HTTP content in `chrome://settings/content/insecureContent`

![image](https://user-images.githubusercontent.com/552629/113601565-c9f13180-9641-11eb-93b7-d97aa141124d.png)

**Comment by lovasoa** [comment]
You can also contact the BNF to warn them that their website is insecure and doesn't guarantee the privacy of their users. They should upgrade to HTTPS.

**Comment by Apollodore** [comment]
Thank you Ophir to take the time to investigate. I did use firefox (87.0 64 bits) but maybe there is now the same feature in firefox... Anyway, I added dezoomify to the list of HTTPS sites authorized to load HTTP in chrome as you have shown me, and it now it works fine, thank you very much !

**Comment by lovasoa** [comment]
I added an entry to the FAQ: https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#i-see-an-error-saying-check-that-your-internet-connection-is-working-and-that-you-can-access-this-url-http

**Comment by Apollodore** [comment]
Great, I didn't notice this FAQ, thank you again.
