### ISSUE TITLE
Denver Art Museum

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#543]
Two examples from the Denver Art Museum's website
https://www.denverartmuseum.org/en/object/35.2017
https://www.denverartmuseum.org/en/object/1935.15

I tried pasting those website into the online dezoomifier, but it didn't work. 

I tried using the dezoomifier extension and got the following:
https://s3.amazonaws.com/damcollections/4d68e143_8811/2000/dzi2000_files/0/0_0.jpg
https://s3.amazonaws.com/damcollections/03dadd64_16/2000/dzi2000_files/0/0_0.jpg

These didn't work via the extension

Also, none of the 4 worked via dezoomify-rs (version 2.6.2).

Any help you can offer would be much appreciated!

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/113697184-27818e80-96d3-11eb-9665-6b84b52b8da8.jpg)

I cannot reproduce the issue. Everything works fine for me. Can you give more details ? Browser and version used, exact error message, console logs... Without that, the report is not actionable.

**Comment by Tricesimo** [comment]
Aha! I was a couple of releases behind in my dezoomify-rs. I now have the latest one and I got it to work.

Thanks!
