### ISSUE TITLE
trove.nla.gov.au

### ISSUE THREAD

**Issue by SirRossington** [lovasoa/dezoomify#545]
Hello everyone,

trove.nla.gov.au doesn't seem to be working.  I think the generic dezoomifier would work, except the site's x and y doesn't start at 0,0.  The XML is at https://trove.nla.gov.au/newspaper/image/info/4929819, and you can see the level 7 zoom has colmin at 8 and rowmin at 6.  Is there any way to add an offset to the generic dezoomifier?

thanks!

**Comment by SirRossington** [comment]
Sorry, forgot to add the url of the first tile:

https://trove.nla.gov.au/imageservice/nla.news-page4929819/tile7-8-6

looks like the format is tile{zoom level}-{x}-{y}

**Comment by lovasoa** [comment]
You can do that using [dezoomify-rs](https://dezoomify-rs.ophir.dev/) and its [custom yaml dezoomer](https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example-for-the-custom-YAML-dezoomer)
