### ISSUE TITLE
[new site support] Van Gogh Museum Amsterdam

### ISSUE THREAD

**Issue by Apollodore** [lovasoa/dezoomify#546]
### Site name and desciption
Dear Ophir, it would be great to have dezoomify supporting the website of the Van Gogh Museum Amsterdam. Thank you again for all you do.

### Example URLs
https://www.vangoghmuseum.nl/en/collection/s0518S2010

### Current error message
Error: Unable to load first tile: https://micr.io/i/LYYcO/0,0,1024,1024/1024,/0/default.png

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:217)

**Comment by lovasoa** [comment]
Hello !

We already have a ticket for this site: https://github.com/lovasoa/dezoomify/issues/487

**Comment by lovasoa** [comment]
You can comment on this other issue if you encounter issues with the proposed solution.

**Comment by Apollodore** [comment]
Dear Ophir, Thanks a lot, it worked fine! All the best.
