### ISSUE TITLE
Haltadefinizione

### ISSUE THREAD

**Issue by lakmay** [lovasoa/dezoomify#55]

**Comment by lovasoa** [comment]
You should read our FAQ. I think the "generic" dezoomer does exactly what you want.

**Comment by lakmay** [comment]
Hi again
not working. when I use 
www.haltadefinizione.com/hdimgsrc/12/imgfull/annunciazione_krpano/l4_0{{Y}}_0{{X}}.jpg
the load start at 
http://www.haltadefinizione.com/hdimgsrc/12/imgfull/annunciazione_krpano/l4_00_00.jpg
but the download should begin from
http://www.haltadefinizione.com/hdimgsrc/12/imgfull/annunciazione_krpano/l4_01_01.jpg

**Comment by lakmay** [comment]
into second URL two coordinates {{X}}
ttp://www.haltadefinizione.com/immagini/privati/brera/70/modigliani_kisling.tiles/l4/{{X}}/l4_{{X}}_{{Y}}.jpg
generic  dezoomer do not load the second coordinate {{X}} ,
and coordinates start from "0"
http://www.haltadefinizione.com/immagini/privati/brera/70/modigliani_kisling.tiles/l4/0/l4_{{X}}_0.jpg
when  true tile 
http://www.haltadefinizione.com/immagini/privati/brera/70/modigliani_kisling.tiles/l4/1/l4_1_1.jpg
