### ISSUE TITLE
[new site support] NEB Book monuments

### ISSUE THREAD

**Issue by sunbliss** [lovasoa/dezoomify#551]
### Site name and desciption
NEB Book monuments
https://kp.rusneb.ru/ 
Digitized Manuscripts

### Example URLs
 https://kp.rusneb.ru/item/reader/apostol-1
https://kp.rusneb.ru/attachments/attachment/preview/5df7e7cb79a4ae3e39831bcc-preview.jpg

### Current error message
```
Uncaught Error: Unable to find a proper dezoomer for:
https://kp.rusneb.ru/item/reader/apostol-1

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)
```

**Comment by lovasoa** [comment]
https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://kp.rusneb.ru/tiles/5df7e7cb79a4ae3e39831bcc_files/12/0_6.jpg

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/118248566-b8067800-b4a4-11eb-9871-9abf6a1a20d0.jpg)

**Comment by lovasoa** [comment]
Actually, I'll move this issue to dezoomify-extension, because the browser extension should be able to detect this image and it doesn't. 

It looks only at files ending in `.jpg` and this site has `.jpeg`
