### ISSUE TITLE
boschproject.org

### ISSUE THREAD

**Issue by DimoNline** [lovasoa/dezoomify#552]
### Site name and desciption
http://boschproject.org
Paintings of Bosch

### Example URLs
http://boschproject.org/view.html?layout=four-pane&mode=curtain&pointer=0.349,0.001&r=0.0000,0.0148,1.0000,1.1630&i=49MCPVIS,49IRREFL,49MCPIRP,49XRADGR
http://boschproject.org/dzi/49MCPVIS_files/0/0_0.jpg

### Current error message
Error sometimes drops **Error: Invalid seadragon XML info file: http://boschproject.org/dzi/17MCPVIS.xml**
Not works in Chrome

**Comment by lovasoa** [comment]
https://dezoomify.ophir.dev/dezoomify/dezoomify.html#http://boschproject.org/dzi/49MCPVIS.dzi

**Comment by lovasoa** [comment]
https://dezoomify.ophir.dev/dezoomify/dezoomify.html#http://boschproject.org/dzi/49IRREFL.dzi

**Comment by lovasoa** [comment]
https://dezoomify.ophir.dev/dezoomify/dezoomify.html#http://boschproject.org/dzi/49MCPIRP.dzi

**Comment by lovasoa** [comment]
https://dezoomify.ophir.dev/dezoomify/dezoomify.html#http://boschproject.org/dzi/49XRADGR.dzi

**Comment by DimoNline** [comment]
Also it downloads in lower resolution (10.7k*2k) then its original on the site
![image](https://user-images.githubusercontent.com/19239834/119276100-9aae7800-bc21-11eb-99a7-3045654c21ef.png)

**Comment by lovasoa** [comment]
See https://github.com/lovasoa/dezoomify/wiki/Very-large-images
