### ISSUE TITLE
archief.ntr.nl

### ISSUE THREAD

**Issue by ArnoldR** [lovasoa/dezoomify#553]
Jheronimus Bosch - The Garden of Earthly Delights
https://archief.ntr.nl/tuinderlusten/en.html

Why is this site of particular interest ?

This site presents the amazing "garden of delights" from Jerome Bosch

### Current error message
Uncaught Error: Unable to find a proper dezoomer for:
https://archief.ntr.nl/tuinderlusten/en.html

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)

It seems to use "micrio" format.

Thanks in advance for your help :)

**Comment by lanaloft** [comment]
put this link in dezoomify-rs, and choose your zoomlevel to download:
http://boschproject.org/dzi/00MCPVIS_files/0/0_0.jpg
    Am Dienstag, 18. Mai 2021, 20:21:02 MESZ hat ArnoldR ***@***.***> Folgendes geschrieben:  
 
 


Jheronimus Bosch - The Garden of Earthly Delights
https://archief.ntr.nl/tuinderlusten/en.html

Why is this site of particular interest ?

This site presents the amazing "garden of delights" from Jerome Bosch

Current error message

Uncaught Error: Unable to find a proper dezoomer for:
https://archief.ntr.nl/tuinderlusten/en.html

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)

It seems to use "micrio" format.

Thanks in advance for your help :)

**Comment by ArnoldR** [comment]
Thanks a lot for this link, it works !!
