### ISSUE TITLE
[new site support] bsrdigitalcollections.it

### ISSUE THREAD

**Issue by Benomrans** [lovasoa/dezoomify#554]
Would be so grateful having any help in dezoomifying at the site:
http://www.bsrdigitalcollections.it/

it uses some type of seadragon container, I couldn't figure out.

example:
http://www.bsrdigitalcollections.it/islandora/object/HAKEWILL-DRAWINGS:261

Thank you so much.

**Comment by lovasoa** [comment]
You can get the full image directly from their server without using an external tool, by changing the URL parameters in tile image URLs:

```
http://www.bsrdigitalcollections.it/adore-djatoka/resolver?url_ver=Z39.88-2004&rft_id=http%3A%2F%2Fwww.bsrdigitalcollections.it%2Fislandora%2Fobject%2FHAKEWILL-DRAWINGS%253A261%2Fdatastream%2FJP2%2Fview%3Ftoken%3D66ae54142ce036d9d2ac163633c30f1544aa6901d5b28e2c37d8c817f051448d&svc_id=info%3Alanl-repo%2Fsvc%2FgetRegion&svc_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajpeg2000&svc.region=0%2C0%2C10000%2C10000&svc.level=5
```

![](http://www.bsrdigitalcollections.it/adore-djatoka/resolver?url_ver=Z39.88-2004&rft_id=http%3A%2F%2Fwww.bsrdigitalcollections.it%2Fislandora%2Fobject%2FHAKEWILL-DRAWINGS%253A261%2Fdatastream%2FJP2%2Fview%3Ftoken%3D66ae54142ce036d9d2ac163633c30f1544aa6901d5b28e2c37d8c817f051448d&svc_id=info%3Alanl-repo%2Fsvc%2FgetRegion&svc_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajpeg2000&svc.region=0%2C0%2C10000%2C10000&svc.level=5)

**Comment by Benomrans** [comment]
So grateful, Thank you so much, highly appreciated.
