### ISSUE TITLE
[new site support]https://artmuseum.princeton.edu/ 

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#557]
In spite of the fact that the image of https://artmuseum.princeton.edu/ is downloadable, I still prefer to now how to detect the exact image URL on this site.
Example: https://static.artmuseum.princeton.edu/mirador/?manifest=https://data.artmuseum.princeton.edu/iiif/objects/32455&canvas=https://data.artmuseum.princeton.edu/iiif/objects/32455/canvas/32455-canvas-7537 
Image URL could not be detected by inspect elements neither in Chrome nor Firefox.

**Comment by lovasoa** [comment]
You have the iiif manifest in the url

https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://data.artmuseum.princeton.edu/iiif/objects/32455

**Comment by dancorpse** [comment]
Got it, thanks！
