### ISSUE TITLE
the site nla.gov.au has ceased to be supported

### ISSUE THREAD

**Issue by zastas** [lovasoa/dezoomify#560]
**Describe the bug**
6 hours ago, all the dezoomify on this site worked fine, but now they are gone.

**To Reproduce**
the page address and scaling are the same:
https://nla.gov.au/nla.obj-163356822/view
he, as usual for this site, was inserted into the working line of the dezoomify, but this time the scaling does not work

**Expected behavior**
The image was expected to open at a larger scale, as was done with this very image 6 hours ago

**Screenshots**
![Image 596](https://user-images.githubusercontent.com/68678470/121888043-2e0a3300-cd20-11eb-9f29-fc4b34397fa3.png)

**Browser:**
 - Browsers Chrome, Firefox
 - Version latest

**Comment by lovasoa** [comment]
I cannot reproduce your issue. 
Pasting ` https://nla.gov.au/nla.obj-163356822/view` into dezoomify works.
Maybe the site had problems when you tried ?

**Comment by lovasoa** [comment]
https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://nla.gov.au/nla.obj-163356822/view



![canvas](https://user-images.githubusercontent.com/552629/121889426-8427a800-cd19-11eb-9261-dcc7a4c54939.jpg)

**Comment by zastas** [comment]
checked now again - it doesn't work for me :(

**Comment by lovasoa** [comment]
The problem is probably on your side, then.
You can try to access the URL in the error message from your browser to see what it says.

**Comment by zastas** [comment]
the error message at the bottom of the screenshot - is that it?

**Comment by lovasoa** [comment]
You may be affected by #337. You can try to hard refresh the page, and check if the error message changed.

**Comment by zastas** [comment]
doesn't even work dezoomify-rs 
![Image 598](https://user-images.githubusercontent.com/68678470/121917248-9ddae680-cd3d-11eb-9dd2-e4da33044b38.png)

**Comment by lovasoa** [comment]
The site does not use a standard deepzoom format, but you can still download it in dezoomify-rs with the generic dezoomer:

```
https://nla.gov.au/nla.obj-163356822/dzi?tile=14/{{X}}_{{Y}}.jpg
```

**Comment by zastas** [comment]
Thank you so much!
