### ISSUE TITLE
Thyssen-Bornemiza museum Gigapixel (museothyssen.org)

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#561]
Van Gogh's "Les Vessenots in Auvers"
https://www.museothyssen.org/en/collection/artists/gogh-vincent-van/vessenots-auvers

There is a Gigapixel page for this image as well:
https://www.museothyssen.org/en/conectathyssen/gigathyssen/vessenots-auvers

I can't seem to get them to download using Dezoomify website, and they also don't work using the URL in dezoomify-rs.

Any thoughts as to how to download a gigapixel?

Thanks,

**Comment by lovasoa** [comment]
Hello !
  You can use the [Generic Dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial) with this site : 

```
https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://sc4hvcfl151058502cff46683.s3.amazonaws.com/gigapixel/Thyssen_VincentVanGogh_LesVessenotsEnAuvers/img_Thyssen_VincentvanGogh_LesVessenotsEnAuvers_6_{{X}}_{{Y}}.jpg
```

**Comment by lovasoa** [comment]
I uploaded the image to wikimedia: https://commons.wikimedia.org/wiki/File:Les_Vessenots_%C3%A0_Auvers.jpg

**Comment by Tricesimo** [comment]
Thanks! Question, though... for other paintings from that site, how do I find that link you used? I opened the F12 inspector panel, but I can't find any string that matches that.

**Comment by lovasoa** [comment]
Our wiki page about the generic dezoomer explains it: https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial

**Comment by lovasoa** [comment]
Thank you for opening this : we have identified the zoomable format behind this image and are going to add support for it. We are consolidating all reports about this format to https://github.com/lovasoa/dezoomify/issues/808
