### ISSUE TITLE
Request support with http://sgi.isprambiente.it/geologia100k/Default.aspx

### ISSUE THREAD

**Issue by seiseiseitan** [lovasoa/dezoomify#563]
**Site name and description**

The name and the link of the website is [http://sgi.isprambiente.it/geologia100k/Default.aspx ](http://sgi.isprambiente.it/geologia100k/Default.aspx). Here is possible, going through the map on the right, enter in the chosen geological sheet and relative zoomify image viewer page. After this, pasting different links from different sheets in the dezoomify page, it always start the download of only one geological sheet (ALWAYS and ONLY the number 152 "Sora"). I saw that in all the source pages from different sheets there is always this link in green that contains the lines:

```
&lt;script type="text/javascript" src="ZoomifyImageViewerFree-min.js"&gt;&lt;/script&gt;
--
&nbsp; | &lt;script type="text/javascript"&gt; Z.showImage("foglio", "fogli/cgis152"); &lt;/script&gt;
&nbsp; | --&gt;
```

Maybe to protect the other from sites like dezoomify. I need the help of download any sheet i need, and not only the number 152 "Sora".

For me and other italian geologist, this site is of particular interest because during the period of the pandemic there was not possibility to go in the library and physically view the geological maps in question.

**Example URLs**
URL - [http://sgi.isprambiente.it/geologia100k/mostra_foglio.aspx?numero_foglio=5(5A)](http://sgi.isprambiente.it/geologia100k/mostra_foglio.aspx?numero_foglio=5(5A))
Metadata URL - [view-source:http://sgi.isprambiente.it/geologia100k/mostra_foglio.aspx?numero_foglio=5(5A)](view-source:http://sgi.isprambiente.it/geologia100k/mostra_foglio.aspx?numero_foglio=5(5A))

**Current error message**

![0](https://user-images.githubusercontent.com/86183847/122667657-3ba63980-d1b4-11eb-9479-9d82b7df16a4.png)
![1](https://user-images.githubusercontent.com/86183847/122667663-3f39c080-d1b4-11eb-9ade-bbb2d2db7958.png)
![2](https://user-images.githubusercontent.com/86183847/122667666-419c1a80-d1b4-11eb-93e2-bd5173ddb34d.png)
![2 5](https://user-images.githubusercontent.com/86183847/122667669-44970b00-d1b4-11eb-893f-e054c529f28b.png)
![3](https://user-images.githubusercontent.com/86183847/122667674-4791fb80-d1b4-11eb-8312-6fbc3bdde494.png)
![4](https://user-images.githubusercontent.com/86183847/122667676-49f45580-d1b4-11eb-97d9-91f6637bf559.png)

**Comment by lovasoa** [comment]
Hello !
  This site already works with the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/).
  Just activate the extension and navigate to any map, and the extension will point you to the URL to use in dezoomify.

**Comment by seiseiseitan** [comment]
Thank you so much @lovasoa
