### ISSUE TITLE
zoom.rcahms.gov.uk

### ISSUE THREAD

**Issue by laird18** [lovasoa/dezoomify#575]
Hello everyone,

 I am having issues when trying to download https://zoom.rcahms.gov.uk/iipsrv?zoomify=live/public/SC0146/SC01469335.ptif/ImageProperties.xml

Dezoomify reports:

```
Uncaught Error: Invalid XML:
https://zoom.rcahms.gov.uk/iipsrv?zoomify=live/public/SC0146/SC01469335.ptif/ImageProperties.xml

(https://dezoomify.ophir.dev/zoommanager.js:217)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
Hello !
  This site seems to be protected. See our wiki page about how to download images from protected pages: https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages


![image](https://user-images.githubusercontent.com/552629/131985968-16b0a8bd-d4c7-4181-8c62-087ca206b0c4.png)

**Comment by laird18** [comment]
Thanks for your help!

Unfortunately when attempting to enter the command (ZoomManager.proxy_tiles
= "proxy.php";) into the browser console in Firefox 91.0.2 and Chrome
92.0.4515.159 on Ubuntu I get the error "Uncaught ReferenceError: ZoomManager
is not defined".

Do you have any advice?
