### ISSUE TITLE
objdigital.bn.br

### ISSUE THREAD

**Issue by geomanta** [lovasoa/dezoomify#579]
Hello everyone,

 I am having issues when trying to download http://objdigital.bn.br/objdigital2/acervo_digital/div_cartografia/cart1030061/cart1030061.html

When choose Seadragon, it tries, but tiles just doesn't load.

Thanks!

**Comment by lovasoa** [comment]
Chrome is trying to fetch the tiles in https. See: https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#i-see-an-error-saying-check-that-your-internet-connection-is-working-and-that-you-can-access-this-url-http

**Comment by MOOPellegrini** [comment]
> Hello ! This site already works with the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/).
> 
> ```
> http://objdigital.bn.br/objdigital2/acervo_digital/div_cartografia/cart1030061/GeneratedImages/dzc_output_files/0/0_0.jpg
> ```
> 
> https://dezoomify.ophir.dev/#http://objdigital.bn.br/objdigital2/acervo_digital/div_cartografia/cart1030061/GeneratedImages/dzc_output_files/0/0_0.jpg

I just tried using it with another images from the same website (https://objdigital.bn.br/acervo_digital/div_manuscritos/mss1198652/mss1198652_095.html) and was unable to get it to work. Can you, please, help?
