### ISSUE TITLE
hi! for some reason the dezoomify wont work for me on this link

### ISSUE THREAD

**Issue by jonkarni** [lovasoa/dezoomify#58]
Hi! I tried to use Dezoomify on this link, but for some reason, it won't work...

http://digital.bodleian.ox.ac.uk/inquire/viewer.dzi?DeepZoom=b68f943a-ca46-4329-bd8f-b20f684812ed.jp2

I tried other pages, and it seems that there is a problem with this one only..
can you help me?
Thanks,
JonKarni

**Comment by jonkarni** [comment]
I was able to download the image by changing the url to this:
http://digital.bodleian.ox.ac.uk/inquire/viewer.dzi?DeepZoom=b68f943a-ca46-4329-bd8f-b20f684812ed.
the truth is, I don't know why it worked..

**Comment by gregg128** [comment]
Hi,
I was able to download the whole page by adding .dzi at the end of the URL.
Plz try this solution.

**Comment by gregg128** [comment]
http://digital.bodleian.ox.ac.uk/inquire/viewer.dzi?DeepZoom=b68f943a-ca46-4329-bd8f-b20f684812ed.dzi
