### ISSUE TITLE
[new site support] Departemental archives (France) archives.allier.fr

### ISSUE THREAD

**Issue by Lapienichehaut** [lovasoa/dezoomify#584]
### Site name and desciption
Archives Départementales de l'Allier (France)

### Example URLs
https://archives.allier.fr/ark:84133/1eba34722fdf636eb3390050568b525d.fiche=arko_fiche_5fb3c5f24a552.moteur=arko_default_5fb3df021fad5

### Current error message
Oops, we have a problem

**Comment by Lapienichehaut** [comment]
Super, merci beaucoup !
Une simple question de débutant : je la tape où la "ligne de commande" ?

**Comment by lovasoa** [comment]
La ligne est une commande bash. Sur MacOS, vous pouvez juste ouvrir l'application Terminal. Sur Windows, vous pouvez installer WSL : https://itsfoss.com/install-bash-on-windows/
