### ISSUE TITLE
[new site support]

### ISSUE THREAD

**Issue by maze61** [lovasoa/dezoomify#586]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?
Austrian National Library: https://onb.digital/
Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.
Austrian National Library has a lot of beautiful images.
### Example URLs
 - Give the URLs of viewing pages
 https://digital.onb.ac.at/rep/osd/?11746980
 - give the URLs of metadata files if you found them

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.
tried automatic and also seadragon mode, but didn't work
Uncaught Error: Unable to find a proper dezoomer for:
https://digital.onb.ac.at/rep/osd/?11746980

Thank you!!!

**Comment by JeovinL** [comment]
Hello, I think I found a solution, what I did is open the developer tool, go in Network section, press Ctrl+R, select the default.png, copy the Request Url of the image and paste in dezoomify.

![Capture](https://user-images.githubusercontent.com/38764196/141363519-b3c7f02b-33b1-45e9-acf4-9e7db0340c50.PNG)

![Capture2](https://user-images.githubusercontent.com/38764196/141363655-eb939f48-c858-41e9-9055-cc69ed66852c.PNG)


not sure if that help

**Comment by maze61** [comment]
Hello JeovinL,

thank you so much, works perfectly!!! I also learned a lot, newer looked at the Network section so far.

Being really happy now and can continue my historical research (with lot more visual details).
