### ISSUE TITLE
https://collections.st-andrews.ac.uk

### ISSUE THREAD

**Issue by a01020304** [lovasoa/dezoomify#587]
Cannot get dezommify to work with this site, am unable to download or recognise anything
https://collections.st-andrews.ac.uk/series/jack-collection---castle-and-church-conservation-sequence/389519

**Comment by lovasoa** [comment]
Hello !
  This site already works with the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/).

```
https://collections.st-andrews.ac.uk/iiif/2/3711~3711/info.json
```
