### ISSUE TITLE
www.diamm.ac.uk

### ISSUE THREAD

**Issue by luysdelmila** [lovasoa/dezoomify#588]
Hello everyone,

 I am having issues when trying to download https://www.diamm.ac.uk/images/27645/info.json

Dezoomify reports:

```
Error: Invalid JSON:
https://www.diamm.ac.uk/images/27645/info.json

(https://dezoomify.ophir.dev/zoommanager.js:217)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
![image](https://user-images.githubusercontent.com/552629/143555400-10d437b6-1182-433e-a6f3-202aa085479d.png)

Your URL leads to a 404 page.

**Comment by lovasoa** [comment]
https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages
