### ISSUE TITLE
[new site support] https://dnnt.mzk.cz

### ISSUE THREAD

**Issue by lludvik** [lovasoa/dezoomify#589]
### Site name and desciption
https://dnnt.mzk.cz Digital Library

### Example URLs
dezoomify detect url https://dnnt.mzk.cz/search/iiif/uuid:270d5cba-eed2-485c-bd73-cd8189879562/info.json
need replace with https://dnnt.mzk.cz/search/img?pid=uuid:270d5cba-eed2-485c-bd73-cd8189879562&stream=IMG_FULL

Could you help me where to fix the source?

**Comment by lovasoa** [comment]
It's the website's iiif manifest that is incorrect:

![image](https://user-images.githubusercontent.com/552629/143724052-c2135ce0-6145-487f-8635-624c6d3be0ef.png)


it contains an invalid url. We are not going to add and maintain an exception to the iiif dezoomer for that site, but you can always download the manifest, fix it locally, and download the resulting image with dezoomify-rs. 

And if that particular site offers a way to download the image directly from the website, then that is even better, and you do not need to use an external tool at all.
