### ISSUE TITLE
can you help me to download pics from this site?

### ISSUE THREAD

**Issue by jonkarni** [lovasoa/dezoomify#59]
can you help me to download pics from this site?
http://gallica.bnf.fr/ark:/12148/btv1b10720903z/f5.item.r=H%C3%A9breu.langEN.zoom

thanks
JonKarni

**Comment by lovasoa** [comment]
If I remember well, you don't need dezoomify for this. There is a Wikimedia help page on how to download gallica images 

17 июня 2016 г. 16:23:14 GMT+02:00, jonkarni <notifications@github.com> пишет:

**Comment by jonkarni** [comment]
Yes, You remember well.. :-)
THANKSS!
