### ISSUE TITLE
[new site support] Nationaal Archief (Dutch National Archive)

### ISSUE THREAD

**Issue by Historyluvr** [lovasoa/dezoomify#591]
### Site name and desciption: https://www.nationaalarchief.nl/

This is a huge repository--millions of images--of historical images and maps covering countless topics.

### Example URL: https://www.nationaalarchief.nl/onderzoeken/kaartencollectie/detail?limitstart=8 
Link to individual tile: https://images.memorix.nl/naa/getpic/5b37e4e1-5167-3b62-8419-196e4eb331e3/10.jpg 

### Error message: I haven't been able to find a zoomable image. The browser extension is also not able to identify a zoomable image. 

I would really appreciate your help. Thank you!

**Comment by Benomrans** [comment]
Hello,
You might take the json url at the network XHR, At Your map it has this url :
https://images.memorix.nl/naa/topviewjson/beeldbank/5b37e4e1-5167-3b62-8419-196e4eb331e3?checkIfTiled=1
and pass it to dezoomify.
Happy new year to all history lovers.

**Comment by Historyluvr** [comment]
Thank you very much!
