### ISSUE TITLE
New site support: artsy.net

### ISSUE THREAD

**Issue by jhoward1045** [lovasoa/dezoomify#592]
https://www.artsy.net/artwork/victor-castillo-you-can-not-get-enough
I've tried posting the url for a tile into the generic dezoomer, and I get an error like this.
![downloadncfgytdxrcfbguhijnmohnbguftvycr](https://user-images.githubusercontent.com/41507324/146637890-654b6356-fdf2-4181-981a-d6a92dfef04a.png)

**Comment by lovasoa** [comment]
There is already a feature request here about that site.

**Comment by jhoward1045** [comment]
I don't understand...
