### ISSUE TITLE
aix.arkotheque.fr

### ISSUE THREAD

**Issue by matriim** [lovasoa/dezoomify#594]
Hello everyone,

 I am having issues when trying to download http://aix.arkotheque.fr/ark:/77636/s0055f2a955cda50/55f2a9661acff

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
http://aix.arkotheque.fr/ark:/77636/s0055f2a955cda50/55f2a9661acff

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)

**Comment by lovasoa** [comment]
It looks like you don't need dezoomify with this website.

You can download the full images directly from their server, you just have to find the URL in your browser's network inspector.

http://aix.arkotheque.fr/arkotheque/visionneuse/img_prot.php?i=129e1dad53.jpg&dt=1640079041710

![](http://aix.arkotheque.fr/arkotheque/visionneuse/img_prot.php?i=129e1dad53.jpg&dt=1640079041710)
