### ISSUE TITLE
www.boijmans.nl

### ISSUE THREAD

**Issue by gp270661** [lovasoa/dezoomify#596]
Hello everyone,

 I am having issues when trying to download https://www.boijmans.nl/en/collection/artworks/1297/village-scene-feeding-the-hungry

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
https://www.boijmans.nl/en/collection/artworks/1297/village-scene-feeding-the-hungry

(https://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
Hello, and thanks for getting in touch !

  It looks like this website doesn't use a tiled image system. The high resolution image can be downloaded directly from their website, without having to use any external tool. You can find the URL of the high resolution image directly from you browser in its web inspector's network panel.

https://storage.boijmans.nl/collection/tmsfotook1175-ok/large-6cc77f1dccb9617897e5ffad862a1815d7975fa1.jpg

![](https://storage.boijmans.nl/collection/tmsfotook1175-ok/large-6cc77f1dccb9617897e5ffad862a1815d7975fa1.jpg)
