### ISSUE TITLE
Tiles not loading/error message

### ISSUE THREAD

**Issue by RedArkady** [lovasoa/dezoomify#61]
I'm trying to download the map image from here: http://www.bl.uk/magnificentmaps/map4.html

Dezoomify goes through the motions of loading the tiles, but no tiles appear. Once it hits 100% the following error message appears:

Error !

Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided. (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:115)

Any ideas?

**Comment by RedArkady** [comment]
(I'm using Chrome, if that helps)

**Comment by RedArkady** [comment]
If I try it in Internet Explorer it works better, but still only captures the top left 1/5th or so of the image.

**Comment by lovasoa** [comment]
Looks like there are two problems here. For the progress bar working while the image doesn't display, it must be that the image it huge and the browser refuses to allocate enough memory for it. Have a look at https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#dezoomify-shows-a-progress-bar-but-my-image-appears-to-be-completely-blank

**Comment by RedArkady** [comment]
Thanks, but I'm not sure it's that. I'm not using Firefox. Does it work for you, using the link I posted above?

**Comment by lovasoa** [comment]
I think it may still be that. Chrome refuses to allocate big canvases too. I will investigate this when I have access to a computer, I'm currently on holidays.

**Comment by RedArkady** [comment]
Much obliged

**Comment by RedArkady** [comment]
Hi Lovaosa, are you still holidaying? I'd love to crack this problem soon.

**Comment by lovasoa** [comment]
Yes, I'm still on holidays. I'll have a look on all open issues as I come back.

**Comment by lovasoa** [comment]
I just checked, this is indeed the problem I mentioned. You can use the workaround mentioned in our FAQ. https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#dezoomify-shows-a-progress-bar-but-my-image-appears-to-be-completely-blank
