### ISSUE TITLE
Error appears for website:http://cbj.jhi.pl/

### ISSUE THREAD

**Issue by Language-Lover** [lovasoa/dezoomify#62]
I would like to download images from this website: http://cbj.jhi.pl, but when I try to an error message appears. Could this please be resolved. Test url:http://cbj.jhi.pl/documents/51268/6/
Thank you very much.

**Comment by dancorpse** [comment]
This site is work for me, maybe you have to find out the exact image path from inspecting elements.
In chrome, right click - inspect, choose resources, click frame folder, then cbj.jhi.pl/ folder, click images, you'll see the url of the image tiles. one for example: http://148.81.197.33:8080/ws/resource/image/51268/0?DeepZoom=51234.tif_files/5/0_0.jpg, delete the wording after .tif and add ".dzi", become http://148.81.197.33:8080/ws/resource/image/51268/0?DeepZoom=51234.tif.dzi, the image will be loading in dezoomify.

**Comment by Language-Lover** [comment]
Thank you very much dancorpse. Your suggestion worked very well. I appreciate it greatly.

**Comment by dancorpse** [comment]
You're welcome!

**Comment by Language-Lover** [comment]
I'm sorry to bother you, but since you're obviously very knowledgeable about such things I was wondering if you know how to download images from this website too: http://www.kb.dk/
In particular, I'm looking to download the individual images that can be viewed (by clicking an arrow) when you click on the image on this page: http://www.kb.dk/manus/judsam/2010/maj/jsmss/object61024/en/
Thank you again.

**Comment by dancorpse** [comment]
Also by inspecting elements, find out http://kb-images.kb.dk/online_master_arkiv/non-archival/Manus/JUDSAM/2011/april/MT9/MT9_0076/full/full/0/native.jpg, this is page 76, you can get the rest pages by changing 0076 to 0075, 0074, 0073... and so on, till 0001.
But it seems not as big as click the image zoom to the maximum size, hmm, I don't know why, it's out of my knowledge, the biggest images I can get is 1480px X 2000px

**Comment by Language-Lover** [comment]
Wow. Thank you so much. I don't even need to go through the process of dezoomifying it from this site. One less step.
And don't worry, the maximum size is fine for me.
I appreciate all you guidance, dancorpse, and I thank you once again.

**Comment by dancorpse** [comment]
My pleasure. 
It seems dezoomify does not work for this site.

**Comment by Language-Lover** [comment]
Interesting. I wonder why. But I guess it doesn't need to since your method works fine.

**Comment by lovasoa** [comment]
For kb.dk, they use IIIF. The procedure to download full-size images is on our wiki: https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server

**Comment by lovasoa** [comment]
Also, next time, please open one issue per problem. Do not reuse old issues.
