### ISSUE TITLE
Dezoomify doesn't recognize University of Pittsburg website

### ISSUE THREAD

**Issue by rbettoni** [lovasoa/dezoomify#625]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?
https://digital.library.pitt.edu/

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.
This is an important university site with tons of images and works of art

### Example URLs
[islandora/object/pitt%3Awmlp0065/viewer](https://digital.library.pitt.edu/islandora/object/pitt%3Awmlp0065/viewer)

### Current error message
Actually there is no error message, just that Dezoomify doesn't recognize the link, I've tried via Firefox, Chrome and Edge. I also couldn't find the links even following alternative tutorial

**Comment by notewordly** [comment]
You can download the full size image by changing the url. Not sure if it works for every image, but does for your example.

for: [islandora/object/pitt%3**Awmlp0065**/viewer](https://digital.library.pitt.edu/islandora/object/pitt%3Awmlp0065/viewer)

[https://digital.library.pitt.edu/adore-djatoka/resolver?url_ver=Z39.88-2004&rft_id=http://digital.library.pitt.edu/islandora/object/pitt%3**Awmlp0065**/datastream/JP2/view?token=&svc_id=info:lanl-repo/svc/getRegion&svc_val_fmt=info:ofi/fmt:kev:mtx:jpeg2000](https://digital.library.pitt.edu/adore-djatoka/resolver?url_ver=Z39.88-2004&rft_id=http://digital.library.pitt.edu/islandora/object/pitt%3Awmlp0065/datastream/JP2/view?token=&svc_id=info:lanl-repo/svc/getRegion&svc_val_fmt=info:ofi/fmt:kev:mtx:jpeg2000)

**Comment by rbettoni** [comment]
thank you very much

**Comment by spkrn** [comment]
Hi ! I think it's not possible to use this trick from May 2022. Anyone has an idea to have HD images of University of Pittsburg website 
Thanks
