### ISSUE TITLE
[bug] type-error 

### ISSUE THREAD

**Issue by obama** [lovasoa/dezoomify#627]
Please open a bug report ONLY if the issue you are facing is not specific to a particular site. If you have an issue with a site in particular and would like dezoomify to add support for it, then please open a __new site support__ issue instead.

**Describe the bug**
TypeError: response.match is not a function

(https://dezoomify.ophir.dev/zoommanager.js:432)

**To Reproduce**
try to dezoom https://www.digitale-bibliothek-mv.de/viewer/image/PPNHST_Po2_28/4/LOG_0004/

**Expected behavior**
workins

**Screenshots**

**Browser:**
independant of browser

**Additional context**
none

**Comment by lovasoa** [comment]
incomplete report
