### ISSUE TITLE
Some undownloadable images at Getty Center

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#63]
Getty center usually provide download for UHQ images. But some are not. For instance, this one: http://www.getty.edu/art/collection/objects/698/nicolas-poussin-the-holy-family-french-about-1651/?dz=0.3726,0.1594,18.87, and dezoomify does not work with this image. Is this of deepzoom protocol? What is the correct image path, I could not find it out from inspecting elements.
Thanks.

**Comment by lovasoa** [comment]
Yes, they use deepzoom. Use the following url: `http://www.getty.edu/museum/media/images/web/zoom/00081501/00081501.dzi`.

You can reconstitute this URL from the URL of tiles.
