### ISSUE TITLE
Drawing from Museu Nacional d'Art de Catalunya (Openseadragon 2.4.2)

### ISSUE THREAD

**Issue by juandelpino** [lovasoa/dezoomify#632]
I can not download a draw from Museu Nacional d'Art de Catalunya:

https://www.museunacional.cat/es/colleccio/retrato-de-pablo-picasso/ramon-casas/027264-d

This is the zoomable link:

https://sc26c7b0z32465y9232634112bda93d66.s3.amazonaws.com/web/index.html?js=26w4871135j64224887828910428182/a26w354w46655v2400659987384e68e_es.json&ua=UA-128970336-5

The JSON file seems to have only information about the portrait:

https://sc26c7b0z32465y9232634112bda93d66.s3.amazonaws.com/web/26w4871135j64224887828910428182/a26w354w46655v2400659987384e68e_es.json

Many thanks.

**Comment by Benomrans** [comment]
Hello, 
Have tried this and worked for me :
Zoom in to the max level, then obtain the url of last set of tiles. For this image the url is :
https://sc26c7b0z32465y9232634112bda93d66.s3.amazonaws.com/gigapixel/26gcd47cfedfce746fd746098555435089c5f/26gcd47cfedfce746fd746098555435089c5f_4_6_6.jpg
then change the last parameters to :
https://sc26c7b0z32465y9232634112bda93d66.s3.amazonaws.com/gigapixel/26gcd47cfedfce746fd746098555435089c5f/26gcd47cfedfce746fd746098555435089c5f_4_{{X}}_{{Y}}.jpg
then pass it to dezoomify generic or dezoomify-rs.
Good luck.

**Comment by juandelpino** [comment]
Terrific! It works like a charm!

Thank you for your answer, Benomrans.

The best,
Juan
