### ISSUE TITLE
can not download images from https://artsandculture.google.com/

### ISSUE THREAD

**Issue by wdc12977** [lovasoa/dezoomify#638]
Please open a bug report ONLY if the issue you are facing is not specific to a particular site. If you have an issue with a site in particular and would like dezoomify to add support for it, then please open a __new site support__ issue instead.

**Describe the bug**
can not download images from https://artsandculture.google.com/

**To Reproduce**
https://artsandculture.google.com/asset/the-water-lily-pond-claude-monet/nQExbyttj8z58A
https://artsandculture.google.com/asset/self-portrait/9gFw_1Vou2CkwQ

**Expected behavior**
Download images successfully

**Screenshots**
![error1](https://user-images.githubusercontent.com/36949463/179133784-c3951133-8e61-4adc-95b1-925f2711bc8e.png)
![error2](https://user-images.githubusercontent.com/36949463/179133807-48c151be-d3e1-4f7e-bcf8-96d8e7b2a7ea.png)

**Browser:**
 - error1 for Browser chrome
 - error2 for Windows client
 - Version 

**Additional context**

**Comment by lovasoa** [comment]
This is the same issue as https://github.com/lovasoa/dezoomify-rs/issues/178

Google changed something on their site and the code needs to be adjusted

**Comment by lovasoa** [comment]
This should be fixed completely. Do not hesitate to open a new issue if you encounter an image that does not work :)

**Comment by lovasoa** [comment]
If you want to contribute to dezoomify but do not know how to code, you can sponsor the work on https://github.com/sponsors/lovasoa
