### ISSUE TITLE
Art Gallery of Ontario[new site support]

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#640]
I got some help with downloading images from the AGO website back in 2018, but I'm stuck on this one:

http://imagelicensing.ago.ca/objects/22693/passengers?ctx=465ad273a878d4f8f6500e136719ab276412ff0e&idx=0

As before, I can't get it to work with the dezoomify website, dezoomify extension, or dezoomify-rs. I read the instructions on how to download from IIIF, but I can't seem to make it work. Can you help me with this one?

**Comment by lovasoa** [comment]
Related to: https://github.com/lovasoa/dezoomify/issues/248

These are still IIIF images, you can follow these instructions : https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server

In your case, this gives the following result:

```
http://imagelicensing.ago.ca/internal/media/zoomdispatcher/111372/full/full/0/default.jpg
```

![](http://imagelicensing.ago.ca/internal/media/zoomdispatcher/111372/0,0,25600,25600/9999,/0/default.jpg)

**Comment by Tricesimo** [comment]
Thanks. I got this to work for a number of images, but some don't seem to work. Maybe you can help me with another?

I tried the same trick on this one:
http://imagelicensing.ago.ca/objects/45197/la-demoiselle-de-magasin?ctx=a40690d2f3906304eda155360868bb719fb64117&idx=23

Using the same logic as before, I tried this:
http://imagelicensing.ago.ca/internal/media/zoomdispatcher/133668/full/full/0/default.jpg

But, I get this error:
Image transformation failed
Transformation of image "ago.45197.jpeg" failed: Transformation of file "ago.45197.jpeg" failed

**Comment by lovasoa** [comment]
In that case you can use large numerical image dimension values instead of `full` : 

```
http://imagelicensing.ago.ca/internal/media/zoomdispatcher/133668/0,0,9999,9999/9999,/0/default.jpg
```

[![la demoiselle de magasin](http://imagelicensing.ago.ca/internal/media/zoomdispatcher/133668/0,0,9999,9999/9999,/0/default.jpg)](http://imagelicensing.ago.ca/internal/media/zoomdispatcher/133668/0,0,9999,9999/9999,/0/default.jpg)

**Comment by Tricesimo** [comment]
Wonderful! Thank you for your help
