### ISSUE TITLE
[new site support] Terra American Art

### ISSUE THREAD

**Issue by iMoons** [lovasoa/dezoomify#643]
### Site name and desciption

Terra American Art (http://collection.terraamericanart.org)
Unique collection of early Americana and watercolors, many of which are unavailable on the broader internet

### Example URLs

http://collection.terraamericanart.org/objects/522/the-chemist
http://collection.terraamericanart.org/internal/media/zoomdispatcher/5095/info.json

According to the web extension, this is an IIIF site but throws an error (see below) when attempting to run dezoomify. Unsure if this site is simply unsupported, if the info.json file is set up in a nonstandard way, or if this is a genuine bug.

### Current error message

> Uncaught Error: Invalid JSON:
> http://collection.terraamericanart.org/internal/media/zoomdispatcher/5095/info.json
> 
> (https://dezoomify.ophir.dev/zoommanager.js:217)

I have tried both the dezoomify extension (chrome + firefox) and dezoomify-rs. I have had some experience manually setting {{x}} and {{y}} values in dezoomify-rs before, but I used the inspector to look at the tileset's naming convention and could not figure out how to work with it. Thank you for investigating!

**Comment by lovasoa** [comment]
This is the same as  https://github.com/lovasoa/dezoomify/issues/640 .
See https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server

```
http://collection.terraamericanart.org/internal/media/zoomdispatcher/5095/full/full/0/default.jpg
```

![](http://collection.terraamericanart.org/internal/media/zoomdispatcher/5095/full/full/0/default.jpg)
