### ISSUE TITLE
openseadragon / mediateca.inah.gob.mx

### ISSUE THREAD

**Issue by jabberwockxeno** [lovasoa/dezoomify#644]
I'm trying to download images from the some pages on the aformentioned website (for example: http://mediateca.inah.gob.mx/repositorio/islandora/object/objetohistorico:2754) , which seem to use a service called Openseadragon to load zoomable panoramas.

The dezoomify website has an error when trying to do so, and the extension isn't finding anything.

**Comment by jabberwockxeno** [comment]
To add, Openseadragon is itself an open source tool on github: https://github.com/openseadragon so in theory I imagine since it is open source it should be easier to reverse engineer whatever it is doing to rip content?

**Comment by lovasoa** [comment]
The format seems non-standard, but allows you to get the full image directly from their server

```
http://mediateca.inah.gob.mx/adore-djatoka/resolver?url_ver=Z39.88-2004&rft_id=http%3A%2F%2Fmediateca.inah.gob.mx%2Frepositorio%2Fislandora%2Fobject%2Fobjetohistorico%253A2754%2Fdatastream%2FJP2%2Fview%3Ftoken%3D0154deca0dc182edd731737232d02b2dc94eb7e72ab1e47e91d979b29996e53d&svc_id=info%3Alanl-repo%2Fsvc%2FgetRegion&svc_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajpeg2000&svc.region=0%2C0%2C9999%2C9999&svc.level=5
```

![](http://mediateca.inah.gob.mx/adore-djatoka/resolver?url_ver=Z39.88-2004&rft_id=http%3A%2F%2Fmediateca.inah.gob.mx%2Frepositorio%2Fislandora%2Fobject%2Fobjetohistorico%253A2754%2Fdatastream%2FJP2%2Fview%3Ftoken%3D0154deca0dc182edd731737232d02b2dc94eb7e72ab1e47e91d979b29996e53d&svc_id=info%3Alanl-repo%2Fsvc%2FgetRegion&svc_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajpeg2000&svc.region=0%2C0%2C9999%2C9999&svc.level=5)

**Comment by lovasoa** [comment]
You can change the svc.region parameter from individual tile URLs

![image](https://user-images.githubusercontent.com/552629/184644179-5a3513f7-8fdb-442f-bab0-c091c430986f.png)
