### ISSUE TITLE
collections.chateauversailles.fr

### ISSUE THREAD

**Issue by altman65** [lovasoa/dezoomify#650]
Hello everyone,

 I am having issues when trying to download http://collections.chateauversailles.fr/imageproxy.aspx?server=127.0.0.1&port=17506&filename=objectimages/MV%207001_001_files/0/0_0.jpg

Dezoomify reports:

```
Uncaught Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
http://collections.chateauversailles.fr/imageproxy.aspx?server=127.0.0.1&port=17506&filename=objectimages/MV%207001_001_files/13/1_0.jpg

(https://dezoomify.ophir.dev/zoommanager.js:217)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
It works fine for me: 
https://dezoomify.ophir.dev/#http://collections.chateauversailles.fr/imageproxy.aspx?server=127.0.0.1&port=17506&filename=objectimages/MV%207001_001_files/0/0_0.jpg

![canvas](https://user-images.githubusercontent.com/552629/185949417-54854751-f3c9-4b9b-8433-b8c56c27ff8e.jpg)

**Comment by altman65** [comment]
For me it worked with dezoomify-rs but not with the online version…

Thanks,

 

De : Ophir LOJKINE ***@***.***> 
Envoyé : lundi 22 août 2022 16:43
À : lovasoa/dezoomify ***@***.***>
Cc : altman65 ***@***.***>; Author ***@***.***>
Objet : Re: [lovasoa/dezoomify] collections.chateauversailles.fr (Issue #650)

 

It works fine for me:
https://dezoomify.ophir.dev/#http://collections.chateauversailles.fr/imageproxy.aspx?server=127.0.0.1 <https://dezoomify.ophir.dev/#http://collections.chateauversailles.fr/imageproxy.aspx?server=127.0.0.1&port=17506&filename=objectimages/MV%207001_001_files/0/0_0.jpg> &port=17506&filename=objectimages/MV%207001_001_files/0/0_0.jpg

 <https://user-images.githubusercontent.com/552629/185949417-54854751-f3c9-4b9b-8433-b8c56c27ff8e.jpg>
