### ISSUE TITLE
problem for krpano images

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#66]
http://www.mba-lyon.fr/static/gigapixels/poussinchione.html this one is using krpano, dezoomify loading but with all white screen, right click save image and nothing happened(maybe bcs of the size of the image, this is a gigapixel image).
Thanks.

**Comment by lovasoa** [comment]
This is a known browser bug with very large images. The only way to work around it is to use the node application. You will find more info on our wiki: https://github.com/lovasoa/dezoomify/wiki/Very-large-images

**Comment by lovasoa** [comment]
The description of your problem is in the FAQ: https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#dezoomify-shows-a-progress-bar-but-my-image-appears-to-be-completely-blank

**Comment by dancorpse** [comment]
Thanks for the guidance,

**Comment by dancorpse** [comment]
I retry this today, but image fail to load with error message , am I anything wrong?
