### ISSUE TITLE
digital.ncdcr.gov

### ISSUE THREAD

**Issue by atk3289** [lovasoa/dezoomify#660]
Hello everyone,

 I am having issues when trying to download https://digital.ncdcr.gov/iiif/2/p16062coll11:451/3072,4096,1024,1024/1024,/0/default.jpg

Dezoomify reports:

```
Uncaught Error: Unable to load first tile: https://digital.ncdcr.gov:80/iiif/2/p16062coll11:451/0,0,1024,1024/1024,/0/default.jpg

(https://dezoomify.ophir.dev/zoommanager.js:217)
```
I don't understand this message. Can someone please help me ?

**Comment by Benomrans** [comment]
Hello,
It doesn't need Dezoomify. Images might be obtained using the browser directly by altering the parameters at the url :

https://digital.ncdcr.gov/iiif/2/p16062coll11:451/3072,4096,1024,1024/1024,/0/default.jpg

To:

https://digital.ncdcr.gov/iiif/2/p16062coll11:451/full/full/0/default.jpg

Good luck.
