### ISSUE TITLE
downloading pictures

### ISSUE THREAD

**Issue by basil-ram** [lovasoa/dezoomify#663]
Hello, it is not possible to download pictures in good quality from the website. Link to the website.
With respect and best wishes!

https://ar.culture.ru/ru/subject/portret-zheny-hudozhnika-i-r-meheda#fullscreen

**Comment by lovasoa** [comment]
Hello !
  You can use the [Generic Dezoomer](https://github.com/lovasoa/dezoomify/wiki/Generic-dezoomer-tutorial) with this site : 

```
https://ar.culture.ru/tiles/5cb5a5c7181d8d524e118d67/4/{{Y}}_{{X}}.jpg
```

https://dezoomify.ophir.dev/#https://ar.culture.ru/tiles/5cb5a5c7181d8d524e118d67/4/{{Y}}_{{X}}.jpg

**Comment by lovasoa** [comment]
![canvas](https://user-images.githubusercontent.com/552629/197365759-9ee208d3-8a52-4f0d-be76-555f57c5d236.jpg)

**Comment by basil-ram** [comment]
WOW!!!! You are awesome. Thank you from the heart!23.10.2022, 02:14, "Ophir LOJKINE" ***@***.***>:
Hello !
You can use the Generic Dezoomer with this site :
https://ar.culture.ru/tiles/5cb5a5c7181d8d524e118d67/4/{{Y}}_{{X}}.jpg

https://dezoomify.ophir.dev/#https://ar.culture.ru/tiles/5cb5a5c7181d8d524e118d67/4/{{Y}}_{{X}}.jpg

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
 С уважением и пожеланием всего самого доброго!
