### ISSUE TITLE
https://gigapixel.museoreinasofia.es

### ISSUE THREAD

**Issue by emallen1973** [lovasoa/dezoomify#664]
Does anyone know how to dezoomify the following image?

https://gigapixel.museoreinasofia.es/en/mujer-azul-pablo-picasso/#3/23.95/-123.66

**Comment by lovasoa** [comment]
Hello !
  This site already works with the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/).

```
https://mncars-gigapixel.s3.eu-central-1.amazonaws.com/AS01618/VIS/ImageProperties.xml
```

**Comment by emallen1973** [comment]
Can you please elaborate? I am not very knowledgeable in programming.

How would I manage to dezoomify an image like the one below with no missing tiles:

https://mncars-gigapixel.s3.eu-central-1.amazonaws.com/AS01618/VIS/ImageProperties.xml

Thanks
