### ISSUE TITLE
www.micro-pano.com

### ISSUE THREAD

**Issue by VoronkoM** [lovasoa/dezoomify#667]
Hello everyone,

 I am having issues when trying to download https://www.micro-pano.com/pearl/index.html

Dezoomify reports:

```
TypeError: el.children[0] is undefined

(https://dezoomify.ophir.dev/dezoomers/krpano.js:68)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
This was a bug in dezoomify, I fixed it. Thanks for reporting it, and helping to make dezoomify better for everyone.

As a side note, this zoomable image has a lot of variants and some very high resolution ones, it may be better suited to be downloaded with [dezoomify-rs](https://dezoomify-rs.ophir.dev/)
