### ISSUE TITLE
Error message after pasting .json file into dezoomify

### ISSUE THREAD

**Issue by scouserdave** [lovasoa/dezoomify#67]
Hi, I located the http://maps.nls.uk/imgsrv/iipsrv.fcgi?iiif=/11563/115632996.jp2/info.json file at http://maps.nls.uk/view/115632996 but I get an error message when I copy and paste it into dezoomify.

Thanks for you help.

**Comment by lovasoa** [comment]
This uses an iiif compatible server, so you don't need dezoomify, you can download the high-resolution image directly from the server. See [our wiki page on the subject](https://github.com/lovasoa/dezoomify/wiki/How-to-download-full-resolution-images-from-an-IIIF-compatible-server).

**Comment by scouserdave** [comment]
Thank you.

**Comment by lovasoa** [comment]
Commit 23624e2189a8e582ac9ca1e1d2a4d4dc1a1166eb added support for IIIF, so now it works in dezoomify too.
