### ISSUE TITLE
www.christies.com

### ISSUE THREAD

**Issue by gobarg** [lovasoa/dezoomify#685]
Hello everyone,

 I am having issues when trying to download https://www.christies.com/en/private-sales/privateitems/Paar-im-Zimmer-SN00649797-001

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
https://www.christies.com/en/private-sales/privateitems/Paar-im-Zimmer-SN00649797-001

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ? How can I generally download from this website for personal use? thanks

**Comment by agmmnn** [comment]
the website is not using zoomify just use the network inspector panel (f12) you will see the url of the image file.

https://apim.christies.com/private-sales-images/v1/SN00649797_001_1/SN00649797_001_1_001.jpg
