### ISSUE TITLE
[new site support] sammlung-online.stadtmuseum.de no longer works

### ISSUE THREAD

**Issue by tomybyte** [lovasoa/dezoomify#697]
### Site name and desciption
Stadtmuseum Berlin - Sammlung Online
sammlung-online.stadtmuseum.de

Largest collection of high-quality, historical Berlin photos

### Example URLs
viewing page: https://sammlung-online.stadtmuseum.de/Details/Index/201254
metadata files: https://sammlung-online.stadtmuseum.de/zoominfo?filename=9cff9360-be2d-4f67-88a6-3bc41e820572.tiff&isMansucript=false

`[{"Width":5673,"Length":4179,"TileWidth":256,"TileLength":256,"TilesAcross":23,"TilesDown":17},{"Width":2836,"Length":2089,"TileWidth":256,"TileLength":256,"TilesAcross":12,"TilesDown":9},{"Width":1418,"Length":1044,"TileWidth":256,"TileLength":256,"TilesAcross":6,"TilesDown":5},{"Width":709,"Length":522,"TileWidth":256,"TileLength":256,"TilesAcross":3,"TilesDown":3},{"Width":354,"Length":261,"TileWidth":256,"TileLength":256,"TilesAcross":2,"TilesDown":2},{"Width":177,"Length":130,"TileWidth":256,"TileLength":256,"TilesAcross":1,"TilesDown":1},{"Width":88,"Length":65,"TileWidth":256,"TileLength":256,"TilesAcross":1,"TilesDown":1},{"Width":44,"Length":32,"TileWidth":256,"TileLength":256,"TilesAcross":1,"TilesDown":1}]`

zoom image part: https://sammlung-online.stadtmuseum.de/zoom?x=14&y=10&z=7&filename=9cff9360-be2d-4f67-88a6-3bc41e820572.tiff&isMansucript=false

### Current error message
Oops, we have a problem

**Comment by agmmnn** [comment]
you can download it with this command using dezoomify-rs.

```
.\dezoomify-rs "https://sammlung-online.stadtmuseum.de/zoom?x={{x}}&y={{y}}&z=7&filename=9cff9360-be2d-4f67-88a6-3bc41e820572.tiff&isMansucript=false"
```

https://github.com/lovasoa/dezoomify-rs/wiki/Usage-example-for-the-custom-YAML-dezoomer#stage-2-construct-the-url-template

**Comment by tomybyte** [comment]
Hi Gökçe,
it works like a charm!
Many Thanks
Tomy
