### ISSUE TITLE
[new site support] NLI support

### ISSUE THREAD

**Issue by yanirmr** [lovasoa/dezoomify#699]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?
https://www.nli.org.il/he/discover/manuscripts/hebrew-manuscripts/viewerpage?vid=MANUSCRIPTS&docid=PNX_MANUSCRIPTS997011941566705171-4#$FL202979451

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.
This site supported in the past. A a lot of images of the National Library of Israel.

### Example URLs
 - Give the URLs of viewing pages - https://www.nli.org.il/he/discover/manuscripts/hebrew-manuscripts/viewerpage?vid=MANUSCRIPTS&docid=PNX_MANUSCRIPTS997011941566705171-4#$FL202979451

 - give the URLs of metadata files if you found them - https://iiif.nli.org.il/IIIFv21/FL202979451/info.json

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.
Uncaught Error: Unable to load first tile: https://iiif.nli.org.il/IIIFv21/FL202979451/0,0,1024,1024/1024,/0/default.jpg

**Comment by agmmnn** [comment]
This website using IIIF but you need to make request to image server with `Referer: https://www.nli.org.il/` header. You can use [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs), enter `info.json` url with `--header` argument.

Example command:
```
.\dezoomify-rs "https://iiif.nli.org.il/IIIFv21/FL202979497/info.json" --header "Referer: https://www.nli.org.il/"
```

**Comment by yanirmr** [comment]
Great, thank you.
