### ISSUE TITLE
"Error: Unable to load tile..."

### ISSUE THREAD

**Issue by Huginn22** [lovasoa/dezoomify#70]
"Error: Unable to load tile. Check that your internet connection is working and that you can access this url: http://www.themorgan.org/sites/default/files/zoomify/53651/105931/TileGroup1/5-11-13.jpg (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:170)"

Platform: Windows 10 x64
It said there's a problem with my internet connection, but the fact is that I have already connected the internet.

**Comment by lovasoa** [comment]
Please give the URL of the page you are trying to dezoomify.

**Comment by Huginn22** [comment]
ok. Here it is : http://www.themorgan.org/collection/tarot-cards/the-chariot
Thanks for your help. :)

**Comment by lovasoa** [comment]
You can use this url to dezoomify the image: http://www.themorgan.org/sites/default/files/zoomify/53591/105861/ImageProperties.xml

**Comment by Huginn22** [comment]
Still can't work... Thank you anyway. :)

**Comment by lovasoa** [comment]
I just tried again and it works on my computer. What do you see when you enter `http://www.themorgan.org/sites/default/files/zoomify/53591/105861/ImageProperties.xml` in dezoomify's text field and press enter ?

**Comment by lovasoa** [comment]
Oh, yes, one tile seems to be missing. You'll have to use a lower resolution version, and stitch it yourself.

**Comment by Huginn22** [comment]
It finally worked! Though its resolution not so high... Thank you so much. :)
