### ISSUE TITLE
[new site support] archives.lamayenne.fr

### ISSUE THREAD

**Issue by genealepretre** [lovasoa/dezoomify#701]
https://archives.lamayenne.fr/page/chercher
This is the official website about history or genealogy in Mayenne (France).

Different types of links on this website :

https://archives.lamayenne.fr/archives-en-ligne/ark:/37963/r692533z5438qk/f1
https://archives.lamayenne.fr/archives-en-ligne/ark:/37963/r23408h6o0ck/f1
https://archives.lamayenne.fr/archives-en-ligne/ark:/37963/r692440zq8q72k/f1

Error message:
"An error occured while trying to dezoomify your image. This is probably because dezoomify did not manage to find a zoomable image at the address you gave."
Uncaught Error: Unable to find a proper dezoomer

Thanks for your help. Best regards.
genealepretre

**Comment by agmmnn** [comment]
This website using IIIF but you need to make request to image server with `Referer: https://archives.lamayenne.fr/` header, otherwise it gives 404 error. You can use [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) give `info.json` url with `--header` (or -H) argument.

Example command:
```
.\dezoomify-rs https://archives.lamayenne.fr/archives-en-ligne/iiif/ark:/37963/r692533z5438qk/f1/info.json --header "Referer: https://archives.lamayenne.fr/"
```
