### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by silviubutuc** [lovasoa/dezoomify#71]
Hi,

I have troubles downloading the image from here  https://digital.library.yorku.ca/yul-87765/elvis-presley-buffalo-and-toronto-no-1

dezoomify doesn't work, or I don't know how to use it...

Please help me, how can a save the image, at the highest resolution and quality?

**Comment by decemus** [comment]
Hello,

I did try to catch an useful url/xml/dzi to dezoomify, but i failed. only found a downloadable JP2 in the pic's url.  it seems that dezoomify do not support this type.
please try this following url and rename it XXX.jp2,  your site cut this jp2 into pieces
http://digital.library.yorku.ca/yul-87765/elvis-presley-buffalo-and-toronto-no-1/datastream/JP2

and you can find many download options in your page, there is a 831.8 KiB jpeg2000 file can be download. same as upper url.

**Comment by lovasoa** [comment]
@decemus is right, you can download the image in full resolution without any extarnal tool, at the URL he gave.
