### ISSUE TITLE
www.sfmoma.org

### ISSUE THREAD

**Issue by galpindecaux** [lovasoa/dezoomify#717]
Hello everyone,

 I am having issues when trying to download https://www.sfmoma.org/artwork/91.161/

Dezoomify reports:

```
Uncaught Error: Unable to find a proper dezoomer for:
https://www.sfmoma.org/artwork/91.161/

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
It is not a tiled image, you don't even need dezoomify, you can use your browser's dev tools to find and download the original image directly from them

https://sfmoma-media-dev.s3.us-west-1.amazonaws.com/www-media/2022/05/17025336/91.161_01_b02-Large-TIFF_4000-pixels-long-scaled.jpg

![](https://sfmoma-media-dev.s3.us-west-1.amazonaws.com/www-media/2022/05/17025336/91.161_01_b02-Large-TIFF_4000-pixels-long-scaled.jpg)
