### ISSUE TITLE
Problem with downloading images from onb.digital

### ISSUE THREAD

**Issue by citroenfan2003** [lovasoa/dezoomify#718]
Hello everyone,

I am having issues when trying to download https://digital.onb.ac.at/RepViewer/viewer.faces?doc=DTL_7579363
Browser: Firefox

I tried going to web developer tools - network - xhr but there is no .json file there.

Can someone please help me ?
Thank you in advance.

**Comment by lovasoa** [comment]
Closing as a duplicate of #676 , feel free to continue the discussion there.

Also discussed in #703
