### ISSUE TITLE
Dezoomify produces repeat tiles of thumbnail rather than image - info.json issue? [bug]

### ISSUE THREAD

**Issue by bridgesmade** [lovasoa/dezoomify#725]
I am getting an image file that consists of the thumbnail image repeated several hundred times, rather than a composite image.
I sense it is something to do with the info.json file.

I have tried both the browser and the Chrome extension and Dezoomify-rs.
Chrome extension and Dezzomify-rs creates the repeated thumbnail issue.

Target image example:
https://i.micr.io/iNJAz

I am using Chrome.

For context, the whole image is here:
Bosch's Garden Of Earthly Delights:
https://archief.ntr.nl/tuinderlusten/en.html
But Zoomify can't pull from there.

I noticed the site was accessing various micr.io addresses (its a huge image, split into 18 pieces) so am trying to scrape from these instead.
https://i.micr.io/xzgeF
https://i.micr.io/KAdHK
https://i.micr.io/XMcGm
https://i.micr.io/nguwI
https://i.micr.io/eKHlF
https://i.micr.io/jhGGN
https://i.micr.io/iNJAz
https://i.micr.io/pgExU
https://i.micr.io/TzqZd
https://i.micr.io/NgjFS
https://i.micr.io/zXtEX
https://i.micr.io/fvaoq
https://i.micr.io/Jrjrg
https://i.micr.io/fovEz
https://i.micr.io/byyDL
https://i.micr.io/iCoWl
https://i.micr.io/IItdv
https://i.micr.io/LMeIv

**Comment by DigitalCurator** [comment]
[Resolved]

**Comment by bridgesmade** [comment]
Amazing @DigitalCurator that is brilliant, thank you.  Could I trouble you to ask how you managed to get things working? Are there some settings I need to be aware of? - I feel that would be less bothersome than lazily pointing you towards the other 17 links :) - I am keen to learn!
