### ISSUE TITLE
https://kmska.be/fr

### ISSUE THREAD

**Issue by jeanchartier** [lovasoa/dezoomify#726]
### Name and description :
Koninklijk Museum voor Schone Kunsten Antwerpen (MKSKA) : https://kmska.be/fr

The site of the Museum of Antwerp contains photographs of famous paintings in gigapixels, including the Musician Angels by Hans Memling.

### Example URLs
 - https://kmska.be/fr/chefdoeuvre/dieu-le-pere-entoure-danges-chanteurs-et-musiciens
 - https://iiif.kmska.be:8183/iiif/2/public@1048.tif/info.json

### Current error message, from dezoomify-rs
- iiif: Unable to download required data: network error: error sending request for url (https://iiif.kmska.be:8183/iiif/2/public@1048.xml): error trying to connect: The trust policy was not trusted.

**Comment by DigitalCurator** [comment]
Remember to close this Ticket thread, thank you.
