### ISSUE TITLE
Add support for digi.archives.cz

### ISSUE THREAD

**Issue by Pettyl** [lovasoa/dezoomify#73]
Hello Sir,

I just have URL of zoomimage tile for example:
http://digi.archives.cz/da/permalink?xid=69BF2956D18B11E5AB77001167D6B623&scan=32

Dezoomify web (http://ophir.alwaysdata.net/dezoomify/dezoomify.html) don't work.

Thanks.

**Comment by lovasoa** [comment]
You can provide the meta information file URL directly. http://digi.archives.cz/mrimage/common/zoomify/cz/archives/CZ-217000010/fotoarchiv/dao/images/0005/bd15f204d3e811e5a5c7001167d6b623.jpg/ImageProperties.xml

**Comment by Pettyl** [comment]
On website archives.cz used a new code, Dezoomify now doesn't work with URL and metainformation.

http://digi.archives.cz/da/permalink?xid=7786E329ADE311E0A7AF506313898F37-01D98151C37211E5959DA0D3C123F1DA&scan=9

Please, help.

Thanks.

**Comment by lovasoa** [comment]
dezoomify now supports tile URLs as input for the zoomify dezoomer.
You can open your browser's network inspector, copy a tile URL, and paste it into dezoomify.

For the example above: https://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://images.archives.cz/mrimage/foto/zoomify/cz/archives/CZ-217000010/fotoarchiv/dao/images/0005/bd15f204d3e811e5a5c7001167d6b623.jpg/TileGroup0/3-2-3.jpg
