### ISSUE TITLE
[resolved]

### ISSUE THREAD

**Issue by DigitalCurator** [lovasoa/dezoomify#738]
[resolved]

**Comment by DigitalCurator** [comment]
[resolved]

**Comment by lovasoa** [comment]
Hey ! If you had an issue but managed to solve it on your own, it may still be interesting to state the problem and the solution here to help others :)

**Comment by DigitalCurator** [comment]
Hi. Well it is only about the EasyZoom _SZI_ file format which you actually solved it in previous reply #287  
Thanks.
