### ISSUE TITLE
gallerycollections.courtauld.ac.uk

### ISSUE THREAD

**Issue by pigsonthewing** [lovasoa/dezoomify#749]
Hello everyone,

 I am having issues when trying to download https://gallerycollections.courtauld.ac.uk/object-p-1978-pg-339

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
https://gallerycollections.courtauld.ac.uk/object-p-1978-pg-339

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)
```
Can someone please help me ?

Site is new, wuth many out-of-copyright paintings

**Comment by lovasoa** [comment]
Works out of the box with the browser extension: https://lovasoa.github.io/dezoomify-extension/

**Comment by pigsonthewing** [comment]
> Works out of the box with the browser extension: https://lovasoa.github.io/dezoomify-extension/

I'll take your word for it 

https://github.com/lovasoa/dezoomify-extension/issues/45

:-(

**Comment by lovasoa** [comment]
install the extension

![image](https://github.com/lovasoa/dezoomify/assets/552629/dd914d22-175a-4036-9c8a-9970c2e627eb)

open the extension panel

![image](https://github.com/lovasoa/dezoomify/assets/552629/40d72295-9cf0-425f-b064-75cd7e96cfdf)

click the extension icon

![image](https://github.com/lovasoa/dezoomify/assets/552629/583d14e1-841c-4c14-a590-480b92efbe97)

zoom in the image

![image](https://github.com/lovasoa/dezoomify/assets/552629/8e9f68a4-2dd4-40ab-ad2f-1c221a74653c)


click the icon again

![image](https://github.com/lovasoa/dezoomify/assets/552629/338b4687-cb9c-46a1-82d1-9084e8318b74)


https://dezoomify.ophir.dev/#https://gallerycollections.courtauld.ac.uk/assets/object_images/4/10/62014/v0_zoom/image_files/0/0_0.jpg

![image](https://github.com/lovasoa/dezoomify/assets/552629/e4837daf-f3be-49f8-9d39-e5442e1bb447)

![image](https://github.com/lovasoa/dezoomify/assets/552629/cb787e5d-cbcd-4554-b50b-7e596a2bfd2f)

![canvas](https://github.com/lovasoa/dezoomify/assets/552629/1dccb298-8871-4b33-bf40-63b8d82d1f42)

**Comment by pigsonthewing** [comment]
Working; Thank you.
