### ISSUE TITLE
Also impossible to use Dezoomify with the Chrome extension. 

### ISSUE THREAD

**Issue by mastix01** [lovasoa/dezoomify#757]
Unfortunatelly the Zoomify extension does also not work in Chrome. Both Firefix and Chrome extensions give error when trying to dezoomify images in Google Arts

**Comment by mastix01** [comment]
Uncaught Error: Our server has received too many requests, and our provider is blocking new requests. You can donate on https://github.com/sponsors/lovasoa to participate to the hosting fees. Once we collect over 5$/month overall, we will switch to a paid plan of the provider, allowing more requests to go through every day. For more details, see https://github.com/lovasoa/dezoomify/issues/337#issuecomment-773498488.

**Comment by lovasoa** [comment]
Hello ! The code still works well, and the image download will work again as soon as someone donates enough to pay for a higher hosting tier: https://github.com/sponsors/lovasoa
