### ISSUE TITLE
www.mza.cz

### ISSUE THREAD

**Issue by josefpavlik** [lovasoa/dezoomify#758]
Hello everyone,

 I am having issues when trying to download https://www.mza.cz/actapublica/iipsrv/iipsrv.fcgi?Deepzoom=/srv/LUN105/LUN105/216000010/216000010-000253-003375-000000-008971-000000-AP-B11443/216000010-000253-003375-000000-008971-000000-AP-B11443-01830.jp2_files/0/0_0.jpg

Dezoomify reports:

```
Error: Unable to load tile.
Check that your internet connection is working and that you can access this url:
https://www.mza.cz/actapublica/iipsrv/iipsrv.fcgi?Deepzoom=/srv/LUN105/LUN105/216000010/216000010-000253-003375-000000-008971-000000-AP-B11443/216000010-000253-003375-000000-008971-000000-AP-B11443-01830.jp2_files/12/3_0.jpg

(https://dezoomify.ophir.dev/zoommanager.js:221)
```

I found that the site reports error 403 with explain something like "there is a bulk download from your ip address". 
However, Using the plugin there are requests like
curl 'https://www.mza.cz/actapublica/iipsrv/iipsrv.fcgi?Deepzoom=/srv/LUN105/LUN105/216000010/216000010-000253-003375-000000-008971-000000-AP-B11443/216000010-000253-003375-000000-008971-000000-AP-B11443-01830.jp2_files/12/7_4.jpg'
this request get the error 403.
When the original page gets the tiles, there is an extra header in the request
 -H 'Referer: https://www.mza.cz/actapublica/matrika/detail/10336?image=216000010-000253-003375-000000-008971-000000-AP-B11443-01830.jp2'
Putting this header in the request copied from your plugin I can download the single tile.
curl 'https://www.mza.cz/actapublica/iipsrv/iipsrv.fcgi?Deepzoom=/srv/LUN105/LUN105/216000010/216000010-000253-003375-000000-008971-000000-AP-B11443/216000010-000253-003375-000000-008971-000000-AP-B11443-01830.jp2_files/12/7_4.jpg'  -H 'Referer: https://www.mza.cz/actapublica/matrika/detail/10336?image=216000010-000253-003375-000000-008971-000000-AP-B11443-01830.jp2'
works fine.

Can you detect the headers too and put the headers (at least the referrer) to requests to download the tiles? I don't know if It's possible in the browser, however if it's possible, please try to add it.

the url of the page is 
https://www.mza.cz/actapublica/matrika/detail/10336?image=216000010-000253-003375-000000-008971-000000-AP-B11443-01830.jp2

thank you very much
ciao
Josef Pavlik

**Comment by lovasoa** [comment]
Hi !
  Have a look at our wiki: https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages
  Entering `ZoomManager.proxy_tiles = "proxy.php";` in your browser's console does what you want.
  It's not enabled by default in order to limit trafic to our proxy (which we pay for using [your generous donations](https://github.com/sponsors/lovasoa)). If you use the proxy, then please donate if you can.

![dezoomify-result](https://github.com/lovasoa/dezoomify/assets/552629/805a044f-1ddd-4f11-a8b7-756bec456d5a)
