### ISSUE TITLE
[new site support] histologyguide.com

### ISSUE THREAD

**Issue by meysam87** [lovasoa/dezoomify#759]
hi 
dezoomify extension and web site can not download zoomable image from Histologyguid.com
for example this URL :https://histologyguide.com/slideview/MH-122-appendix/14-slide-1.html?f=1
i read FAQ but i can not download any thing.

**Comment by lovasoa** [comment]
Hi !
  You don't need dezoomify with this. You can download the file as [ZIF](https://github.com/lovasoa/ZIF) directly from the website (find the url in your browser's network panel):
 https://histologyguide.com/slides/MH-122-appendix.zif?t1700571084962n248

![canvas](https://github.com/lovasoa/dezoomify/assets/552629/4d9fe0b5-c4cc-4e62-8f96-8f347d241202)

**Comment by meysam87** [comment]
Great...thanks 
I download  images in *.ZIF format. But a problem, i cannot open this format (*.ZIF). how. Can i open it or  convert to other Format in high-resolution (jpg, PNG,..)

**Comment by lovasoa** [comment]
Rename the .zif to .tiff and open it with The Gimp.
