### ISSUE TITLE
[new site support] arthive.com

### ISSUE THREAD

**Issue by jhoward1045** [lovasoa/dezoomify#760]
https://arthive.com/de/joaquinsorolla/works/468052~Clotilde_und_Elena_auf_den_Felsen_in_Javea#show-work://468052
Does this image exist at 2262 x 1600 at this page?

**Comment by lovasoa** [comment]
The site does not seem to use tiled zoomable images. It serves the full image directly:

https://arthive.net/res/media/img/orig/work/fe9/382568.webp

![](https://arthive.net/res/media/img/orig/work/fe9/382568.webp)
