### ISSUE TITLE
www.rmg.co.uk

### ISSUE THREAD

**Issue by pigsonthewing** [lovasoa/dezoomify#762]
Dezoomify does not find the image on  https://www.rmg.co.uk/collections/objects/rmgc-object-84411

It reports:

```
Error: Unable to find a proper dezoomer for:
https://www.rmg.co.uk/collections/objects/rmgc-object-84411

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)
```

**Comment by Cosmicore** [comment]
It doesn't look like mosaic [image](https://collections.rmg.co.uk/media/2/292/76/j5057.jpg). At least I don't see any good quality image there when I zoom it in and out. It shows the same file, just zooming it.

The URL can be found in the section **data-img-full** of the [main](https://www.rmg.co.uk/collections/objects/rmgc-object-84411) page.
