### ISSUE TITLE
Unable to find a proper dezoomer for: www.historicnewengland.org

### ISSUE THREAD

**Issue by robiss99** [lovasoa/dezoomify#766]
Hello everyone,

 I am having issues when trying to download https://www.historicnewengland.org/explore/collections-access/gusn/267545/

Dezoomify reports:

```
Uncaught Error: Unable to find a proper dezoomer for:
https://www.historicnewengland.org/explore/collections-access/gusn/267545/

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by Cosmicore** [comment]
It should be DeepZoom. Try [this](https://hne-rs.s3.amazonaws.com/filestore/zoom/2/4/4/0/0/1_f8f356208ca748a/zoom_244001/zoom.xml) URL.

It can be found in the section **div class="full_image "** of the [main](https://www.historicnewengland.org/explore/collections-access/gusn/267545/) page. But it takes a little bit of manual work to form the URL by adding the domain to the link.

**Comment by robiss99** [comment]
yes..  your URL script works on the other zoomable links from this site also..  not a quick process, however; but it does work.. thank you..  do you have a paypal account for contributions..??

**Comment by Cosmicore** [comment]
Hi! The author of this project and scripts is respected @lovasoa, I am a user like you who decided to help. So I am virtually forwarding your thanks and suggestion from your last message to him.

**Comment by lovasoa** [comment]
@robiss99 , if you would like to support the dezoomify project, you can contribute here: https://github.com/sponsors/lovasoa :)
