### ISSUE TITLE
michiganology.org

### ISSUE THREAD

**Issue by robiss99** [lovasoa/dezoomify#767]
Hello everyone,

 I am having issues when trying to download https://michiganology.org/uncategorized/IO_3362c842-7319-4950-9c3d-8c2324cefd01

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
https://michiganology.org/uncategorized/IO_3362c842-7319-4950-9c3d-8c2324cefd01

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ?

**Comment by lovasoa** [comment]
The image is not tiled, you can download the full image directly from their server just by opening your browser's network monitoring tab.

https://michigan.preservica.com/Render/render/resource/3362c842-7319-4950-9c3d-8c2324cefd01/openseadragon/image?token=7d946b0c-cae3-485f-bd9f-b3942d06eadd

![image](https://github.com/lovasoa/dezoomify/assets/552629/5ef6e948-4579-4a1c-aa03-69913b0f1738)
