### ISSUE TITLE
museecognacqjay.paris.fr

### ISSUE THREAD

**Issue by gp27066** [lovasoa/dezoomify#768]
Hello everyone,

 I am having issues when trying to download https://www.google.com/complete/search?q&cp=0&client=gws-wiz-serp&xssi=t&gs_pcrt=2&hl=en-IL&authuser=0&pq=736727d9a9166%2Fa22w47066m79643244698326096c569_fr.json

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
https://www.google.com/complete/search?q&cp=0&client=gws-wiz-serp&xssi=t&gs_pcrt=2&hl=en-IL&authuser=0&pq=736727d9a9166%2Fa22w47066m79643244698326096c569_fr.json

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)
```
I don't understand this message. Can someone please help me ? The address https://www.museecognacqjay.paris.fr/en/balaam-and-donkey

**Comment by lovasoa** [comment]
The URL you are giving leads to a 400 error page

**Comment by lovasoa** [comment]
Concerning  museecognacqjay.paris.fr : it does not seem to contain tiled zoomable images. You can download images from the website directly with a simple right click, no need for dezoomify.

![](https://www.museecognacqjay.paris.fr/sites/default/files/collection24769-15.jpg)
