### ISSUE TITLE
www.internetculturale.it

### ISSUE THREAD

**Issue by Carleoinserra** [lovasoa/dezoomify#769]
### Site name and desciption
www.internetculturale.it
There is a method for dezoomify from www.internetculturale.it?

### Example URLs
 [
](https://www.internetculturale.it/jmms/magparser?id=oai%3Awww.internetculturale.sbn.it%2FTeca%3A20%3ANT0000%3AN%3ARML0448184&teca=MagTeca+-+ICCU&mode=all&fulltext=0&_=1703836433735)

### Current error message
Error: Unable to find a proper dezoomer for:
https://www.internetculturale.it/jmms/magparser?id=oai%3Awww.internetculturale.sbn.it%2FTeca%3A20%3ANT0000%3AN%3ARML0448184&teca=MagTeca+-+ICCU&mode=all&fulltext=0&_=1703836433735

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)

**Comment by lovasoa** [comment]
It doesn't seem that the website offers tiled zoomable images. You can download the images directly from the website as they are shown.
