### ISSUE TITLE
Dezoomify v3 not compatible, Seek alternate de-zoomify & Save Digital Archive of Dead Sea Scroll, Israel & Aleppo Codex in its respective Sites!

### ISSUE THREAD

**Issue by destinationfer2** [lovasoa/dezoomify#77]
Hello lovasoa!
side note: HUGE FAN!!!! YOU HAVE NO IDEA WHAT BLESSING YOU HAVE BEEN SO FAR,  A GOD SENT TOOL FOR MY BIBLE PROJECT!!! YOU ARE A PIONEER AND SO FAR YOU BRING THE ONLY REAL SOLUTION FOR US OF LESS TECHNICAL BACKGROUND!!! THANK YOU!, IF YOU ONLY KNEW THE AMOUNT OF WISDOM & KNOWLEDGE THAT WILL RESULT FROM YOUR CREATION, HOPEFULLY LEADING TO SALVATION OF MANY SOULS!

Upon discovery I successfully used Dezoomify on www.bl.uk, to step up the quality to its highest standard avail!
Soon ran into a compatibility issue using Dezoomify on Gallica. Searched here,found your Gallica URL trick extremely usefull! helping me progress my Lifes work thus far but......

Nevertheless I "hit another BRICK WALL", My most time-enduring & unsolved case yet.. Help lol.
Endless web search & not even 1 tutorial in sight! even less with laymans instructions for the Avg.-Joe!
 As far as ive tried Dezoomify v.3 wont work, am I missing something? 

is there another way (similar to Gallica perhaps) to Dezoomify & Save Archived "Zoom" Images back to it's Natural-Full-Dimensions & Format (Pref. Lossless)???

I hope im not a bother or rambling too much. im just stuck..
I  need Hi-Res Digital Images for whole project incl both 
Dead Sea Scrolsl sites: deadseascroll (hundreds of fragmented scripture),
 the Israel Museum site (Isaiah,War,Temple,etc.Scrolls from DSS) 
and soon after that The Aleppo Codex (Torah, Masoretic Text).

Example: these 2 img's (many more) each 1 frm Dead Scrolls sites, deadsescroll & Israel Museum respectively. (both are Zoom Digital-Archive online Viewers seemingly powered by Google):
1) 1Q Genesis (1Q1 Manuscript Fragments):
http://www.deadseascrolls.org.il/explore-the-archive/image/B-277259

2) 1Q The Great Isaiah Scroll (1Qlsa):  
http://dss.collections.imj.org.il/isaiah

after DeadSS i'll need access to Aleppo (Same as DeadSS?) 

3)AleppoCodex.org digital zoom view URL containing zoom images:
http://aleppocodex.org/newsite/index.html

**Comment by lovasoa** [comment]
I didn't have time to watch 2 & 3, but at least for 1, you can use the generic dezoomer.
Just enter `http://lh4.ggpht.com/uy7s-_wptyZQWOkOHdVehwWRJ1wG6DxLPqmLeQP8KYM0GjYOq8c6IoNFfQ=x{{X}}-y{{Y}}-z3-nt0GT0Xn3AD62HP_PsIyedaikjb7ks` into dezoomify.

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/18085088/f6110098-6ea9-11e6-8511-a0dc42bd0588.jpg)

**Comment by lovasoa** [comment]
See https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#the-page-uses-an-image-viewer-that-is-not-supported-by-dezoomify-is-there-still-a-chance-

**Comment by lovasoa** [comment]
I just gave a look at number 2 and 3.

####  1) 1Q Genesis (1Q1 Manuscript Fragments)
You can use the [generic dezoomer](https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#the-page-uses-an-image-viewer-that-is-not-supported-by-dezoomify-is-there-still-a-chance-), as explained above.

#### 2) 1Q The Great Isaiah Scroll (1Qlsa)
This will be the most difficult. The generic dezoomer works, but the image is really huge, so you will most probably hit [this issue](https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#dezoomify-shows-a-progress-bar-but-my-image-appears-to-be-completely-blank). I recommend reading our FAQ carefully.

#### 3)AleppoCodex.org
They use a simple zoomify format. Again, just read [this question in the FAQ](https://github.com/lovasoa/dezoomify/wiki/Dezoomify-FAQ#the-page-uses-an-image-viewer-supported-by-dezoomify-but-dezoomify-still-doesnt-work-what-to-do-).

Don't hesitate to ask more questions in this thread if something doesn't work as expected.

And, simply out of curiosity, what is your *Bible Project* ?

**Comment by destinationfer2** [comment]
Thank you! I have come very far because of your help brother  I managed to figure out #3 literally right after sending this request lol Thank you for #1 aswell!! 
But yes just like you said #2 is quite the stumble...

I read your FAQ for the past 3 weeks over and over and it seems i learn something new everytime but as far as progress i get the Generic dezoomer Blank loading screen, which is still miles ahead of where i understood 3 weeks ago lol.

For #2 is it only possible to download it as just 1 Massive Scroll of 66 Columns instead of 66 seperate Pics for every column? cause i own a 2014 Macbook Air and im not sure if the size aocation to 2,000,000,000 made any difference either..




As for the Curiosity part Man... if i told you , you would not belive me.. My journey thus far, what I have seen with my own eyes, from life of a Drug Dealer to Addict & Saved by Christ to witnessing real life Incredible super natural episodes over and over again leading me to absorbing so much shocking truths that i cant even do it justice in so little words. also I feel If I say too much that my work would be at risk by the "adversary'. 
I mean just an example: 
I live in Alaska, i have witnessed amazing things like seeing 2 Suns in the sky!! many times we see what most cal UFO's but we know to be Spirits that transform, etc... al this only happening to me ater being trully saved.. and I HAVE evidence.. So now my mission in life is to open as many eyes as possible.

No one has ever done what im trying to pull (How could they?) & YOU are probably the one earthly reason this is becoming a true possibility at a High Level of Quality. When i Finish this, with your permission I wouldnt feel comfortable leaving your name out of the credits! Thats how important your project has been to mine!.

Hint: you ever wonder why they make most of these ancient scripture & documents, so hard & near impossible for the layman to even access (Less have possesion & control). That only in these very recent times is this possible to have the all the tools and key people willingto wake up. (2016-17 beginning of the end).  Yet like the bible says in the endtimes there will be a pouring out of The Holy Spirit (Wisdom & Truths from Our Creator). The children of sin are becoming more bold aswell. 

When im finished i will send you a free copy and maybe even I can inspire you like i have been, (No Offense intended)

Again Thank You For everything! If everything works out as i believe it will, I will make your name to be read in every copy!

**Comment by lovasoa** [comment]
I downloaded all the tiles from [(2)](http://dss.collections.imj.org.il/isaiah#2:21) using wget, and stitched them on my computer using [imagemagick](http://www.imagemagick.org/Usage/montage/).
Just, the [JPEG file format](https://en.wikipedia.org/wiki/JPEG) can't hold images larger than 65,535 pixels, and huge files are really impractical, so I created 4 different files. I posted them online here: https://mab.to/HxNawazLi.

**Comment by lovasoa** [comment]
And I don't think you should put my name on every copy of your book, as I'm not associated to it. You'd better put a link to this project :)

**Comment by destinationfer2** [comment]
Brother you surely went out of your way for me but unfortunately I gotta have these images in a Lossless Format like .PNG or JP2 Format. This is why you have been a lifesaver cause theres really better way than the highest qulity possible when i take this scripture and enhance it almost like a photographic-font-ish format im doing this in. its hard to explain untill i show you the finish product lol.65,535 Pixels is absolutely far too big i agree. this why I was hoping it would download in Columns in a "Lossles Format" ie.PNG,JP2,etc. is that possibe?

Thank you so much brother, God Bless you!!  

PS.
oh ocourse! it would only credit your name, with permission lol  also my project wont be a kind of "me pushing my ideas and experience" book. 
More like an "Present evidence in the OG real source of _The Word_ ,in its actual literal photographic Font next to our more accurate modern english scripture with translations & Concordance etc. 

It will eliminate many of the "Bible naysayers" who say things like "How can i trust this book? man corrupted it, etc." it will be an amazing tool for the critic & belivers alike, and it will also have some shocking revelations about certain establishments  that have been going out of there way to print watered down and or mileading scripture.

**Comment by destinationfer2** [comment]
in fact, i wouldnt mind learning how to download it as a whole "Lossless" File(PNG,etc.) and maybe just edit it into the 50 or so columns myself on a much more 'powerfull desktop' if need be. Just need the know how. You have already gone too far & beyond out of your way . but are there any tutorials out there you can point me to? 

i think im gonna give back and make a tutorial video of everything you have taught me so far.. cause, theres like 2 or 3 dezoomify youtubes  of the standard and odd method & solutions. This is a fraction of your programs extended versatility and many methods you have described thus far.... Then again.. I wouldn't want to motivate Google and Microsoft in stepping up even more sophisticated & hard to dezoomify methods like this here #2 lol

**Comment by lovasoa** [comment]
This (2) isn't especially obfuscated. It was hard to download just because of its huge size. 

The tile themselves are in jpg (a lossy format), so there is no point to saving it in png. The file would just be bigger, without any significant quality gain (jpg is very tolerant to re-compression). 

But if you still want to do so, you can. I have linked tools to the tools I've used. I work on Linux, and it was just wget and imagemagic. 

In a bash terminal, typing 
```
wget http://example.com/{0..511}_{0..19}.jpg
```

Will download all files from http://example.com/0_0.jpg to http://example.com/511_19.jpg

Just adapt it to your tile urls. Then, you can use the `montage` command from imagemagic. I have a link to a tutorial about how to use it in my previous post.

**Comment by yairitmar** [comment]
Hi @lovasoa,
I have run into the same issues and have read your instructions; they are very helpful.
I have been able to download images from the dead sea scroll website, but have not been successful with the Isaiah Scroll or the Aleppo Codex.

Following the instructions for the generic dezoomer, I have pulled this URL for the Isaiah Scroll: http://tiles.imj.org.il/tiles/isaiah/10_511_10.jpg
and modified it to:
http://tiles.imj.org.il/tiles/isaiah/{{x}}_{{y}}_10.jpg

For the Aleppo Codex I modified this URL:
https://barhama.com/ajaxzoom/pic/AleppoWM/1-1-r_photo_by_Ardon_Bar-Hama.jpg
to this:
https://barhama.com/ajaxzoom/pic/AleppoWM/{{x}}-{{y}}-r_photo_by_Ardon_Bar-Hama.jpg

By both I am receiving an error message.
Can you show me where I am going wrong?

Also, I see that you have already downloaded the Isaiah Scroll, but the link has expired by now. Can you send it again?

Thank you very much!
Yair

**Comment by lovasoa** [comment]
You can use [dezoomify-rs](https://dezoomify-rs.ophir.dev/) to download it : 

```
dezoomify-rs "http://tiles.imj.org.il/tiles/isaiah/10_{{X}}_{{Y}}.jpg"
```

When creating URL templates, make sure the number you replace with `{{X}}` really represents the x coordinate of the tile in the overall picture, and  the number you replace with `{{Y}}` really represents the y coordinate of the tile in the overall picture

**Comment by yairitmar** [comment]
Dear Ophir,
Hi,
You've assisted me in the past with your incredible program 'dezoomify',
and I've used it successfully since.
I'm trying now to download a full manuscript (namely, the Xanten Bible
<https://digitalcollections.nypl.org/items/a53384b6-4d51-105d-e040-e00a180652fa#/?uuid=a53384b6-4d51-105d-e040-e00a180652fa>),
and I was wondering if you can possibly create a tool that can scroll
through the manuscript, 'dezoomify' each image, and download it.
If you can, it would greatly help my research!
Thanks again for all your help,
All the best,
Yair




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/09/22,
05:28:44 PM
