### ISSUE TITLE
[Deletion Request]

### ISSUE THREAD

**Issue by DigitalCurator** [lovasoa/dezoomify#774]

**Comment by DigitalCurator** [comment]
Does anyone knows the {{x}}{{y}} URL for this to be used in dezoomify?
If nobody has any idea, I will be closing this issue and maybe try python.
Thank you.

**Comment by lovasoa** [comment]
Giga pan is not supported yet.

The tile urls seem to be regular, it should be possible to create a dezoomer.

[tiles.zip](https://github.com/lovasoa/dezoomify/files/14434640/tiles.zip)


Let me know if you figure out the tile numbering logic

**Comment by DigitalCurator** [comment]
@lovasoa

May I request this issue be deleted? As their site has reinforced company’s intellectual property rights. (I was unaware of it previously.)

Thank you!
