### ISSUE TITLE
[new site support] request www.nids.mod.go.jp

### ISSUE THREAD

**Issue by AmiralCrapaud** [lovasoa/dezoomify#776]
Hello guys,

No idea if I am going to find somebody who has a clue regarding this one, but here's my problem. Trying to access these contents (which are a few graphs & tables in Hi Res from the above-mentioned archives)

Here's one of these:
https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=049&f=049_345.jpg&t=%E7%8F%8A%E7%91%9A%E6%B5%B7%E6%B5%B7%E6%88%A6%E3%80%81%E4%B8%83%E6%97%A5%E6%9C%9D%E3%81%AE%E5%90%84%E9%9A%8A%E7%B4%A2%E6%95%B5%E8%A8%88%E7%94%BB%E5%9B%B3
And Dezoomify in any fashion (including rs) doesn't seem to click with anything I try, considering I can't manage to get a proper URL out of this mess

Big thanks if you have any clue about that one. Cheers ^^

Dezoomify reports:

```
Error: Unable to find a proper dezoomer for:
https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=049&f=049_345.jpg

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)
Any clue? Is that due to an extra layer of protection, or it's just my being very bad at it (which is absolutely most often the case).

**Comment by DigitalCurator** [comment]
Website it down

**Comment by DigitalCurator** [comment]
Webpage is down, unable to load

**Comment by DigitalCurator** [comment]
[Resolved]

**Comment by AmiralCrapaud** [comment]
Thank you so much @DigitalCurator !
But I am always on the lookout for a way to do so with other pics I need from some of these volumes, so if you would have the kindness to tell me how I should be doing it, I'd be grateful.
And happy to send a small donation your way too (same with @lovasoa, bien sûr!)

**Comment by AmiralCrapaud** [comment]
Re-opened properly as #780
