### ISSUE TITLE
geoportal.rgo.ru amd 403 Forbidden errors [new site support]

### ISSUE THREAD

**Issue by takaji10** [lovasoa/dezoomify#778]
I'm trying to download an image from this link: [https://geoportal.rgo.ru/iipview/12938](https://geoportal.rgo.ru/iipview/12938)

I'm using IIPImage with the following link: [https://geoportal.rgo.ru/iipsrv?FIF=12938.tif&obj=IIP,1.0&obj=Max-size&obj=Tile-size&obj=Resolution-number](https://geoportal.rgo.ru/iipsrv?FIF=12938.tif&obj=IIP,1.0&obj=Max-size&obj=Tile-size&obj=Resolution-number)

I also used `ZoomManager.proxy_tiles = "proxy.php";` and also tried using dezoomify-rs with the following format, where I copied the header of the request link to the IIPImage link:
`--header "https://geoportal.rgo.ru/iipview/12938" "https://geoportal.rgo.ru/iipsrv?FIF=12938.tif&obj=IIP,1.0&obj=Max-size&obj=Tile-size&obj=Resolution-number"`

Despite this, 403 Forbidden errors still persist in the dezoomify web app, and dezoomify-rs tells me `IIPImage: Unable to download required data: Input/Output error: The filename, directory name, or volume label syntax is incorrect. (os error 123)`

Any help would be appreciated so that I understand what I'm doing incorrectly. Thanks!

**Comment by Benomrans** [comment]
Hello,
You need to initiate dezoomify-rs using the command line not directly.
initiate CMD then at the command line paste:
path to dezoomify-rs folder\dezoomify-rs.exe --header "Referer: https://geoportal.rgo.ru/iipview/12938" --header "Cookie: paste the cookie value of any tile" "https://geoportal.rgo.ru/iipsrv?FIF=12938.tif"
(the image is 7162px) (windows not mac)

**Comment by takaji10** [comment]
That worked like a charm! Thank you very much for the help. It seemed I didn't understand how to use it properly. :)
