### ISSUE TITLE
[new site support] Matricula Online

### ISSUE THREAD

**Issue by ozarugit** [lovasoa/dezoomify#779]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?

* Matricula Online, https://data.matricula-online.eu/en/

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.

* It contains scans of historical documents useful for anyone researching genealogy.

### Example URLs
 - Give the URLs of viewing pages

* https://data.matricula-online.eu/en/oesterreich/salzburg/goldegg/TFBII/?pg=95
* https://data.matricula-online.eu/de/oesterreich/wien/01-unsere-liebe-frau-zu-den-schotten/02-57/?pg=109 (N.B. this was 'solved' as a one-off 'bug' request, q.v. dezoomify/issues/735)

 - give the URLs of metadata files if you found them

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.

* "dezoomify did not manage to find a zoomable image at the address you gave"

**Comment by Benomrans** [comment]
Hello,
This site does not need dezoomify as it usues full images not tiled images.
Images urls might be obtained from the network section at the browser console and downloaded using the browser directly.

**Comment by ozarugit** [comment]
Thanks for the explanation; that works fine.
