### ISSUE TITLE
seek support for ngv.vic.gov.au images (National Gallery of Victoria)

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#78]
For example: http://www.ngv.vic.gov.au/explore/collection/work/4202/, what kind of zoom tool this site use? Is it called open zoom? Seems dezoomify does not support. 
Thanks a lot in advance.

**Comment by lovasoa** [comment]
This is a custom zoomify viewer. From the URL of the tiles, you can deduce the URL to give to dezoomify. In this case: `http://content.ngv.vic.gov.au/col-images/zooms/Fd000514/ImageProperties.xml`.

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/18171509/9767b888-7062-11e6-8130-740f80dd4261.jpg)

**Comment by lovasoa** [comment]
Just added support for the site to dezoomify. Empty your browser's cache, reload dezoomify, enter an URL from NGV (for instance http://www.ngv.vic.gov.au/explore/collection/work/4202/), and it should work.

**Comment by dancorpse** [comment]
It works! You're so great!
