### ISSUE TITLE
[new site support] https://www.nids.mod.go.jp/military_history_search/

### ISSUE THREAD

**Issue by AmiralCrapaud** [lovasoa/dezoomify#780]
Replaces the other thread (sorry, hadn't made that one properly)

### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?

Library & Historical Records Search System of the Japanese Military Archives
https://www.nids.mod.go.jp/military_history_search/

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.

This is the virtual reading room of the website of the historical archives fund of the Japanese Ministry of Defense. The items of interest are from a copyright-free series of official history pertaining Japanese war activities during WW2. These documents are very much sought after by a lot of people in our field, as they were never published in English and are very hard to find in print. It's pretty niche, but I can tell you people will be grateful.

### Example URLs
 - Give the URLs of viewing pages

 - https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=049&f=049_345.jpg&t=%E7%8F%8A%E7%91%9A%E6%B5%B7%E6%B5%B7%E6%88%A6%E3%80%81%E4%B8%83%E6%97%A5%E6%9C%9D%E3%81%AE%E5%90%84%E9%9A%8A%E7%B4%A2%E6%95%B5%E8%A8%88%E7%94%BB%E5%9B%B3
 (my thanks to @DigitalCurator for helping me getting this one done)

https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=049&f=049_344.jpg
https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=049&f=049_346.jpg
https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=049&f=049_347.jpg

Other examples from another volume of the series
https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=010&f=010_359.jpg
https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=010&f=010_360.jpg
https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=010&f=010_361.jpg

 - give the URLs of metadata files if you found them
Unfortunately, that is the issue. I just can't find the complete URL for these.

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.

Error: Unable to find a proper dezoomer for:
https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=049&f=049_345.jpg

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)

Doesn't work with -rs either, but it could be human error on my part
Any clue? Is that due to an extra layer of protection, or it's just my being very bad at it (which is absolutely most often the case).

Cheers and big thanks in advance! Merci beaucoup ^^

**Comment by Benomrans** [comment]
Hello,
This site does not need dezoomify as it usues full images with openseadragon not tiled images.
Images urls might be obtained from the network section at the browser console and saved from within the section (because a Cors policy is applied), then add .jpg to the downloaded file 
for example: 
the url https://www.nids.mod.go.jp/military_history_search/SoshoAppendixView?no=010&f=010_361.jpg has the image url : https://www.nids.mod.go.jp/military_history_search/GetImage?sa=010/appendix/010_361.jpg

(I'm using firefox)

**Comment by AmiralCrapaud** [comment]
Thank you kindly for your time @Benomrans 
Unfortunately on my end, I can only achieve on two machines, both using FF, that kind of result
![image](https://github.com/lovasoa/dezoomify/assets/75530983/61c6acd1-4329-426b-8601-067a69f21412)

Another angle, if I've missed something
![image](https://github.com/lovasoa/dezoomify/assets/75530983/bf3b5591-70d0-480e-88ed-578af0e195fd)

Ultimately, each time I try to save the response, even when I renew the query, only about 1/3 of the image will DL, and I'll end up with a 1Mb file out of a 3Mb original file (to give an order of magnitude). I tried several ways of doing that, but I am probably doing it wrong? If I hover over the source, it clearly only shows what I ultimately get.

Sorry to bother you again, but if you see the answer to that issue on the screen, a big thanks in advance!

**Comment by Benomrans** [comment]
@AmiralCrapaud 
Well, in this case we would need an image downloader that allow applying a referer header. the Downthemall Add-on at firefox would do that, as per this pic :

![10-361](https://github.com/lovasoa/dezoomify/assets/75787532/c73d6357-b5ee-4ef0-b350-0786d08d6f07)

(each image url with it's page url as referer).

**Comment by AmiralCrapaud** [comment]
I was honestly losing hope because my DownThemAll extension just did not manage to do it the first time around. Only realized then that it had refused to update since 2019 and that I had to reinstall it manually to its latest version - and now it works!
Big thanks @Benomrans !!
