### ISSUE TITLE
Unable to dezoomify site from 2016. I'm hooked.

### ISSUE THREAD

**Issue by ScottAbrams** [lovasoa/dezoomify#793]
Hello
  I am trying to dezoomify this page https://www.porthopehistory.com/ccreightonalbum/image6.htm
  This is a historical site for a town I once lived in.
  When trying this page I get the error
--
  Uncaught Error: Invalid XML:
https://www.porthopehistory.com/ccreightonalbum/image6.zif/ImageProperties.xml

(https://dezoomify.ophir.dev/zoommanager.js:221)
--
The javascript file is here - https://www.porthopehistory.com/ZoomifyImageViewerEnterprise-min.js  I have searched through this code for hours and can't make any progress.

I wasn't able to find any of the mentioned metadata files.

Trying Generic gives me the unable to load tiles so I followed the FAQ but still received the same error.
When looking through the developer tools (network) I can see it has downloaded some jpeg files.  I tried the {{X}}{{Y}} trick but it didn't work either.

Is there anywhere else I should be looking?  Any help would be greatly appreciated.  I like to figure out puzzles and this has me hooked.

**Comment by Benomrans** [comment]
@ScottAbrams 
Hello,
(Wonder no more, the answer is here : https://github.com/lovasoa/dezoomify/issues/237#issuecomment-390718490 )

**Comment by ScottAbrams** [comment]
> @ScottAbrams Hello, (Wonder no more, the answer is here : [#237 (comment)](https://github.com/lovasoa/dezoomify/issues/237#issuecomment-390718490) )

Thank You!  I did the first one I came across, where lovasoa said to download it and rename it to tif and then open it with Gimp but that didn't work for this one.

**Comment by Benomrans** [comment]
@ScottAbrams 
Perhaps the easiest way is to download the zif file then use Lovasoa online reader at : http://lovasoa.github.io/ZIF/ 
to convert the images to jpg.

**Comment by ScottAbrams** [comment]
> @ScottAbrams 
> Perhaps the easiest way is to download the zif file then use Lovasoa online reader at : http://lovasoa.github.io/ZIF/ 
> to convert the images to jpg.

I did that and it worked perfectly thanks.
