### ISSUE TITLE
Support for "Biblioteka zabytków polskiego piśmiennictwa średniowiecznego"

### ISSUE THREAD

**Issue by jsbien** [lovasoa/dezoomify#8]
This is actually a CD: https://sklep.ijp-pan.krakow.pl/images/zabytki.gif.

It never worked for me on Linux although the content is just a HTML with zoomify, now it does't work even on Windows. I would be happy to extract the images from the CD. My earlier attempt to use some dezoomify software failed for various reasons.

Unfortunately I cannot provide you with the complete CD as some parts of it are copyrighted (you can still buy it for 9,99 PLN = 2,5 Euro at https://sklep.ijp-pan.krakow.pl/product_info.php?products_id=30).

Here is a listing of a directory containing a document:
```
dr-x------ 3 jsbien jsbien   4096 Aug 13  2006 001r
dr-x------ 3 jsbien jsbien   4096 Aug 13  2006 001v
dr-x------ 3 jsbien jsbien   4096 Aug 13  2006 002r
dr-x------ 3 jsbien jsbien   4096 Aug 13  2006 002v
dr-x------ 3 jsbien jsbien   4096 Aug 13  2006 003r
dr-x------ 3 jsbien jsbien   4096 Aug 13  2006 003v
dr-x------ 3 jsbien jsbien   4096 Aug 13  2006 004r
dr-x------ 3 jsbien jsbien   4096 Aug 13  2006 004v
-r-------- 1 jsbien jsbien    781 Jun 18  2006 ar.htm
-r-------- 1 jsbien jsbien    779 Jun 18  2006 av.htm
-r-------- 1 jsbien jsbien   1043 Jun 18  2006 bottom.html
-r-------- 1 jsbien jsbien    781 Jun 18  2006 br.htm
-r-------- 1 jsbien jsbien    829 Jun 18  2006 btm_2.gif
-r-------- 1 jsbien jsbien   4792 Jan 29  2007 btm_2.html
-r-------- 1 jsbien jsbien    779 Jun 18  2006 bv.htm
-r-------- 1 jsbien jsbien    781 Jun 18  2006 cr.htm
-r-------- 1 jsbien jsbien    779 Jun 18  2006 cv.htm
-r-------- 1 jsbien jsbien    781 Jun 18  2006 dr.htm
-r-------- 1 jsbien jsbien    779 Jun 18  2006 dv.htm
-r-------- 1 jsbien jsbien    848 Jan 29  2007 index2.html
-r-------- 1 jsbien jsbien    720 Nov 17  2006 index3.html
-r-------- 1 jsbien jsbien    848 Jan 29  2007 index.html
-r-------- 1 jsbien jsbien 339758 Nov  8  2006 KazSKSkr.pdf
-r-------- 1 jsbien jsbien 929341 Jan 15  2007 KazSKTL.pdf
-r-------- 1 jsbien jsbien 614020 Jan 15  2007 KazSKTS.pdf
-r-------- 1 jsbien jsbien   2231 Apr 26  2006 _l.jpg
-r-------- 1 jsbien jsbien    657 Apr 26  2006 _m2.jpg
-r-------- 1 jsbien jsbien   1893 Apr 26  2006 main_2.html
-r-------- 1 jsbien jsbien    676 Apr 26  2006 _m.jpg
-r-------- 1 jsbien jsbien   1240 Jun 18  2006 panel2.gif
-r-------- 1 jsbien jsbien   1241 Jun 18  2006 panel.gif
-r-------- 1 jsbien jsbien   2329 Aug 10  2006 _p.jpg
-r-------- 1 jsbien jsbien   6144 Nov 21  2006 Thumbs.db
-r-------- 1 jsbien jsbien   1502 Jan 22  2007 top.html
-r-------- 1 jsbien jsbien  23302 Nov 20  2003 zoomifyViewer.swf
```
and this is a sample page (ar.htm):

```
<HTML><style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
-->
</style><BODY><DIV ALIGN="center">
<OBJECT CLASSID="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" CODEBASE="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,40,0" WIDTH="100%" HEIGHT="100%">
                <PARAM NAME="FlashVars" VALUE="zoomifyImagePath=001r/">
				<PARAM NAME="zoomifyZoom" VALUE="200">
                <PARAM NAME="src" VALUE="zoomifyViewer.swf">
		
		  
                <EMBED  SRC="zoomifyViewer.swf" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"  WIDTH="100%" HEIGHT="100%"></EMBED>
              </OBJECT>
  </DIV>
</BODY></HTML>
```
I will appreciate your advice how to proceede with the extraction task.

Best regards

Janusz

P.S. Thank you very much for Polona support!

**Comment by lovasoa** [comment]
Hello,
  I don't think there is much I can do without access to the images. I think the most simple thing to do if you can't adapt an existing tool is upload your files somewhere and use dezoomify.

Sorry,
Ophir

**Comment by jsbien** [comment]
I've uploaded a sample document to http://fleksem.klf.uw.edu.pl/~jsbien/ksw/ afer removing copyrighed transcription and transliteration. Would you be so kind to give it a try?

Regards

Janusz

**Comment by lovasoa** [comment]
Now just open [dezoomify](http://ophir.alwaysdata.net/dezoomify/dezoomify.html), and give it the URLs of the xml files that you have in all your folders.

http://fleksem.klf.uw.edu.pl/~jsbien/ksw/001r/ImageProperties.xml
http://fleksem.klf.uw.edu.pl/~jsbien/ksw/001v/ImageProperties.xml
http://fleksem.klf.uw.edu.pl/~jsbien/ksw/002r/ImageProperties.xml
etc...

**Comment by jsbien** [comment]
Thanks!

I tried already zoomify with the URL of the file on my disk, but it didn't work. I understand this should be expected? Just of pure curiosity, what makes the difference?

**Comment by lovasoa** [comment]
dezoomify can't access the files on your disk. This is a security limitation implemented by all browsers. No website should be able to access the files you have on your disk.

If you wanted to do it locally, you would have to run a webserver on your machine, and serve both dezoomify and your files through this server.

**Comment by jsbien** [comment]
Thanks again.

**Comment by lovasoa** [comment]
You're welcome.
