### ISSUE TITLE
bl.uk again

### ISSUE THREAD

**Issue by gregg128** [lovasoa/dezoomify#80]
Hi.
Thank you for your marvellous work,
I tried to download an image from bl.uk. Unfortunately it didn't work: http://www.bl.uk/manuscripts/Viewer.aspx?ref=add_ms_47682_f002r  Dezoomifier seems to download something but it doesn't show up.
Any ideas?
Thanks in advance!

**Comment by lovasoa** [comment]
I just tried and it works just fine. Are you using firefox?

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/18585017/7f768afa-7c25-11e6-83a2-109bb9b0e666.jpg)

**Comment by gregg128** [comment]
aha! It worked with Chrome, thank you very much! It didn't work with firefox/linux
thanks a lot!

**Comment by lovasoa** [comment]
I am using firefox on linux too, and it works...

**Comment by gregg128** [comment]
I'll try with no addons etc.
