### ISSUE TITLE
WSU website not working anymore`

### ISSUE THREAD

**Issue by AmiralCrapaud** [lovasoa/dezoomify#806]
Considering the previous one was closed, I wasn't sure if I had to open a new one or not - apologies in advance if I wasn't supposed to do so.
---------------------------------------
Sorry to dig up that cold corpse, but I just so happen to be in the same situation as the OP in this older thread, with that very same website as mentioned in #510. And although I ended up finding the same URL through the browser extension, both the online version of dezoomify & the prompt return errors (in the case of the prompt, it finds the files, but will tell you on selection & execution "ERROR Input/Output error: Access is denied. (os error 5)")

For instance you can try it again with the same URL as the one you posted above
https://cdm16866.contentdm.oclc.org/digital/iiif/propaganda/374/info.json
You'll get the same mistakes as the ones I encountered I guess (just tried it myself)

Any idea of what could be done to go around this?

Big thanks!

              ```
https://cdm16866.contentdm.oclc.org/digital/iiif/propaganda/374/info.json
```

![canvas](https://user-images.githubusercontent.com/552629/103785252-48d2d000-503b-11eb-9855-32c66b2ebf0a.jpg)

_Originally posted by @lovasoa in https://github.com/lovasoa/dezoomify/issues/510#issuecomment-755362576_

**Comment by lovasoa** [comment]
Hi !
  I just tried it; can't reproduce the error. It works fine for me.

**Comment by lovasoa** [comment]
![canvas](https://github.com/user-attachments/assets/4ed211ab-290a-4ca1-8ec5-77332087685d)

**Comment by AmiralCrapaud** [comment]
Aye! Thank you very much. Strange, it is now working, indeed.
Perhaps an unlucky maintenance right at the wrong moment. My bad. Big thanks and sorry for your time!

**Comment by lovasoa** [comment]
Next time, can you please include the error message you get when reporting the error ?

And if the error message mentions that we are above our monthly request limit, consider donating on https://github.com/sponsors/lovasoa , which pays for the bandwidth used.

**Comment by AmiralCrapaud** [comment]
I'll donate happily :)
but it wasn't the request limit though (did not make requests before that). I'll make sure to leave the error in here next time. Big thanks!

**Comment by lovasoa** [comment]
The request limit is shared between users 😃
