### ISSUE TITLE
please support for artandarchitecture.org.uk

### ISSUE THREAD

**Issue by travis1000** [lovasoa/dezoomify#81]
http://www.artandarchitecture.org.uk/images/gallery/c4629695.html

**Comment by lovasoa** [comment]
Wow, this almost caused me a headache! Looks like zoomify has a strange way of dividing tiles when one image dimension is close to a power of two.

This image width is 2052, which is close to 2048. I'll have to fix that.

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/18620467/74555d4e-7e24-11e6-8920-99eaa99dff3e.jpg)
