### ISSUE TITLE
Non-permanent watermark removal?

### ISSUE THREAD

**Issue by Apossibility** [lovasoa/dezoomify#812]
Hi! I was wondering if such feature (getting original unwatermarked photo) could be added to Dezoomify? 

Example of website:
https://cacheagency.com/scripts/IF/if.cgi?action=view&link=Contributors/Chansley_Entertainment_Archives&image=Bodyguard_PFC_92127.ifz

I believe this website is using non-tagged pix, because when you zoom in you can see the watermark is changing its place to accommodate the preview size. And for the millisecond while it's loading, the actual unwatermarked version can be seen.
When Dezoomify loads the photo from this website, each tile has the watermark on its centre. 
So me, being a noob, is thinking there should be a way to dig that original unwatermarked photo? I would appreciate any help :)

**Comment by lovasoa** [comment]
Hello and thanks for reaching out ! Unfortunately, I think this is out of scope for dezoomify

**Comment by DigitalCurator** [comment]
![image](https://github.com/user-attachments/assets/1d5e5240-9e4d-423c-9c22-1a1a5360c08c)
