### ISSUE TITLE
can not find ImageProperties.xml on www.globaljetservices.com

### ISSUE THREAD

**Issue by www2000** [lovasoa/dezoomify#82]
test url: https://www.globaljetservices.com/falcon2000.php
Error:
can not find 
Error: Invalid XML: https://www.globaljetservices.com/_img/cockpits/cp3po/cp_falcon2000_v3.zif/ImageProperties.xml (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:170)

**Comment by lovasoa** [comment]
This is a zif file, see #21.

**Comment by lovasoa** [comment]
![falcon](https://cloud.githubusercontent.com/assets/552629/18618238/7e82f6a4-7df3-11e6-902d-890093bc97de.jpg)
