### ISSUE TITLE
[new site support] museothyssen.org

### ISSUE THREAD

**Issue by abhayjain9** [lovasoa/dezoomify#822]
### Site name and desciption
What is the name and the URL of the site you would like dezoomify to support ?

https://www.museothyssen.org

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.

Thyssen Museum. Provides gigapixel views of paintings

### Example URLs
https://www.museothyssen.org/en/conectathyssen/gigathyssen/vessenots-auvers

https://sc4hvcfl151058502cff46683.s3.amazonaws.com/gigapixel/Thyssen_VincentVanGogh_LesVessenotsEnAuvers/img_Thyssen_VincentvanGogh_LesVessenotsEnAuvers_6_0_0.jpg

 - Give the URLs of viewing pages
 - give the URLs of metadata files if you found them

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.
Error: Unable to find a proper dezoomer for:
https://www.museothyssen.org/en/conectathyssen/gigathyssen/vessenots-auvers

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)

**Comment by lovasoa** [comment]
Hello ! I'm closing this as a duplicate of https://github.com/lovasoa/dezoomify/issues/561

If it does not work, please comment on the existing issue instead of opening a new one.

**Comment by lovasoa** [comment]
Thank you for opening this : we have identified the zoomable format behind this image and are going to add support for it. We are consolidating all reports about this format to https://github.com/lovasoa/dezoomify/issues/808
