### ISSUE TITLE
[new site support] vintage-maps.com

### ISSUE THREAD

**Issue by natrius** [lovasoa/dezoomify#826]
### Site name and desciption
https://www.vintage-maps.com/de/antike-landkarten/europa/oesterreich-ungarn/ortelius-oesterreich-ungarn-salzburg-1609::12689

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.
The site has quite some big and detailed scans of old maps

### Example URLs
- It seems the picture get split. When using network-tab in firefox i can find the url https://www.vintage-maps.com/img/z/12947_0_files/13/1_0.jpg but i was not able to make it work. 
-- It seems its `x_y.jpg`, the `/8/` before that seems to be kind of the zoom level? With `/12689_0_files/8/0_0.jpg` i get the small whole picture, with `/12689_0_files/9/0_0.jpg` i get the top left quarter. Maximum zoom-level seems to be 13 with `https://www.vintage-maps.com/img/z/12689_0_files/13/0_0.jpg` - 14 deliveres a question mark. 
- With right-click "open picture in new tab" i get just part of the picture and the url `blob:null/c1a5b04e-8c5a-40bc-83bc-ade00089ad42`

### Current error message
When using https://www.vintage-maps.com/de/antike-landkarten/europa/oesterreich-ungarn/ortelius-oesterreich-ungarn-salzburg-1609::12689
i get 

```
Error: Unable to find a proper dezoomer for:
https://www.vintage-maps.com/de/antike-landkarten/europa/oesterreich-ungarn/ortelius-oesterreich-ungarn-salzburg-1609::12689

(https://dezoomify.ophir.dev/dezoomers/automatic.js:30)
```

I mean, i could theoretically get the indivudual pieces but i think i will die of old age :D

**Comment by natrius** [comment]
Oh, great, right after posting i got the i idea to try inputting `https://www.vintage-maps.com/img/z/12689_0_files/13/0_0.jpg` into https://dezoomify.ophir.dev/ and... it works :D 
But maybe there is a way to support the root-site without having to check the network-tab? Issue can be closed if you like. Thanks for your incredible tool! :)

**Comment by natrius** [comment]
Also, it seems to always take the part behind the two `::` for the image-url https://www.vintage-maps.com/de/antike-landkarten/europa/oesterreich-ungarn/ortelius-oesterreich-ungarn-salzburg-1609::12139 --> https://www.vintage-maps.com/img/z/12139_0_files/13/0_0.jpg and from a really quick check 13 seems to be max zoom. But i have not verified this.

**Comment by Benomrans** [comment]
Well, it would be much easier using the incredible [dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) , by providing the dzi file : 
https://www.vintage-maps.com/img/z/12689_0.xml for this map. And so on for other images.

**Comment by natrius** [comment]
Oh, i managed to completely miss this. Thanks a lot, much apreciated!
