### ISSUE TITLE
[new site support] https://maps.arcanum.com/

### ISSUE THREAD

**Issue by natrius** [lovasoa/dezoomify#827]
### Site name and desciption
https://maps.arcanum.com/

It the official site of the austrian archive if i understood everything correct. 

### Example URLs
 - https://maps.arcanum.com/de/map/europe-18century-firstsurvey/?layers=163%2C165&bbox=1412122.337146307%2C6127192.033494448%2C1448812.1107231916%2C6140358.31161657
 - With firefox network analyze max zoom https://maps-cdn.arcanum.com/de/map/europe-18century-firstsurvey/boundaries/18/140424/90954/?v=3 does not work with online or dezoomify-rs.exe and just shows some json? 
 - dezoomify-Browser-plugin does not help unfortunately
 - Was not able to find something usefull in the sourcecode

### Current error message
-

**Comment by Benomrans** [comment]
hello,
have zoomed to the largest level which gave level 15 then obtained last tile url and altered it to :
https://tiles.arcanum.com/mercator/europe-18century-firstsurvey/15/{{X}}/{{Y}} 
it seems working with dezoomify-rs. (it's a huge image so I just stopped dezoomify-rs. so please try it and confirm)

**Comment by natrius** [comment]
Ah, i missed the second URL. I just used the first one i linked above that did not work. 

Well, the image seems too big for my RAM to download with dezoomify-rs. It seems bigger than 20GB, i have to look into the wiki for dezoomify-rs later on on how to handle. Thanks a lot!

**Comment by agiudiceandrea** [comment]
@Benomrans @natrius have you managed to "dezoomify" the arcanum maps?

**Comment by Benomrans** [comment]
@agiudiceandrea 
I have not tried to download since it's a huge map. the mentioned altered url should work by using Dezoomify-rs .

**Comment by agiudiceandrea** [comment]
@Benomrans , no, it doesn't work. It looks like the tiles' scheme used by arcanum maps is not correctly supported by either dezoomify or dezoomify-rs.

**Comment by natrius** [comment]
I made a new issue at dezoomify-rs because it should be done on your own computer :D https://github.com/lovasoa/dezoomify-rs/issues/273

But my RAM was full, i have not yet tried to download IIIF.

**Comment by agiudiceandrea** [comment]
@natrius if you set a .png file as output, then the RAM is not used. Anyway the arcanum maps are not correctly downloaded.
