### ISSUE TITLE
Help with wdl.org

### ISSUE THREAD

**Issue by jeffstud** [lovasoa/dezoomify#83]
Hi,
I install the code on my server. When I run it, I received the following message:
Error: Error: Unable to find a proper dezoomer for the given URL. (http://192.168.1.102/dezoomify-master/zoommanager.js:170).
How can I do?
Best regards,
Jeff

**Comment by lovasoa** [comment]
How did you install it ? Is the URL you are trying to dezoomify working on [the official dezoomify server](http://ophir.alwaysdata.net/dezoomify/dezoomify.html) ?

The official server updates itself automatically from github, so there shouldn't be any difference.

**Comment by jeffstud** [comment]
I copy the files to my apache webserver installed on my desktop computer.

**Comment by jeffstud** [comment]
I can not access the http://ophir.alwaysdata.net/dezoomify/dezoomify.html. So I download the files to my local webserver.

**Comment by jeffstud** [comment]
And I receive Error: Unable to find a proper dezoomer for the given URL. (http://192.168.1.102/dezoomify-master/zoommanager.js:170).

**Comment by lovasoa** [comment]
Please give the URL to the resource you are trying to dezoomify.

**Comment by jeffstud** [comment]
This is a WDL address. https://www.wdl.org/en/item/44/view/1/1/

**Comment by lovasoa** [comment]
OK, so the problem doesn't come from your installation. You should read our FAQ about how to deal with this error. You have to locate the meta-info file yourself. In your exemple, it is https://www.wdl.org/media/44/service/dzi/1403113583/1/1.dzi

**Comment by lovasoa** [comment]
![peking](https://cloud.githubusercontent.com/assets/552629/18630139/930451f8-7e7b-11e6-8785-54c4bc491096.jpg)

**Comment by jeffstud** [comment]
I copy https://www.wdl.org/media/44/service/dzi/1403113583/1/1.dzi on the dezoomify, I receive a error message
Error: Invalid XML: https://www.wdl.org/media/44/service/dzi/1403113583/1/1.dzi (http://192.168.1.102/dezoomify-master/zoommanager.js:170)

**Comment by lovasoa** [comment]
Is php installed and working. What do you see at : (http://192.168.1.102/dezoomify-master/proxy.php?url=https%3A%2F%2Fwww.wdl.org%2Fmedia%2F44%2Fservice%2Fdzi%2F1403113583%2F1%2F1.dzi

**Comment by jeffstud** [comment]
I have installed the php on my server. It works well. But the dezoomify doesn't work.
For example,
I want to dezoomify a picture on the site of WDL. 
https://www.wdl.org/zh/item/11250/view/1/1/
I input this address into the dezoomify website (http://ophir.alwaysdata.net/dezoomify/dezoomify.html)
I can do it.
If I input this address into the local dezoomify site(http://192.168.1.102/dezoomify-master/dezoomify.html), I got the message
Uncaught Error: Error: Unable to find a proper dezoomer for the given URL. (http://192.168.2.105/dezoomify-master/zoommanager.js:170) 
Why?
Could you help me?
Thank you.

**Comment by lovasoa** [comment]
I just gave you an URL: http://192.168.1.102/dezoomify-master/proxy.php?url=https%3A%2F%2Fwww.wdl.org%2Fmedia%2F44%2Fservice%2Fdzi%2F1403113583%2F1%2F1.dzi

Please load this url in your browser, press ctrl-u, copy what you see, and post it here.

**Comment by jeffstud** [comment]
I change a machine, the ip is 192.168.2.105

**Comment by jeffstud** [comment]
nothing happened

**Comment by lovasoa** [comment]
Please poste the source of `{YOUR DEZOOMIFY INSTALLATION}/proxy.php?url=https%3A%2F%2Fwww.wdl.org%2Fmedia%2F44%2Fservice%2Fdzi%2F1403113583%2F1%2F1.dzi`

**Comment by jeffstud** [comment]
http://192.168.2.105/dezoomify-master/proxy.php?url=https%3A%2F%2Fwww.wdl.org%2Fmedia%2F44%2Fservice%2Fdzi%2F1403113583%2F1%2F1.dzi

nothing happened

**Comment by lovasoa** [comment]
What do you mean by *nothing happened* ?

**Comment by jeffstud** [comment]
Is it can not run at local webserver?

**Comment by jeffstud** [comment]
Is it not run at local webserver?

**Comment by lovasoa** [comment]
What do you mean by nothing happened ?

**Comment by lovasoa** [comment]
Please load the page in your browser, press ctrl-u, and then post a screenshot here.

**Comment by lovasoa** [comment]
Of course, dezoomify can run on a local webserver. But it needs a functional PHP intallation.

**Comment by jeffstud** [comment]
I have installed php.

**Comment by lovasoa** [comment]
If you don't do what I'm asking you to, I'm afraid I won't be able to help.

**Comment by jeffstud** [comment]
Does php work correctly?

**Comment by lovasoa** [comment]
I was not asking for index.php, but http://192.168.2.105/dezoomify-master/proxy.php?url=https%3A%2F%2Fwww.wdl.org%2Fmedia%2F44%2Fservice%2Fdzi%2F1403113583%2F1%2F1.dzi

Load the page, press Ctrl-U to view the source, and post it here.

**Comment by jeffstud** [comment]
![ss](https://cloud.githubusercontent.com/assets/7098034/18635938/8e5e5232-7eb9-11e6-8cf1-da57f889c9cf.jpg)

**Comment by jeffstud** [comment]
This is the screenshot.

**Comment by jeffstud** [comment]
Which website?

**Comment by jeffstud** [comment]
If I don't use vpn, I can not access http://ophir.alwaysdata.net/dezoomify/dezoomify.html

**Comment by lovasoa** [comment]
Looks like you don't have access to the image you're trying to dezoomify from the server you installed dezoomify on.
