### ISSUE TITLE
Norton Simon Museum

### ISSUE THREAD

**Issue by NikR1994** [lovasoa/dezoomify#831]
Hello,

Would somebody be able to tell me how to download images from this site?

Norton Simon Museum
https://www.nortonsimon.org/

The Norton Simon Museum is home to one of the world's most remarkable private art collections ever assembled. 
The Norton Simon collections include: European paintings, sculptures, and tapestries; Asian sculptures, paintings, and woodblock prints.

Example URLs:
https://www.nortonsimon.org/art/detail/P.1964.39
https://www.nortonsimon.org/art/viewer/P.1964.39

https://images.nortonsimon.org/iipsrv/iipsrv.fcgi?QLT=100&IIIF=P196439.jpf/info.json

https://images.nortonsimon.org/iipsrv/iipsrv.fcgi?QLT=100&DeepZoom=/P196439.jpf.dzi

https://images.nortonsimon.org/iipsrv/iipsrv.fcgi?QLT=100&DeepZoom=/P196439.jpf_files/14/16_16.jpg
https://images.nortonsimon.org/iipsrv/iipsrv.fcgi?QLT=100&DeepZoom=/P196439.jpf_files/14/{{X}}_{{Y}}.jpg

Dezoomer Error (Dezoomify-rs)
Oops, we have a problem (Dezoomify) 

Thank you

**Comment by Benomrans** [comment]
@NikR1994 
Hello,
Due to the limitations of the browsers to handle such huge images, It would be much easier using [Dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) to download them. by just providing the dzi file's url :

https://images.nortonsimon.org/iipsrv/iipsrv.fcgi?QLT=100&DeepZoom=/P196439.jpf.dzi
then choose the required zoom level.

**Comment by NikR1994** [comment]
> @NikR1994 Hello, Due to the limitations of the browsers to handle such huge images, It would be much easier using [Dezoomify-rs](https://github.com/lovasoa/dezoomify-rs) to download them. by just providing the dzi file's url :
> 
> https://images.nortonsimon.org/iipsrv/iipsrv.fcgi?QLT=100&DeepZoom=/P196439.jpf.dzi then choose the required zoom level.

Hello,

Dezoomify-rs does not load images from this site.

**Comment by Benomrans** [comment]
@NikR1994 
It works perfectly with me. Have downloaded level 1 image (5795px) : 
![P196439](https://github.com/user-attachments/assets/59cdc0e6-b24f-44a8-a217-0a95af4daca1)

**Comment by NikR1994** [comment]
> @NikR1994 It works perfectly with me. Have downloaded level 1 image (5795px) : ![P196439](https://private-user-images.githubusercontent.com/75787532/396601483-59cdc0e6-b24f-44a8-a217-0a95af4daca1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NTcwNzAsIm5iZiI6MTczNDQ1Njc3MCwicGF0aCI6Ii83NTc4NzUzMi8zOTY2MDE0ODMtNTljZGMwZTYtYjI0Zi00NGE4LWEyMTctMGE5NWFmNGRhY2ExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDE3MzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMjA5Y2M5NjBiMThiZGE4YmUzMGFlN2M0YzVmMWY4ZWMwOWFlYmI0Y2JhMDBlYjMxYjYxMDM5Yjk4NDAxYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.syhftAA_Xc8LREbHFNhv9lv8StDzxNZ1XxUM3OoBSzE)

What version Dezoomify-rs did you use?

**Comment by Benomrans** [comment]
I'm using the last version. Directly with no alterations, just the dzi file url.

**Comment by NikR1994** [comment]
> I'm using the last version. Directly with no alterations, just the dzi file url.

Thanks for the answer, I'll try the latest version
