### ISSUE TITLE
Please add support for www.kb.dk

### ISSUE THREAD

**Issue by BrokenButton** [lovasoa/dezoomify#84]
Hello,

I am trying to download several highres maps from the archive of the Royal Library of Denmark.
They seem to be using OpenSeadragon with the IIIF framework. 
The generic dezoomer stops after fetching one image.

Fetching the image using  "full/full" as the location and size parameter 
(as specified in the IIIF API) doesn't work: The resulting image is limited to 2000px, 
while the original is bigger.

Could you please take a look ?
Thank you.

Example URL:
[http://www.kb.dk/maps/kortsa/2012/jul/kortatlas/object60564/en/#](http://www.kb.dk/maps/kortsa/2012/jul/kortatlas/object60564/en/#)
with the JSON located at:
[http://kb-images.kb.dk/online_master_arkiv_6/non-archival/Maps/KORTSA/2009/jun/KBK2_2_07/KBK2_2_07_021/info.json](http://kb-images.kb.dk/online_master_arkiv_6/non-archival/Maps/KORTSA/2009/jun/KBK2_2_07/KBK2_2_07_021/info.json)

**Comment by lovasoa** [comment]
![normannia](https://cloud.githubusercontent.com/assets/552629/18645788/ad55d89e-7ebf-11e6-9d85-74cac289efb2.jpg)
