### ISSUE TITLE
Add support for Quru Image Server (https://quru.com/qis/)

### ISSUE THREAD

**Issue by Kinryu** [lovasoa/dezoomify#85]
Hey! I am a fan of your work. It is an excellent tool. 

I wasn't able to archive some images from Bonhams using Dezoomify, can you take a look at this example? http://www.bonhams.com/auctions/23603/lot/2/?category=results&length=90&page=1

The images are split into many 279x155 tiles. but I cannot find the .js responsible for it. 

Also, with Revs Digital Libraries, using Dezoomify I get; "Uncaught Error: Invalid seadragon XML info file: https://revslib.stanford.edu/catalog/opensearch.xml" https://revslib.stanford.edu/item/yk807wq6530. Is this because it is protected content?

**Comment by lovasoa** [comment]
Looks like they are using that: https://quru.com/qis/
It's not supported in dezoomify yet.

**Comment by lovasoa** [comment]
For the second link, they use IIIF, the support of which has been added just today. You just have to find the URL of the little json meta-information file. For your example, it is https://stacks.stanford.edu/image/iiif/yk807wq6530%2F2010-030BRES-1972-b1_14.0_0008/info.json

**Comment by lovasoa** [comment]
![car](https://cloud.githubusercontent.com/assets/552629/18651682/db86a158-7edd-11e6-9c23-baaf6c6fcfad.jpg)

**Comment by lovasoa** [comment]
But please, in the future, open distinct issues for distinct problems :)

**Comment by Kinryu** [comment]
Thank you very much! Any idea if you will add Quru support? 

I had almost forgot about Revs so I just added it onto this issue. If I have any more problems I will open a new one.

**Comment by lovasoa** [comment]
I haven't seen it anywhere else, so it's not on my priority list. But if you want to, I'll help!

**Comment by Kinryu** [comment]
I'm not familiar with javascript so cannot be much help now. I will get started on it soon, so perhaps in the near future. :)

**Comment by gregg128** [comment]
Is IIIF the same as Mirador Viewer?

**Comment by lovasoa** [comment]
IIIF is the name of the tiling system used by the Mirador Viewer, yes.

**Comment by lovasoa** [comment]
I just gave a deeper look at the Quru system, and it seems that you can download images directly, using a small url tweak.

Take a tile image URL, replace the end (after `tile=`) by `1%3A1`, and voilà :)

![quru image](http://images1.bonhams.com/image?src=Images%2Flive%2F2016-08%2F01%2F24078071-2-20.jpg&width=3984&height=2656&strip=1&format=jpg&fill=none&autosizefit=0&stats=0&tile=1%3A1)

**Comment by lovasoa** [comment]
Feel free to reopen this if they end up correcting this.
