### ISSUE TITLE
Harward Mirador Viewer

### ISSUE THREAD

**Issue by gregg128** [lovasoa/dezoomify#87]
Hi,
Any chance for support of the Mirador Viewer?
https://iiif.lib.harvard.edu/manifests/view/drs:9827622$43i
Thank you!

**Comment by lovasoa** [comment]
They use IIIF, that is already supported by dezoomify, however, their server doesn't seem to support all request formats, and thus doesn't work with dezoomify.

**Comment by gregg128** [comment]
Could you please try to make it work? Or is it too much work? 
This server contains a lot of valueble manuscripts I need to download in hi-rez.
Thank you very much in advance!

**Comment by lovasoa** [comment]
Just committed 81b6cba879f80a02ccb29546ddcde1227065ba1a, and now [it works](http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://ids.lib.harvard.edu/ids/iiif/9828170/info.json).

You'll still have to find the json meta-file on your own, though.

**Comment by gregg128** [comment]
Thank you so much!

**Comment by gregg128** [comment]
https://cudl.lib.cam.ac.uk/iiif/MS-ADD-00662 seems to contain a json manifest without a "json" extension. Could you please fix this issue? Thanks a lot in advance!
