### ISSUE TITLE
http://www.mansoojat.org/ can't extract/combine tiles with dezoomify

### ISSUE THREAD

**Issue by kaithaba** [lovasoa/dezoomify#88]
Right, so this site has absolutely gorgeous costumes and I've managed to find the individual tiles via Network Inspector (swf and images sections), but when your FAQ suggested finding their coordinates, I couldn't find them (not programming-savvy enough for that). It's a Flash viewer but all the tiles are individually saved on the server. Here's a lovely costume I wanted to get a hi-res image of:
http://www.mansoojat.org/costume23.html

And I found the tiles were like http://www.mansoojat.org/costume23/TileGroup0/3-0-3.jpg but I had no way of getting my hands on them, especially as the TileGroup folder was, obviously, forbidden to access. I tried various swf extractors but they didn't work.

**Comment by lovasoa** [comment]
Maybe I should add this to the FAQ. If the tiles url end with `/TileGroupN/Z-X-Y.jpg` (where N, Z, X, and Y are numbers), then you can use the `Zoomify` dezoomer. You just have to replace the end of the tile URL (starting from `TileGroup`) by `ImageProperties.xml`.

So in your case, the tile URL was `http://www.mansoojat.org/costume23/TileGroup0/3-0-3.jpg` so you give `http://www.mansoojat.org/costume23/ImageProperties.xml` to dezoomify, and it works.

**Comment by kaithaba** [comment]
Oh, you should absolutely put that in the FAQ! However, I can only get 99% at most, as it seems to be unable to access one or few tiles:

Error: Unable to load tile. Check that your internet connection is working and that you can access this url: http://www.mansoojat.org/costume23/TileGroup0/5-2-12.jpg (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:170) 

But when I go to the URL of the tile it says it doesn't exist, but some mistyped variations of tiles like that exist (all different ones), so I'm presuming that problem is on the site's own end.

**Comment by lovasoa** [comment]
Yes, looks like they miss a tile. I downloaded the image with a hole in it, and filled the hole manually with GIMP.

Here is the result: 
![trous](https://cloud.githubusercontent.com/assets/552629/18826062/8a0af6cc-83dc-11e6-918c-35965e2c2c68.jpg)
