### ISSUE TITLE
Please support this site: http://www.nla.gov.au/

### ISSUE THREAD

**Issue by Huginn22** [lovasoa/dezoomify#89]
Though it provides download option, the quality of images are very low.
I hope you can support this website, I really appreciate it.  :)

http://nla.gov.au/nla.obj-152642460/view
I try lots of ways to grab the high quality image, but I failed.

**Comment by lovasoa** [comment]
They use deep zoom images, but the tile URLs aren't conventional. I may add support for it later. In the mean time here is your image.
![canvas](https://cloud.githubusercontent.com/assets/552629/18809051/d6c2eed4-8283-11e6-811f-9359dceaf2b2.jpg)

**Comment by Huginn22** [comment]
Thank you. I really appreciate it. :)

**Comment by Huginn22** [comment]
Hey, I just tested and it was great! However, I found that there is a file can not be displayed.
Here it is: http://nla.gov.au/nla.obj-152794741/view
It was zoomified successfully but it's just a blank image.

**Comment by lovasoa** [comment]
This problem is recurrent, and unfortunately, cannot be solved inside inside zoomify itself, as it most probably comes from your browser refusing to create a large canvas. Read our FAQ to know how to work around it.

**Comment by lovasoa** [comment]
I created [a small bash script](https://gist.github.com/lovasoa/8a176cb1c1079ba6447bb71b83135d8e) to download the picture and [uploaded it to wikimedia](https://commons.wikimedia.org/wiki/File:%E6%B8%85%E4%BB%A3%E5%AE%98%E5%AE%A6%E4%BA%BA%E5%AE%B6%E5%B1%85%E5%AE%B6%E7%94%9F%E6%B4%BB%E5%9C%96%E9%9B%86._%E5%AE%98%E4%BA%BA%E9%80%B2%E8%AB%AB.jpg).

**Comment by Huginn22** [comment]
I coundn't say a thing except showing my gratitude to you. Thank you very very much! :) 
P.S. :I will try the way you wrote in FAQ. I want to learn it.

**Comment by Huginn22** [comment]
Sorry to bother you again. I tried the way which in FAQ, unfortunately, it still can't work. 
So could you tell me how to use the little bash script that you wrote? I'm not a programmer so I have no idea how to use it. @lovasoa

**Comment by lovasoa** [comment]
What operating system do you have? MacOS, Linux, or windows?

**Comment by Huginn22** [comment]
windows 10  x64

**Comment by lovasoa** [comment]
Then you'll have to install a Linux-like environment, like cygwin. 

29 сентября 2016 г. 4:57:47 GMT+03:00, Huginn22 <notifications@github.com> пишет:

**Comment by Huginn22** [comment]
Ok, I got it. Then I just use dezoomify as usual? Or there still have something I need to do?

**Comment by lovasoa** [comment]
No.

First install cygwin, and inside it, the *wget* and *imagemagick* packages.

Then download the [little dezoomify bash script](https://gist.github.com/lovasoa/8a176cb1c1079ba6447bb71b83135d8e) and put it in the home repository of your cygwin installation.

Then open a cygwin terminal and type `bash dezoom.sh W H url`, where W and H are the dimensions of the image in number of tiles, and url is the tile url, where you replace the x coordinate by `%X` and y coordinate by `%Y`.

**Comment by Huginn22** [comment]
Could you give me an example? I am not quite understand the last part.
For example: http://nla.gov.au/nla.obj-152794741/view
Like this? : bash dezoom.sh 10624 15120 nla.gov.au/nla.obj-152794741/dzi?tile=%X_%Y.jpg

**Comment by lovasoa** [comment]
No, the two numbers at the beginning have to be the dimensions of the image *in number of tiles* (and not in number of pixels). So if your tiles are 256*256 px in size, then width in tiles will be 42 (10624/256=41.5, but half tiles don't exist)

**Comment by Huginn22** [comment]
I couldn't thank you more! :)
Thank you for teaching me patiently. Wishing you have a great day! :)

**Comment by GrampGit** [comment]
I know this thread's been closed, but here's another request for the NLA site to be supported.

The tile URLs seem quite straightforward - e.g. https://nla.gov.au/nla.obj-551141767/ is split into various resolutions (numbered 8 = 1 image of full page to 13 = highest), 34 columns x 26 rows = 884 tiles, mostly 256x256 but the final row is 242 and the final column is 25, making a total size of (33*256+25) x (25*256+242) = 8473 by 6642... I think... with individual tiles numbered https://nla.gov.au/nla.obj-551141767/dzi?tile=13/0_0.jpg through to https://nla.gov.au/nla.obj-551141767/dzi?tile=13/33_25.jpg (at resolution '13').

I know I could use DownThemAll to retrieve all 884 images & name them appropriately, then use ImageMagick to stitch ('montage') them together, but it would be great if DZ handled the whole site automagically.
