### ISSUE TITLE
garfield.jtsa.edu

### ISSUE THREAD

**Issue by gregg128** [lovasoa/dezoomify#90]
Hi
Here is just another "new site support" request.
http://garfield.jtsa.edu:5881/ImageServer/dtlscrollnav.jsp?filename=L2V4bGlicmlzL2R0bC9qM18xL2RpZ2l0b29sL2hvbWUvcHJvZmlsZS9zdG9yYWdlL2JpZ3N0cmVhbXMvMjAxMi8xMC8yMi9maWxlXzIvODkwOTM%3D
Any chance?
Thanks in advance!

**Comment by lovasoa** [comment]
There zooming system is quite simple, you can simply use the generic dezoomer with it.

http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://garfield.jtsa.edu:5881/ImageServer/tileServer?filename=L2V4bGlicmlzL2R0bC9qM18xL2RpZ2l0b29sL2hvbWUvcHJvZmlsZS9zdG9yYWdlL2JpZ3N0cmVhbXMvMjAxMi8xMC8yMi9maWxlXzIvODkwOTM=&zoom=3&x={{X}}&y={{Y}}&rotation=0

**Comment by gregg128** [comment]
I've tried with generic dezoomer, yes. It did not work:
Error: Unable to load tile. Check that your internet connection is working and that you can access this url: http://garfield.jtsa.edu:5881/ImageServer/tileServer?filename=L2V4bGlicmlzL2R0bC9qM18xL2RpZ2l0b29sL2hvbWUvcHJvZmlsZS9zdG9yYWdlL2JpZ3N0cmVhbXMvMjAxMi8xMC8yMi9maWxlXzIvODkwOTM=&zoom=3&x=%7B%7BX%7D%7D&y=%7B%7BY%7D%7D&rotation=0 (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:170)

**Comment by lovasoa** [comment]
You probably didn't use it right. I tried the link I posted above, it works fine.

**Comment by lovasoa** [comment]
The address you have to enter is : `http://garfield.jtsa.edu:5881/ImageServer/tileServer?filename=L2V4bGlicmlzL2R0bC9qM18xL2RpZ2l0b29sL2hvbWUvcHJvZmlsZS9zdG9yYWdlL2JpZ3N0cmVhbXMvMjAxMi8xMC8yMi9maWxlXzIvODkwOTM=&zoom=3&x={{X}}&y={{Y}}&rotation=0`

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/18951202/fe790ea2-8654-11e6-8bbd-b377c4a76c13.jpg)

**Comment by gregg128** [comment]
Thank you very much!

**Comment by gregg128** [comment]
Hi,

@lovasoa could you please tell me how should I change the following URL?

http://garfield.jtsa.edu:5881/ImageServer/dtlimagenav.jsp?filename=L2V4bGlicmlzL2R0bC9qM18xL2RpZ2l0b29sL2hvbWUvcHJvZmlsZS9zdG9yYWdlL2JpZ3N0cmVhbXMvMjAxNC8wOS8xOC9maWxlXzEyLzMyMTE1MA==&display_plugin=false

I have tried to add "=&zoom=3&x={{X}}&y={{Y}}&rotation=0" instead of the "==&display_plugin=false" but it didn't work :(
