### ISSUE TITLE
generic dezoomer doesn't guess tile overlap.

### ISSUE THREAD

**Issue by Madiran** [lovasoa/dezoomify#93]
Gentleman (men),

Here is the problem : when we use generic dezoomer, the image built is not done "properly". A web appears slightly on the picture corresponding to the limits of the tiles. Every 256 pixels (the common width of a tile) a thin mark appears creating a grid on the whole picture.
Just look at this :   the dezoom picture made with _generic_ dezoomer :
![Uploading example.jpg…]()
and the original : https://www.sfmoma.org/artwork/2004.97
Use maximum zoom and compare to original.

I love the dezoomify script. Hope i can help improving it.
Thank you so much for your work.

**Comment by lovasoa** [comment]
Your example image didn't upload...

**Comment by lovasoa** [comment]
You don't need the generic dezoomer in your example. The site uses `dzi`, that is supported by dezoomify. You just need to find the URL of the dzi file.

In your case, you should [open dezoomify with `https://s3-us-west-2.amazonaws.com/sfmomamedia/media/zoom_tiles/13330/image.dzi`](http://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://s3-us-west-2.amazonaws.com/sfmomamedia/media/zoom_tiles/13330/image.dzi)

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/19729552/66c676bc-9ba8-11e6-9084-b51db7c40fb1.jpg)

**Comment by lovasoa** [comment]
The generic dezoomer cannot guess how much the tiles overlap, so it supposes they don't.
That's why in your case, in generates a *«wrong»* image.

**Comment by Madiran** [comment]
Monsieur,


Je vous remercie beaucoup du temps que vous m'avez consacré et pour vos réponses claires et nettes.
Sur le lien que j'avais choisi, l'image que vous avez générée est en effet sans commune mesure avec celle que j'avais obtenue par "generic dezoomer".
Je vous en envoie quand même le fichier, par souci de comparaison.
Je n'avais pas su proprement individualisé le lien que vous m'avez envoyé (pourtant décelable via l'onglet XHR sous la console firefox).
Merci encore.

Je voulais vous demander : l'image générée en .png par "canvas" est-elle de meilleure qualité que si on la sauve en .jpeg via "save image as" ?
(je pense qu'a priori non, vu que les tuiles originales sont en .jpeg...)

Sur ce lien précis, je n'arrive pas à utiliser autre chose que "generic dezoomer" :
http://www.getty.edu/art/collection/objects/55734/andre-kertesz-clock-of-the-academie-francaise-paris-american-negative-1929-1932-print-1950s/?dz=0.5000,0.6483,1.92
Là, sous XHR, rien ne s'affiche. Je ne dois pas chercher au bon endroit, il me semble qu'il s'agit du dzi encore une fois.
Pouvez-vous m'aider ?

Dezoomify est un superbe outil... Vous avez du talent.

Bien à vous,


Madiran

**Comment by lovasoa** [comment]
Merci pour les compliments :)

Pour la comparaison, de toute façon, les fichiers jpeg des tuiles originales devront être décodés pour être assemblés. Réencoder le résultat en jpeg peut donc théoriquement causer une perte de qualité. Mais je n'ai jamais constaté cette perte de qualité de manière visible sur aucun exemple. Par contre, la différence de taille de fichier peut varier de un à dix. Je vous conseillerais donc de ne pas vous inquiéter à ce sujet, et conserver vos images au format jpeg.

Pour votre dernier exemple, le site utilise deepzoom. [L'URL à utiliser est `http://www.getty.edu/museum/media/images/web/zoom/06224401/06224401.dzi`](http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://www.getty.edu/museum/media/images/web/zoom/06224401/06224401.dzi). Vous n'aviez pas vraiment moyen de le deviner, sauf à remarquer le `_files` dans l'URL des tuiles, qui est un signe de l'utilisation de ce système de zoom.

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/19786950/7144f0aa-9cb1-11e6-82cf-ad2cadc74ce6.jpg)

**Comment by Madiran** [comment]
Ouh là là mon ami ! Que n'aviez-vous pas dit !! J'ai derechef recouvré ces bons gros "canvas", bien gras, bien lourds.
Je suis un ayatollah de la qualité, même illusoire, même invisible à l'oeil nu.

Les compliments, il ne faut jamais se gêner d'en faire, surtout quand ils sont mérités. Vous êtes le fruit de ce qui reste de la formation d'excellence
à la française, avec un joli zeste d'esprit autodidacte et surtout de transgression. C'est rare, désormais, dans une époque effarante de nivellement et
de conformisme. Je vais citer à dessein Gomez Davila :
"Son sérieux entraînement universitaire blinde l'ingénieur-technicien contre toute idée." (de mémoire)
Ce n'est pas votre cas...
Et puis surtout, pour le plaisir que vous me procurez depuis un an à dénicher des trésors de photos anciennes dans leur plus bel écrin... Bon, certes, ce n'est le .TIF original, mais ça en est diablement approchant.

A ce propos je hante les sites des musées et autres bibliothèques :
Comment un lien propre à une photo peut-il "marcher" et faire défaut pour une autre (en en changeant judicieusement le numéro) ? Y'a t-il moyen de passer outre ?
Je veux dire "marcher" pour un téléchargement ou pour "dezoomify". Parfois ça marche... Le plus souvent non, quand c'est "not on view" ou que la fonction zoom n'est pas disponible...

Je souhaitais installer Python sur mon ordinateur pour utiliser le code originel, pour me la jouer un peu "geek" : est-ce d'un intérêt certain ou plus globalement illusoire ? Ca m'a quand même l'air diablement interessant et ouvrant des possibilités incroyables...

Questions certainement naïves, mais vos réponses me seront précieuses.

Salutations cordiales,


Madiran





--------------------------------------------
En date de : Jeu 27.10.16, Ophir LOJKINE <notifications@github.com> a écrit :

 Objet: Re: [lovasoa/dezoomify] generic dezoomer doesn't guess tile overlap. (#93)
 À: "lovasoa/dezoomify" <dezoomify@noreply.github.com>
 Cc: "Madiran" <damien_114@yahoo.fr>, "Author" <author@noreply.github.com>
 Date: Jeudi 27 octobre 2016, 22h53
 
 Merci pour les compliments :)
 
 Pour la comparaison, de toute façon, les fichiers jpeg
 des tuiles originales devront être décodés pour être
 assemblés. Réencoder le résultat en jpeg peut donc
 théoriquement causer une perte de qualité. Mais je
 n'ai jamais constaté cette perte de qualité de
 manière visible sur aucun exemple. Par contre, la
 différence de taille de fichier peut varier de un à dix.
 Je vous conseillerais donc de ne pas vous inquiéter à ce
 sujet, et conserver vos images au format jpeg.
 
 Pour votre dernier exemple, le site utilise deepzoom. L'URL
 à utiliser est
 http://www.getty.edu/museum/media/images/web/zoom/06224401/06224401.dzi.
 Vous n'aviez pas vraiment moyen de le deviner, sauf à
 remarquer le _files dans l'URL des tuiles,
 qui est un signe de l'utilisation de ce système de
 zoom.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by lovasoa** [comment]
Pour cette histoire de qualité, voilà par exemple la différence entre l'image png exportée et cette même image convertie en jpg:

![diff-small](https://cloud.githubusercontent.com/assets/552629/19891176/5ad2b906-a058-11e6-95ce-d5d0567c170a.jpg)

(plus un pixel est foncé, plus il est différent entre l'image en png et en jpg)


Comme on le voit, la perte est quasiment nulle... seulement par endroit, contrairement à ce que je prétendais plus haut (et à mon expérience passée). Cela m'a intrigué, et, investigation faite, j'ai trouvé d'où cela venait! Cette image utilise des tuiles de 254x254 px (contrairement aux 256x256 px habituels). Hors [la compression JPG compresse l'image par "blocs" de 8x8 px](https://fr.wikipedia.org/wiki/JPEG#D.C3.A9coupage_en_blocs). Donc la compression de l'image originale en tuiles fait perdre de l'information (que l'on ne peut pas récupérer de toute façon). Mais **si et seulement si les tuiles ont une largeur et une hauteur multiple de 8**, la recompression de l'image finale (après assemblage des tuiles) ne fait pas perdre plus d'information (les «hautes fréquences» ne sont déjà plus présentes dans l'image). Si au contraire les tuiles ont une *mauvaise* taille (comme dans l'exemple ci-dessus), alors les blocs utilisés pour les deux compressions successives ne sont pas les mêmes, et la perte de qualité est beaucoup plus importante.

Donc je vais mettre à jour mon conseil: on peut conserver les images en jpg sans véritable perte de qualité si les tuiles qui la composaient on une largeur et une hauteur multiples de 8.

**Comment by lovasoa** [comment]
Pour tenter de répondre à vos autres questions:

> Comment un lien propre à une photo peut-il "marcher" et faire défaut pour une autre (en en changeant judicieusement le numéro) ? Y'a t-il moyen de passer outre ?

Je ne suis pas sûr de comprendre... Vous voulez-dire que sur certains sites, on peut voir différentes photos à différentes URL, qui ne diffèrent entre elles que d'un numéro, et que pour certaines pages on peut zoomer sur l'image, pour d'autres non ?

Si c'est cela, alors cela signifie simplement que le musée n'a pas mis l'image grand format sur son site, parce qu'il ne l'a pas ou parce qu'il ne veut pas que l'on puisse y accéder. La meilleure chose à faire est alors d'écrire au musée. La plupart vendent des reproductions. Sentez-vous libre ensuite, si l'image est libre de droits, de la poster sur Wikimedia Commons, pour que d'autres y aient accès plus simplement. 

> Je souhaitais installer Python sur mon ordinateur pour utiliser le code originel, pour me la jouer un peu "geek" : est-ce d'un intérêt certain ou plus globalement illusoire ? Ca m'a quand même l'air diablement interessant et ouvrant des possibilités incroyables...

Est-ce que vous parlez de [dezoomify-py](https://github.com/lovasoa/dezoomify-py) ? Le code est vieux et n'est pas activement maintenu, et il ne marche que pour zoomify. Mais il utilise utilise jpegtran, qui permet d'assembler des images sans les décompresser, ce qui donne un avantage de qualité imperceptible, mais probablement très important pour un ayatollah :stuck_out_tongue:

**Comment by Madiran** [comment]
Oui, en effet, le résultat est sans appel...
Ce que dictait inconsciemment une certaine intuition : retravailler un format destructif, aussi soigneusement que possible, ne va pas dans le sens d'une amélioration. Merci encore pour cet effet de comparaison.

J'ai pu, à deux reprises, comparer le fichier "originel" fourni par le musée (la National Gallery et le Getty's) au résultat fourni par dezoomify.
On dirait deux clones. A l'oeil nu, sous Photoshop, niet, nada. Juste une très légère différence de taille entre les 2 images, dans les deux cas.
A l'avantage du dezoomify.
Je ne sais pas à quoi ça tient, peut-être la dimension du pixel, c'est assez drôle.

J'en reste donc au bon vieux canvas... Tellement de choses entrent en ligne de compte dans l'appréciation de l'image, les conditions dans lesquelles on l'a scannée, le matériel utilisé, le soin apporté par l'institution à la mise en ligne, son propre ordinateur... etc etc
On peut s'y perdre. Mais le résultat obtenu reste, de toute façon, assez exceptionnel... Il serait d'ailleurs intéressant de défier un professionnel de l'image avec...



--------------------------------------------
En date de : Mar 1.11.16, Ophir LOJKINE <notifications@github.com> a écrit :

 Objet: Re: [lovasoa/dezoomify] generic dezoomer doesn't guess tile overlap. (#93)
 À: "lovasoa/dezoomify" <dezoomify@noreply.github.com>
 Cc: "Madiran" <damien_114@yahoo.fr>, "Author" <author@noreply.github.com>
 Date: Mardi 1 novembre 2016, 14h47
 
 Pour cette histoire de qualité,
 voilà par exemple la différence entre l'image png
 exportée et cette même image convertie en jpg:
 
 
 
 (plus un pixel est foncé, plus il est différent entre
 l'image en png et en jpg)
 
 Comme on le voit, la perte est quasiment nulle...
 seulement par endroit, contrairement à ce que je
 prétendais plus haut (et à mon expérience passée). Cela
 m'a intrigué, et, investigation faite, j'ai trouvé
 d'où cela venait! Cette image utilise des tuiles de
 254x254 px (contrairement aux 256x256 px habituels). Hors la
 compression JPG compresse l'image par "blocs"
 de 8x8 px. Donc la compression de l'image originale
 en tuiles fait perdre de l'information (que l'on ne
 peut pas récupérer de toute façon). Mais si et
 seulement si les tuiles ont une largeur et une hauteur
 multiple de 8, la recompression de l'image
 finale (après assemblage des tuiles) ne fait pas perdre
 plus d'information (les «hautes fréquences» ne sont
 déjà plus présentes dans l'image). Si au contraire
 les tuiles ont une mauvaise taille (comme dans
 l'exemple ci-dessus), alors les blocs utilisés pour les
 deux compressions successives ne sont pas les mêmes, et la
 perte de qualité est beaucoup plus importante.
 
 Donc je vais mettre à jour mon conseil: on peut
 conserver les images en jpg sans véritable perte de
 qualité si les tuiles qui la composaient on une largeur et
 une hauteur multiples de 8.

**Comment by Madiran** [comment]
Exactement. On peut zoomer certaines images, rares, les autres a priori, non.
Mais en en récupérant le numéro, là miracle, dezoomify fait le travail.
Mais ça reste rare. Tout est généralement cadenassé.

Oui, mais vous le savez comme moi, les musées délivrent au compte-goutte la qualité, requièrent un tas de coordonnées, traitent quand bon leur chante, font grassement payer... Pour un seul fichier. Et ce que je recherche est toujours pratiquement la propriété de quelque chose ou quelqu'un (par exemple l'Horloge de Kertész).
Bon, à moins de passer outre les défenses des dits musées... C'est mort.

Jpegtran... Mmmmh... Sourire


--------------------------------------------
En date de : Mar 1.11.16, Ophir LOJKINE <notifications@github.com> a écrit :

 Objet: Re: [lovasoa/dezoomify] generic dezoomer doesn't guess tile overlap. (#93)
 À: "lovasoa/dezoomify" <dezoomify@noreply.github.com>
 Cc: "Madiran" <damien_114@yahoo.fr>, "Author" <author@noreply.github.com>
 Date: Mardi 1 novembre 2016, 15h17
 
 Pour tenter de répondre à vos
 autres questions:
 
 
 Comment un lien propre à une photo peut-il
 "marcher" et faire défaut pour une autre (en en
 changeant judicieusement le numéro) ? Y'a t-il moyen de
 passer outre ?
 
 
 Je ne suis pas sûr de comprendre... Vous voulez-dire que
 sur certains sites, on peut voir différentes photos à
 différentes URL, qui ne diffèrent entre elles que d'un
 numéro, et que pour certaines pages on peut zoomer sur
 l'image, pour d'autres non ?
 
 Si c'est cela, alors cela signifie simplement que le
 musée n'a pas mis l'image grand format sur son
 site, parce qu'il ne l'a pas ou parce qu'il ne
 veut pas que l'on puisse y accéder. La meilleure chose
 à faire est alors d'écrire au musée. La plupart
 vendent des reproductions. Sentez-vous libre ensuite, si
 l'image est libre de droits, de la poster sur Wikimedia
 Commons, pour que d'autres y aient accès plus
 simplement. 
 
 
 Je souhaitais installer Python sur mon ordinateur pour
 utiliser le code originel, pour me la jouer un peu
 "geek" : est-ce d'un intérêt certain ou plus
 globalement illusoire ? Ca m'a quand même l'air
 diablement interessant et ouvrant des possibilités
 incroyables...
 
 
 Est-ce que vous parlez de dezoomify-py
 ? Le code est vieux et n'est pas activement maintenu, et
 il ne marche que pour zoomify. Mais il utilise utilise
 jpegtran, qui permet d'assembler des images sans les
 décompresser, ce qui donne un avantage de qualité
 imperceptible, mais probablement très important pour un
 ayatollah 😛  
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by Madiran** [comment]
Monsieur,


Je sollicite votre aide pour le zoom de l'image suivante dont l'url me renvoie un message d'erreur dans "dezoomify" :

https://digitaltmuseum.se/021015930827/paris-en-pojke-sparkar-fotboll-under-en-bro/media?aq=owner%3A%22S-NM%22+text%3A%22tore%22%2C%22johnson%22&i=31

En sélectionnant plus spécifiquement : https://qdms.dimu.org/image/012wX1d2bT8U/zi.dzi , ça ne marche pas non plus.

Peut-être n'y a-t-il pas de solution ?


D'avance, je vous en remercie.

Bien cordialement,


Madiran

**Comment by lovasoa** [comment]
Le second lien que vous donnez est celui d’une page d’erreur. EN tout cas chez moi, il retourne:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4818612E6F8D770B</RequestId>
<HostId>J22BeZCGyQvsXEVDw+1v3qlmwNwcwDJg8KKnDfj1EgVRiPX0ht+5Go58fPxdONnpZz315hjN0GY=</HostId>
</Error>
```

**Comment by lovasoa** [comment]
L’image de la page que vous donnez en lien n’est en fait pas une image zoomable. Elle est accessible directement à https://dms-cf-08.dimu.org/image/012wX1d2bT8U?dimension=max

![image grand format](https://dms-cf-08.dimu.org/image/012wX1d2bT8U?dimension=max)

**Comment by Madiran** [comment]
Ophir,


Je sollicite votre aide concernant les images du site "artsy" pour en récupérer des images.

Prenons cet exemple : https://www.artsy.net/artwork/elliott-erwitt-third-avenue-el-dot-new-york-city

En mettant cette url dans dezoomify, il m'est renvoyé un message d'erreur (le script a pourtant bien sélectionné automatiquement artsy).

Y a t-il une adresse plus spécifique que je doive sélectionner en passant par la console ?


Merci à vous.

Très bon week-end.

**Comment by lovasoa** [comment]
Bonjour, artsy a changé son format depuis la création du dézoomeur associé, et ne marche plus. C'est un bug connu, qui a déjà été rapporté plusieurs fois: https://github.com/lovasoa/dezoomify/issues?utf8=%E2%9C%93&q=artsy
