### ISSUE TITLE
please support for tretyakovgallery.ru

### ISSUE THREAD

**Issue by travis1000** [lovasoa/dezoomify#94]
http://www.tretyakovgallery.ru/ru/collection/_show/image/_id/394

**Comment by lovasoa** [comment]
Хорошая идея! I I'll have a look at it!

28 октября 2016 г. 2:32:02 GMT+03:00, travis1000 <notifications@github.com> пишет:

**Comment by lovasoa** [comment]
[Here it is !](http://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://www.tretyakovgallery.ru/ru/collection/_show/image/_id/394#)

![canvas png](https://cloud.githubusercontent.com/assets/552629/19807596/ddb4dcb6-9d31-11e6-8112-963c33df0c53.jpg)

**Comment by travis1000** [comment]
Thanks!
