### ISSUE TITLE
help for www.rijksmuseum.nl

### ISSUE THREAD

**Issue by macdorli** [lovasoa/dezoomify#95]
I tried this but it does not work: https://www.rijksmuseum.nl/en/search/objects?q=rome&p=78&ps=12&st=OBJECTS&ii=4#/RP-F-F01125-71,928

Can you help me? Thanks

**Comment by lovasoa** [comment]
You can actually download high-res images right from the page, using the little scissors icon in the bottom.

![rp-f-f01125-71](https://cloud.githubusercontent.com/assets/552629/19894495/abd9728c-a066-11e6-8dcc-57941c8fa6bd.jpg)

**Comment by macdorli** [comment]
ouch ... thanks for your time :)

**Comment by koxivega** [comment]
Actually, certain images aren't available for free download, like this one https://www.rijksmuseum.nl/nl/collectie/RP-F-2000-11-232
Does it work on this type?

**Comment by lovasoa** [comment]
Most URLs on the RijksMuseum are now supported. Try for instance https://www.rijksmuseum.nl/nl/rijksstudio/kunstenaars/aelbert-cuyp/objecten#/SK-C-120,1

**Comment by lanaloft** [comment]
Thank you!!!!

These URLS/works very well:‘De Staalmeesters’, Rembrandt van Rijn, 1662Portret van een vrouw, mogelijk Maria Trip_1639Zelfportret als de apostel Paulus, Rembrandt van Rijn
A few of Rembrandt paintings works, the most do not work.EG https://www.rijksmuseum.nl/nl/zoeken/objecten?p=2&ps=12&f.hnrCode.section.sort=17de+Eeuw&f.hnrCode.hall.sort=2.8%3a+De+jonge+Rembrandt+%2f+De+Vrede+van+M%c3%bcnster+1648&ondisplay=True&st=Objects&ii=2#/SK-A-4674,14

One gets always these pictures:Is there a trick to get the other pictures of Rembrandt in big size?
Thanks  for your great work!!









    Am Samstag, 18. Juli 2020, 16:44:50 MESZ hat Ophir LOJKINE <notifications@github.com> Folgendes geschrieben:  
 
 


Most URLs on the RijksMuseum are now supported. Try for instance https://www.rijksmuseum.nl/nl/rijksstudio/kunstenaars/aelbert-cuyp/objecten#/SK-C-120,1

**Comment by lovasoa** [comment]
Hi @lanaloft ! The picture you link to can be downloaded with the following meta-information URL: https://q42imageserver.appspot.com/api/getTilesInfo?object_id=SK-A-4674

![canvas](https://user-images.githubusercontent.com/552629/87872461-182daa00-c9b9-11ea-8966-25f7835358b3.jpg)


I am going to update the [dezoomify browser extension](https://github.com/lovasoa/dezoomify-extension/) so that it can get this meta-information file automatically.

**Comment by lovasoa** [comment]
Okay, I made a few improvements to the micrio dezoomer, and urls such as https://www.rijksmuseum.nl/nl/zoeken/objecten?p=2&ps=12&f.hnrCode.section.sort=17de+Eeuw&f.hnrCode.hall.sort=2.8%3a+De+jonge+Rembrandt+%2f+De+Vrede+van+M%c3%bcnster+1648&ondisplay=True&st=Objects&ii=2#/SK-A-4674,14 should now work directly.
